#!/bin/tcsh
setenv PATH /opt/centos/devtoolset-1.0/root/usr/bin/:$PATH
echo "Info: compiling /tmp/gamma_build/preprocessed-debug/Gamma/Gamma.c"
/usr/bin/gcc -I/tmp/gamma_build/preprocessed-debug  -lm -ltcl8.5  -g -O5 -D GAMMA_COMPILATION -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wnested-externs -Wold-style-definition -Wredundant-decls -Wconversion -I/tmp/gamma_build/preprocessed-debug/ngspice/root -I/usr/include/c++/4.4.4/x86_64-redhat-linux -ldb-6.0  -I/tmp/gamma_build/preprocessed-debug/ngspice/root/maths/poly -I/tmp/gamma_build/preprocessed-debug/ngspice/root/frontend -I/tmp/gamma_build/preprocessed-debug/ngspice/root/spicelib/devices -I/tmp/gamma_build/preprocessed-debug/ngspice/root/xspice/icm/analog -D SENSDEBUG -D X_DISPLAY_MISSING -D CIDER -D SIMULATOR -c /tmp/gamma_build/preprocessed-debug/Gamma/Gamma.c | & tee -a log
mv Gamma.o /tmp/gamma_build/object_files-debug
echo "Info: compiling /tmp/gamma_build/preprocessed-debug/Gamma/virtual_machine.c"
/usr/bin/gcc -I/tmp/gamma_build/preprocessed-debug  -lm -ltcl8.5  -g -O5 -D GAMMA_COMPILATION -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wnested-externs -Wold-style-definition -Wredundant-decls -Wconversion -I/tmp/gamma_build/preprocessed-debug/ngspice/root -I/usr/include/c++/4.4.4/x86_64-redhat-linux -ldb-6.0  -I/tmp/gamma_build/preprocessed-debug/ngspice/root/maths/poly -I/tmp/gamma_build/preprocessed-debug/ngspice/root/frontend -I/tmp/gamma_build/preprocessed-debug/ngspice/root/spicelib/devices -I/tmp/gamma_build/preprocessed-debug/ngspice/root/xspice/icm/analog -D SENSDEBUG -D X_DISPLAY_MISSING -D CIDER -D SIMULATOR -c /tmp/gamma_build/preprocessed-debug/Gamma/virtual_machine.c | & tee -a log
mv virtual_machine.o /tmp/gamma_build/object_files-debug
echo "Info: compiling /tmp/gamma_build/preprocessed-debug/Gamma/Web/bmp/paulslib.c"
/usr/bin/gcc -I/tmp/gamma_build/preprocessed-debug  -lm -ltcl8.5  -g -O5 -D GAMMA_COMPILATION -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wnested-externs -Wold-style-definition -Wredundant-decls -Wconversion -I/tmp/gamma_build/preprocessed-debug/ngspice/root -I/usr/include/c++/4.4.4/x86_64-redhat-linux -ldb-6.0  -I/tmp/gamma_build/preprocessed-debug/ngspice/root/maths/poly -I/tmp/gamma_build/preprocessed-debug/ngspice/root/frontend -I/tmp/gamma_build/preprocessed-debug/ngspice/root/spicelib/devices -I/tmp/gamma_build/preprocessed-debug/ngspice/root/xspice/icm/analog -D SENSDEBUG -D X_DISPLAY_MISSING -D CIDER -D SIMULATOR -c /tmp/gamma_build/preprocessed-debug/Gamma/Web/bmp/paulslib.c | & tee -a log
mv paulslib.o /tmp/gamma_build/object_files-debug
echo "Info: compiling /tmp/gamma_build/preprocessed-debug/Gamma/Web/bmp/bmp.c"
/usr/bin/gcc -I/tmp/gamma_build/preprocessed-debug  -lm -ltcl8.5  -g -O5 -D GAMMA_COMPILATION -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wnested-externs -Wold-style-definition -Wredundant-decls -Wconversion -I/tmp/gamma_build/preprocessed-debug/ngspice/root -I/usr/include/c++/4.4.4/x86_64-redhat-linux -ldb-6.0  -I/tmp/gamma_build/preprocessed-debug/ngspice/root/maths/poly -I/tmp/gamma_build/preprocessed-debug/ngspice/root/frontend -I/tmp/gamma_build/preprocessed-debug/ngspice/root/spicelib/devices -I/tmp/gamma_build/preprocessed-debug/ngspice/root/xspice/icm/analog -D SENSDEBUG -D X_DISPLAY_MISSING -D CIDER -D SIMULATOR -c /tmp/gamma_build/preprocessed-debug/Gamma/Web/bmp/bmp.c | & tee -a log
mv bmp.o /tmp/gamma_build/object_files-debug
echo "Info: compiling /tmp/gamma_build/preprocessed-debug/Gamma/Web/bmp/bitmaplib.c"
/usr/bin/gcc -I/tmp/gamma_build/preprocessed-debug  -lm -ltcl8.5  -g -O5 -D GAMMA_COMPILATION -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wnested-externs -Wold-style-definition -Wredundant-decls -Wconversion -I/tmp/gamma_build/preprocessed-debug/ngspice/root -I/usr/include/c++/4.4.4/x86_64-redhat-linux -ldb-6.0  -I/tmp/gamma_build/preprocessed-debug/ngspice/root/maths/poly -I/tmp/gamma_build/preprocessed-debug/ngspice/root/frontend -I/tmp/gamma_build/preprocessed-debug/ngspice/root/spicelib/devices -I/tmp/gamma_build/preprocessed-debug/ngspice/root/xspice/icm/analog -D SENSDEBUG -D X_DISPLAY_MISSING -D CIDER -D SIMULATOR -c /tmp/gamma_build/preprocessed-debug/Gamma/Web/bmp/bitmaplib.c | & tee -a log
mv bitmaplib.o /tmp/gamma_build/object_files-debug
echo "Info: compiling /tmp/gamma_build/preprocessed-debug/Gamma/LUT/look_up_table.c"
/usr/bin/gcc -I/tmp/gamma_build/preprocessed-debug  -lm -ltcl8.5  -g -O5 -D GAMMA_COMPILATION -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wnested-externs -Wold-style-definition -Wredundant-decls -Wconversion -I/tmp/gamma_build/preprocessed-debug/ngspice/root -I/usr/include/c++/4.4.4/x86_64-redhat-linux -ldb-6.0  -I/tmp/gamma_build/preprocessed-debug/ngspice/root/maths/poly -I/tmp/gamma_build/preprocessed-debug/ngspice/root/frontend -I/tmp/gamma_build/preprocessed-debug/ngspice/root/spicelib/devices -I/tmp/gamma_build/preprocessed-debug/ngspice/root/xspice/icm/analog -D SENSDEBUG -D X_DISPLAY_MISSING -D CIDER -D SIMULATOR -c /tmp/gamma_build/preprocessed-debug/Gamma/LUT/look_up_table.c | & tee -a log
mv look_up_table.o /tmp/gamma_build/object_files-debug
echo "Info: compiling /tmp/gamma_build/preprocessed-debug/Gamma/Data/ctree.c"
/usr/bin/gcc -I/tmp/gamma_build/preprocessed-debug  -lm -ltcl8.5  -g -O5 -D GAMMA_COMPILATION -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wnested-externs -Wold-style-definition -Wredundant-decls -Wconversion -I/tmp/gamma_build/preprocessed-debug/ngspice/root -I/usr/include/c++/4.4.4/x86_64-redhat-linux -ldb-6.0  -I/tmp/gamma_build/preprocessed-debug/ngspice/root/maths/poly -I/tmp/gamma_build/preprocessed-debug/ngspice/root/frontend -I/tmp/gamma_build/preprocessed-debug/ngspice/root/spicelib/devices -I/tmp/gamma_build/preprocessed-debug/ngspice/root/xspice/icm/analog -D SENSDEBUG -D X_DISPLAY_MISSING -D CIDER -D SIMULATOR -c /tmp/gamma_build/preprocessed-debug/Gamma/Data/ctree.c | & tee -a log
mv ctree.o /tmp/gamma_build/object_files-debug
