#!/bin/tcsh
setenv PATH /opt/centos/devtoolset-1.0/root/usr/bin/:$PATH
echo "Info: compiling /tmp/ramspice_build/preprocessed-silent/Gamma/Gamma.c"
/usr/bin/gcc -I/tmp/ramspice_build/preprocessed-silent  -lm -ltcl8.5  -g -O5 -D SPICE_COMPILATION -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wnested-externs -Wold-style-definition -Wredundant-decls -Wconversion -I/tmp/ramspice_build/preprocessed-silent/ngspice/root -I/usr/include/c++/4.4.4/x86_64-redhat-linux -ldb-6.0  -I/tmp/ramspice_build/preprocessed-silent/ngspice/root/maths/poly -I/tmp/ramspice_build/preprocessed-silent/ngspice/root/frontend -I/tmp/ramspice_build/preprocessed-silent/ngspice/root/spicelib/devices -I/tmp/ramspice_build/preprocessed-silent/ngspice/root/xspice/icm/analog -D SENSDEBUG -D X_DISPLAY_MISSING -D CIDER -D SIMULATOR -c /tmp/ramspice_build/preprocessed-silent/Gamma/Gamma.c | & tee -a log
mv Gamma.o /tmp/ramspice_build/object_files-silent
echo "Info: compiling /tmp/ramspice_build/preprocessed-silent/Gamma/MC/tcl_input.c"
/usr/bin/gcc -I/tmp/ramspice_build/preprocessed-silent  -lm -ltcl8.5  -g -O5 -D SPICE_COMPILATION -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wnested-externs -Wold-style-definition -Wredundant-decls -Wconversion -I/tmp/ramspice_build/preprocessed-silent/ngspice/root -I/usr/include/c++/4.4.4/x86_64-redhat-linux -ldb-6.0  -I/tmp/ramspice_build/preprocessed-silent/ngspice/root/maths/poly -I/tmp/ramspice_build/preprocessed-silent/ngspice/root/frontend -I/tmp/ramspice_build/preprocessed-silent/ngspice/root/spicelib/devices -I/tmp/ramspice_build/preprocessed-silent/ngspice/root/xspice/icm/analog -D SENSDEBUG -D X_DISPLAY_MISSING -D CIDER -D SIMULATOR -c /tmp/ramspice_build/preprocessed-silent/Gamma/MC/tcl_input.c | & tee -a log
mv tcl_input.o /tmp/ramspice_build/object_files-silent
echo "Info: compiling /tmp/ramspice_build/preprocessed-silent/Gamma/Data/ctree.c"
/usr/bin/gcc -I/tmp/ramspice_build/preprocessed-silent  -lm -ltcl8.5  -g -O5 -D SPICE_COMPILATION -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wnested-externs -Wold-style-definition -Wredundant-decls -Wconversion -I/tmp/ramspice_build/preprocessed-silent/ngspice/root -I/usr/include/c++/4.4.4/x86_64-redhat-linux -ldb-6.0  -I/tmp/ramspice_build/preprocessed-silent/ngspice/root/maths/poly -I/tmp/ramspice_build/preprocessed-silent/ngspice/root/frontend -I/tmp/ramspice_build/preprocessed-silent/ngspice/root/spicelib/devices -I/tmp/ramspice_build/preprocessed-silent/ngspice/root/xspice/icm/analog -D SENSDEBUG -D X_DISPLAY_MISSING -D CIDER -D SIMULATOR -c /tmp/ramspice_build/preprocessed-silent/Gamma/Data/ctree.c | & tee -a log
mv ctree.o /tmp/ramspice_build/object_files-silent
echo "Info: compiling /tmp/ramspice_build/preprocessed-silent/ngspice/main.c"
/usr/bin/gcc -I/tmp/ramspice_build/preprocessed-silent  -lm -ltcl8.5  -g -O5 -D SPICE_COMPILATION -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wnested-externs -Wold-style-definition -Wredundant-decls -Wconversion -I/tmp/ramspice_build/preprocessed-silent/ngspice/root -I/usr/include/c++/4.4.4/x86_64-redhat-linux -ldb-6.0  -I/tmp/ramspice_build/preprocessed-silent/ngspice/root/maths/poly -I/tmp/ramspice_build/preprocessed-silent/ngspice/root/frontend -I/tmp/ramspice_build/preprocessed-silent/ngspice/root/spicelib/devices -I/tmp/ramspice_build/preprocessed-silent/ngspice/root/xspice/icm/analog -D SENSDEBUG -D X_DISPLAY_MISSING -D CIDER -D SIMULATOR -c /tmp/ramspice_build/preprocessed-silent/ngspice/main.c | & tee -a log
mv main.o /tmp/ramspice_build/object_files-silent
