
        #include <tcl.h>
        #include <stdio.h>
        #include <stdlib.h>
        #include "Gamma/Data/ctree.h"
        #include "Gamma/LUT/look_up_table.h"
        #include "Gamma/Web/heatmap/heatmap.h"
        // Some global pointers to keep reference of the contexts this object manipulates
        float *Pcs_nmos_param_area_spacing;
float *Pcs_nmos_param_iref;
float *Pcs_nmos_param_rload;
float *Pcs_nmos_param_in;
float *Pcs_nmos_param_vdd;
float *Pcs_nmos_param_unique;
float *Pcs_nmos_look_up_tables_nch;
float *Pcs_nmos_look_up_tables_pch;
float *Pcs_nmos_size_L;
float *Pcs_nmos_size_W;
float *Pcs_nmos_size_iref;
float *Pcs_nmos_size_rin;
float *Pcs_nmos_out_V;
float *Pcs_nmos_out_Next;
float *Pcs_nmos_0_V;
float *Pcs_nmos_0_Next;
float *Pcs_nmos_in_V;
float *Pcs_nmos_in_Next;
float *Pcs_nmos_vdd_V;
float *Pcs_nmos_vdd_Next;
float *Pcs_nmos_mid_V;
float *Pcs_nmos_mid_Next;
float *Pcs_nmos_property_Adc;
float *Pcs_nmos_property_CMRR;
float *Pcs_nmos_property_PSRR;
float *Pcs_nmos_property_Rout;
float *Pcs_nmos_property_BW;
float *Pcs_nmos_property_PM;
float *Pcs_nmos_property_Cin;
float *Pcs_nmos_property_ts;
float *Pcs_nmos_property_Nt;
float *Pcs_nmos_property_Nf;
float *Pcs_nmos_property_TotalNoise;
float *Pcs_nmos_property_fc;
float *Pcs_nmos_property_Vos;
float *Pcs_nmos_property_Area;
float *Pcs_nmos_property_Power;
float *Pcs_nmos_n_ref_Ideq;
float *Pcs_nmos_n_ref_go;
float *Pcs_nmos_n_ref_gm;
float *Pcs_nmos_n_ref_cgd;
float *Pcs_nmos_n_ref_cgg;
float *Pcs_nmos_n_ref_cgs;
float *Pcs_nmos_n_ref_cgb;
float *Pcs_nmos_n_ref_cdd;
float *Pcs_nmos_n_ref_cdg;
float *Pcs_nmos_n_ref_cds;
float *Pcs_nmos_n_ref_cdb;
float *Pcs_nmos_n_ref_csd;
float *Pcs_nmos_n_ref_csg;
float *Pcs_nmos_n_ref_css;
float *Pcs_nmos_n_ref_csb;
float *Pcs_nmos_n_ref_cbd;
float *Pcs_nmos_n_ref_cbg;
float *Pcs_nmos_n_ref_cbs;
float *Pcs_nmos_n_ref_cbb;
float *Pcs_nmos_cs_nmos_circuits_PAT;
float *Pcs_nmos_config_pat_size_target;
float *Pcs_nmos_size_L_min;
float *Pcs_nmos_size_L_max;
float *Pcs_nmos_size_W_max;
float *Pcs_nmos_size_iref_min;
float *Pcs_nmos_size_iref_max;
float *Pcs_nmos_size_rin_min;
float *Pcs_nmos_size_rin_max;
float *Pcs_nmos_size_L_step;
float *Pcs_nmos_size_W_step;
float *Pcs_nmos_size_iref_step;
float *Pcs_nmos_size_rin_step;
float *Pcs_nmos_max_Adc;
float *Pcs_nmos_pat_size_target;
float *Pcs_nmos_mode_freash_op;
float *Pcs_nmos_status_index;
float *Pcs_nmos_config_size_L;
float *Pcs_nmos_config_size_W;
float *Pcs_nmos_config_size_iref;
float *Pcs_nmos_config_size_rin;
float *Pcs_nmos_status_fail;
float *Pcs_nmos_design_feedback;
float *Pcs_nmos_n_ref_bin;
float *Pcs_nmos_n_ref_W;
float *Pcs_nmos_n_ref_L;
float *Pcs_nmos_look_up_tables_nch_binning_LUT;
float *Pcs_nmos_leak;
float *Pcs_nmos_config_op_iterations;
float *Pcs_nmos_config_kcl_th;
float *Pcs_nmos_config_design_feedback_th;
float *Pcs_nmos_n_ref_gb;
float *Pcs_nmos_n_ref_Ids;
float *Pcs_nmos_look_up_tables_nch_go_ss_CONTEXT;
float *Pcs_nmos_look_up_tables_nch_gm_ss_CONTEXT;
float *Pcs_nmos_look_up_tables_nch_gb_ss_CONTEXT;
float *Pcs_nmos_look_up_tables_nch_Ids_ss_CONTEXT;
float *Pcs_nmos_Gds_in_mid;
float *Pcs_nmos_config_kcl_step;
float *Pcs_nmos_config_fail_on_properties;
float *Pcs_nmos_s;
float *Pcs_nmos_config_cgg_factor;
float *Pcs_nmos_look_up_tables_nch_cgg_ss_LUT;
float *Pcs_nmos_config_cgd_factor;
float *Pcs_nmos_look_up_tables_nch_cgd_ss_LUT;
float *Pcs_nmos_config_cgs_factor;
float *Pcs_nmos_look_up_tables_nch_cgs_ss_LUT;
float *Pcs_nmos_config_cgb_factor;
float *Pcs_nmos_look_up_tables_nch_cgb_ss_LUT;
float *Pcs_nmos_config_cdd_factor;
float *Pcs_nmos_look_up_tables_nch_cdd_ss_LUT;
float *Pcs_nmos_config_cdg_factor;
float *Pcs_nmos_look_up_tables_nch_cdg_ss_LUT;
float *Pcs_nmos_config_cdb_factor;
float *Pcs_nmos_look_up_tables_nch_cdb_ss_LUT;
float *Pcs_nmos_config_cds_factor;
float *Pcs_nmos_look_up_tables_nch_cds_ss_LUT;
float *Pcs_nmos_config_csd_factor;
float *Pcs_nmos_look_up_tables_nch_csd_ss_LUT;
float *Pcs_nmos_config_csg_factor;
float *Pcs_nmos_look_up_tables_nch_csg_ss_LUT;
float *Pcs_nmos_config_css_factor;
float *Pcs_nmos_look_up_tables_nch_css_ss_LUT;
float *Pcs_nmos_config_csb_factor;
float *Pcs_nmos_look_up_tables_nch_csb_ss_LUT;
float *Pcs_nmos_config_cbd_factor;
float *Pcs_nmos_look_up_tables_nch_cbd_ss_LUT;
float *Pcs_nmos_config_cbg_factor;
float *Pcs_nmos_look_up_tables_nch_cbg_ss_LUT;
float *Pcs_nmos_config_cbs_factor;
float *Pcs_nmos_look_up_tables_nch_cbs_ss_LUT;
float *Pcs_nmos_config_cbb_factor;
float *Pcs_nmos_look_up_tables_nch_cbb_ss_LUT;
float *Pcs_nmos_property_BW_s;
float *Pcs_nmos_p1;
float *Pcs_nmos_p2;
float *Pcs_nmos_n_ref_dNt_dvgs;
float *Pcs_nmos_n_ref_dNt_dvds;
float *Pcs_nmos_n_ref_dNt_dvbs;
float *Pcs_nmos_n_ref_dNt_dl;
float *Pcs_nmos_n_ref_Nt_unit;
float *Pcs_nmos__look_up_tables_nch_thermal_noise_ss_LUT;
float *Pcs_nmos_n_ref_Nt;
float *Pcs_nmos_n_ref_dNf_dvgs;
float *Pcs_nmos_n_ref_dNf_dvds;
float *Pcs_nmos_n_ref_dNf_dvbs;
float *Pcs_nmos_n_ref_dNf_dl;
float *Pcs_nmos_n_ref_Nf_unit;
float *Pcs_nmos__look_up_tables_nch_flicker_noise_ss_LUT;
float *Pcs_nmos_n_ref_Nf;
float *Pcs_nmos_config_shift_Adc;
float *Pcs_nmos_config_factor_Adc;
float *Pcs_nmos_config_shift_CMRR;
float *Pcs_nmos_config_factor_CMRR;
float *Pcs_nmos_config_shift_PSRR;
float *Pcs_nmos_config_factor_PSRR;
float *Pcs_nmos_config_shift_Rout;
float *Pcs_nmos_config_factor_Rout;
float *Pcs_nmos_config_shift_BW;
float *Pcs_nmos_config_factor_BW;
float *Pcs_nmos_config_shift_PM;
float *Pcs_nmos_config_factor_PM;
float *Pcs_nmos_config_shift_Cin;
float *Pcs_nmos_config_factor_Cin;
float *Pcs_nmos_config_shift_ts;
float *Pcs_nmos_config_factor_ts;
float *Pcs_nmos_config_shift_Nt;
float *Pcs_nmos_config_factor_Nt;
float *Pcs_nmos_config_shift_Nf;
float *Pcs_nmos_config_factor_Nf;
float *Pcs_nmos_config_shift_TotalNoise;
float *Pcs_nmos_config_factor_TotalNoise;
float *Pcs_nmos_config_shift_fc;
float *Pcs_nmos_config_factor_fc;
float *Pcs_nmos_config_shift_Vos;
float *Pcs_nmos_config_factor_Vos;
float *Pcs_nmos_config_shift_Area;
float *Pcs_nmos_config_factor_Area;
float *Pcs_nmos_config_shift_Power;
float *Pcs_nmos_config_factor_Power;
float *Pcs_nmos_circuit_breed_id;
float *Pcs_nmos_circuit_breed_target;

        float cs_nmos_param_area_spacing;
float cs_nmos_param_iref;
float cs_nmos_param_rload;
float cs_nmos_param_in;
float cs_nmos_param_vdd;
float cs_nmos_param_unique;
float cs_nmos_look_up_tables_nch;
float cs_nmos_look_up_tables_pch;
float cs_nmos_size_L;
float cs_nmos_size_W;
float cs_nmos_size_iref;
float cs_nmos_size_rin;
float cs_nmos_out_V;
float cs_nmos_out_Next;
float cs_nmos_0_V;
float cs_nmos_0_Next;
float cs_nmos_in_V;
float cs_nmos_in_Next;
float cs_nmos_vdd_V;
float cs_nmos_vdd_Next;
float cs_nmos_mid_V;
float cs_nmos_mid_Next;
float cs_nmos_property_Adc;
float cs_nmos_property_CMRR;
float cs_nmos_property_PSRR;
float cs_nmos_property_Rout;
float cs_nmos_property_BW;
float cs_nmos_property_PM;
float cs_nmos_property_Cin;
float cs_nmos_property_ts;
float cs_nmos_property_Nt;
float cs_nmos_property_Nf;
float cs_nmos_property_TotalNoise;
float cs_nmos_property_fc;
float cs_nmos_property_Vos;
float cs_nmos_property_Area;
float cs_nmos_property_Power;
float cs_nmos_n_ref_Ideq;
float cs_nmos_n_ref_go;
float cs_nmos_n_ref_gm;
float cs_nmos_n_ref_cgd;
float cs_nmos_n_ref_cgg;
float cs_nmos_n_ref_cgs;
float cs_nmos_n_ref_cgb;
float cs_nmos_n_ref_cdd;
float cs_nmos_n_ref_cdg;
float cs_nmos_n_ref_cds;
float cs_nmos_n_ref_cdb;
float cs_nmos_n_ref_csd;
float cs_nmos_n_ref_csg;
float cs_nmos_n_ref_css;
float cs_nmos_n_ref_csb;
float cs_nmos_n_ref_cbd;
float cs_nmos_n_ref_cbg;
float cs_nmos_n_ref_cbs;
float cs_nmos_n_ref_cbb;
float cs_nmos_cs_nmos_circuits_PAT;
float cs_nmos_config_pat_size_target;
float cs_nmos_size_L_min;
float cs_nmos_size_L_max;
float cs_nmos_size_W_max;
float cs_nmos_size_iref_min;
float cs_nmos_size_iref_max;
float cs_nmos_size_rin_min;
float cs_nmos_size_rin_max;
float cs_nmos_size_L_step;
float cs_nmos_size_W_step;
float cs_nmos_size_iref_step;
float cs_nmos_size_rin_step;
float cs_nmos_max_Adc;
float cs_nmos_pat_size_target;
float cs_nmos_mode_freash_op;
float cs_nmos_status_index;
float cs_nmos_config_size_L;
float cs_nmos_config_size_W;
float cs_nmos_config_size_iref;
float cs_nmos_config_size_rin;
float cs_nmos_status_fail;
float cs_nmos_design_feedback;
float cs_nmos_n_ref_bin;
float cs_nmos_n_ref_W;
float cs_nmos_n_ref_L;
float cs_nmos_look_up_tables_nch_binning_LUT;
float cs_nmos_leak;
float cs_nmos_config_op_iterations;
float cs_nmos_config_kcl_th;
float cs_nmos_config_design_feedback_th;
float cs_nmos_n_ref_gb;
float cs_nmos_n_ref_Ids;
float cs_nmos_look_up_tables_nch_go_ss_CONTEXT;
float cs_nmos_look_up_tables_nch_gm_ss_CONTEXT;
float cs_nmos_look_up_tables_nch_gb_ss_CONTEXT;
float cs_nmos_look_up_tables_nch_Ids_ss_CONTEXT;
float cs_nmos_Gds_in_mid;
float cs_nmos_config_kcl_step;
float cs_nmos_config_fail_on_properties;
float cs_nmos_s;
float cs_nmos_config_cgg_factor;
float cs_nmos_look_up_tables_nch_cgg_ss_LUT;
float cs_nmos_config_cgd_factor;
float cs_nmos_look_up_tables_nch_cgd_ss_LUT;
float cs_nmos_config_cgs_factor;
float cs_nmos_look_up_tables_nch_cgs_ss_LUT;
float cs_nmos_config_cgb_factor;
float cs_nmos_look_up_tables_nch_cgb_ss_LUT;
float cs_nmos_config_cdd_factor;
float cs_nmos_look_up_tables_nch_cdd_ss_LUT;
float cs_nmos_config_cdg_factor;
float cs_nmos_look_up_tables_nch_cdg_ss_LUT;
float cs_nmos_config_cdb_factor;
float cs_nmos_look_up_tables_nch_cdb_ss_LUT;
float cs_nmos_config_cds_factor;
float cs_nmos_look_up_tables_nch_cds_ss_LUT;
float cs_nmos_config_csd_factor;
float cs_nmos_look_up_tables_nch_csd_ss_LUT;
float cs_nmos_config_csg_factor;
float cs_nmos_look_up_tables_nch_csg_ss_LUT;
float cs_nmos_config_css_factor;
float cs_nmos_look_up_tables_nch_css_ss_LUT;
float cs_nmos_config_csb_factor;
float cs_nmos_look_up_tables_nch_csb_ss_LUT;
float cs_nmos_config_cbd_factor;
float cs_nmos_look_up_tables_nch_cbd_ss_LUT;
float cs_nmos_config_cbg_factor;
float cs_nmos_look_up_tables_nch_cbg_ss_LUT;
float cs_nmos_config_cbs_factor;
float cs_nmos_look_up_tables_nch_cbs_ss_LUT;
float cs_nmos_config_cbb_factor;
float cs_nmos_look_up_tables_nch_cbb_ss_LUT;
float cs_nmos_property_BW_s;
float cs_nmos_p1;
float cs_nmos_p2;
float cs_nmos_n_ref_dNt_dvgs;
float cs_nmos_n_ref_dNt_dvds;
float cs_nmos_n_ref_dNt_dvbs;
float cs_nmos_n_ref_dNt_dl;
float cs_nmos_n_ref_Nt_unit;
float cs_nmos__look_up_tables_nch_thermal_noise_ss_LUT;
float cs_nmos_n_ref_Nt;
float cs_nmos_n_ref_dNf_dvgs;
float cs_nmos_n_ref_dNf_dvds;
float cs_nmos_n_ref_dNf_dvbs;
float cs_nmos_n_ref_dNf_dl;
float cs_nmos_n_ref_Nf_unit;
float cs_nmos__look_up_tables_nch_flicker_noise_ss_LUT;
float cs_nmos_n_ref_Nf;
float cs_nmos_config_shift_Adc;
float cs_nmos_config_factor_Adc;
float cs_nmos_config_shift_CMRR;
float cs_nmos_config_factor_CMRR;
float cs_nmos_config_shift_PSRR;
float cs_nmos_config_factor_PSRR;
float cs_nmos_config_shift_Rout;
float cs_nmos_config_factor_Rout;
float cs_nmos_config_shift_BW;
float cs_nmos_config_factor_BW;
float cs_nmos_config_shift_PM;
float cs_nmos_config_factor_PM;
float cs_nmos_config_shift_Cin;
float cs_nmos_config_factor_Cin;
float cs_nmos_config_shift_ts;
float cs_nmos_config_factor_ts;
float cs_nmos_config_shift_Nt;
float cs_nmos_config_factor_Nt;
float cs_nmos_config_shift_Nf;
float cs_nmos_config_factor_Nf;
float cs_nmos_config_shift_TotalNoise;
float cs_nmos_config_factor_TotalNoise;
float cs_nmos_config_shift_fc;
float cs_nmos_config_factor_fc;
float cs_nmos_config_shift_Vos;
float cs_nmos_config_factor_Vos;
float cs_nmos_config_shift_Area;
float cs_nmos_config_factor_Area;
float cs_nmos_config_shift_Power;
float cs_nmos_config_factor_Power;
float cs_nmos_circuit_breed_id;
float cs_nmos_circuit_breed_target;

        // The compiled function
        static int tcl_gamma_cs_nmos_import_cmd(ClientData clientData,Tcl_Interp *interp,int argc,char *argv[]) {
            cs_nmos_param_area_spacing=*Pcs_nmos_param_area_spacing;
cs_nmos_param_iref=*Pcs_nmos_param_iref;
cs_nmos_param_rload=*Pcs_nmos_param_rload;
cs_nmos_param_in=*Pcs_nmos_param_in;
cs_nmos_param_vdd=*Pcs_nmos_param_vdd;
cs_nmos_param_unique=*Pcs_nmos_param_unique;
cs_nmos_look_up_tables_nch=*Pcs_nmos_look_up_tables_nch;
cs_nmos_look_up_tables_pch=*Pcs_nmos_look_up_tables_pch;
cs_nmos_size_L=*Pcs_nmos_size_L;
cs_nmos_size_W=*Pcs_nmos_size_W;
cs_nmos_size_iref=*Pcs_nmos_size_iref;
cs_nmos_size_rin=*Pcs_nmos_size_rin;
cs_nmos_out_V=*Pcs_nmos_out_V;
cs_nmos_out_Next=*Pcs_nmos_out_Next;
cs_nmos_0_V=*Pcs_nmos_0_V;
cs_nmos_0_Next=*Pcs_nmos_0_Next;
cs_nmos_in_V=*Pcs_nmos_in_V;
cs_nmos_in_Next=*Pcs_nmos_in_Next;
cs_nmos_vdd_V=*Pcs_nmos_vdd_V;
cs_nmos_vdd_Next=*Pcs_nmos_vdd_Next;
cs_nmos_mid_V=*Pcs_nmos_mid_V;
cs_nmos_mid_Next=*Pcs_nmos_mid_Next;
cs_nmos_property_Adc=*Pcs_nmos_property_Adc;
cs_nmos_property_CMRR=*Pcs_nmos_property_CMRR;
cs_nmos_property_PSRR=*Pcs_nmos_property_PSRR;
cs_nmos_property_Rout=*Pcs_nmos_property_Rout;
cs_nmos_property_BW=*Pcs_nmos_property_BW;
cs_nmos_property_PM=*Pcs_nmos_property_PM;
cs_nmos_property_Cin=*Pcs_nmos_property_Cin;
cs_nmos_property_ts=*Pcs_nmos_property_ts;
cs_nmos_property_Nt=*Pcs_nmos_property_Nt;
cs_nmos_property_Nf=*Pcs_nmos_property_Nf;
cs_nmos_property_TotalNoise=*Pcs_nmos_property_TotalNoise;
cs_nmos_property_fc=*Pcs_nmos_property_fc;
cs_nmos_property_Vos=*Pcs_nmos_property_Vos;
cs_nmos_property_Area=*Pcs_nmos_property_Area;
cs_nmos_property_Power=*Pcs_nmos_property_Power;
cs_nmos_n_ref_Ideq=*Pcs_nmos_n_ref_Ideq;
cs_nmos_n_ref_go=*Pcs_nmos_n_ref_go;
cs_nmos_n_ref_gm=*Pcs_nmos_n_ref_gm;
cs_nmos_n_ref_cgd=*Pcs_nmos_n_ref_cgd;
cs_nmos_n_ref_cgg=*Pcs_nmos_n_ref_cgg;
cs_nmos_n_ref_cgs=*Pcs_nmos_n_ref_cgs;
cs_nmos_n_ref_cgb=*Pcs_nmos_n_ref_cgb;
cs_nmos_n_ref_cdd=*Pcs_nmos_n_ref_cdd;
cs_nmos_n_ref_cdg=*Pcs_nmos_n_ref_cdg;
cs_nmos_n_ref_cds=*Pcs_nmos_n_ref_cds;
cs_nmos_n_ref_cdb=*Pcs_nmos_n_ref_cdb;
cs_nmos_n_ref_csd=*Pcs_nmos_n_ref_csd;
cs_nmos_n_ref_csg=*Pcs_nmos_n_ref_csg;
cs_nmos_n_ref_css=*Pcs_nmos_n_ref_css;
cs_nmos_n_ref_csb=*Pcs_nmos_n_ref_csb;
cs_nmos_n_ref_cbd=*Pcs_nmos_n_ref_cbd;
cs_nmos_n_ref_cbg=*Pcs_nmos_n_ref_cbg;
cs_nmos_n_ref_cbs=*Pcs_nmos_n_ref_cbs;
cs_nmos_n_ref_cbb=*Pcs_nmos_n_ref_cbb;
cs_nmos_config_pat_size_target=*Pcs_nmos_config_pat_size_target;
cs_nmos_size_L_min=*Pcs_nmos_size_L_min;
cs_nmos_size_L_max=*Pcs_nmos_size_L_max;
cs_nmos_size_W_max=*Pcs_nmos_size_W_max;
cs_nmos_size_iref_min=*Pcs_nmos_size_iref_min;
cs_nmos_size_iref_max=*Pcs_nmos_size_iref_max;
cs_nmos_size_rin_min=*Pcs_nmos_size_rin_min;
cs_nmos_size_rin_max=*Pcs_nmos_size_rin_max;
cs_nmos_size_L_step=*Pcs_nmos_size_L_step;
cs_nmos_size_W_step=*Pcs_nmos_size_W_step;
cs_nmos_size_iref_step=*Pcs_nmos_size_iref_step;
cs_nmos_size_rin_step=*Pcs_nmos_size_rin_step;
cs_nmos_max_Adc=*Pcs_nmos_max_Adc;
cs_nmos_pat_size_target=*Pcs_nmos_pat_size_target;
cs_nmos_mode_freash_op=*Pcs_nmos_mode_freash_op;
cs_nmos_status_index=*Pcs_nmos_status_index;
cs_nmos_config_size_L=*Pcs_nmos_config_size_L;
cs_nmos_config_size_W=*Pcs_nmos_config_size_W;
cs_nmos_config_size_iref=*Pcs_nmos_config_size_iref;
cs_nmos_config_size_rin=*Pcs_nmos_config_size_rin;
cs_nmos_status_fail=*Pcs_nmos_status_fail;
cs_nmos_design_feedback=*Pcs_nmos_design_feedback;
cs_nmos_n_ref_bin=*Pcs_nmos_n_ref_bin;
cs_nmos_n_ref_W=*Pcs_nmos_n_ref_W;
cs_nmos_n_ref_L=*Pcs_nmos_n_ref_L;
cs_nmos_leak=*Pcs_nmos_leak;
cs_nmos_config_op_iterations=*Pcs_nmos_config_op_iterations;
cs_nmos_config_kcl_th=*Pcs_nmos_config_kcl_th;
cs_nmos_config_design_feedback_th=*Pcs_nmos_config_design_feedback_th;
cs_nmos_n_ref_gb=*Pcs_nmos_n_ref_gb;
cs_nmos_n_ref_Ids=*Pcs_nmos_n_ref_Ids;
cs_nmos_Gds_in_mid=*Pcs_nmos_Gds_in_mid;
cs_nmos_config_kcl_step=*Pcs_nmos_config_kcl_step;
cs_nmos_config_fail_on_properties=*Pcs_nmos_config_fail_on_properties;
cs_nmos_s=*Pcs_nmos_s;
cs_nmos_config_cgg_factor=*Pcs_nmos_config_cgg_factor;
cs_nmos_config_cgd_factor=*Pcs_nmos_config_cgd_factor;
cs_nmos_config_cgs_factor=*Pcs_nmos_config_cgs_factor;
cs_nmos_config_cgb_factor=*Pcs_nmos_config_cgb_factor;
cs_nmos_config_cdd_factor=*Pcs_nmos_config_cdd_factor;
cs_nmos_config_cdg_factor=*Pcs_nmos_config_cdg_factor;
cs_nmos_config_cdb_factor=*Pcs_nmos_config_cdb_factor;
cs_nmos_config_cds_factor=*Pcs_nmos_config_cds_factor;
cs_nmos_config_csd_factor=*Pcs_nmos_config_csd_factor;
cs_nmos_config_csg_factor=*Pcs_nmos_config_csg_factor;
cs_nmos_config_css_factor=*Pcs_nmos_config_css_factor;
cs_nmos_config_csb_factor=*Pcs_nmos_config_csb_factor;
cs_nmos_config_cbd_factor=*Pcs_nmos_config_cbd_factor;
cs_nmos_config_cbg_factor=*Pcs_nmos_config_cbg_factor;
cs_nmos_config_cbs_factor=*Pcs_nmos_config_cbs_factor;
cs_nmos_config_cbb_factor=*Pcs_nmos_config_cbb_factor;
cs_nmos_property_BW_s=*Pcs_nmos_property_BW_s;
cs_nmos_p1=*Pcs_nmos_p1;
cs_nmos_p2=*Pcs_nmos_p2;
cs_nmos_n_ref_dNt_dvgs=*Pcs_nmos_n_ref_dNt_dvgs;
cs_nmos_n_ref_dNt_dvds=*Pcs_nmos_n_ref_dNt_dvds;
cs_nmos_n_ref_dNt_dvbs=*Pcs_nmos_n_ref_dNt_dvbs;
cs_nmos_n_ref_dNt_dl=*Pcs_nmos_n_ref_dNt_dl;
cs_nmos_n_ref_Nt_unit=*Pcs_nmos_n_ref_Nt_unit;
cs_nmos_n_ref_Nt=*Pcs_nmos_n_ref_Nt;
cs_nmos_n_ref_dNf_dvgs=*Pcs_nmos_n_ref_dNf_dvgs;
cs_nmos_n_ref_dNf_dvds=*Pcs_nmos_n_ref_dNf_dvds;
cs_nmos_n_ref_dNf_dvbs=*Pcs_nmos_n_ref_dNf_dvbs;
cs_nmos_n_ref_dNf_dl=*Pcs_nmos_n_ref_dNf_dl;
cs_nmos_n_ref_Nf_unit=*Pcs_nmos_n_ref_Nf_unit;
cs_nmos_n_ref_Nf=*Pcs_nmos_n_ref_Nf;
cs_nmos_config_shift_Adc=*Pcs_nmos_config_shift_Adc;
cs_nmos_config_factor_Adc=*Pcs_nmos_config_factor_Adc;
cs_nmos_config_shift_CMRR=*Pcs_nmos_config_shift_CMRR;
cs_nmos_config_factor_CMRR=*Pcs_nmos_config_factor_CMRR;
cs_nmos_config_shift_PSRR=*Pcs_nmos_config_shift_PSRR;
cs_nmos_config_factor_PSRR=*Pcs_nmos_config_factor_PSRR;
cs_nmos_config_shift_Rout=*Pcs_nmos_config_shift_Rout;
cs_nmos_config_factor_Rout=*Pcs_nmos_config_factor_Rout;
cs_nmos_config_shift_BW=*Pcs_nmos_config_shift_BW;
cs_nmos_config_factor_BW=*Pcs_nmos_config_factor_BW;
cs_nmos_config_shift_PM=*Pcs_nmos_config_shift_PM;
cs_nmos_config_factor_PM=*Pcs_nmos_config_factor_PM;
cs_nmos_config_shift_Cin=*Pcs_nmos_config_shift_Cin;
cs_nmos_config_factor_Cin=*Pcs_nmos_config_factor_Cin;
cs_nmos_config_shift_ts=*Pcs_nmos_config_shift_ts;
cs_nmos_config_factor_ts=*Pcs_nmos_config_factor_ts;
cs_nmos_config_shift_Nt=*Pcs_nmos_config_shift_Nt;
cs_nmos_config_factor_Nt=*Pcs_nmos_config_factor_Nt;
cs_nmos_config_shift_Nf=*Pcs_nmos_config_shift_Nf;
cs_nmos_config_factor_Nf=*Pcs_nmos_config_factor_Nf;
cs_nmos_config_shift_TotalNoise=*Pcs_nmos_config_shift_TotalNoise;
cs_nmos_config_factor_TotalNoise=*Pcs_nmos_config_factor_TotalNoise;
cs_nmos_config_shift_fc=*Pcs_nmos_config_shift_fc;
cs_nmos_config_factor_fc=*Pcs_nmos_config_factor_fc;
cs_nmos_config_shift_Vos=*Pcs_nmos_config_shift_Vos;
cs_nmos_config_factor_Vos=*Pcs_nmos_config_factor_Vos;
cs_nmos_config_shift_Area=*Pcs_nmos_config_shift_Area;
cs_nmos_config_factor_Area=*Pcs_nmos_config_factor_Area;
cs_nmos_config_shift_Power=*Pcs_nmos_config_shift_Power;
cs_nmos_config_factor_Power=*Pcs_nmos_config_factor_Power;
cs_nmos_circuit_breed_id=*Pcs_nmos_circuit_breed_id;
cs_nmos_circuit_breed_target=*Pcs_nmos_circuit_breed_target;

            return TCL_OK;
        }
        static int tcl_gamma_cs_nmos_export_cmd(ClientData clientData,Tcl_Interp *interp,int argc,char *argv[]) {
            *Pcs_nmos_param_area_spacing=cs_nmos_param_area_spacing;
*Pcs_nmos_param_iref=cs_nmos_param_iref;
*Pcs_nmos_param_rload=cs_nmos_param_rload;
*Pcs_nmos_param_in=cs_nmos_param_in;
*Pcs_nmos_param_vdd=cs_nmos_param_vdd;
*Pcs_nmos_param_unique=cs_nmos_param_unique;
*Pcs_nmos_look_up_tables_nch=cs_nmos_look_up_tables_nch;
*Pcs_nmos_look_up_tables_pch=cs_nmos_look_up_tables_pch;
*Pcs_nmos_size_L=cs_nmos_size_L;
*Pcs_nmos_size_W=cs_nmos_size_W;
*Pcs_nmos_size_iref=cs_nmos_size_iref;
*Pcs_nmos_size_rin=cs_nmos_size_rin;
*Pcs_nmos_out_V=cs_nmos_out_V;
*Pcs_nmos_out_Next=cs_nmos_out_Next;
*Pcs_nmos_0_V=cs_nmos_0_V;
*Pcs_nmos_0_Next=cs_nmos_0_Next;
*Pcs_nmos_in_V=cs_nmos_in_V;
*Pcs_nmos_in_Next=cs_nmos_in_Next;
*Pcs_nmos_vdd_V=cs_nmos_vdd_V;
*Pcs_nmos_vdd_Next=cs_nmos_vdd_Next;
*Pcs_nmos_mid_V=cs_nmos_mid_V;
*Pcs_nmos_mid_Next=cs_nmos_mid_Next;
*Pcs_nmos_property_Adc=cs_nmos_property_Adc;
*Pcs_nmos_property_CMRR=cs_nmos_property_CMRR;
*Pcs_nmos_property_PSRR=cs_nmos_property_PSRR;
*Pcs_nmos_property_Rout=cs_nmos_property_Rout;
*Pcs_nmos_property_BW=cs_nmos_property_BW;
*Pcs_nmos_property_PM=cs_nmos_property_PM;
*Pcs_nmos_property_Cin=cs_nmos_property_Cin;
*Pcs_nmos_property_ts=cs_nmos_property_ts;
*Pcs_nmos_property_Nt=cs_nmos_property_Nt;
*Pcs_nmos_property_Nf=cs_nmos_property_Nf;
*Pcs_nmos_property_TotalNoise=cs_nmos_property_TotalNoise;
*Pcs_nmos_property_fc=cs_nmos_property_fc;
*Pcs_nmos_property_Vos=cs_nmos_property_Vos;
*Pcs_nmos_property_Area=cs_nmos_property_Area;
*Pcs_nmos_property_Power=cs_nmos_property_Power;
*Pcs_nmos_n_ref_Ideq=cs_nmos_n_ref_Ideq;
*Pcs_nmos_n_ref_go=cs_nmos_n_ref_go;
*Pcs_nmos_n_ref_gm=cs_nmos_n_ref_gm;
*Pcs_nmos_n_ref_cgd=cs_nmos_n_ref_cgd;
*Pcs_nmos_n_ref_cgg=cs_nmos_n_ref_cgg;
*Pcs_nmos_n_ref_cgs=cs_nmos_n_ref_cgs;
*Pcs_nmos_n_ref_cgb=cs_nmos_n_ref_cgb;
*Pcs_nmos_n_ref_cdd=cs_nmos_n_ref_cdd;
*Pcs_nmos_n_ref_cdg=cs_nmos_n_ref_cdg;
*Pcs_nmos_n_ref_cds=cs_nmos_n_ref_cds;
*Pcs_nmos_n_ref_cdb=cs_nmos_n_ref_cdb;
*Pcs_nmos_n_ref_csd=cs_nmos_n_ref_csd;
*Pcs_nmos_n_ref_csg=cs_nmos_n_ref_csg;
*Pcs_nmos_n_ref_css=cs_nmos_n_ref_css;
*Pcs_nmos_n_ref_csb=cs_nmos_n_ref_csb;
*Pcs_nmos_n_ref_cbd=cs_nmos_n_ref_cbd;
*Pcs_nmos_n_ref_cbg=cs_nmos_n_ref_cbg;
*Pcs_nmos_n_ref_cbs=cs_nmos_n_ref_cbs;
*Pcs_nmos_n_ref_cbb=cs_nmos_n_ref_cbb;
*Pcs_nmos_config_pat_size_target=cs_nmos_config_pat_size_target;
*Pcs_nmos_size_L_min=cs_nmos_size_L_min;
*Pcs_nmos_size_L_max=cs_nmos_size_L_max;
*Pcs_nmos_size_W_max=cs_nmos_size_W_max;
*Pcs_nmos_size_iref_min=cs_nmos_size_iref_min;
*Pcs_nmos_size_iref_max=cs_nmos_size_iref_max;
*Pcs_nmos_size_rin_min=cs_nmos_size_rin_min;
*Pcs_nmos_size_rin_max=cs_nmos_size_rin_max;
*Pcs_nmos_size_L_step=cs_nmos_size_L_step;
*Pcs_nmos_size_W_step=cs_nmos_size_W_step;
*Pcs_nmos_size_iref_step=cs_nmos_size_iref_step;
*Pcs_nmos_size_rin_step=cs_nmos_size_rin_step;
*Pcs_nmos_max_Adc=cs_nmos_max_Adc;
*Pcs_nmos_pat_size_target=cs_nmos_pat_size_target;
*Pcs_nmos_mode_freash_op=cs_nmos_mode_freash_op;
*Pcs_nmos_status_index=cs_nmos_status_index;
*Pcs_nmos_config_size_L=cs_nmos_config_size_L;
*Pcs_nmos_config_size_W=cs_nmos_config_size_W;
*Pcs_nmos_config_size_iref=cs_nmos_config_size_iref;
*Pcs_nmos_config_size_rin=cs_nmos_config_size_rin;
*Pcs_nmos_status_fail=cs_nmos_status_fail;
*Pcs_nmos_design_feedback=cs_nmos_design_feedback;
*Pcs_nmos_n_ref_bin=cs_nmos_n_ref_bin;
*Pcs_nmos_n_ref_W=cs_nmos_n_ref_W;
*Pcs_nmos_n_ref_L=cs_nmos_n_ref_L;
*Pcs_nmos_leak=cs_nmos_leak;
*Pcs_nmos_config_op_iterations=cs_nmos_config_op_iterations;
*Pcs_nmos_config_kcl_th=cs_nmos_config_kcl_th;
*Pcs_nmos_config_design_feedback_th=cs_nmos_config_design_feedback_th;
*Pcs_nmos_n_ref_gb=cs_nmos_n_ref_gb;
*Pcs_nmos_n_ref_Ids=cs_nmos_n_ref_Ids;
*Pcs_nmos_Gds_in_mid=cs_nmos_Gds_in_mid;
*Pcs_nmos_config_kcl_step=cs_nmos_config_kcl_step;
*Pcs_nmos_config_fail_on_properties=cs_nmos_config_fail_on_properties;
*Pcs_nmos_s=cs_nmos_s;
*Pcs_nmos_config_cgg_factor=cs_nmos_config_cgg_factor;
*Pcs_nmos_config_cgd_factor=cs_nmos_config_cgd_factor;
*Pcs_nmos_config_cgs_factor=cs_nmos_config_cgs_factor;
*Pcs_nmos_config_cgb_factor=cs_nmos_config_cgb_factor;
*Pcs_nmos_config_cdd_factor=cs_nmos_config_cdd_factor;
*Pcs_nmos_config_cdg_factor=cs_nmos_config_cdg_factor;
*Pcs_nmos_config_cdb_factor=cs_nmos_config_cdb_factor;
*Pcs_nmos_config_cds_factor=cs_nmos_config_cds_factor;
*Pcs_nmos_config_csd_factor=cs_nmos_config_csd_factor;
*Pcs_nmos_config_csg_factor=cs_nmos_config_csg_factor;
*Pcs_nmos_config_css_factor=cs_nmos_config_css_factor;
*Pcs_nmos_config_csb_factor=cs_nmos_config_csb_factor;
*Pcs_nmos_config_cbd_factor=cs_nmos_config_cbd_factor;
*Pcs_nmos_config_cbg_factor=cs_nmos_config_cbg_factor;
*Pcs_nmos_config_cbs_factor=cs_nmos_config_cbs_factor;
*Pcs_nmos_config_cbb_factor=cs_nmos_config_cbb_factor;
*Pcs_nmos_property_BW_s=cs_nmos_property_BW_s;
*Pcs_nmos_p1=cs_nmos_p1;
*Pcs_nmos_p2=cs_nmos_p2;
*Pcs_nmos_n_ref_dNt_dvgs=cs_nmos_n_ref_dNt_dvgs;
*Pcs_nmos_n_ref_dNt_dvds=cs_nmos_n_ref_dNt_dvds;
*Pcs_nmos_n_ref_dNt_dvbs=cs_nmos_n_ref_dNt_dvbs;
*Pcs_nmos_n_ref_dNt_dl=cs_nmos_n_ref_dNt_dl;
*Pcs_nmos_n_ref_Nt_unit=cs_nmos_n_ref_Nt_unit;
*Pcs_nmos_n_ref_Nt=cs_nmos_n_ref_Nt;
*Pcs_nmos_n_ref_dNf_dvgs=cs_nmos_n_ref_dNf_dvgs;
*Pcs_nmos_n_ref_dNf_dvds=cs_nmos_n_ref_dNf_dvds;
*Pcs_nmos_n_ref_dNf_dvbs=cs_nmos_n_ref_dNf_dvbs;
*Pcs_nmos_n_ref_dNf_dl=cs_nmos_n_ref_dNf_dl;
*Pcs_nmos_n_ref_Nf_unit=cs_nmos_n_ref_Nf_unit;
*Pcs_nmos_n_ref_Nf=cs_nmos_n_ref_Nf;
*Pcs_nmos_config_shift_Adc=cs_nmos_config_shift_Adc;
*Pcs_nmos_config_factor_Adc=cs_nmos_config_factor_Adc;
*Pcs_nmos_config_shift_CMRR=cs_nmos_config_shift_CMRR;
*Pcs_nmos_config_factor_CMRR=cs_nmos_config_factor_CMRR;
*Pcs_nmos_config_shift_PSRR=cs_nmos_config_shift_PSRR;
*Pcs_nmos_config_factor_PSRR=cs_nmos_config_factor_PSRR;
*Pcs_nmos_config_shift_Rout=cs_nmos_config_shift_Rout;
*Pcs_nmos_config_factor_Rout=cs_nmos_config_factor_Rout;
*Pcs_nmos_config_shift_BW=cs_nmos_config_shift_BW;
*Pcs_nmos_config_factor_BW=cs_nmos_config_factor_BW;
*Pcs_nmos_config_shift_PM=cs_nmos_config_shift_PM;
*Pcs_nmos_config_factor_PM=cs_nmos_config_factor_PM;
*Pcs_nmos_config_shift_Cin=cs_nmos_config_shift_Cin;
*Pcs_nmos_config_factor_Cin=cs_nmos_config_factor_Cin;
*Pcs_nmos_config_shift_ts=cs_nmos_config_shift_ts;
*Pcs_nmos_config_factor_ts=cs_nmos_config_factor_ts;
*Pcs_nmos_config_shift_Nt=cs_nmos_config_shift_Nt;
*Pcs_nmos_config_factor_Nt=cs_nmos_config_factor_Nt;
*Pcs_nmos_config_shift_Nf=cs_nmos_config_shift_Nf;
*Pcs_nmos_config_factor_Nf=cs_nmos_config_factor_Nf;
*Pcs_nmos_config_shift_TotalNoise=cs_nmos_config_shift_TotalNoise;
*Pcs_nmos_config_factor_TotalNoise=cs_nmos_config_factor_TotalNoise;
*Pcs_nmos_config_shift_fc=cs_nmos_config_shift_fc;
*Pcs_nmos_config_factor_fc=cs_nmos_config_factor_fc;
*Pcs_nmos_config_shift_Vos=cs_nmos_config_shift_Vos;
*Pcs_nmos_config_factor_Vos=cs_nmos_config_factor_Vos;
*Pcs_nmos_config_shift_Area=cs_nmos_config_shift_Area;
*Pcs_nmos_config_factor_Area=cs_nmos_config_factor_Area;
*Pcs_nmos_config_shift_Power=cs_nmos_config_shift_Power;
*Pcs_nmos_config_factor_Power=cs_nmos_config_factor_Power;
*Pcs_nmos_circuit_breed_id=cs_nmos_circuit_breed_id;
*Pcs_nmos_circuit_breed_target=cs_nmos_circuit_breed_target;

            return TCL_OK;
        }
        static int tcl_gamma_cs_nmos_op_cmd(ClientData clientData,Tcl_Interp *interp,int argc,char *argv[]) {
            //            Tcl_ResetResult(interp);
            if (cs_nmos_mode_freash_op) {
cs_nmos_out_V=cs_nmos_vdd_V/2;
cs_nmos_in_V=cs_nmos_param_in;
cs_nmos_mid_V=cs_nmos_vdd_V/2;
}
cs_nmos_status_index=0;
if(cs_nmos_config_size_L!=0) cs_nmos_size_L=cs_nmos_config_size_L;
if(cs_nmos_config_size_W!=0) cs_nmos_size_W=cs_nmos_config_size_W;
if(cs_nmos_config_size_iref!=0) cs_nmos_size_iref=cs_nmos_config_size_iref;
if(cs_nmos_config_size_rin!=0) cs_nmos_size_rin=cs_nmos_config_size_rin;
cs_nmos_vdd_V=1.1;
cs_nmos_0_V=0;
// Calculating circuit operating point:
int op_it=0;
cs_nmos_status_fail=-1;
cs_nmos_design_feedback=1000;
cs_nmos_n_ref_bin=get_transistor_bin(Pcs_nmos_look_up_tables_nch_binning_LUT,cs_nmos_n_ref_L,cs_nmos_n_ref_W);
cs_nmos_leak=1e3;
float node_step=0;
for (op_it=0;(op_it<cs_nmos_config_op_iterations)&&((cs_nmos_leak>cs_nmos_config_kcl_th)||(cs_nmos_design_feedback>cs_nmos_config_design_feedback_th));op_it++) {
float previous_out_dc=cs_nmos_out_V;
composite_gamma_gcc_interpolate_2p3(cs_nmos_n_ref_bin,Pcs_nmos_look_up_tables_nch_Ids_ss_CONTEXT,Pcs_nmos_look_up_tables_nch_gm_ss_CONTEXT,Pcs_nmos_look_up_tables_nch_go_ss_CONTEXT,Pcs_nmos_look_up_tables_nch_gb_ss_CONTEXT,&(cs_nmos_n_ref_gb),&(cs_nmos_n_ref_gm),&(cs_nmos_n_ref_go),&(cs_nmos_n_ref_Ids),(cs_nmos_mid_V)-(cs_nmos_0_V),(cs_nmos_out_V)-(cs_nmos_0_V),(cs_nmos_0_V)-(cs_nmos_0_V),cs_nmos_size_L,cs_nmos_size_W);
if (cs_nmos_n_ref_Ids<0) cs_nmos_n_ref_Ids=0;
if (cs_nmos_n_ref_Ids>1e-3) cs_nmos_n_ref_Ids=1e-3;
cs_nmos_Gds_in_mid=1.0/cs_nmos_size_rin;
if (cs_nmos_n_ref_gm==0) cs_nmos_n_ref_gm=1e-6;
if (cs_nmos_n_ref_go==0) cs_nmos_n_ref_go=1e-6;
// Updating node voltages
cs_nmos_leak=0;
node_step=cs_nmos_config_kcl_step*(0)/(cs_nmos_Gds_in_mid);
if (node_step<-0.02) node_step=-0.02;
if (node_step>0.02) node_step=0.02;
cs_nmos_in_V+=node_step;
if (fabs(0)>cs_nmos_leak) cs_nmos_leak=fabs(0);
if (cs_nmos_in_V<0) cs_nmos_in_V=0;
if (cs_nmos_in_V>1.1) cs_nmos_in_V=1.1;
node_step=cs_nmos_config_kcl_step*(0)/(cs_nmos_Gds_in_mid);
if (node_step<-0.02) node_step=-0.02;
if (node_step>0.02) node_step=0.02;
cs_nmos_mid_V+=node_step;
if (fabs(0)>cs_nmos_leak) cs_nmos_leak=fabs(0);
if (cs_nmos_mid_V<0) cs_nmos_mid_V=0;
if (cs_nmos_mid_V>1.1) cs_nmos_mid_V=1.1;
node_step=cs_nmos_config_kcl_step*(cs_nmos_size_iref-cs_nmos_n_ref_Ids)/(cs_nmos_n_ref_go);
if (node_step<-0.02) node_step=-0.02;
if (node_step>0.02) node_step=0.02;
cs_nmos_out_V+=node_step;
if (fabs(cs_nmos_size_iref-cs_nmos_n_ref_Ids)>cs_nmos_leak) cs_nmos_leak=fabs(cs_nmos_size_iref-cs_nmos_n_ref_Ids);
if (cs_nmos_out_V<0) cs_nmos_out_V=0;
if (cs_nmos_out_V>1.1) cs_nmos_out_V=1.1;
cs_nmos_design_feedback=0;
}
if (op_it>=cs_nmos_config_op_iterations) {cs_nmos_status_fail=cs_nmos_leak; return TCL_ERROR;}
if (cs_nmos_0_V>cs_nmos_out_V) {cs_nmos_status_fail=3; return TCL_ERROR;}
float W,M;
double Det=(-(-cs_nmos_Gds_in_mid*(-cs_nmos_n_ref_go)));
double Ted=1/Det;
cs_nmos_property_Adc=Ted*((-(-cs_nmos_Gds_in_mid)*cs_nmos_n_ref_gm));
cs_nmos_property_CMRR=cs_nmos_property_Adc;
cs_nmos_property_PSRR=Ted*((-(-0)));
cs_nmos_property_Adc=fabs(cs_nmos_property_Adc);
if ((cs_nmos_property_Adc<1)&&(cs_nmos_config_fail_on_properties)) {cs_nmos_status_fail=2; return TCL_ERROR;}
cs_nmos_property_Rout=fabs(((-(-cs_nmos_Gds_in_mid)))*Ted);
//AC output: (-((-cs_nmos_Gds_in_mid)*(cs_nmos_n_ref_gm+cs_nmos_n_ref_cdg*cs_nmos_s)*(-cs_nmos_param_in)-(cs_nmos_Gds_in_mid+cs_nmos_n_ref_cgg*cs_nmos_s)*(-(cs_nmos_size_iref-cs_nmos_n_ref_Ideq))))/(-((-(cs_nmos_Gds_in_mid+cs_nmos_n_ref_cgg*cs_nmos_s)*(-(cs_nmos_n_ref_go+cs_nmos_n_ref_cdd*cs_nmos_s)))+cs_nmos_n_ref_cgd*cs_nmos_s*(-(cs_nmos_n_ref_gm+cs_nmos_n_ref_cdg*cs_nmos_s))))
//AC gain: (-(-cs_nmos_Gds_in_mid)*(cs_nmos_n_ref_gm+cs_nmos_n_ref_cdg*cs_nmos_s))/(-((-(cs_nmos_Gds_in_mid+cs_nmos_n_ref_cgg*cs_nmos_s)*(-(cs_nmos_n_ref_go+cs_nmos_n_ref_cdd*cs_nmos_s)))+cs_nmos_n_ref_cgd*cs_nmos_s*(-(cs_nmos_n_ref_gm+cs_nmos_n_ref_cdg*cs_nmos_s))))
cs_nmos_n_ref_cgg=gamma_gcc_interpolate_4(Pcs_nmos_look_up_tables_nch_cgg_ss_LUT,(cs_nmos_mid_V)-(cs_nmos_0_V),(cs_nmos_out_V)-(cs_nmos_0_V),(cs_nmos_0_V)-(cs_nmos_0_V),cs_nmos_size_L)*cs_nmos_size_L*cs_nmos_size_W*cs_nmos_config_cgg_factor;
cs_nmos_n_ref_cgd=gamma_gcc_interpolate_4(Pcs_nmos_look_up_tables_nch_cgd_ss_LUT,(cs_nmos_mid_V)-(cs_nmos_0_V),(cs_nmos_out_V)-(cs_nmos_0_V),(cs_nmos_0_V)-(cs_nmos_0_V),cs_nmos_size_L)*cs_nmos_size_L*cs_nmos_size_W*cs_nmos_config_cgd_factor;
cs_nmos_n_ref_cgs=gamma_gcc_interpolate_4(Pcs_nmos_look_up_tables_nch_cgs_ss_LUT,(cs_nmos_mid_V)-(cs_nmos_0_V),(cs_nmos_out_V)-(cs_nmos_0_V),(cs_nmos_0_V)-(cs_nmos_0_V),cs_nmos_size_L)*cs_nmos_size_L*cs_nmos_size_W*cs_nmos_config_cgs_factor;
cs_nmos_n_ref_cgb=gamma_gcc_interpolate_4(Pcs_nmos_look_up_tables_nch_cgb_ss_LUT,(cs_nmos_mid_V)-(cs_nmos_0_V),(cs_nmos_out_V)-(cs_nmos_0_V),(cs_nmos_0_V)-(cs_nmos_0_V),cs_nmos_size_L)*cs_nmos_size_L*cs_nmos_size_W*cs_nmos_config_cgb_factor;
cs_nmos_n_ref_cdd=gamma_gcc_interpolate_4(Pcs_nmos_look_up_tables_nch_cdd_ss_LUT,(cs_nmos_mid_V)-(cs_nmos_0_V),(cs_nmos_out_V)-(cs_nmos_0_V),(cs_nmos_0_V)-(cs_nmos_0_V),cs_nmos_size_L)*cs_nmos_size_L*cs_nmos_size_W*cs_nmos_config_cdd_factor;
cs_nmos_n_ref_cdg=gamma_gcc_interpolate_4(Pcs_nmos_look_up_tables_nch_cdg_ss_LUT,(cs_nmos_mid_V)-(cs_nmos_0_V),(cs_nmos_out_V)-(cs_nmos_0_V),(cs_nmos_0_V)-(cs_nmos_0_V),cs_nmos_size_L)*cs_nmos_size_L*cs_nmos_size_W*cs_nmos_config_cdg_factor;
cs_nmos_n_ref_cdb=gamma_gcc_interpolate_4(Pcs_nmos_look_up_tables_nch_cdb_ss_LUT,(cs_nmos_mid_V)-(cs_nmos_0_V),(cs_nmos_out_V)-(cs_nmos_0_V),(cs_nmos_0_V)-(cs_nmos_0_V),cs_nmos_size_L)*cs_nmos_size_L*cs_nmos_size_W*cs_nmos_config_cdb_factor;
cs_nmos_n_ref_cds=gamma_gcc_interpolate_4(Pcs_nmos_look_up_tables_nch_cds_ss_LUT,(cs_nmos_mid_V)-(cs_nmos_0_V),(cs_nmos_out_V)-(cs_nmos_0_V),(cs_nmos_0_V)-(cs_nmos_0_V),cs_nmos_size_L)*cs_nmos_size_L*cs_nmos_size_W*cs_nmos_config_cds_factor;
cs_nmos_n_ref_csd=gamma_gcc_interpolate_4(Pcs_nmos_look_up_tables_nch_csd_ss_LUT,(cs_nmos_mid_V)-(cs_nmos_0_V),(cs_nmos_out_V)-(cs_nmos_0_V),(cs_nmos_0_V)-(cs_nmos_0_V),cs_nmos_size_L)*cs_nmos_size_L*cs_nmos_size_W*cs_nmos_config_csd_factor;
cs_nmos_n_ref_csg=gamma_gcc_interpolate_4(Pcs_nmos_look_up_tables_nch_csg_ss_LUT,(cs_nmos_mid_V)-(cs_nmos_0_V),(cs_nmos_out_V)-(cs_nmos_0_V),(cs_nmos_0_V)-(cs_nmos_0_V),cs_nmos_size_L)*cs_nmos_size_L*cs_nmos_size_W*cs_nmos_config_csg_factor;
cs_nmos_n_ref_css=gamma_gcc_interpolate_4(Pcs_nmos_look_up_tables_nch_css_ss_LUT,(cs_nmos_mid_V)-(cs_nmos_0_V),(cs_nmos_out_V)-(cs_nmos_0_V),(cs_nmos_0_V)-(cs_nmos_0_V),cs_nmos_size_L)*cs_nmos_size_L*cs_nmos_size_W*cs_nmos_config_css_factor;
cs_nmos_n_ref_csb=gamma_gcc_interpolate_4(Pcs_nmos_look_up_tables_nch_csb_ss_LUT,(cs_nmos_mid_V)-(cs_nmos_0_V),(cs_nmos_out_V)-(cs_nmos_0_V),(cs_nmos_0_V)-(cs_nmos_0_V),cs_nmos_size_L)*cs_nmos_size_L*cs_nmos_size_W*cs_nmos_config_csb_factor;
cs_nmos_n_ref_cbd=gamma_gcc_interpolate_4(Pcs_nmos_look_up_tables_nch_cbd_ss_LUT,(cs_nmos_mid_V)-(cs_nmos_0_V),(cs_nmos_out_V)-(cs_nmos_0_V),(cs_nmos_0_V)-(cs_nmos_0_V),cs_nmos_size_L)*cs_nmos_size_L*cs_nmos_size_W*cs_nmos_config_cbd_factor;
cs_nmos_n_ref_cbg=gamma_gcc_interpolate_4(Pcs_nmos_look_up_tables_nch_cbg_ss_LUT,(cs_nmos_mid_V)-(cs_nmos_0_V),(cs_nmos_out_V)-(cs_nmos_0_V),(cs_nmos_0_V)-(cs_nmos_0_V),cs_nmos_size_L)*cs_nmos_size_L*cs_nmos_size_W*cs_nmos_config_cbg_factor;
cs_nmos_n_ref_cbs=gamma_gcc_interpolate_4(Pcs_nmos_look_up_tables_nch_cbs_ss_LUT,(cs_nmos_mid_V)-(cs_nmos_0_V),(cs_nmos_out_V)-(cs_nmos_0_V),(cs_nmos_0_V)-(cs_nmos_0_V),cs_nmos_size_L)*cs_nmos_size_L*cs_nmos_size_W*cs_nmos_config_cbs_factor;
cs_nmos_n_ref_cbb=gamma_gcc_interpolate_4(Pcs_nmos_look_up_tables_nch_cbb_ss_LUT,(cs_nmos_mid_V)-(cs_nmos_0_V),(cs_nmos_out_V)-(cs_nmos_0_V),(cs_nmos_0_V)-(cs_nmos_0_V),cs_nmos_size_L)*cs_nmos_size_L*cs_nmos_size_W*cs_nmos_config_cbb_factor;
float s=-1;
int BW_it;
W=0;
float BW_Mag0=1;
float BW_Mag=1;
float snr;
float sni;
float sdr;
float sdi;
while ((BW_Mag0/BW_Mag)<2) {
      snr=-((-cs_nmos_Gds_in_mid)*cs_nmos_n_ref_gm);
      sni=-((-cs_nmos_Gds_in_mid)*cs_nmos_n_ref_cdg*W);
      sdr=-(-((cs_nmos_Gds_in_mid+cs_nmos_n_ref_cgg*s)*(-(cs_nmos_n_ref_go+cs_nmos_n_ref_cdd*s)))+cs_nmos_n_ref_cgd*s*(-(cs_nmos_n_ref_gm+cs_nmos_n_ref_cdg*s)));
      sdi=0;
      BW_Mag=(snr*snr+sni*sni)/(sdr*sdr+sdi*sdi);
      if (W==0) BW_Mag0=BW_Mag;
      if (W==0) W=1; else W*=1.01;
}
cs_nmos_property_BW=fabs(W/(2*3.141592656));
for (BW_it=0;BW_it<5;BW_it++)  s-=((-((-(cs_nmos_Gds_in_mid+cs_nmos_n_ref_cgg*s)*(-(cs_nmos_n_ref_go+cs_nmos_n_ref_cdd*s)))+cs_nmos_n_ref_cgd*s*(-(cs_nmos_n_ref_gm+cs_nmos_n_ref_cdg*s)))))/((-((-(cs_nmos_n_ref_cgg*(-(cs_nmos_n_ref_go+cs_nmos_n_ref_cdd*s))+(cs_nmos_Gds_in_mid+cs_nmos_n_ref_cgg*s)*(-cs_nmos_n_ref_cdd)))+(cs_nmos_n_ref_cgd*(-(cs_nmos_n_ref_gm+cs_nmos_n_ref_cdg*s))+cs_nmos_n_ref_cgd*s*(-cs_nmos_n_ref_cdg)))));
cs_nmos_property_BW_s=(-((-(cs_nmos_n_ref_cgg*(-(cs_nmos_n_ref_go+cs_nmos_n_ref_cdd*s))+(cs_nmos_Gds_in_mid+cs_nmos_n_ref_cgg*s)*(-cs_nmos_n_ref_cdd)))+(cs_nmos_n_ref_cgd*(-(cs_nmos_n_ref_gm+cs_nmos_n_ref_cdg*s))+cs_nmos_n_ref_cgd*s*(-cs_nmos_n_ref_cdg))));
cs_nmos_p1=-s;
if (!isfinite(cs_nmos_property_BW))  {cs_nmos_status_fail=8; return TCL_ERROR;}
s-=1e3;
for (BW_it=0;BW_it<20;BW_it++)  s-=(((-((-(cs_nmos_Gds_in_mid+cs_nmos_n_ref_cgg*s)*(-(cs_nmos_n_ref_go+cs_nmos_n_ref_cdd*s)))+cs_nmos_n_ref_cgd*s*(-(cs_nmos_n_ref_gm+cs_nmos_n_ref_cdg*s)))))*(s+cs_nmos_p1-5e2))/(((-((-(cs_nmos_n_ref_cgg*(-(cs_nmos_n_ref_go+cs_nmos_n_ref_cdd*s))+(cs_nmos_Gds_in_mid+cs_nmos_n_ref_cgg*s)*(-cs_nmos_n_ref_cdd)))+(cs_nmos_n_ref_cgd*(-(cs_nmos_n_ref_gm+cs_nmos_n_ref_cdg*s))+cs_nmos_n_ref_cgd*s*(-cs_nmos_n_ref_cdg)))))*(s+cs_nmos_p1-5e2)-((-((-(cs_nmos_Gds_in_mid+cs_nmos_n_ref_cgg*s)*(-(cs_nmos_n_ref_go+cs_nmos_n_ref_cdd*s)))+cs_nmos_n_ref_cgd*s*(-(cs_nmos_n_ref_gm+cs_nmos_n_ref_cdg*s))))));
cs_nmos_p2=-s;
if (!isfinite(cs_nmos_p1)) {
    cs_nmos_property_ts=1/cs_nmos_property_BW;
} else if (!isfinite(cs_nmos_p2)) {
    cs_nmos_property_ts=-log(0.02)/cs_nmos_p1;
} else {
    float A1=-cs_nmos_p2/(-cs_nmos_p1+cs_nmos_p2);
    float A2=-cs_nmos_p1/(-cs_nmos_p1+cs_nmos_p2);
    cs_nmos_property_ts=0;
    for (BW_it=0;BW_it<10;BW_it++) cs_nmos_property_ts-=(0.02+A1*exp(-cs_nmos_p1*cs_nmos_property_ts)+A2*exp(-cs_nmos_p2*cs_nmos_property_ts))/(-cs_nmos_p1*A1*exp(-cs_nmos_p1*cs_nmos_property_ts)-cs_nmos_p2*A2*exp(-cs_nmos_p2*cs_nmos_property_ts));
}
if (!isfinite(cs_nmos_property_ts)) {
    cs_nmos_property_ts=1/cs_nmos_property_BW;
}
while (BW_Mag>4) {
      snr=-((-cs_nmos_Gds_in_mid)*cs_nmos_n_ref_gm);
      sni=-((-cs_nmos_Gds_in_mid)*cs_nmos_n_ref_cdg*W);
      sdr=-(-((cs_nmos_Gds_in_mid+cs_nmos_n_ref_cgg*s)*(-(cs_nmos_n_ref_go+cs_nmos_n_ref_cdd*s)))+cs_nmos_n_ref_cgd*s*(-(cs_nmos_n_ref_gm+cs_nmos_n_ref_cdg*s)));
      sdi=0;
      BW_Mag=(snr*snr+sni*sni)/(sdr*sdr+sdi*sdi);
      W*=1.01;
}
cs_nmos_property_PM=180-180*(atan(sni/snr)-atan(sdi/sdr))/3.1415926;
cs_nmos_n_ref_Nt_unit=gamma_gcc_interpolateg_4(&cs_nmos__look_up_tables_nch_thermal_noise_ss_LUT,cs_nmos_mid_V,cs_nmos_out_V,cs_nmos_0_V,cs_nmos_size_L,&cs_nmos_n_ref_dNt_dvgs,&cs_nmos_n_ref_dNt_dvds,&cs_nmos_n_ref_dNt_dvbs,&cs_nmos_n_ref_dNt_dl);
cs_nmos_n_ref_Nt=cs_nmos_n_ref_Nt_unit*cs_nmos_n_ref_go;
if (!isfinite(cs_nmos_n_ref_Nt))  {cs_nmos_status_fail=5; return TCL_ERROR;}
cs_nmos_n_ref_Nf_unit=gamma_gcc_interpolateg_4(&cs_nmos__look_up_tables_nch_flicker_noise_ss_LUT,cs_nmos_mid_V,cs_nmos_out_V,cs_nmos_0_V,cs_nmos_size_L,&cs_nmos_n_ref_dNf_dvgs,&cs_nmos_n_ref_dNf_dvds,&cs_nmos_n_ref_dNf_dvbs,&cs_nmos_n_ref_dNf_dl);
cs_nmos_n_ref_Nf=cs_nmos_n_ref_Nf_unit*cs_nmos_n_ref_go*cs_nmos_n_ref_go/(cs_nmos_size_W*cs_nmos_size_L);
if (!isfinite(cs_nmos_n_ref_Nf))  {cs_nmos_status_fail=6; return TCL_ERROR;}
float current_transfer_n_ref=Ted*((-(-cs_nmos_Gds_in_mid)))/cs_nmos_property_Adc;
cs_nmos_property_Nt=(current_transfer_n_ref*current_transfer_n_ref*cs_nmos_n_ref_Nt)/cs_nmos_property_Adc;
cs_nmos_property_Nf=(current_transfer_n_ref*current_transfer_n_ref*cs_nmos_n_ref_Nf)/cs_nmos_property_Adc;
cs_nmos_property_fc=cs_nmos_property_Nf/cs_nmos_property_Nt;
cs_nmos_property_TotalNoise=(log(2*cs_nmos_property_BW)*cs_nmos_property_Nf+2*cs_nmos_property_BW*cs_nmos_property_Nt);
cs_nmos_property_Area=1e12*(cs_nmos_size_W*cs_nmos_size_L);
float single_transistor_vos;
cs_nmos_property_Vos=0;
cs_nmos_property_Vos=1e-3*sqrt(cs_nmos_property_Vos);
cs_nmos_property_Power=0;
cs_nmos_property_Power+=fabs(cs_nmos_n_ref_Ids*((cs_nmos_out_V)-(cs_nmos_0_V)));
cs_nmos_property_Adc=20*log10(fabs(cs_nmos_property_Adc));
cs_nmos_property_CMRR=20*log10(fabs(cs_nmos_property_CMRR));
cs_nmos_property_CMRR=cs_nmos_property_Adc-cs_nmos_property_CMRR;
cs_nmos_property_PSRR=20*log10(fabs(cs_nmos_property_PSRR));
cs_nmos_property_PSRR=cs_nmos_property_Adc-cs_nmos_property_PSRR;
if (cs_nmos_max_Adc<cs_nmos_property_Adc) cs_nmos_max_Adc=cs_nmos_property_Adc;
PAT *p=(PAT *)Pcs_nmos_cs_nmos_circuits_PAT;
float sizes[6];
sizes[0]=cs_nmos_size_L;
sizes[1]=cs_nmos_size_W;
sizes[2]=cs_nmos_size_iref;
sizes[3]=cs_nmos_size_rin;
sizes[4]=cs_nmos_out_V;
sizes[5]=cs_nmos_mid_V;
float properties[15];
if ((cs_nmos_config_factor_Adc!=0)||(cs_nmos_config_shift_Adc!=0)) cs_nmos_property_Adc=cs_nmos_property_Adc*cs_nmos_config_factor_Adc+cs_nmos_config_shift_Adc;
properties[0]=cs_nmos_property_Adc;
if ((cs_nmos_config_factor_CMRR!=0)||(cs_nmos_config_shift_CMRR!=0)) cs_nmos_property_CMRR=cs_nmos_property_CMRR*cs_nmos_config_factor_CMRR+cs_nmos_config_shift_CMRR;
properties[1]=cs_nmos_property_CMRR;
if ((cs_nmos_config_factor_PSRR!=0)||(cs_nmos_config_shift_PSRR!=0)) cs_nmos_property_PSRR=cs_nmos_property_PSRR*cs_nmos_config_factor_PSRR+cs_nmos_config_shift_PSRR;
properties[2]=cs_nmos_property_PSRR;
if ((cs_nmos_config_factor_Rout!=0)||(cs_nmos_config_shift_Rout!=0)) cs_nmos_property_Rout=cs_nmos_property_Rout*cs_nmos_config_factor_Rout+cs_nmos_config_shift_Rout;
properties[3]=cs_nmos_property_Rout;
if ((cs_nmos_config_factor_BW!=0)||(cs_nmos_config_shift_BW!=0)) cs_nmos_property_BW=cs_nmos_property_BW*cs_nmos_config_factor_BW+cs_nmos_config_shift_BW;
properties[4]=cs_nmos_property_BW;
if ((cs_nmos_config_factor_PM!=0)||(cs_nmos_config_shift_PM!=0)) cs_nmos_property_PM=cs_nmos_property_PM*cs_nmos_config_factor_PM+cs_nmos_config_shift_PM;
properties[5]=cs_nmos_property_PM;
if ((cs_nmos_config_factor_Cin!=0)||(cs_nmos_config_shift_Cin!=0)) cs_nmos_property_Cin=cs_nmos_property_Cin*cs_nmos_config_factor_Cin+cs_nmos_config_shift_Cin;
properties[6]=cs_nmos_property_Cin;
if ((cs_nmos_config_factor_ts!=0)||(cs_nmos_config_shift_ts!=0)) cs_nmos_property_ts=cs_nmos_property_ts*cs_nmos_config_factor_ts+cs_nmos_config_shift_ts;
properties[7]=cs_nmos_property_ts;
if ((cs_nmos_config_factor_Nt!=0)||(cs_nmos_config_shift_Nt!=0)) cs_nmos_property_Nt=cs_nmos_property_Nt*cs_nmos_config_factor_Nt+cs_nmos_config_shift_Nt;
properties[8]=cs_nmos_property_Nt;
if ((cs_nmos_config_factor_Nf!=0)||(cs_nmos_config_shift_Nf!=0)) cs_nmos_property_Nf=cs_nmos_property_Nf*cs_nmos_config_factor_Nf+cs_nmos_config_shift_Nf;
properties[9]=cs_nmos_property_Nf;
if ((cs_nmos_config_factor_TotalNoise!=0)||(cs_nmos_config_shift_TotalNoise!=0)) cs_nmos_property_TotalNoise=cs_nmos_property_TotalNoise*cs_nmos_config_factor_TotalNoise+cs_nmos_config_shift_TotalNoise;
properties[10]=cs_nmos_property_TotalNoise;
if ((cs_nmos_config_factor_fc!=0)||(cs_nmos_config_shift_fc!=0)) cs_nmos_property_fc=cs_nmos_property_fc*cs_nmos_config_factor_fc+cs_nmos_config_shift_fc;
properties[11]=cs_nmos_property_fc;
if ((cs_nmos_config_factor_Vos!=0)||(cs_nmos_config_shift_Vos!=0)) cs_nmos_property_Vos=cs_nmos_property_Vos*cs_nmos_config_factor_Vos+cs_nmos_config_shift_Vos;
properties[12]=cs_nmos_property_Vos;
if ((cs_nmos_config_factor_Area!=0)||(cs_nmos_config_shift_Area!=0)) cs_nmos_property_Area=cs_nmos_property_Area*cs_nmos_config_factor_Area+cs_nmos_config_shift_Area;
properties[13]=cs_nmos_property_Area;
if ((cs_nmos_config_factor_Power!=0)||(cs_nmos_config_shift_Power!=0)) cs_nmos_property_Power=cs_nmos_property_Power*cs_nmos_config_factor_Power+cs_nmos_config_shift_Power;
properties[14]=cs_nmos_property_Power;
cs_nmos_status_fail=op_it;
cs_nmos_status_index=add_pat_array(p,sizes,properties);

            return TCL_OK;
        }
        //      static int tcl_gamma_grad_cmd(ClientData clientData,Tcl_Interp *interp,int argc,char *argv[]) {
            //            Tcl_ResetResult(interp);
            //          GRAD_CODE_GOES_HERE
            //         return TCL_OK;
        //    }
        static int tcl_gamma_cs_nmos_heatmap_cmd(ClientData clientData,Tcl_Interp *interp,int argc,char *argv[]) {
            int i,j;
ClientData CD;
if ((argc!=15)&&(argc!=14)&&(argc!=13)) {
    #Error: "%s: usage: %s <x context> <minX> <maxX> <stepX> <y context> <minY> <maxY> <stepY> <z context> <pixel width> <pixel height> <pallet> [<pallet mode> {[<pass threshold>]}]" argv[0] argv[0]
    return TCL_ERROR;
}
    float *pX=(float *)&(create_context(argv[1]))->value.s;
    float *pY=(float *)&(create_context(argv[5]))->value.s;
    float *pZ=(float *)&(create_context(argv[7]))->value.s;
    float *PX=NULL;
if (strcmp(argv[1],"param:area_spacing")==0) PX=&(cs_nmos_param_area_spacing);
if (strcmp(argv[1],"param:iref")==0) PX=&(cs_nmos_param_iref);
if (strcmp(argv[1],"param:rload")==0) PX=&(cs_nmos_param_rload);
if (strcmp(argv[1],"param:in")==0) PX=&(cs_nmos_param_in);
if (strcmp(argv[1],"param:vdd")==0) PX=&(cs_nmos_param_vdd);
if (strcmp(argv[1],"param:unique")==0) PX=&(cs_nmos_param_unique);
if (strcmp(argv[1],"look_up_tables:nch")==0) PX=&(cs_nmos_look_up_tables_nch);
if (strcmp(argv[1],"look_up_tables:pch")==0) PX=&(cs_nmos_look_up_tables_pch);
if (strcmp(argv[1],"size:L")==0) PX=&(cs_nmos_size_L);
if (strcmp(argv[1],"size:W")==0) PX=&(cs_nmos_size_W);
if (strcmp(argv[1],"size:iref")==0) PX=&(cs_nmos_size_iref);
if (strcmp(argv[1],"size:rin")==0) PX=&(cs_nmos_size_rin);
if (strcmp(argv[1],"out:V")==0) PX=&(cs_nmos_out_V);
if (strcmp(argv[1],"out:Next")==0) PX=&(cs_nmos_out_Next);
if (strcmp(argv[1],"0:V")==0) PX=&(cs_nmos_0_V);
if (strcmp(argv[1],"0:Next")==0) PX=&(cs_nmos_0_Next);
if (strcmp(argv[1],"in:V")==0) PX=&(cs_nmos_in_V);
if (strcmp(argv[1],"in:Next")==0) PX=&(cs_nmos_in_Next);
if (strcmp(argv[1],"vdd:V")==0) PX=&(cs_nmos_vdd_V);
if (strcmp(argv[1],"vdd:Next")==0) PX=&(cs_nmos_vdd_Next);
if (strcmp(argv[1],"mid:V")==0) PX=&(cs_nmos_mid_V);
if (strcmp(argv[1],"mid:Next")==0) PX=&(cs_nmos_mid_Next);
if (strcmp(argv[1],"property:Adc")==0) PX=&(cs_nmos_property_Adc);
if (strcmp(argv[1],"property:CMRR")==0) PX=&(cs_nmos_property_CMRR);
if (strcmp(argv[1],"property:PSRR")==0) PX=&(cs_nmos_property_PSRR);
if (strcmp(argv[1],"property:Rout")==0) PX=&(cs_nmos_property_Rout);
if (strcmp(argv[1],"property:BW")==0) PX=&(cs_nmos_property_BW);
if (strcmp(argv[1],"property:PM")==0) PX=&(cs_nmos_property_PM);
if (strcmp(argv[1],"property:Cin")==0) PX=&(cs_nmos_property_Cin);
if (strcmp(argv[1],"property:ts")==0) PX=&(cs_nmos_property_ts);
if (strcmp(argv[1],"property:Nt")==0) PX=&(cs_nmos_property_Nt);
if (strcmp(argv[1],"property:Nf")==0) PX=&(cs_nmos_property_Nf);
if (strcmp(argv[1],"property:TotalNoise")==0) PX=&(cs_nmos_property_TotalNoise);
if (strcmp(argv[1],"property:fc")==0) PX=&(cs_nmos_property_fc);
if (strcmp(argv[1],"property:Vos")==0) PX=&(cs_nmos_property_Vos);
if (strcmp(argv[1],"property:Area")==0) PX=&(cs_nmos_property_Area);
if (strcmp(argv[1],"property:Power")==0) PX=&(cs_nmos_property_Power);
if (strcmp(argv[1],"n_ref:Ideq")==0) PX=&(cs_nmos_n_ref_Ideq);
if (strcmp(argv[1],"n_ref:go")==0) PX=&(cs_nmos_n_ref_go);
if (strcmp(argv[1],"n_ref:gm")==0) PX=&(cs_nmos_n_ref_gm);
if (strcmp(argv[1],"n_ref:cgd")==0) PX=&(cs_nmos_n_ref_cgd);
if (strcmp(argv[1],"n_ref:cgg")==0) PX=&(cs_nmos_n_ref_cgg);
if (strcmp(argv[1],"n_ref:cgs")==0) PX=&(cs_nmos_n_ref_cgs);
if (strcmp(argv[1],"n_ref:cgb")==0) PX=&(cs_nmos_n_ref_cgb);
if (strcmp(argv[1],"n_ref:cdd")==0) PX=&(cs_nmos_n_ref_cdd);
if (strcmp(argv[1],"n_ref:cdg")==0) PX=&(cs_nmos_n_ref_cdg);
if (strcmp(argv[1],"n_ref:cds")==0) PX=&(cs_nmos_n_ref_cds);
if (strcmp(argv[1],"n_ref:cdb")==0) PX=&(cs_nmos_n_ref_cdb);
if (strcmp(argv[1],"n_ref:csd")==0) PX=&(cs_nmos_n_ref_csd);
if (strcmp(argv[1],"n_ref:csg")==0) PX=&(cs_nmos_n_ref_csg);
if (strcmp(argv[1],"n_ref:css")==0) PX=&(cs_nmos_n_ref_css);
if (strcmp(argv[1],"n_ref:csb")==0) PX=&(cs_nmos_n_ref_csb);
if (strcmp(argv[1],"n_ref:cbd")==0) PX=&(cs_nmos_n_ref_cbd);
if (strcmp(argv[1],"n_ref:cbg")==0) PX=&(cs_nmos_n_ref_cbg);
if (strcmp(argv[1],"n_ref:cbs")==0) PX=&(cs_nmos_n_ref_cbs);
if (strcmp(argv[1],"n_ref:cbb")==0) PX=&(cs_nmos_n_ref_cbb);
if (PX==NULL) {
    #Error: "%s: context %s is not available for heatmap generation." argv[0] argv[1]
    return TCL_ERROR;
}
float minX=atof(argv[2]);
float maxX=atof(argv[3]);
float stepX=atof(argv[4]);
    float *PY=NULL;
if (strcmp(argv[5],"param:area_spacing")==0) PY=&(cs_nmos_param_area_spacing);
if (strcmp(argv[5],"param:iref")==0) PY=&(cs_nmos_param_iref);
if (strcmp(argv[5],"param:rload")==0) PY=&(cs_nmos_param_rload);
if (strcmp(argv[5],"param:in")==0) PY=&(cs_nmos_param_in);
if (strcmp(argv[5],"param:vdd")==0) PY=&(cs_nmos_param_vdd);
if (strcmp(argv[5],"param:unique")==0) PY=&(cs_nmos_param_unique);
if (strcmp(argv[5],"look_up_tables:nch")==0) PY=&(cs_nmos_look_up_tables_nch);
if (strcmp(argv[5],"look_up_tables:pch")==0) PY=&(cs_nmos_look_up_tables_pch);
if (strcmp(argv[5],"size:L")==0) PY=&(cs_nmos_size_L);
if (strcmp(argv[5],"size:W")==0) PY=&(cs_nmos_size_W);
if (strcmp(argv[5],"size:iref")==0) PY=&(cs_nmos_size_iref);
if (strcmp(argv[5],"size:rin")==0) PY=&(cs_nmos_size_rin);
if (strcmp(argv[5],"out:V")==0) PY=&(cs_nmos_out_V);
if (strcmp(argv[5],"out:Next")==0) PY=&(cs_nmos_out_Next);
if (strcmp(argv[5],"0:V")==0) PY=&(cs_nmos_0_V);
if (strcmp(argv[5],"0:Next")==0) PY=&(cs_nmos_0_Next);
if (strcmp(argv[5],"in:V")==0) PY=&(cs_nmos_in_V);
if (strcmp(argv[5],"in:Next")==0) PY=&(cs_nmos_in_Next);
if (strcmp(argv[5],"vdd:V")==0) PY=&(cs_nmos_vdd_V);
if (strcmp(argv[5],"vdd:Next")==0) PY=&(cs_nmos_vdd_Next);
if (strcmp(argv[5],"mid:V")==0) PY=&(cs_nmos_mid_V);
if (strcmp(argv[5],"mid:Next")==0) PY=&(cs_nmos_mid_Next);
if (strcmp(argv[5],"property:Adc")==0) PY=&(cs_nmos_property_Adc);
if (strcmp(argv[5],"property:CMRR")==0) PY=&(cs_nmos_property_CMRR);
if (strcmp(argv[5],"property:PSRR")==0) PY=&(cs_nmos_property_PSRR);
if (strcmp(argv[5],"property:Rout")==0) PY=&(cs_nmos_property_Rout);
if (strcmp(argv[5],"property:BW")==0) PY=&(cs_nmos_property_BW);
if (strcmp(argv[5],"property:PM")==0) PY=&(cs_nmos_property_PM);
if (strcmp(argv[5],"property:Cin")==0) PY=&(cs_nmos_property_Cin);
if (strcmp(argv[5],"property:ts")==0) PY=&(cs_nmos_property_ts);
if (strcmp(argv[5],"property:Nt")==0) PY=&(cs_nmos_property_Nt);
if (strcmp(argv[5],"property:Nf")==0) PY=&(cs_nmos_property_Nf);
if (strcmp(argv[5],"property:TotalNoise")==0) PY=&(cs_nmos_property_TotalNoise);
if (strcmp(argv[5],"property:fc")==0) PY=&(cs_nmos_property_fc);
if (strcmp(argv[5],"property:Vos")==0) PY=&(cs_nmos_property_Vos);
if (strcmp(argv[5],"property:Area")==0) PY=&(cs_nmos_property_Area);
if (strcmp(argv[5],"property:Power")==0) PY=&(cs_nmos_property_Power);
if (strcmp(argv[5],"n_ref:Ideq")==0) PY=&(cs_nmos_n_ref_Ideq);
if (strcmp(argv[5],"n_ref:go")==0) PY=&(cs_nmos_n_ref_go);
if (strcmp(argv[5],"n_ref:gm")==0) PY=&(cs_nmos_n_ref_gm);
if (strcmp(argv[5],"n_ref:cgd")==0) PY=&(cs_nmos_n_ref_cgd);
if (strcmp(argv[5],"n_ref:cgg")==0) PY=&(cs_nmos_n_ref_cgg);
if (strcmp(argv[5],"n_ref:cgs")==0) PY=&(cs_nmos_n_ref_cgs);
if (strcmp(argv[5],"n_ref:cgb")==0) PY=&(cs_nmos_n_ref_cgb);
if (strcmp(argv[5],"n_ref:cdd")==0) PY=&(cs_nmos_n_ref_cdd);
if (strcmp(argv[5],"n_ref:cdg")==0) PY=&(cs_nmos_n_ref_cdg);
if (strcmp(argv[5],"n_ref:cds")==0) PY=&(cs_nmos_n_ref_cds);
if (strcmp(argv[5],"n_ref:cdb")==0) PY=&(cs_nmos_n_ref_cdb);
if (strcmp(argv[5],"n_ref:csd")==0) PY=&(cs_nmos_n_ref_csd);
if (strcmp(argv[5],"n_ref:csg")==0) PY=&(cs_nmos_n_ref_csg);
if (strcmp(argv[5],"n_ref:css")==0) PY=&(cs_nmos_n_ref_css);
if (strcmp(argv[5],"n_ref:csb")==0) PY=&(cs_nmos_n_ref_csb);
if (strcmp(argv[5],"n_ref:cbd")==0) PY=&(cs_nmos_n_ref_cbd);
if (strcmp(argv[5],"n_ref:cbg")==0) PY=&(cs_nmos_n_ref_cbg);
if (strcmp(argv[5],"n_ref:cbs")==0) PY=&(cs_nmos_n_ref_cbs);
if (strcmp(argv[5],"n_ref:cbb")==0) PY=&(cs_nmos_n_ref_cbb);
if (PY==NULL) {
    #Error: "%s: context %s is not available for heatmap generation." argv[0] argv[1]
    return TCL_ERROR;
}
float minY=atof(argv[6]);
float maxY=atof(argv[7]);
float stepY=atof(argv[8]);
    float *PZ=NULL;
if (strcmp(argv[7],"param:area_spacing")==0) PZ=&(cs_nmos_param_area_spacing);
if (strcmp(argv[7],"param:iref")==0) PZ=&(cs_nmos_param_iref);
if (strcmp(argv[7],"param:rload")==0) PZ=&(cs_nmos_param_rload);
if (strcmp(argv[7],"param:in")==0) PZ=&(cs_nmos_param_in);
if (strcmp(argv[7],"param:vdd")==0) PZ=&(cs_nmos_param_vdd);
if (strcmp(argv[7],"param:unique")==0) PZ=&(cs_nmos_param_unique);
if (strcmp(argv[7],"look_up_tables:nch")==0) PZ=&(cs_nmos_look_up_tables_nch);
if (strcmp(argv[7],"look_up_tables:pch")==0) PZ=&(cs_nmos_look_up_tables_pch);
if (strcmp(argv[7],"size:L")==0) PZ=&(cs_nmos_size_L);
if (strcmp(argv[7],"size:W")==0) PZ=&(cs_nmos_size_W);
if (strcmp(argv[7],"size:iref")==0) PZ=&(cs_nmos_size_iref);
if (strcmp(argv[7],"size:rin")==0) PZ=&(cs_nmos_size_rin);
if (strcmp(argv[7],"out:V")==0) PZ=&(cs_nmos_out_V);
if (strcmp(argv[7],"out:Next")==0) PZ=&(cs_nmos_out_Next);
if (strcmp(argv[7],"0:V")==0) PZ=&(cs_nmos_0_V);
if (strcmp(argv[7],"0:Next")==0) PZ=&(cs_nmos_0_Next);
if (strcmp(argv[7],"in:V")==0) PZ=&(cs_nmos_in_V);
if (strcmp(argv[7],"in:Next")==0) PZ=&(cs_nmos_in_Next);
if (strcmp(argv[7],"vdd:V")==0) PZ=&(cs_nmos_vdd_V);
if (strcmp(argv[7],"vdd:Next")==0) PZ=&(cs_nmos_vdd_Next);
if (strcmp(argv[7],"mid:V")==0) PZ=&(cs_nmos_mid_V);
if (strcmp(argv[7],"mid:Next")==0) PZ=&(cs_nmos_mid_Next);
if (strcmp(argv[7],"property:Adc")==0) PZ=&(cs_nmos_property_Adc);
if (strcmp(argv[7],"property:CMRR")==0) PZ=&(cs_nmos_property_CMRR);
if (strcmp(argv[7],"property:PSRR")==0) PZ=&(cs_nmos_property_PSRR);
if (strcmp(argv[7],"property:Rout")==0) PZ=&(cs_nmos_property_Rout);
if (strcmp(argv[7],"property:BW")==0) PZ=&(cs_nmos_property_BW);
if (strcmp(argv[7],"property:PM")==0) PZ=&(cs_nmos_property_PM);
if (strcmp(argv[7],"property:Cin")==0) PZ=&(cs_nmos_property_Cin);
if (strcmp(argv[7],"property:ts")==0) PZ=&(cs_nmos_property_ts);
if (strcmp(argv[7],"property:Nt")==0) PZ=&(cs_nmos_property_Nt);
if (strcmp(argv[7],"property:Nf")==0) PZ=&(cs_nmos_property_Nf);
if (strcmp(argv[7],"property:TotalNoise")==0) PZ=&(cs_nmos_property_TotalNoise);
if (strcmp(argv[7],"property:fc")==0) PZ=&(cs_nmos_property_fc);
if (strcmp(argv[7],"property:Vos")==0) PZ=&(cs_nmos_property_Vos);
if (strcmp(argv[7],"property:Area")==0) PZ=&(cs_nmos_property_Area);
if (strcmp(argv[7],"property:Power")==0) PZ=&(cs_nmos_property_Power);
if (strcmp(argv[7],"n_ref:Ideq")==0) PZ=&(cs_nmos_n_ref_Ideq);
if (strcmp(argv[7],"n_ref:go")==0) PZ=&(cs_nmos_n_ref_go);
if (strcmp(argv[7],"n_ref:gm")==0) PZ=&(cs_nmos_n_ref_gm);
if (strcmp(argv[7],"n_ref:cgd")==0) PZ=&(cs_nmos_n_ref_cgd);
if (strcmp(argv[7],"n_ref:cgg")==0) PZ=&(cs_nmos_n_ref_cgg);
if (strcmp(argv[7],"n_ref:cgs")==0) PZ=&(cs_nmos_n_ref_cgs);
if (strcmp(argv[7],"n_ref:cgb")==0) PZ=&(cs_nmos_n_ref_cgb);
if (strcmp(argv[7],"n_ref:cdd")==0) PZ=&(cs_nmos_n_ref_cdd);
if (strcmp(argv[7],"n_ref:cdg")==0) PZ=&(cs_nmos_n_ref_cdg);
if (strcmp(argv[7],"n_ref:cds")==0) PZ=&(cs_nmos_n_ref_cds);
if (strcmp(argv[7],"n_ref:cdb")==0) PZ=&(cs_nmos_n_ref_cdb);
if (strcmp(argv[7],"n_ref:csd")==0) PZ=&(cs_nmos_n_ref_csd);
if (strcmp(argv[7],"n_ref:csg")==0) PZ=&(cs_nmos_n_ref_csg);
if (strcmp(argv[7],"n_ref:css")==0) PZ=&(cs_nmos_n_ref_css);
if (strcmp(argv[7],"n_ref:csb")==0) PZ=&(cs_nmos_n_ref_csb);
if (strcmp(argv[7],"n_ref:cbd")==0) PZ=&(cs_nmos_n_ref_cbd);
if (strcmp(argv[7],"n_ref:cbg")==0) PZ=&(cs_nmos_n_ref_cbg);
if (strcmp(argv[7],"n_ref:cbs")==0) PZ=&(cs_nmos_n_ref_cbs);
if (strcmp(argv[7],"n_ref:cbb")==0) PZ=&(cs_nmos_n_ref_cbb);
if (PZ==NULL) {
    #Error: "%s: context %s is not available for heatmap generation." argv[0] argv[1]
    return TCL_ERROR;
}
int width=(int)(maxX-minX)/stepX+1;
int height=(int)(maxY-minY)/stepY+1;
int ARGC;
char **ARGV;
Tcl_SplitList(interp,argv[12],&ARGC,&ARGV);
int *pal=(int *)malloc(sizeof(int)*ARGC);
for (i=0;i<ARGC;i++) pal[i]=atoi(ARGV[i]);
heatmap *hm=new_heatmap(width,height,atoi(argv[10]),atoi(argv[11]),pal,ARGC);
int mode=-1;
float th=0;
if (argc==13) mode=HM_TH_MODE_FLAT; else {
if (strcmp(argv[13],"flat")==0) mode=HM_TH_MODE_FLAT;
if (strcmp(argv[13],"snap")==0) mode=HM_TH_MODE_SNAP;
if (strcmp(argv[13],"half")==0) mode=HM_TH_MODE_HALF;
}
if (mode==-1) {
	#Error: "%s: pallet mode %s is not available for heatmap generation. Use flat, snap or half" argv[0] argv[13]
	return TCL_ERROR;
}
if ((mode!=HM_TH_MODE_FLAT)&&(argc!=15)) {
	#Error: "%s: pallet mode %s requires a threshold for passing specifications." argv[0] argv[13]
	return TCL_ERROR;
} else th=atof(argv[14]);
float X,Y;
i=0;
for (X=minX;X<=maxX;X+=stepX) {
    j=0;
    for (Y=minY;Y<=maxY;Y+=stepY) {
        *PX=X;
        *PY=Y;
        tcl_gamma_cs_nmos_op_cmd(CD,NULL,0,NULL);
        set_heatmap_pixel(hm,i,j,*PZ);
        j++;
    }
    i++;
}
heatmap_thresholds(hm,mode,th);
char *out_channel_name=Tcl_GetVar(interp,"::HTML",0);
FILE *HTML;
Tcl_GetOpenFile(interp,out_channel_name,1,0,&HTML);
plot_heatmap(hm,0,0,HTML);

            return TCL_OK;
        }
        static int tcl_gamma_cs_nmos_random_cmd(ClientData clientData,Tcl_Interp *interp,int argc,char *argv[]) {
            ClientData CD;
PAT *p=(PAT *)Pcs_nmos_cs_nmos_circuits_PAT;
while (p->content->num_of<cs_nmos_config_pat_size_target) {
cs_nmos_size_L=cs_nmos_size_L_min+random()*(cs_nmos_size_L_max-cs_nmos_size_L_min)/RAND_MAX;
cs_nmos_size_W=cs_nmos_size_L+random()*(cs_nmos_size_W_max-cs_nmos_size_L)/RAND_MAX;
cs_nmos_size_iref=cs_nmos_size_iref_min+random()*(cs_nmos_size_iref_max-cs_nmos_size_iref_min)/RAND_MAX;
cs_nmos_size_rin=cs_nmos_size_rin_min+random()*(cs_nmos_size_rin_max-cs_nmos_size_rin_min)/RAND_MAX;
if (tcl_gamma_cs_nmos_op_cmd(CD,NULL,0,NULL)==TCL_ERROR) continue;
}

            return TCL_OK;
        }
        static int tcl_gamma_cs_nmos_breed_cmd(ClientData clientData,Tcl_Interp *interp,int argc,char *argv[]) {
            ClientData CD;
int i,viable;
PAT *p=(PAT *)Pcs_nmos_cs_nmos_circuits_PAT;
int more_to_breed=1;
while (more_to_breed&&(p->content->num_of<cs_nmos_pat_size_target)) {
more_to_breed=0;
int sweep_size=p->content->num_of;
for (i=0;i<sweep_size;i++) {
if (p->content->content[i]->flags) continue;
p->content->content[i]->flags=1;
more_to_breed++;
cs_nmos_size_L=p->content->content[i]->sizes->content[0];
cs_nmos_size_W=p->content->content[i]->sizes->content[1];
cs_nmos_size_iref=p->content->content[i]->sizes->content[2];
cs_nmos_size_rin=p->content->content[i]->sizes->content[3];
cs_nmos_size_L=cs_nmos_size_L+cs_nmos_size_L_step;
viable=1;
if ((cs_nmos_size_L>=cs_nmos_size_L_min)&&(cs_nmos_size_L<=cs_nmos_size_L_max)) {
tcl_gamma_cs_nmos_op_cmd(CD,NULL,0,NULL);
}
cs_nmos_size_L=cs_nmos_size_L-2*cs_nmos_size_L_step;
viable=1;
if ((cs_nmos_size_L>=cs_nmos_size_L_min)&&(cs_nmos_size_L<=cs_nmos_size_L_max)) {
tcl_gamma_cs_nmos_op_cmd(CD,NULL,0,NULL);
}
cs_nmos_size_L=cs_nmos_size_L+cs_nmos_size_L_step;
cs_nmos_size_W=cs_nmos_size_W+cs_nmos_size_W_step;
viable=1;
if ((cs_nmos_size_W>=cs_nmos_size_L)&&(cs_nmos_size_W<=cs_nmos_size_W_max)) {
tcl_gamma_cs_nmos_op_cmd(CD,NULL,0,NULL);
}
cs_nmos_size_W=cs_nmos_size_W-2*cs_nmos_size_W_step;
viable=1;
if ((cs_nmos_size_W>=cs_nmos_size_L)&&(cs_nmos_size_W<=cs_nmos_size_W_max)) {
tcl_gamma_cs_nmos_op_cmd(CD,NULL,0,NULL);
}
cs_nmos_size_W=cs_nmos_size_W+cs_nmos_size_W_step;
cs_nmos_size_iref=cs_nmos_size_iref+cs_nmos_size_iref_step;
viable=1;
if ((cs_nmos_size_iref>=cs_nmos_size_iref_min)&&(cs_nmos_size_iref<=cs_nmos_size_iref_max)) {
tcl_gamma_cs_nmos_op_cmd(CD,NULL,0,NULL);
}
cs_nmos_size_iref=cs_nmos_size_iref-2*cs_nmos_size_iref_step;
viable=1;
if ((cs_nmos_size_iref>=cs_nmos_size_iref_min)&&(cs_nmos_size_iref<=cs_nmos_size_iref_max)) {
tcl_gamma_cs_nmos_op_cmd(CD,NULL,0,NULL);
}
cs_nmos_size_iref=cs_nmos_size_iref+cs_nmos_size_iref_step;
cs_nmos_size_rin=cs_nmos_size_rin+cs_nmos_size_rin_step;
viable=1;
if ((cs_nmos_size_rin>=cs_nmos_size_rin_min)&&(cs_nmos_size_rin<=cs_nmos_size_rin_max)) {
tcl_gamma_cs_nmos_op_cmd(CD,NULL,0,NULL);
}
cs_nmos_size_rin=cs_nmos_size_rin-2*cs_nmos_size_rin_step;
viable=1;
if ((cs_nmos_size_rin>=cs_nmos_size_rin_min)&&(cs_nmos_size_rin<=cs_nmos_size_rin_max)) {
tcl_gamma_cs_nmos_op_cmd(CD,NULL,0,NULL);
}
cs_nmos_size_rin=cs_nmos_size_rin+cs_nmos_size_rin_step;
if (p->content->num_of%100==0) {
    printf("               %ld/%g=%g%%\n",p->content->num_of,cs_nmos_pat_size_target,100*p->content->num_of/cs_nmos_pat_size_target);
    fflush(stdout);
    if (cs_nmos_param_unique>0) {
        pat_unique(p,cs_nmos_param_unique);
}
}
}
printf("   Done %ld/%g=%g%% (%ld visited)\n",p->content->num_of,cs_nmos_pat_size_target,100*p->content->num_of/cs_nmos_pat_size_target,more_to_breed);
}

            return TCL_OK;
        }
        static int tcl_gamma_cs_nmos_random_breed_cmd(ClientData clientData,Tcl_Interp *interp,int argc,char *argv[]) {
            ClientData CD;
int i,j;
PAT *p=(PAT *)Pcs_nmos_cs_nmos_circuits_PAT;
long int r;
float step;
while (1) {
    if (p->content->num_of>cs_nmos_config_pat_size_target) break;
int sweep_size=p->content->num_of;
for (i=0;i<sweep_size;i++) {
cs_nmos_size_L=p->content->content[i]->sizes->content[0];
cs_nmos_size_W=p->content->content[i]->sizes->content[1];
cs_nmos_size_iref=p->content->content[i]->sizes->content[2];
cs_nmos_size_rin=p->content->content[i]->sizes->content[3];
while (1) {
step=(2.0*random()/RAND_MAX-1)*cs_nmos_size_L_step;
if (cs_nmos_size_L+step<cs_nmos_size_L_min) continue;
if (cs_nmos_size_L+step>cs_nmos_size_L_max) continue;
break;
}
cs_nmos_size_L+=step;
while (1) {
step=(2.0*random()/RAND_MAX-1)*cs_nmos_size_W_step;
if (cs_nmos_size_W+step<cs_nmos_size_L) continue;
if (cs_nmos_size_W+step>cs_nmos_size_W_max) continue;
break;
}
cs_nmos_size_W+=step;
while (1) {
step=(2.0*random()/RAND_MAX-1)*cs_nmos_size_iref_step;
if (cs_nmos_size_iref+step<cs_nmos_size_iref_min) continue;
if (cs_nmos_size_iref+step>cs_nmos_size_iref_max) continue;
break;
}
cs_nmos_size_iref+=step;
while (1) {
step=(2.0*random()/RAND_MAX-1)*cs_nmos_size_rin_step;
if (cs_nmos_size_rin+step<cs_nmos_size_rin_min) continue;
if (cs_nmos_size_rin+step>cs_nmos_size_rin_max) continue;
break;
}
cs_nmos_size_rin+=step;
int pre_volume=p->content->num_of;
if (tcl_gamma_cs_nmos_op_cmd(CD,NULL,0,NULL)==TCL_ERROR) {i--; continue;}
if (pre_volume==p->content->num_of) {i--; continue;}
if (p->content->num_of%1000==0) {
    printf("               %ld/%g=%g%% max gain=%g\n",p->content->num_of,cs_nmos_config_pat_size_target,100*p->content->num_of/cs_nmos_config_pat_size_target,cs_nmos_max_Adc);
    printf("               %ld/%g=%g%%\n",p->content->num_of,cs_nmos_config_pat_size_target,100*p->content->num_of/cs_nmos_config_pat_size_target);
    fflush(stdout);
    if (cs_nmos_param_unique>0) {
        pat_unique(p,cs_nmos_param_unique);
    printf("               post unique: %ld/%g=%g%%\n",p->content->num_of,cs_nmos_config_pat_size_target,100*p->content->num_of/cs_nmos_config_pat_size_target);
    if (p->content->num_of>0.92*cs_nmos_config_pat_size_target) break;
}
}
    if (p->content->num_of>cs_nmos_config_pat_size_target) break;
}
    if (p->content->num_of>cs_nmos_config_pat_size_target) break;
}

            return TCL_OK;
        }
        static int tcl_gamma_cs_nmos_random_breed_single_cmd(ClientData clientData,Tcl_Interp *interp,int argc,char *argv[]) {
            ClientData CD;
int i;
PAT *p=(PAT *)Pcs_nmos_cs_nmos_circuits_PAT;
int more_to_breed=0;
long int r;
long int breed_count=p->content->num_of;
long int watchdog=0;
float step;
int sweep_size=p->content->num_of;
int searched_id=(int)cs_nmos_circuit_breed_id;
for (i=0;i<p->content->num_of;i++) {
    if (p->content->content[i]->id==searched_id) break;
}
printf("Found circuit id %d at index %d\n",searched_id,i);
while (watchdog++<10000) {
cs_nmos_size_L=p->content->content[i]->sizes->content[0];
cs_nmos_size_W=p->content->content[i]->sizes->content[1];
cs_nmos_size_iref=p->content->content[i]->sizes->content[2];
cs_nmos_size_rin=p->content->content[i]->sizes->content[3];
while (1) {
step=(2.0*random()/RAND_MAX-1)*cs_nmos_size_L_step;
if (cs_nmos_size_L+step<cs_nmos_size_L_min) continue;
if (cs_nmos_size_L+step>cs_nmos_size_L_max) continue;
break;
}
cs_nmos_size_L+=step;
while (1) {
step=(2.0*random()/RAND_MAX-1)*cs_nmos_size_W_step;
if (cs_nmos_size_W+step<cs_nmos_size_L) continue;
if (cs_nmos_size_W+step>cs_nmos_size_W_max) continue;
break;
}
cs_nmos_size_W+=step;
while (1) {
step=(2.0*random()/RAND_MAX-1)*cs_nmos_size_iref_step;
if (cs_nmos_size_iref+step<cs_nmos_size_iref_min) continue;
if (cs_nmos_size_iref+step>cs_nmos_size_iref_max) continue;
break;
}
cs_nmos_size_iref+=step;
while (1) {
step=(2.0*random()/RAND_MAX-1)*cs_nmos_size_rin_step;
if (cs_nmos_size_rin+step<cs_nmos_size_rin_min) continue;
if (cs_nmos_size_rin+step>cs_nmos_size_rin_max) continue;
break;
}
cs_nmos_size_rin+=step;
if (tcl_gamma_cs_nmos_op_cmd(CD,NULL,0,NULL)==TCL_ERROR) continue;
if (p->content->num_of>=breed_count+cs_nmos_circuit_breed_target) break;
}

            return TCL_OK;
        }
        // Initializing cTree references and registering the tcl_gamma_op_cmd command as ::C::cs_nmos
        int Gamma_cs_nmos_Init(Tcl_Interp *interp) {
            float *array_entry;
            context *c;
            c=create_context("cs_nmos:param:area_spacing");
Pcs_nmos_param_area_spacing=(float *)(&c->value.s);
c=create_context("cs_nmos:param:iref");
Pcs_nmos_param_iref=(float *)(&c->value.s);
c=create_context("cs_nmos:param:rload");
Pcs_nmos_param_rload=(float *)(&c->value.s);
c=create_context("cs_nmos:param:in");
Pcs_nmos_param_in=(float *)(&c->value.s);
c=create_context("cs_nmos:param:vdd");
Pcs_nmos_param_vdd=(float *)(&c->value.s);
c=create_context("cs_nmos:param:unique");
Pcs_nmos_param_unique=(float *)(&c->value.s);
c=create_context("cs_nmos:look_up_tables:nch");
Pcs_nmos_look_up_tables_nch=(float *)(&c->value.s);
c=create_context("cs_nmos:look_up_tables:pch");
Pcs_nmos_look_up_tables_pch=(float *)(&c->value.s);
c=create_context("cs_nmos:size:L");
Pcs_nmos_size_L=(float *)(&c->value.s);
c=create_context("cs_nmos:size:W");
Pcs_nmos_size_W=(float *)(&c->value.s);
c=create_context("cs_nmos:size:iref");
Pcs_nmos_size_iref=(float *)(&c->value.s);
c=create_context("cs_nmos:size:rin");
Pcs_nmos_size_rin=(float *)(&c->value.s);
c=create_context("cs_nmos:out:V");
Pcs_nmos_out_V=(float *)(&c->value.s);
c=create_context("cs_nmos:out:Next");
Pcs_nmos_out_Next=(float *)(&c->value.s);
c=create_context("cs_nmos:0:V");
Pcs_nmos_0_V=(float *)(&c->value.s);
c=create_context("cs_nmos:0:Next");
Pcs_nmos_0_Next=(float *)(&c->value.s);
c=create_context("cs_nmos:in:V");
Pcs_nmos_in_V=(float *)(&c->value.s);
c=create_context("cs_nmos:in:Next");
Pcs_nmos_in_Next=(float *)(&c->value.s);
c=create_context("cs_nmos:vdd:V");
Pcs_nmos_vdd_V=(float *)(&c->value.s);
c=create_context("cs_nmos:vdd:Next");
Pcs_nmos_vdd_Next=(float *)(&c->value.s);
c=create_context("cs_nmos:mid:V");
Pcs_nmos_mid_V=(float *)(&c->value.s);
c=create_context("cs_nmos:mid:Next");
Pcs_nmos_mid_Next=(float *)(&c->value.s);
c=create_context("cs_nmos:property:Adc");
Pcs_nmos_property_Adc=(float *)(&c->value.s);
c=create_context("cs_nmos:property:CMRR");
Pcs_nmos_property_CMRR=(float *)(&c->value.s);
c=create_context("cs_nmos:property:PSRR");
Pcs_nmos_property_PSRR=(float *)(&c->value.s);
c=create_context("cs_nmos:property:Rout");
Pcs_nmos_property_Rout=(float *)(&c->value.s);
c=create_context("cs_nmos:property:BW");
Pcs_nmos_property_BW=(float *)(&c->value.s);
c=create_context("cs_nmos:property:PM");
Pcs_nmos_property_PM=(float *)(&c->value.s);
c=create_context("cs_nmos:property:Cin");
Pcs_nmos_property_Cin=(float *)(&c->value.s);
c=create_context("cs_nmos:property:ts");
Pcs_nmos_property_ts=(float *)(&c->value.s);
c=create_context("cs_nmos:property:Nt");
Pcs_nmos_property_Nt=(float *)(&c->value.s);
c=create_context("cs_nmos:property:Nf");
Pcs_nmos_property_Nf=(float *)(&c->value.s);
c=create_context("cs_nmos:property:TotalNoise");
Pcs_nmos_property_TotalNoise=(float *)(&c->value.s);
c=create_context("cs_nmos:property:fc");
Pcs_nmos_property_fc=(float *)(&c->value.s);
c=create_context("cs_nmos:property:Vos");
Pcs_nmos_property_Vos=(float *)(&c->value.s);
c=create_context("cs_nmos:property:Area");
Pcs_nmos_property_Area=(float *)(&c->value.s);
c=create_context("cs_nmos:property:Power");
Pcs_nmos_property_Power=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:Ideq");
Pcs_nmos_n_ref_Ideq=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:go");
Pcs_nmos_n_ref_go=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:gm");
Pcs_nmos_n_ref_gm=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:cgd");
Pcs_nmos_n_ref_cgd=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:cgg");
Pcs_nmos_n_ref_cgg=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:cgs");
Pcs_nmos_n_ref_cgs=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:cgb");
Pcs_nmos_n_ref_cgb=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:cdd");
Pcs_nmos_n_ref_cdd=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:cdg");
Pcs_nmos_n_ref_cdg=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:cds");
Pcs_nmos_n_ref_cds=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:cdb");
Pcs_nmos_n_ref_cdb=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:csd");
Pcs_nmos_n_ref_csd=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:csg");
Pcs_nmos_n_ref_csg=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:css");
Pcs_nmos_n_ref_css=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:csb");
Pcs_nmos_n_ref_csb=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:cbd");
Pcs_nmos_n_ref_cbd=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:cbg");
Pcs_nmos_n_ref_cbg=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:cbs");
Pcs_nmos_n_ref_cbs=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:cbb");
Pcs_nmos_n_ref_cbb=(float *)(&c->value.s);
Pcs_nmos_cs_nmos_circuits_PAT=(float *)get_PAT("cs_nmos:cs_nmos:circuits");
c=create_context("cs_nmos:config:pat_size_target");
Pcs_nmos_config_pat_size_target=(float *)(&c->value.s);
c=create_context("cs_nmos:size:L:min");
Pcs_nmos_size_L_min=(float *)(&c->value.s);
c=create_context("cs_nmos:size:L:max");
Pcs_nmos_size_L_max=(float *)(&c->value.s);
c=create_context("cs_nmos:size:W:max");
Pcs_nmos_size_W_max=(float *)(&c->value.s);
c=create_context("cs_nmos:size:iref:min");
Pcs_nmos_size_iref_min=(float *)(&c->value.s);
c=create_context("cs_nmos:size:iref:max");
Pcs_nmos_size_iref_max=(float *)(&c->value.s);
c=create_context("cs_nmos:size:rin:min");
Pcs_nmos_size_rin_min=(float *)(&c->value.s);
c=create_context("cs_nmos:size:rin:max");
Pcs_nmos_size_rin_max=(float *)(&c->value.s);
c=create_context("cs_nmos:size:L:step");
Pcs_nmos_size_L_step=(float *)(&c->value.s);
c=create_context("cs_nmos:size:W:step");
Pcs_nmos_size_W_step=(float *)(&c->value.s);
c=create_context("cs_nmos:size:iref:step");
Pcs_nmos_size_iref_step=(float *)(&c->value.s);
c=create_context("cs_nmos:size:rin:step");
Pcs_nmos_size_rin_step=(float *)(&c->value.s);
c=create_context("cs_nmos:max_Adc");
Pcs_nmos_max_Adc=(float *)(&c->value.s);
c=create_context("cs_nmos:pat_size_target");
Pcs_nmos_pat_size_target=(float *)(&c->value.s);
c=create_context("cs_nmos:mode:freash_op");
Pcs_nmos_mode_freash_op=(float *)(&c->value.s);
c=create_context("cs_nmos:status:index");
Pcs_nmos_status_index=(float *)(&c->value.s);
c=create_context("cs_nmos:config:size:L");
Pcs_nmos_config_size_L=(float *)(&c->value.s);
c=create_context("cs_nmos:config:size:W");
Pcs_nmos_config_size_W=(float *)(&c->value.s);
c=create_context("cs_nmos:config:size:iref");
Pcs_nmos_config_size_iref=(float *)(&c->value.s);
c=create_context("cs_nmos:config:size:rin");
Pcs_nmos_config_size_rin=(float *)(&c->value.s);
c=create_context("cs_nmos:status:fail");
Pcs_nmos_status_fail=(float *)(&c->value.s);
c=create_context("cs_nmos:design_feedback");
Pcs_nmos_design_feedback=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:bin");
Pcs_nmos_n_ref_bin=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:W");
Pcs_nmos_n_ref_W=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:L");
Pcs_nmos_n_ref_L=(float *)(&c->value.s);
Pcs_nmos_look_up_tables_nch_binning_LUT=(float *)get_LUT("look_up_tables:nch:binning");
c=create_context("cs_nmos:leak");
Pcs_nmos_leak=(float *)(&c->value.s);
c=create_context("cs_nmos:config:op_iterations");
Pcs_nmos_config_op_iterations=(float *)(&c->value.s);
c=create_context("cs_nmos:config:kcl_th");
Pcs_nmos_config_kcl_th=(float *)(&c->value.s);
c=create_context("cs_nmos:config:design_feedback_th");
Pcs_nmos_config_design_feedback_th=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:gb");
Pcs_nmos_n_ref_gb=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:Ids");
Pcs_nmos_n_ref_Ids=(float *)(&c->value.s);
c=create_context("cs_nmos:look_up_tables:nch:go:ss");
Pcs_nmos_look_up_tables_nch_go_ss_CONTEXT=(float *)&c;
c=create_context("cs_nmos:look_up_tables:nch:gm:ss");
Pcs_nmos_look_up_tables_nch_gm_ss_CONTEXT=(float *)&c;
c=create_context("cs_nmos:look_up_tables:nch:gb:ss");
Pcs_nmos_look_up_tables_nch_gb_ss_CONTEXT=(float *)&c;
c=create_context("cs_nmos:look_up_tables:nch:Ids:ss");
Pcs_nmos_look_up_tables_nch_Ids_ss_CONTEXT=(float *)&c;
c=create_context("cs_nmos:Gds_in_mid");
Pcs_nmos_Gds_in_mid=(float *)(&c->value.s);
c=create_context("cs_nmos:config:kcl_step");
Pcs_nmos_config_kcl_step=(float *)(&c->value.s);
c=create_context("cs_nmos:config:fail_on_properties");
Pcs_nmos_config_fail_on_properties=(float *)(&c->value.s);
c=create_context("cs_nmos:s");
Pcs_nmos_s=(float *)(&c->value.s);
c=create_context("cs_nmos:config:cgg_factor");
Pcs_nmos_config_cgg_factor=(float *)(&c->value.s);
Pcs_nmos_look_up_tables_nch_cgg_ss_LUT=(float *)get_LUT("look_up_tables:nch:cgg:ss");
c=create_context("cs_nmos:config:cgd_factor");
Pcs_nmos_config_cgd_factor=(float *)(&c->value.s);
Pcs_nmos_look_up_tables_nch_cgd_ss_LUT=(float *)get_LUT("look_up_tables:nch:cgd:ss");
c=create_context("cs_nmos:config:cgs_factor");
Pcs_nmos_config_cgs_factor=(float *)(&c->value.s);
Pcs_nmos_look_up_tables_nch_cgs_ss_LUT=(float *)get_LUT("look_up_tables:nch:cgs:ss");
c=create_context("cs_nmos:config:cgb_factor");
Pcs_nmos_config_cgb_factor=(float *)(&c->value.s);
Pcs_nmos_look_up_tables_nch_cgb_ss_LUT=(float *)get_LUT("look_up_tables:nch:cgb:ss");
c=create_context("cs_nmos:config:cdd_factor");
Pcs_nmos_config_cdd_factor=(float *)(&c->value.s);
Pcs_nmos_look_up_tables_nch_cdd_ss_LUT=(float *)get_LUT("look_up_tables:nch:cdd:ss");
c=create_context("cs_nmos:config:cdg_factor");
Pcs_nmos_config_cdg_factor=(float *)(&c->value.s);
Pcs_nmos_look_up_tables_nch_cdg_ss_LUT=(float *)get_LUT("look_up_tables:nch:cdg:ss");
c=create_context("cs_nmos:config:cdb_factor");
Pcs_nmos_config_cdb_factor=(float *)(&c->value.s);
Pcs_nmos_look_up_tables_nch_cdb_ss_LUT=(float *)get_LUT("look_up_tables:nch:cdb:ss");
c=create_context("cs_nmos:config:cds_factor");
Pcs_nmos_config_cds_factor=(float *)(&c->value.s);
Pcs_nmos_look_up_tables_nch_cds_ss_LUT=(float *)get_LUT("look_up_tables:nch:cds:ss");
c=create_context("cs_nmos:config:csd_factor");
Pcs_nmos_config_csd_factor=(float *)(&c->value.s);
Pcs_nmos_look_up_tables_nch_csd_ss_LUT=(float *)get_LUT("look_up_tables:nch:csd:ss");
c=create_context("cs_nmos:config:csg_factor");
Pcs_nmos_config_csg_factor=(float *)(&c->value.s);
Pcs_nmos_look_up_tables_nch_csg_ss_LUT=(float *)get_LUT("look_up_tables:nch:csg:ss");
c=create_context("cs_nmos:config:css_factor");
Pcs_nmos_config_css_factor=(float *)(&c->value.s);
Pcs_nmos_look_up_tables_nch_css_ss_LUT=(float *)get_LUT("look_up_tables:nch:css:ss");
c=create_context("cs_nmos:config:csb_factor");
Pcs_nmos_config_csb_factor=(float *)(&c->value.s);
Pcs_nmos_look_up_tables_nch_csb_ss_LUT=(float *)get_LUT("look_up_tables:nch:csb:ss");
c=create_context("cs_nmos:config:cbd_factor");
Pcs_nmos_config_cbd_factor=(float *)(&c->value.s);
Pcs_nmos_look_up_tables_nch_cbd_ss_LUT=(float *)get_LUT("look_up_tables:nch:cbd:ss");
c=create_context("cs_nmos:config:cbg_factor");
Pcs_nmos_config_cbg_factor=(float *)(&c->value.s);
Pcs_nmos_look_up_tables_nch_cbg_ss_LUT=(float *)get_LUT("look_up_tables:nch:cbg:ss");
c=create_context("cs_nmos:config:cbs_factor");
Pcs_nmos_config_cbs_factor=(float *)(&c->value.s);
Pcs_nmos_look_up_tables_nch_cbs_ss_LUT=(float *)get_LUT("look_up_tables:nch:cbs:ss");
c=create_context("cs_nmos:config:cbb_factor");
Pcs_nmos_config_cbb_factor=(float *)(&c->value.s);
Pcs_nmos_look_up_tables_nch_cbb_ss_LUT=(float *)get_LUT("look_up_tables:nch:cbb:ss");
c=create_context("cs_nmos:property:BW:s");
Pcs_nmos_property_BW_s=(float *)(&c->value.s);
c=create_context("cs_nmos:p1");
Pcs_nmos_p1=(float *)(&c->value.s);
c=create_context("cs_nmos:p2");
Pcs_nmos_p2=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:dNt_dvgs");
Pcs_nmos_n_ref_dNt_dvgs=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:dNt_dvds");
Pcs_nmos_n_ref_dNt_dvds=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:dNt_dvbs");
Pcs_nmos_n_ref_dNt_dvbs=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:dNt_dl");
Pcs_nmos_n_ref_dNt_dl=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:Nt_unit");
Pcs_nmos_n_ref_Nt_unit=(float *)(&c->value.s);
Pcs_nmos__look_up_tables_nch_thermal_noise_ss_LUT=(float *)get_LUT(":look_up_tables:nch:thermal_noise:ss");
c=create_context("cs_nmos:n_ref:Nt");
Pcs_nmos_n_ref_Nt=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:dNf_dvgs");
Pcs_nmos_n_ref_dNf_dvgs=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:dNf_dvds");
Pcs_nmos_n_ref_dNf_dvds=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:dNf_dvbs");
Pcs_nmos_n_ref_dNf_dvbs=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:dNf_dl");
Pcs_nmos_n_ref_dNf_dl=(float *)(&c->value.s);
c=create_context("cs_nmos:n_ref:Nf_unit");
Pcs_nmos_n_ref_Nf_unit=(float *)(&c->value.s);
Pcs_nmos__look_up_tables_nch_flicker_noise_ss_LUT=(float *)get_LUT(":look_up_tables:nch:flicker_noise:ss");
c=create_context("cs_nmos:n_ref:Nf");
Pcs_nmos_n_ref_Nf=(float *)(&c->value.s);
c=create_context("cs_nmos:config:shift:Adc");
Pcs_nmos_config_shift_Adc=(float *)(&c->value.s);
c=create_context("cs_nmos:config:factor:Adc");
Pcs_nmos_config_factor_Adc=(float *)(&c->value.s);
c=create_context("cs_nmos:config:shift:CMRR");
Pcs_nmos_config_shift_CMRR=(float *)(&c->value.s);
c=create_context("cs_nmos:config:factor:CMRR");
Pcs_nmos_config_factor_CMRR=(float *)(&c->value.s);
c=create_context("cs_nmos:config:shift:PSRR");
Pcs_nmos_config_shift_PSRR=(float *)(&c->value.s);
c=create_context("cs_nmos:config:factor:PSRR");
Pcs_nmos_config_factor_PSRR=(float *)(&c->value.s);
c=create_context("cs_nmos:config:shift:Rout");
Pcs_nmos_config_shift_Rout=(float *)(&c->value.s);
c=create_context("cs_nmos:config:factor:Rout");
Pcs_nmos_config_factor_Rout=(float *)(&c->value.s);
c=create_context("cs_nmos:config:shift:BW");
Pcs_nmos_config_shift_BW=(float *)(&c->value.s);
c=create_context("cs_nmos:config:factor:BW");
Pcs_nmos_config_factor_BW=(float *)(&c->value.s);
c=create_context("cs_nmos:config:shift:PM");
Pcs_nmos_config_shift_PM=(float *)(&c->value.s);
c=create_context("cs_nmos:config:factor:PM");
Pcs_nmos_config_factor_PM=(float *)(&c->value.s);
c=create_context("cs_nmos:config:shift:Cin");
Pcs_nmos_config_shift_Cin=(float *)(&c->value.s);
c=create_context("cs_nmos:config:factor:Cin");
Pcs_nmos_config_factor_Cin=(float *)(&c->value.s);
c=create_context("cs_nmos:config:shift:ts");
Pcs_nmos_config_shift_ts=(float *)(&c->value.s);
c=create_context("cs_nmos:config:factor:ts");
Pcs_nmos_config_factor_ts=(float *)(&c->value.s);
c=create_context("cs_nmos:config:shift:Nt");
Pcs_nmos_config_shift_Nt=(float *)(&c->value.s);
c=create_context("cs_nmos:config:factor:Nt");
Pcs_nmos_config_factor_Nt=(float *)(&c->value.s);
c=create_context("cs_nmos:config:shift:Nf");
Pcs_nmos_config_shift_Nf=(float *)(&c->value.s);
c=create_context("cs_nmos:config:factor:Nf");
Pcs_nmos_config_factor_Nf=(float *)(&c->value.s);
c=create_context("cs_nmos:config:shift:TotalNoise");
Pcs_nmos_config_shift_TotalNoise=(float *)(&c->value.s);
c=create_context("cs_nmos:config:factor:TotalNoise");
Pcs_nmos_config_factor_TotalNoise=(float *)(&c->value.s);
c=create_context("cs_nmos:config:shift:fc");
Pcs_nmos_config_shift_fc=(float *)(&c->value.s);
c=create_context("cs_nmos:config:factor:fc");
Pcs_nmos_config_factor_fc=(float *)(&c->value.s);
c=create_context("cs_nmos:config:shift:Vos");
Pcs_nmos_config_shift_Vos=(float *)(&c->value.s);
c=create_context("cs_nmos:config:factor:Vos");
Pcs_nmos_config_factor_Vos=(float *)(&c->value.s);
c=create_context("cs_nmos:config:shift:Area");
Pcs_nmos_config_shift_Area=(float *)(&c->value.s);
c=create_context("cs_nmos:config:factor:Area");
Pcs_nmos_config_factor_Area=(float *)(&c->value.s);
c=create_context("cs_nmos:config:shift:Power");
Pcs_nmos_config_shift_Power=(float *)(&c->value.s);
c=create_context("cs_nmos:config:factor:Power");
Pcs_nmos_config_factor_Power=(float *)(&c->value.s);
c=create_context("cs_nmos:circuit_breed_id");
Pcs_nmos_circuit_breed_id=(float *)(&c->value.s);
c=create_context("cs_nmos:circuit_breed_target");
Pcs_nmos_circuit_breed_target=(float *)(&c->value.s);

            return TCL_OK;
        }
        int Gamma_cs_nmos_Register(Tcl_Interp *interp) {
            Tcl_CreateCommand(interp, "::Gamma::cs_nmos::heatmap", tcl_gamma_cs_nmos_heatmap_cmd, NULL, NULL);
            Tcl_CreateCommand(interp, "::Gamma::cs_nmos::random", tcl_gamma_cs_nmos_random_cmd, NULL, NULL);
            Tcl_CreateCommand(interp, "::Gamma::cs_nmos::random_breed", tcl_gamma_cs_nmos_random_breed_cmd, NULL, NULL);
            Tcl_CreateCommand(interp, "::Gamma::cs_nmos::random_breed_single", tcl_gamma_cs_nmos_random_breed_single_cmd, NULL, NULL);
            Tcl_CreateCommand(interp, "::Gamma::cs_nmos::breed", tcl_gamma_cs_nmos_breed_cmd, NULL, NULL);
            Tcl_CreateCommand(interp, "::Gamma::cs_nmos::op", tcl_gamma_cs_nmos_op_cmd, NULL, NULL);
            Tcl_CreateCommand(interp, "::Gamma::cs_nmos::import", tcl_gamma_cs_nmos_import_cmd, NULL, NULL);
            Tcl_CreateCommand(interp, "::Gamma::cs_nmos::export", tcl_gamma_cs_nmos_export_cmd, NULL, NULL);
            return TCL_OK;
        }
    
