
        #include <tcl.h>
        #include <stdio.h>
        #include <stdlib.h>
        #include "Gamma/Data/ctree.h"
        #include "Gamma/LUT/look_up_table.h"
        #include "Gamma/Web/heatmap/heatmap.h"
        // Some global pointers to keep reference of the contexts this object manipulates
        float *Pcs_pmos_param_area_spacing;
float *Pcs_pmos_param_iref;
float *Pcs_pmos_param_rload;
float *Pcs_pmos_param_in;
float *Pcs_pmos_param_vdd;
float *Pcs_pmos_param_unique;
float *Pcs_pmos_look_up_tables_nch;
float *Pcs_pmos_look_up_tables_pch;
float *Pcs_pmos_size_L;
float *Pcs_pmos_size_W;
float *Pcs_pmos_size_iref;
float *Pcs_pmos_0_V;
float *Pcs_pmos_0_Next;
float *Pcs_pmos_out_V;
float *Pcs_pmos_out_Next;
float *Pcs_pmos_in_V;
float *Pcs_pmos_in_Next;
float *Pcs_pmos_vdd_V;
float *Pcs_pmos_vdd_Next;
float *Pcs_pmos_property_Adc;
float *Pcs_pmos_property_CMRR;
float *Pcs_pmos_property_PSRR;
float *Pcs_pmos_property_Rout;
float *Pcs_pmos_property_BW;
float *Pcs_pmos_property_PM;
float *Pcs_pmos_property_Cin;
float *Pcs_pmos_property_ts;
float *Pcs_pmos_property_Nt;
float *Pcs_pmos_property_Nf;
float *Pcs_pmos_property_TotalNoise;
float *Pcs_pmos_property_fc;
float *Pcs_pmos_property_Vos;
float *Pcs_pmos_property_Area;
float *Pcs_pmos_property_Power;
float *Pcs_pmos_pin_Ideq;
float *Pcs_pmos_pin_go;
float *Pcs_pmos_pin_gm;
float *Pcs_pmos_pin_cgd;
float *Pcs_pmos_pin_cgg;
float *Pcs_pmos_pin_cgs;
float *Pcs_pmos_pin_cgb;
float *Pcs_pmos_pin_cdd;
float *Pcs_pmos_pin_cdg;
float *Pcs_pmos_pin_cds;
float *Pcs_pmos_pin_cdb;
float *Pcs_pmos_pin_csd;
float *Pcs_pmos_pin_csg;
float *Pcs_pmos_pin_css;
float *Pcs_pmos_pin_csb;
float *Pcs_pmos_pin_cbd;
float *Pcs_pmos_pin_cbg;
float *Pcs_pmos_pin_cbs;
float *Pcs_pmos_pin_cbb;
float *Pcs_pmos_cs_pmos_circuits_PAT;
float *Pcs_pmos_config_pat_size_target;
float *Pcs_pmos_size_L_min;
float *Pcs_pmos_size_L_max;
float *Pcs_pmos_size_W_max;
float *Pcs_pmos_size_iref_min;
float *Pcs_pmos_size_iref_max;
float *Pcs_pmos_size_L_step;
float *Pcs_pmos_size_W_step;
float *Pcs_pmos_size_iref_step;
float *Pcs_pmos_max_Adc;
float *Pcs_pmos_pat_size_target;
float *Pcs_pmos_mode_freash_op;
float *Pcs_pmos_status_index;
float *Pcs_pmos_config_size_L;
float *Pcs_pmos_config_size_W;
float *Pcs_pmos_config_size_iref;
float *Pcs_pmos_status_fail;
float *Pcs_pmos_design_feedback;
float *Pcs_pmos_pin_bin;
float *Pcs_pmos_pin_W;
float *Pcs_pmos_pin_L;
float *Pcs_pmos_look_up_tables_pch_binning_LUT;
float *Pcs_pmos_leak;
float *Pcs_pmos_config_op_iterations;
float *Pcs_pmos_config_kcl_th;
float *Pcs_pmos_config_design_feedback_th;
float *Pcs_pmos_pin_gb;
float *Pcs_pmos_pin_Ids;
float *Pcs_pmos_look_up_tables_pch_go_ss_CONTEXT;
float *Pcs_pmos_look_up_tables_pch_gm_ss_CONTEXT;
float *Pcs_pmos_look_up_tables_pch_gb_ss_CONTEXT;
float *Pcs_pmos_look_up_tables_pch_Ids_ss_CONTEXT;
float *Pcs_pmos_config_kcl_step;
float *Pcs_pmos_config_fail_on_properties;
float *Pcs_pmos_s;
float *Pcs_pmos_config_cgg_factor;
float *Pcs_pmos_look_up_tables_pch_cgg_ss_LUT;
float *Pcs_pmos_config_cgd_factor;
float *Pcs_pmos_look_up_tables_pch_cgd_ss_LUT;
float *Pcs_pmos_config_cgs_factor;
float *Pcs_pmos_look_up_tables_pch_cgs_ss_LUT;
float *Pcs_pmos_config_cgb_factor;
float *Pcs_pmos_look_up_tables_pch_cgb_ss_LUT;
float *Pcs_pmos_config_cdd_factor;
float *Pcs_pmos_look_up_tables_pch_cdd_ss_LUT;
float *Pcs_pmos_config_cdg_factor;
float *Pcs_pmos_look_up_tables_pch_cdg_ss_LUT;
float *Pcs_pmos_config_cdb_factor;
float *Pcs_pmos_look_up_tables_pch_cdb_ss_LUT;
float *Pcs_pmos_config_cds_factor;
float *Pcs_pmos_look_up_tables_pch_cds_ss_LUT;
float *Pcs_pmos_config_csd_factor;
float *Pcs_pmos_look_up_tables_pch_csd_ss_LUT;
float *Pcs_pmos_config_csg_factor;
float *Pcs_pmos_look_up_tables_pch_csg_ss_LUT;
float *Pcs_pmos_config_css_factor;
float *Pcs_pmos_look_up_tables_pch_css_ss_LUT;
float *Pcs_pmos_config_csb_factor;
float *Pcs_pmos_look_up_tables_pch_csb_ss_LUT;
float *Pcs_pmos_config_cbd_factor;
float *Pcs_pmos_look_up_tables_pch_cbd_ss_LUT;
float *Pcs_pmos_config_cbg_factor;
float *Pcs_pmos_look_up_tables_pch_cbg_ss_LUT;
float *Pcs_pmos_config_cbs_factor;
float *Pcs_pmos_look_up_tables_pch_cbs_ss_LUT;
float *Pcs_pmos_config_cbb_factor;
float *Pcs_pmos_look_up_tables_pch_cbb_ss_LUT;
float *Pcs_pmos_property_BW_s;
float *Pcs_pmos_p1;
float *Pcs_pmos_p2;
float *Pcs_pmos_pin_dNt_dvgs;
float *Pcs_pmos_pin_dNt_dvds;
float *Pcs_pmos_pin_dNt_dvbs;
float *Pcs_pmos_pin_dNt_dl;
float *Pcs_pmos_pin_Nt_unit;
float *Pcs_pmos__look_up_tables_pch_thermal_noise_ss_LUT;
float *Pcs_pmos_pin_Nt;
float *Pcs_pmos_pin_dNf_dvgs;
float *Pcs_pmos_pin_dNf_dvds;
float *Pcs_pmos_pin_dNf_dvbs;
float *Pcs_pmos_pin_dNf_dl;
float *Pcs_pmos_pin_Nf_unit;
float *Pcs_pmos__look_up_tables_pch_flicker_noise_ss_LUT;
float *Pcs_pmos_pin_Nf;
float *Pcs_pmos_config_shift_Adc;
float *Pcs_pmos_config_factor_Adc;
float *Pcs_pmos_config_shift_CMRR;
float *Pcs_pmos_config_factor_CMRR;
float *Pcs_pmos_config_shift_PSRR;
float *Pcs_pmos_config_factor_PSRR;
float *Pcs_pmos_config_shift_Rout;
float *Pcs_pmos_config_factor_Rout;
float *Pcs_pmos_config_shift_BW;
float *Pcs_pmos_config_factor_BW;
float *Pcs_pmos_config_shift_PM;
float *Pcs_pmos_config_factor_PM;
float *Pcs_pmos_config_shift_Cin;
float *Pcs_pmos_config_factor_Cin;
float *Pcs_pmos_config_shift_ts;
float *Pcs_pmos_config_factor_ts;
float *Pcs_pmos_config_shift_Nt;
float *Pcs_pmos_config_factor_Nt;
float *Pcs_pmos_config_shift_Nf;
float *Pcs_pmos_config_factor_Nf;
float *Pcs_pmos_config_shift_TotalNoise;
float *Pcs_pmos_config_factor_TotalNoise;
float *Pcs_pmos_config_shift_fc;
float *Pcs_pmos_config_factor_fc;
float *Pcs_pmos_config_shift_Vos;
float *Pcs_pmos_config_factor_Vos;
float *Pcs_pmos_config_shift_Area;
float *Pcs_pmos_config_factor_Area;
float *Pcs_pmos_config_shift_Power;
float *Pcs_pmos_config_factor_Power;
float *Pcs_pmos_circuit_breed_id;
float *Pcs_pmos_circuit_breed_target;

        float cs_pmos_param_area_spacing;
float cs_pmos_param_iref;
float cs_pmos_param_rload;
float cs_pmos_param_in;
float cs_pmos_param_vdd;
float cs_pmos_param_unique;
float cs_pmos_look_up_tables_nch;
float cs_pmos_look_up_tables_pch;
float cs_pmos_size_L;
float cs_pmos_size_W;
float cs_pmos_size_iref;
float cs_pmos_0_V;
float cs_pmos_0_Next;
float cs_pmos_out_V;
float cs_pmos_out_Next;
float cs_pmos_in_V;
float cs_pmos_in_Next;
float cs_pmos_vdd_V;
float cs_pmos_vdd_Next;
float cs_pmos_property_Adc;
float cs_pmos_property_CMRR;
float cs_pmos_property_PSRR;
float cs_pmos_property_Rout;
float cs_pmos_property_BW;
float cs_pmos_property_PM;
float cs_pmos_property_Cin;
float cs_pmos_property_ts;
float cs_pmos_property_Nt;
float cs_pmos_property_Nf;
float cs_pmos_property_TotalNoise;
float cs_pmos_property_fc;
float cs_pmos_property_Vos;
float cs_pmos_property_Area;
float cs_pmos_property_Power;
float cs_pmos_pin_Ideq;
float cs_pmos_pin_go;
float cs_pmos_pin_gm;
float cs_pmos_pin_cgd;
float cs_pmos_pin_cgg;
float cs_pmos_pin_cgs;
float cs_pmos_pin_cgb;
float cs_pmos_pin_cdd;
float cs_pmos_pin_cdg;
float cs_pmos_pin_cds;
float cs_pmos_pin_cdb;
float cs_pmos_pin_csd;
float cs_pmos_pin_csg;
float cs_pmos_pin_css;
float cs_pmos_pin_csb;
float cs_pmos_pin_cbd;
float cs_pmos_pin_cbg;
float cs_pmos_pin_cbs;
float cs_pmos_pin_cbb;
float cs_pmos_cs_pmos_circuits_PAT;
float cs_pmos_config_pat_size_target;
float cs_pmos_size_L_min;
float cs_pmos_size_L_max;
float cs_pmos_size_W_max;
float cs_pmos_size_iref_min;
float cs_pmos_size_iref_max;
float cs_pmos_size_L_step;
float cs_pmos_size_W_step;
float cs_pmos_size_iref_step;
float cs_pmos_max_Adc;
float cs_pmos_pat_size_target;
float cs_pmos_mode_freash_op;
float cs_pmos_status_index;
float cs_pmos_config_size_L;
float cs_pmos_config_size_W;
float cs_pmos_config_size_iref;
float cs_pmos_status_fail;
float cs_pmos_design_feedback;
float cs_pmos_pin_bin;
float cs_pmos_pin_W;
float cs_pmos_pin_L;
float cs_pmos_look_up_tables_pch_binning_LUT;
float cs_pmos_leak;
float cs_pmos_config_op_iterations;
float cs_pmos_config_kcl_th;
float cs_pmos_config_design_feedback_th;
float cs_pmos_pin_gb;
float cs_pmos_pin_Ids;
float cs_pmos_look_up_tables_pch_go_ss_CONTEXT;
float cs_pmos_look_up_tables_pch_gm_ss_CONTEXT;
float cs_pmos_look_up_tables_pch_gb_ss_CONTEXT;
float cs_pmos_look_up_tables_pch_Ids_ss_CONTEXT;
float cs_pmos_config_kcl_step;
float cs_pmos_config_fail_on_properties;
float cs_pmos_s;
float cs_pmos_config_cgg_factor;
float cs_pmos_look_up_tables_pch_cgg_ss_LUT;
float cs_pmos_config_cgd_factor;
float cs_pmos_look_up_tables_pch_cgd_ss_LUT;
float cs_pmos_config_cgs_factor;
float cs_pmos_look_up_tables_pch_cgs_ss_LUT;
float cs_pmos_config_cgb_factor;
float cs_pmos_look_up_tables_pch_cgb_ss_LUT;
float cs_pmos_config_cdd_factor;
float cs_pmos_look_up_tables_pch_cdd_ss_LUT;
float cs_pmos_config_cdg_factor;
float cs_pmos_look_up_tables_pch_cdg_ss_LUT;
float cs_pmos_config_cdb_factor;
float cs_pmos_look_up_tables_pch_cdb_ss_LUT;
float cs_pmos_config_cds_factor;
float cs_pmos_look_up_tables_pch_cds_ss_LUT;
float cs_pmos_config_csd_factor;
float cs_pmos_look_up_tables_pch_csd_ss_LUT;
float cs_pmos_config_csg_factor;
float cs_pmos_look_up_tables_pch_csg_ss_LUT;
float cs_pmos_config_css_factor;
float cs_pmos_look_up_tables_pch_css_ss_LUT;
float cs_pmos_config_csb_factor;
float cs_pmos_look_up_tables_pch_csb_ss_LUT;
float cs_pmos_config_cbd_factor;
float cs_pmos_look_up_tables_pch_cbd_ss_LUT;
float cs_pmos_config_cbg_factor;
float cs_pmos_look_up_tables_pch_cbg_ss_LUT;
float cs_pmos_config_cbs_factor;
float cs_pmos_look_up_tables_pch_cbs_ss_LUT;
float cs_pmos_config_cbb_factor;
float cs_pmos_look_up_tables_pch_cbb_ss_LUT;
float cs_pmos_property_BW_s;
float cs_pmos_p1;
float cs_pmos_p2;
float cs_pmos_pin_dNt_dvgs;
float cs_pmos_pin_dNt_dvds;
float cs_pmos_pin_dNt_dvbs;
float cs_pmos_pin_dNt_dl;
float cs_pmos_pin_Nt_unit;
float cs_pmos__look_up_tables_pch_thermal_noise_ss_LUT;
float cs_pmos_pin_Nt;
float cs_pmos_pin_dNf_dvgs;
float cs_pmos_pin_dNf_dvds;
float cs_pmos_pin_dNf_dvbs;
float cs_pmos_pin_dNf_dl;
float cs_pmos_pin_Nf_unit;
float cs_pmos__look_up_tables_pch_flicker_noise_ss_LUT;
float cs_pmos_pin_Nf;
float cs_pmos_config_shift_Adc;
float cs_pmos_config_factor_Adc;
float cs_pmos_config_shift_CMRR;
float cs_pmos_config_factor_CMRR;
float cs_pmos_config_shift_PSRR;
float cs_pmos_config_factor_PSRR;
float cs_pmos_config_shift_Rout;
float cs_pmos_config_factor_Rout;
float cs_pmos_config_shift_BW;
float cs_pmos_config_factor_BW;
float cs_pmos_config_shift_PM;
float cs_pmos_config_factor_PM;
float cs_pmos_config_shift_Cin;
float cs_pmos_config_factor_Cin;
float cs_pmos_config_shift_ts;
float cs_pmos_config_factor_ts;
float cs_pmos_config_shift_Nt;
float cs_pmos_config_factor_Nt;
float cs_pmos_config_shift_Nf;
float cs_pmos_config_factor_Nf;
float cs_pmos_config_shift_TotalNoise;
float cs_pmos_config_factor_TotalNoise;
float cs_pmos_config_shift_fc;
float cs_pmos_config_factor_fc;
float cs_pmos_config_shift_Vos;
float cs_pmos_config_factor_Vos;
float cs_pmos_config_shift_Area;
float cs_pmos_config_factor_Area;
float cs_pmos_config_shift_Power;
float cs_pmos_config_factor_Power;
float cs_pmos_circuit_breed_id;
float cs_pmos_circuit_breed_target;

        // The compiled function
        static int tcl_gamma_cs_pmos_import_cmd(ClientData clientData,Tcl_Interp *interp,int argc,char *argv[]) {
            cs_pmos_param_area_spacing=*Pcs_pmos_param_area_spacing;
cs_pmos_param_iref=*Pcs_pmos_param_iref;
cs_pmos_param_rload=*Pcs_pmos_param_rload;
cs_pmos_param_in=*Pcs_pmos_param_in;
cs_pmos_param_vdd=*Pcs_pmos_param_vdd;
cs_pmos_param_unique=*Pcs_pmos_param_unique;
cs_pmos_look_up_tables_nch=*Pcs_pmos_look_up_tables_nch;
cs_pmos_look_up_tables_pch=*Pcs_pmos_look_up_tables_pch;
cs_pmos_size_L=*Pcs_pmos_size_L;
cs_pmos_size_W=*Pcs_pmos_size_W;
cs_pmos_size_iref=*Pcs_pmos_size_iref;
cs_pmos_0_V=*Pcs_pmos_0_V;
cs_pmos_0_Next=*Pcs_pmos_0_Next;
cs_pmos_out_V=*Pcs_pmos_out_V;
cs_pmos_out_Next=*Pcs_pmos_out_Next;
cs_pmos_in_V=*Pcs_pmos_in_V;
cs_pmos_in_Next=*Pcs_pmos_in_Next;
cs_pmos_vdd_V=*Pcs_pmos_vdd_V;
cs_pmos_vdd_Next=*Pcs_pmos_vdd_Next;
cs_pmos_property_Adc=*Pcs_pmos_property_Adc;
cs_pmos_property_CMRR=*Pcs_pmos_property_CMRR;
cs_pmos_property_PSRR=*Pcs_pmos_property_PSRR;
cs_pmos_property_Rout=*Pcs_pmos_property_Rout;
cs_pmos_property_BW=*Pcs_pmos_property_BW;
cs_pmos_property_PM=*Pcs_pmos_property_PM;
cs_pmos_property_Cin=*Pcs_pmos_property_Cin;
cs_pmos_property_ts=*Pcs_pmos_property_ts;
cs_pmos_property_Nt=*Pcs_pmos_property_Nt;
cs_pmos_property_Nf=*Pcs_pmos_property_Nf;
cs_pmos_property_TotalNoise=*Pcs_pmos_property_TotalNoise;
cs_pmos_property_fc=*Pcs_pmos_property_fc;
cs_pmos_property_Vos=*Pcs_pmos_property_Vos;
cs_pmos_property_Area=*Pcs_pmos_property_Area;
cs_pmos_property_Power=*Pcs_pmos_property_Power;
cs_pmos_pin_Ideq=*Pcs_pmos_pin_Ideq;
cs_pmos_pin_go=*Pcs_pmos_pin_go;
cs_pmos_pin_gm=*Pcs_pmos_pin_gm;
cs_pmos_pin_cgd=*Pcs_pmos_pin_cgd;
cs_pmos_pin_cgg=*Pcs_pmos_pin_cgg;
cs_pmos_pin_cgs=*Pcs_pmos_pin_cgs;
cs_pmos_pin_cgb=*Pcs_pmos_pin_cgb;
cs_pmos_pin_cdd=*Pcs_pmos_pin_cdd;
cs_pmos_pin_cdg=*Pcs_pmos_pin_cdg;
cs_pmos_pin_cds=*Pcs_pmos_pin_cds;
cs_pmos_pin_cdb=*Pcs_pmos_pin_cdb;
cs_pmos_pin_csd=*Pcs_pmos_pin_csd;
cs_pmos_pin_csg=*Pcs_pmos_pin_csg;
cs_pmos_pin_css=*Pcs_pmos_pin_css;
cs_pmos_pin_csb=*Pcs_pmos_pin_csb;
cs_pmos_pin_cbd=*Pcs_pmos_pin_cbd;
cs_pmos_pin_cbg=*Pcs_pmos_pin_cbg;
cs_pmos_pin_cbs=*Pcs_pmos_pin_cbs;
cs_pmos_pin_cbb=*Pcs_pmos_pin_cbb;
cs_pmos_config_pat_size_target=*Pcs_pmos_config_pat_size_target;
cs_pmos_size_L_min=*Pcs_pmos_size_L_min;
cs_pmos_size_L_max=*Pcs_pmos_size_L_max;
cs_pmos_size_W_max=*Pcs_pmos_size_W_max;
cs_pmos_size_iref_min=*Pcs_pmos_size_iref_min;
cs_pmos_size_iref_max=*Pcs_pmos_size_iref_max;
cs_pmos_size_L_step=*Pcs_pmos_size_L_step;
cs_pmos_size_W_step=*Pcs_pmos_size_W_step;
cs_pmos_size_iref_step=*Pcs_pmos_size_iref_step;
cs_pmos_max_Adc=*Pcs_pmos_max_Adc;
cs_pmos_pat_size_target=*Pcs_pmos_pat_size_target;
cs_pmos_mode_freash_op=*Pcs_pmos_mode_freash_op;
cs_pmos_status_index=*Pcs_pmos_status_index;
cs_pmos_config_size_L=*Pcs_pmos_config_size_L;
cs_pmos_config_size_W=*Pcs_pmos_config_size_W;
cs_pmos_config_size_iref=*Pcs_pmos_config_size_iref;
cs_pmos_status_fail=*Pcs_pmos_status_fail;
cs_pmos_design_feedback=*Pcs_pmos_design_feedback;
cs_pmos_pin_bin=*Pcs_pmos_pin_bin;
cs_pmos_pin_W=*Pcs_pmos_pin_W;
cs_pmos_pin_L=*Pcs_pmos_pin_L;
cs_pmos_leak=*Pcs_pmos_leak;
cs_pmos_config_op_iterations=*Pcs_pmos_config_op_iterations;
cs_pmos_config_kcl_th=*Pcs_pmos_config_kcl_th;
cs_pmos_config_design_feedback_th=*Pcs_pmos_config_design_feedback_th;
cs_pmos_pin_gb=*Pcs_pmos_pin_gb;
cs_pmos_pin_Ids=*Pcs_pmos_pin_Ids;
cs_pmos_config_kcl_step=*Pcs_pmos_config_kcl_step;
cs_pmos_config_fail_on_properties=*Pcs_pmos_config_fail_on_properties;
cs_pmos_s=*Pcs_pmos_s;
cs_pmos_config_cgg_factor=*Pcs_pmos_config_cgg_factor;
cs_pmos_config_cgd_factor=*Pcs_pmos_config_cgd_factor;
cs_pmos_config_cgs_factor=*Pcs_pmos_config_cgs_factor;
cs_pmos_config_cgb_factor=*Pcs_pmos_config_cgb_factor;
cs_pmos_config_cdd_factor=*Pcs_pmos_config_cdd_factor;
cs_pmos_config_cdg_factor=*Pcs_pmos_config_cdg_factor;
cs_pmos_config_cdb_factor=*Pcs_pmos_config_cdb_factor;
cs_pmos_config_cds_factor=*Pcs_pmos_config_cds_factor;
cs_pmos_config_csd_factor=*Pcs_pmos_config_csd_factor;
cs_pmos_config_csg_factor=*Pcs_pmos_config_csg_factor;
cs_pmos_config_css_factor=*Pcs_pmos_config_css_factor;
cs_pmos_config_csb_factor=*Pcs_pmos_config_csb_factor;
cs_pmos_config_cbd_factor=*Pcs_pmos_config_cbd_factor;
cs_pmos_config_cbg_factor=*Pcs_pmos_config_cbg_factor;
cs_pmos_config_cbs_factor=*Pcs_pmos_config_cbs_factor;
cs_pmos_config_cbb_factor=*Pcs_pmos_config_cbb_factor;
cs_pmos_property_BW_s=*Pcs_pmos_property_BW_s;
cs_pmos_p1=*Pcs_pmos_p1;
cs_pmos_p2=*Pcs_pmos_p2;
cs_pmos_pin_dNt_dvgs=*Pcs_pmos_pin_dNt_dvgs;
cs_pmos_pin_dNt_dvds=*Pcs_pmos_pin_dNt_dvds;
cs_pmos_pin_dNt_dvbs=*Pcs_pmos_pin_dNt_dvbs;
cs_pmos_pin_dNt_dl=*Pcs_pmos_pin_dNt_dl;
cs_pmos_pin_Nt_unit=*Pcs_pmos_pin_Nt_unit;
cs_pmos_pin_Nt=*Pcs_pmos_pin_Nt;
cs_pmos_pin_dNf_dvgs=*Pcs_pmos_pin_dNf_dvgs;
cs_pmos_pin_dNf_dvds=*Pcs_pmos_pin_dNf_dvds;
cs_pmos_pin_dNf_dvbs=*Pcs_pmos_pin_dNf_dvbs;
cs_pmos_pin_dNf_dl=*Pcs_pmos_pin_dNf_dl;
cs_pmos_pin_Nf_unit=*Pcs_pmos_pin_Nf_unit;
cs_pmos_pin_Nf=*Pcs_pmos_pin_Nf;
cs_pmos_config_shift_Adc=*Pcs_pmos_config_shift_Adc;
cs_pmos_config_factor_Adc=*Pcs_pmos_config_factor_Adc;
cs_pmos_config_shift_CMRR=*Pcs_pmos_config_shift_CMRR;
cs_pmos_config_factor_CMRR=*Pcs_pmos_config_factor_CMRR;
cs_pmos_config_shift_PSRR=*Pcs_pmos_config_shift_PSRR;
cs_pmos_config_factor_PSRR=*Pcs_pmos_config_factor_PSRR;
cs_pmos_config_shift_Rout=*Pcs_pmos_config_shift_Rout;
cs_pmos_config_factor_Rout=*Pcs_pmos_config_factor_Rout;
cs_pmos_config_shift_BW=*Pcs_pmos_config_shift_BW;
cs_pmos_config_factor_BW=*Pcs_pmos_config_factor_BW;
cs_pmos_config_shift_PM=*Pcs_pmos_config_shift_PM;
cs_pmos_config_factor_PM=*Pcs_pmos_config_factor_PM;
cs_pmos_config_shift_Cin=*Pcs_pmos_config_shift_Cin;
cs_pmos_config_factor_Cin=*Pcs_pmos_config_factor_Cin;
cs_pmos_config_shift_ts=*Pcs_pmos_config_shift_ts;
cs_pmos_config_factor_ts=*Pcs_pmos_config_factor_ts;
cs_pmos_config_shift_Nt=*Pcs_pmos_config_shift_Nt;
cs_pmos_config_factor_Nt=*Pcs_pmos_config_factor_Nt;
cs_pmos_config_shift_Nf=*Pcs_pmos_config_shift_Nf;
cs_pmos_config_factor_Nf=*Pcs_pmos_config_factor_Nf;
cs_pmos_config_shift_TotalNoise=*Pcs_pmos_config_shift_TotalNoise;
cs_pmos_config_factor_TotalNoise=*Pcs_pmos_config_factor_TotalNoise;
cs_pmos_config_shift_fc=*Pcs_pmos_config_shift_fc;
cs_pmos_config_factor_fc=*Pcs_pmos_config_factor_fc;
cs_pmos_config_shift_Vos=*Pcs_pmos_config_shift_Vos;
cs_pmos_config_factor_Vos=*Pcs_pmos_config_factor_Vos;
cs_pmos_config_shift_Area=*Pcs_pmos_config_shift_Area;
cs_pmos_config_factor_Area=*Pcs_pmos_config_factor_Area;
cs_pmos_config_shift_Power=*Pcs_pmos_config_shift_Power;
cs_pmos_config_factor_Power=*Pcs_pmos_config_factor_Power;
cs_pmos_circuit_breed_id=*Pcs_pmos_circuit_breed_id;
cs_pmos_circuit_breed_target=*Pcs_pmos_circuit_breed_target;

            return TCL_OK;
        }
        static int tcl_gamma_cs_pmos_export_cmd(ClientData clientData,Tcl_Interp *interp,int argc,char *argv[]) {
            *Pcs_pmos_param_area_spacing=cs_pmos_param_area_spacing;
*Pcs_pmos_param_iref=cs_pmos_param_iref;
*Pcs_pmos_param_rload=cs_pmos_param_rload;
*Pcs_pmos_param_in=cs_pmos_param_in;
*Pcs_pmos_param_vdd=cs_pmos_param_vdd;
*Pcs_pmos_param_unique=cs_pmos_param_unique;
*Pcs_pmos_look_up_tables_nch=cs_pmos_look_up_tables_nch;
*Pcs_pmos_look_up_tables_pch=cs_pmos_look_up_tables_pch;
*Pcs_pmos_size_L=cs_pmos_size_L;
*Pcs_pmos_size_W=cs_pmos_size_W;
*Pcs_pmos_size_iref=cs_pmos_size_iref;
*Pcs_pmos_0_V=cs_pmos_0_V;
*Pcs_pmos_0_Next=cs_pmos_0_Next;
*Pcs_pmos_out_V=cs_pmos_out_V;
*Pcs_pmos_out_Next=cs_pmos_out_Next;
*Pcs_pmos_in_V=cs_pmos_in_V;
*Pcs_pmos_in_Next=cs_pmos_in_Next;
*Pcs_pmos_vdd_V=cs_pmos_vdd_V;
*Pcs_pmos_vdd_Next=cs_pmos_vdd_Next;
*Pcs_pmos_property_Adc=cs_pmos_property_Adc;
*Pcs_pmos_property_CMRR=cs_pmos_property_CMRR;
*Pcs_pmos_property_PSRR=cs_pmos_property_PSRR;
*Pcs_pmos_property_Rout=cs_pmos_property_Rout;
*Pcs_pmos_property_BW=cs_pmos_property_BW;
*Pcs_pmos_property_PM=cs_pmos_property_PM;
*Pcs_pmos_property_Cin=cs_pmos_property_Cin;
*Pcs_pmos_property_ts=cs_pmos_property_ts;
*Pcs_pmos_property_Nt=cs_pmos_property_Nt;
*Pcs_pmos_property_Nf=cs_pmos_property_Nf;
*Pcs_pmos_property_TotalNoise=cs_pmos_property_TotalNoise;
*Pcs_pmos_property_fc=cs_pmos_property_fc;
*Pcs_pmos_property_Vos=cs_pmos_property_Vos;
*Pcs_pmos_property_Area=cs_pmos_property_Area;
*Pcs_pmos_property_Power=cs_pmos_property_Power;
*Pcs_pmos_pin_Ideq=cs_pmos_pin_Ideq;
*Pcs_pmos_pin_go=cs_pmos_pin_go;
*Pcs_pmos_pin_gm=cs_pmos_pin_gm;
*Pcs_pmos_pin_cgd=cs_pmos_pin_cgd;
*Pcs_pmos_pin_cgg=cs_pmos_pin_cgg;
*Pcs_pmos_pin_cgs=cs_pmos_pin_cgs;
*Pcs_pmos_pin_cgb=cs_pmos_pin_cgb;
*Pcs_pmos_pin_cdd=cs_pmos_pin_cdd;
*Pcs_pmos_pin_cdg=cs_pmos_pin_cdg;
*Pcs_pmos_pin_cds=cs_pmos_pin_cds;
*Pcs_pmos_pin_cdb=cs_pmos_pin_cdb;
*Pcs_pmos_pin_csd=cs_pmos_pin_csd;
*Pcs_pmos_pin_csg=cs_pmos_pin_csg;
*Pcs_pmos_pin_css=cs_pmos_pin_css;
*Pcs_pmos_pin_csb=cs_pmos_pin_csb;
*Pcs_pmos_pin_cbd=cs_pmos_pin_cbd;
*Pcs_pmos_pin_cbg=cs_pmos_pin_cbg;
*Pcs_pmos_pin_cbs=cs_pmos_pin_cbs;
*Pcs_pmos_pin_cbb=cs_pmos_pin_cbb;
*Pcs_pmos_config_pat_size_target=cs_pmos_config_pat_size_target;
*Pcs_pmos_size_L_min=cs_pmos_size_L_min;
*Pcs_pmos_size_L_max=cs_pmos_size_L_max;
*Pcs_pmos_size_W_max=cs_pmos_size_W_max;
*Pcs_pmos_size_iref_min=cs_pmos_size_iref_min;
*Pcs_pmos_size_iref_max=cs_pmos_size_iref_max;
*Pcs_pmos_size_L_step=cs_pmos_size_L_step;
*Pcs_pmos_size_W_step=cs_pmos_size_W_step;
*Pcs_pmos_size_iref_step=cs_pmos_size_iref_step;
*Pcs_pmos_max_Adc=cs_pmos_max_Adc;
*Pcs_pmos_pat_size_target=cs_pmos_pat_size_target;
*Pcs_pmos_mode_freash_op=cs_pmos_mode_freash_op;
*Pcs_pmos_status_index=cs_pmos_status_index;
*Pcs_pmos_config_size_L=cs_pmos_config_size_L;
*Pcs_pmos_config_size_W=cs_pmos_config_size_W;
*Pcs_pmos_config_size_iref=cs_pmos_config_size_iref;
*Pcs_pmos_status_fail=cs_pmos_status_fail;
*Pcs_pmos_design_feedback=cs_pmos_design_feedback;
*Pcs_pmos_pin_bin=cs_pmos_pin_bin;
*Pcs_pmos_pin_W=cs_pmos_pin_W;
*Pcs_pmos_pin_L=cs_pmos_pin_L;
*Pcs_pmos_leak=cs_pmos_leak;
*Pcs_pmos_config_op_iterations=cs_pmos_config_op_iterations;
*Pcs_pmos_config_kcl_th=cs_pmos_config_kcl_th;
*Pcs_pmos_config_design_feedback_th=cs_pmos_config_design_feedback_th;
*Pcs_pmos_pin_gb=cs_pmos_pin_gb;
*Pcs_pmos_pin_Ids=cs_pmos_pin_Ids;
*Pcs_pmos_config_kcl_step=cs_pmos_config_kcl_step;
*Pcs_pmos_config_fail_on_properties=cs_pmos_config_fail_on_properties;
*Pcs_pmos_s=cs_pmos_s;
*Pcs_pmos_config_cgg_factor=cs_pmos_config_cgg_factor;
*Pcs_pmos_config_cgd_factor=cs_pmos_config_cgd_factor;
*Pcs_pmos_config_cgs_factor=cs_pmos_config_cgs_factor;
*Pcs_pmos_config_cgb_factor=cs_pmos_config_cgb_factor;
*Pcs_pmos_config_cdd_factor=cs_pmos_config_cdd_factor;
*Pcs_pmos_config_cdg_factor=cs_pmos_config_cdg_factor;
*Pcs_pmos_config_cdb_factor=cs_pmos_config_cdb_factor;
*Pcs_pmos_config_cds_factor=cs_pmos_config_cds_factor;
*Pcs_pmos_config_csd_factor=cs_pmos_config_csd_factor;
*Pcs_pmos_config_csg_factor=cs_pmos_config_csg_factor;
*Pcs_pmos_config_css_factor=cs_pmos_config_css_factor;
*Pcs_pmos_config_csb_factor=cs_pmos_config_csb_factor;
*Pcs_pmos_config_cbd_factor=cs_pmos_config_cbd_factor;
*Pcs_pmos_config_cbg_factor=cs_pmos_config_cbg_factor;
*Pcs_pmos_config_cbs_factor=cs_pmos_config_cbs_factor;
*Pcs_pmos_config_cbb_factor=cs_pmos_config_cbb_factor;
*Pcs_pmos_property_BW_s=cs_pmos_property_BW_s;
*Pcs_pmos_p1=cs_pmos_p1;
*Pcs_pmos_p2=cs_pmos_p2;
*Pcs_pmos_pin_dNt_dvgs=cs_pmos_pin_dNt_dvgs;
*Pcs_pmos_pin_dNt_dvds=cs_pmos_pin_dNt_dvds;
*Pcs_pmos_pin_dNt_dvbs=cs_pmos_pin_dNt_dvbs;
*Pcs_pmos_pin_dNt_dl=cs_pmos_pin_dNt_dl;
*Pcs_pmos_pin_Nt_unit=cs_pmos_pin_Nt_unit;
*Pcs_pmos_pin_Nt=cs_pmos_pin_Nt;
*Pcs_pmos_pin_dNf_dvgs=cs_pmos_pin_dNf_dvgs;
*Pcs_pmos_pin_dNf_dvds=cs_pmos_pin_dNf_dvds;
*Pcs_pmos_pin_dNf_dvbs=cs_pmos_pin_dNf_dvbs;
*Pcs_pmos_pin_dNf_dl=cs_pmos_pin_dNf_dl;
*Pcs_pmos_pin_Nf_unit=cs_pmos_pin_Nf_unit;
*Pcs_pmos_pin_Nf=cs_pmos_pin_Nf;
*Pcs_pmos_config_shift_Adc=cs_pmos_config_shift_Adc;
*Pcs_pmos_config_factor_Adc=cs_pmos_config_factor_Adc;
*Pcs_pmos_config_shift_CMRR=cs_pmos_config_shift_CMRR;
*Pcs_pmos_config_factor_CMRR=cs_pmos_config_factor_CMRR;
*Pcs_pmos_config_shift_PSRR=cs_pmos_config_shift_PSRR;
*Pcs_pmos_config_factor_PSRR=cs_pmos_config_factor_PSRR;
*Pcs_pmos_config_shift_Rout=cs_pmos_config_shift_Rout;
*Pcs_pmos_config_factor_Rout=cs_pmos_config_factor_Rout;
*Pcs_pmos_config_shift_BW=cs_pmos_config_shift_BW;
*Pcs_pmos_config_factor_BW=cs_pmos_config_factor_BW;
*Pcs_pmos_config_shift_PM=cs_pmos_config_shift_PM;
*Pcs_pmos_config_factor_PM=cs_pmos_config_factor_PM;
*Pcs_pmos_config_shift_Cin=cs_pmos_config_shift_Cin;
*Pcs_pmos_config_factor_Cin=cs_pmos_config_factor_Cin;
*Pcs_pmos_config_shift_ts=cs_pmos_config_shift_ts;
*Pcs_pmos_config_factor_ts=cs_pmos_config_factor_ts;
*Pcs_pmos_config_shift_Nt=cs_pmos_config_shift_Nt;
*Pcs_pmos_config_factor_Nt=cs_pmos_config_factor_Nt;
*Pcs_pmos_config_shift_Nf=cs_pmos_config_shift_Nf;
*Pcs_pmos_config_factor_Nf=cs_pmos_config_factor_Nf;
*Pcs_pmos_config_shift_TotalNoise=cs_pmos_config_shift_TotalNoise;
*Pcs_pmos_config_factor_TotalNoise=cs_pmos_config_factor_TotalNoise;
*Pcs_pmos_config_shift_fc=cs_pmos_config_shift_fc;
*Pcs_pmos_config_factor_fc=cs_pmos_config_factor_fc;
*Pcs_pmos_config_shift_Vos=cs_pmos_config_shift_Vos;
*Pcs_pmos_config_factor_Vos=cs_pmos_config_factor_Vos;
*Pcs_pmos_config_shift_Area=cs_pmos_config_shift_Area;
*Pcs_pmos_config_factor_Area=cs_pmos_config_factor_Area;
*Pcs_pmos_config_shift_Power=cs_pmos_config_shift_Power;
*Pcs_pmos_config_factor_Power=cs_pmos_config_factor_Power;
*Pcs_pmos_circuit_breed_id=cs_pmos_circuit_breed_id;
*Pcs_pmos_circuit_breed_target=cs_pmos_circuit_breed_target;

            return TCL_OK;
        }
        static int tcl_gamma_cs_pmos_op_cmd(ClientData clientData,Tcl_Interp *interp,int argc,char *argv[]) {
            //            Tcl_ResetResult(interp);
            if (cs_pmos_mode_freash_op) {
cs_pmos_out_V=cs_pmos_vdd_V/2;
cs_pmos_in_V=cs_pmos_param_in;
}
cs_pmos_status_index=0;
if(cs_pmos_config_size_L!=0) cs_pmos_size_L=cs_pmos_config_size_L;
if(cs_pmos_config_size_W!=0) cs_pmos_size_W=cs_pmos_config_size_W;
if(cs_pmos_config_size_iref!=0) cs_pmos_size_iref=cs_pmos_config_size_iref;
cs_pmos_vdd_V=1.1;
cs_pmos_0_V=0;
// Calculating circuit operating point:
int op_it=0;
cs_pmos_status_fail=-1;
cs_pmos_design_feedback=1000;
cs_pmos_pin_bin=get_transistor_bin(Pcs_pmos_look_up_tables_pch_binning_LUT,cs_pmos_pin_L,cs_pmos_pin_W);
cs_pmos_leak=1e3;
float node_step=0;
for (op_it=0;(op_it<cs_pmos_config_op_iterations)&&((cs_pmos_leak>cs_pmos_config_kcl_th)||(cs_pmos_design_feedback>cs_pmos_config_design_feedback_th));op_it++) {
float previous_out_dc=cs_pmos_out_V;
composite_gamma_gcc_interpolate_2p3(cs_pmos_pin_bin,Pcs_pmos_look_up_tables_pch_Ids_ss_CONTEXT,Pcs_pmos_look_up_tables_pch_gm_ss_CONTEXT,Pcs_pmos_look_up_tables_pch_go_ss_CONTEXT,Pcs_pmos_look_up_tables_pch_gb_ss_CONTEXT,&(cs_pmos_pin_gb),&(cs_pmos_pin_gm),&(cs_pmos_pin_go),&(cs_pmos_pin_Ids),(cs_pmos_in_V)-(cs_pmos_vdd_V),(cs_pmos_out_V)-(cs_pmos_vdd_V),(cs_pmos_vdd_V)-(cs_pmos_vdd_V),cs_pmos_size_L,cs_pmos_size_W);
if (cs_pmos_pin_Ids<0) cs_pmos_pin_Ids=0;
if (cs_pmos_pin_Ids>1e-3) cs_pmos_pin_Ids=1e-3;
cs_pmos_pin_Ids=-cs_pmos_pin_Ids;
if (cs_pmos_pin_gm==0) cs_pmos_pin_gm=1e-6;
if (cs_pmos_pin_go==0) cs_pmos_pin_go=1e-6;
// Updating node voltages
cs_pmos_leak=0;
node_step=cs_pmos_config_kcl_step*(-cs_pmos_size_iref-cs_pmos_pin_Ids)/(cs_pmos_pin_go);
if (node_step<-0.02) node_step=-0.02;
if (node_step>0.02) node_step=0.02;
cs_pmos_out_V+=node_step;
if (fabs(-cs_pmos_size_iref-cs_pmos_pin_Ids)>cs_pmos_leak) cs_pmos_leak=fabs(-cs_pmos_size_iref-cs_pmos_pin_Ids);
if (cs_pmos_out_V<0) cs_pmos_out_V=0;
if (cs_pmos_out_V>1.1) cs_pmos_out_V=1.1;
cs_pmos_design_feedback=0;
}
if (op_it>=cs_pmos_config_op_iterations) {cs_pmos_status_fail=cs_pmos_leak; return TCL_ERROR;}
if (cs_pmos_vdd_V<cs_pmos_out_V) {cs_pmos_status_fail=4; return TCL_ERROR;}
float W,M;
double Det=(-cs_pmos_pin_go);
double Ted=1/Det;
cs_pmos_property_Adc=Ted*(cs_pmos_pin_gm);
cs_pmos_property_CMRR=cs_pmos_property_Adc;
cs_pmos_property_PSRR=Ted*(((-cs_pmos_pin_go)-cs_pmos_pin_gm));
cs_pmos_property_Adc=fabs(cs_pmos_property_Adc);
if ((cs_pmos_property_Adc<1)&&(cs_pmos_config_fail_on_properties)) {cs_pmos_status_fail=2; return TCL_ERROR;}
cs_pmos_property_Rout=fabs(((-(-1)))*Ted);
//AC output: (((cs_pmos_pin_gm+cs_pmos_pin_cdg*cs_pmos_s)*(-cs_pmos_param_in)-((-cs_pmos_size_iref)-cs_pmos_pin_Ideq))+((((-cs_pmos_pin_go)-cs_pmos_pin_gm)+cs_pmos_pin_cds*cs_pmos_s)+cs_pmos_pin_cdb*cs_pmos_s)*(-cs_pmos_param_vdd))/(-(cs_pmos_pin_go+cs_pmos_pin_cdd*cs_pmos_s))
//AC gain: (cs_pmos_pin_gm+cs_pmos_pin_cdg*cs_pmos_s)/(-(cs_pmos_pin_go+cs_pmos_pin_cdd*cs_pmos_s))
cs_pmos_pin_cgg=gamma_gcc_interpolate_4(Pcs_pmos_look_up_tables_pch_cgg_ss_LUT,(cs_pmos_in_V)-(cs_pmos_vdd_V),(cs_pmos_out_V)-(cs_pmos_vdd_V),(cs_pmos_vdd_V)-(cs_pmos_vdd_V),cs_pmos_size_L)*cs_pmos_size_L*cs_pmos_size_W*cs_pmos_config_cgg_factor;
cs_pmos_pin_cgd=gamma_gcc_interpolate_4(Pcs_pmos_look_up_tables_pch_cgd_ss_LUT,(cs_pmos_in_V)-(cs_pmos_vdd_V),(cs_pmos_out_V)-(cs_pmos_vdd_V),(cs_pmos_vdd_V)-(cs_pmos_vdd_V),cs_pmos_size_L)*cs_pmos_size_L*cs_pmos_size_W*cs_pmos_config_cgd_factor;
cs_pmos_pin_cgs=gamma_gcc_interpolate_4(Pcs_pmos_look_up_tables_pch_cgs_ss_LUT,(cs_pmos_in_V)-(cs_pmos_vdd_V),(cs_pmos_out_V)-(cs_pmos_vdd_V),(cs_pmos_vdd_V)-(cs_pmos_vdd_V),cs_pmos_size_L)*cs_pmos_size_L*cs_pmos_size_W*cs_pmos_config_cgs_factor;
cs_pmos_pin_cgb=gamma_gcc_interpolate_4(Pcs_pmos_look_up_tables_pch_cgb_ss_LUT,(cs_pmos_in_V)-(cs_pmos_vdd_V),(cs_pmos_out_V)-(cs_pmos_vdd_V),(cs_pmos_vdd_V)-(cs_pmos_vdd_V),cs_pmos_size_L)*cs_pmos_size_L*cs_pmos_size_W*cs_pmos_config_cgb_factor;
cs_pmos_pin_cdd=gamma_gcc_interpolate_4(Pcs_pmos_look_up_tables_pch_cdd_ss_LUT,(cs_pmos_in_V)-(cs_pmos_vdd_V),(cs_pmos_out_V)-(cs_pmos_vdd_V),(cs_pmos_vdd_V)-(cs_pmos_vdd_V),cs_pmos_size_L)*cs_pmos_size_L*cs_pmos_size_W*cs_pmos_config_cdd_factor;
cs_pmos_pin_cdg=gamma_gcc_interpolate_4(Pcs_pmos_look_up_tables_pch_cdg_ss_LUT,(cs_pmos_in_V)-(cs_pmos_vdd_V),(cs_pmos_out_V)-(cs_pmos_vdd_V),(cs_pmos_vdd_V)-(cs_pmos_vdd_V),cs_pmos_size_L)*cs_pmos_size_L*cs_pmos_size_W*cs_pmos_config_cdg_factor;
cs_pmos_pin_cdb=gamma_gcc_interpolate_4(Pcs_pmos_look_up_tables_pch_cdb_ss_LUT,(cs_pmos_in_V)-(cs_pmos_vdd_V),(cs_pmos_out_V)-(cs_pmos_vdd_V),(cs_pmos_vdd_V)-(cs_pmos_vdd_V),cs_pmos_size_L)*cs_pmos_size_L*cs_pmos_size_W*cs_pmos_config_cdb_factor;
cs_pmos_pin_cds=gamma_gcc_interpolate_4(Pcs_pmos_look_up_tables_pch_cds_ss_LUT,(cs_pmos_in_V)-(cs_pmos_vdd_V),(cs_pmos_out_V)-(cs_pmos_vdd_V),(cs_pmos_vdd_V)-(cs_pmos_vdd_V),cs_pmos_size_L)*cs_pmos_size_L*cs_pmos_size_W*cs_pmos_config_cds_factor;
cs_pmos_pin_csd=gamma_gcc_interpolate_4(Pcs_pmos_look_up_tables_pch_csd_ss_LUT,(cs_pmos_in_V)-(cs_pmos_vdd_V),(cs_pmos_out_V)-(cs_pmos_vdd_V),(cs_pmos_vdd_V)-(cs_pmos_vdd_V),cs_pmos_size_L)*cs_pmos_size_L*cs_pmos_size_W*cs_pmos_config_csd_factor;
cs_pmos_pin_csg=gamma_gcc_interpolate_4(Pcs_pmos_look_up_tables_pch_csg_ss_LUT,(cs_pmos_in_V)-(cs_pmos_vdd_V),(cs_pmos_out_V)-(cs_pmos_vdd_V),(cs_pmos_vdd_V)-(cs_pmos_vdd_V),cs_pmos_size_L)*cs_pmos_size_L*cs_pmos_size_W*cs_pmos_config_csg_factor;
cs_pmos_pin_css=gamma_gcc_interpolate_4(Pcs_pmos_look_up_tables_pch_css_ss_LUT,(cs_pmos_in_V)-(cs_pmos_vdd_V),(cs_pmos_out_V)-(cs_pmos_vdd_V),(cs_pmos_vdd_V)-(cs_pmos_vdd_V),cs_pmos_size_L)*cs_pmos_size_L*cs_pmos_size_W*cs_pmos_config_css_factor;
cs_pmos_pin_csb=gamma_gcc_interpolate_4(Pcs_pmos_look_up_tables_pch_csb_ss_LUT,(cs_pmos_in_V)-(cs_pmos_vdd_V),(cs_pmos_out_V)-(cs_pmos_vdd_V),(cs_pmos_vdd_V)-(cs_pmos_vdd_V),cs_pmos_size_L)*cs_pmos_size_L*cs_pmos_size_W*cs_pmos_config_csb_factor;
cs_pmos_pin_cbd=gamma_gcc_interpolate_4(Pcs_pmos_look_up_tables_pch_cbd_ss_LUT,(cs_pmos_in_V)-(cs_pmos_vdd_V),(cs_pmos_out_V)-(cs_pmos_vdd_V),(cs_pmos_vdd_V)-(cs_pmos_vdd_V),cs_pmos_size_L)*cs_pmos_size_L*cs_pmos_size_W*cs_pmos_config_cbd_factor;
cs_pmos_pin_cbg=gamma_gcc_interpolate_4(Pcs_pmos_look_up_tables_pch_cbg_ss_LUT,(cs_pmos_in_V)-(cs_pmos_vdd_V),(cs_pmos_out_V)-(cs_pmos_vdd_V),(cs_pmos_vdd_V)-(cs_pmos_vdd_V),cs_pmos_size_L)*cs_pmos_size_L*cs_pmos_size_W*cs_pmos_config_cbg_factor;
cs_pmos_pin_cbs=gamma_gcc_interpolate_4(Pcs_pmos_look_up_tables_pch_cbs_ss_LUT,(cs_pmos_in_V)-(cs_pmos_vdd_V),(cs_pmos_out_V)-(cs_pmos_vdd_V),(cs_pmos_vdd_V)-(cs_pmos_vdd_V),cs_pmos_size_L)*cs_pmos_size_L*cs_pmos_size_W*cs_pmos_config_cbs_factor;
cs_pmos_pin_cbb=gamma_gcc_interpolate_4(Pcs_pmos_look_up_tables_pch_cbb_ss_LUT,(cs_pmos_in_V)-(cs_pmos_vdd_V),(cs_pmos_out_V)-(cs_pmos_vdd_V),(cs_pmos_vdd_V)-(cs_pmos_vdd_V),cs_pmos_size_L)*cs_pmos_size_L*cs_pmos_size_W*cs_pmos_config_cbb_factor;
float s=-1;
int BW_it;
W=0;
float BW_Mag0=1;
float BW_Mag=1;
float snr;
float sni;
float sdr;
float sdi;
while ((BW_Mag0/BW_Mag)<2) {
      snr=cs_pmos_pin_gm;
      sni=cs_pmos_pin_cdg*W;
      sdr=-(cs_pmos_pin_go+cs_pmos_pin_cdd*s);
      sdi=0;
      BW_Mag=(snr*snr+sni*sni)/(sdr*sdr+sdi*sdi);
      if (W==0) BW_Mag0=BW_Mag;
      if (W==0) W=1; else W*=1.01;
}
cs_pmos_property_BW=fabs(W/(2*3.141592656));
for (BW_it=0;BW_it<5;BW_it++)  s-=((-(cs_pmos_pin_go+cs_pmos_pin_cdd*s)))/((-cs_pmos_pin_cdd));
cs_pmos_property_BW_s=(-cs_pmos_pin_cdd);
cs_pmos_p1=-s;
if (!isfinite(cs_pmos_property_BW))  {cs_pmos_status_fail=8; return TCL_ERROR;}
s-=1e3;
for (BW_it=0;BW_it<20;BW_it++)  s-=(((-(cs_pmos_pin_go+cs_pmos_pin_cdd*s)))*(s+cs_pmos_p1-5e2))/(((-cs_pmos_pin_cdd))*(s+cs_pmos_p1-5e2)-((-(cs_pmos_pin_go+cs_pmos_pin_cdd*s))));
cs_pmos_p2=-s;
if (!isfinite(cs_pmos_p1)) {
    cs_pmos_property_ts=1/cs_pmos_property_BW;
} else if (!isfinite(cs_pmos_p2)) {
    cs_pmos_property_ts=-log(0.02)/cs_pmos_p1;
} else {
    float A1=-cs_pmos_p2/(-cs_pmos_p1+cs_pmos_p2);
    float A2=-cs_pmos_p1/(-cs_pmos_p1+cs_pmos_p2);
    cs_pmos_property_ts=0;
    for (BW_it=0;BW_it<10;BW_it++) cs_pmos_property_ts-=(0.02+A1*exp(-cs_pmos_p1*cs_pmos_property_ts)+A2*exp(-cs_pmos_p2*cs_pmos_property_ts))/(-cs_pmos_p1*A1*exp(-cs_pmos_p1*cs_pmos_property_ts)-cs_pmos_p2*A2*exp(-cs_pmos_p2*cs_pmos_property_ts));
}
if (!isfinite(cs_pmos_property_ts)) {
    cs_pmos_property_ts=1/cs_pmos_property_BW;
}
cs_pmos_property_Cin=cs_pmos_pin_cgd+cs_pmos_pin_cgs;
cs_pmos_property_PM=(cs_pmos_property_BW/9.76e8)+(cs_pmos_property_Adc-21)-sqrt(cs_pmos_size_L*cs_pmos_size_W)/5e-7-cs_pmos_size_iref*2.5e4;
cs_pmos_property_PM=(cs_pmos_property_PM*180/3.1415)/2.16+29-1.4-0.75/2;
while (cs_pmos_property_PM<0) cs_pmos_property_PM+=360;
while (fabs(cs_pmos_property_PM)>180) cs_pmos_property_PM-=360;
cs_pmos_property_PM=fabs(cs_pmos_property_PM);
while (BW_Mag>4) {
      snr=cs_pmos_pin_gm;
      sni=cs_pmos_pin_cdg*W;
      sdr=-(cs_pmos_pin_go+cs_pmos_pin_cdd*s);
      sdi=0;
      BW_Mag=(snr*snr+sni*sni)/(sdr*sdr+sdi*sdi);
      W*=1.01;
}
cs_pmos_property_PM=180-180*(atan(sni/snr)-atan(sdi/sdr))/3.1415926;
cs_pmos_pin_Nt_unit=gamma_gcc_interpolateg_4(&cs_pmos__look_up_tables_pch_thermal_noise_ss_LUT,(cs_pmos_in_V-cs_pmos_vdd_V),(cs_pmos_out_V-cs_pmos_vdd_V),0,cs_pmos_size_L,&cs_pmos_pin_dNt_dvgs,&cs_pmos_pin_dNt_dvds,&cs_pmos_pin_dNt_dvbs,&cs_pmos_pin_dNt_dl);
cs_pmos_pin_Nt=cs_pmos_pin_Nt_unit*cs_pmos_pin_go;
if (!isfinite(cs_pmos_pin_Nt))  {cs_pmos_status_fail=5; return TCL_ERROR;}
cs_pmos_pin_Nf_unit=gamma_gcc_interpolateg_4(&cs_pmos__look_up_tables_pch_flicker_noise_ss_LUT,(cs_pmos_in_V-cs_pmos_vdd_V),(cs_pmos_out_V-cs_pmos_vdd_V),0,cs_pmos_size_L,&cs_pmos_pin_dNf_dvgs,&cs_pmos_pin_dNf_dvds,&cs_pmos_pin_dNf_dvbs,&cs_pmos_pin_dNf_dl);
cs_pmos_pin_Nf=cs_pmos_pin_Nf_unit*cs_pmos_pin_go*cs_pmos_pin_go/(cs_pmos_size_W*cs_pmos_size_L);
if (!isfinite(cs_pmos_pin_Nf))  {cs_pmos_status_fail=6; return TCL_ERROR;}
float current_transfer_pin=Ted*((-(-1)))/cs_pmos_property_Adc;
cs_pmos_property_Nt=(current_transfer_pin*current_transfer_pin*cs_pmos_pin_Nt)/cs_pmos_property_Adc;
cs_pmos_property_Nf=(current_transfer_pin*current_transfer_pin*cs_pmos_pin_Nf)/cs_pmos_property_Adc;
cs_pmos_property_fc=cs_pmos_property_Nf/cs_pmos_property_Nt;
cs_pmos_property_TotalNoise=(log(2*cs_pmos_property_BW)*cs_pmos_property_Nf+2*cs_pmos_property_BW*cs_pmos_property_Nt);
cs_pmos_property_Area=1e12*(cs_pmos_size_W*cs_pmos_size_L);
float single_transistor_vos;
cs_pmos_property_Vos=0;
single_transistor_vos=vos(-cs_pmos_pin_Ids*cs_pmos_size_L/cs_pmos_size_W,cs_pmos_property_Area);
cs_pmos_property_Vos+=single_transistor_vos*single_transistor_vos;
cs_pmos_property_Vos=1e-3*sqrt(cs_pmos_property_Vos);
cs_pmos_property_Power=0;
cs_pmos_property_Power+=fabs(cs_pmos_pin_Ids*((cs_pmos_out_V)-(cs_pmos_vdd_V)));
cs_pmos_property_Adc=20*log10(fabs(cs_pmos_property_Adc));
cs_pmos_property_CMRR=20*log10(fabs(cs_pmos_property_CMRR));
cs_pmos_property_CMRR=cs_pmos_property_Adc-cs_pmos_property_CMRR;
cs_pmos_property_PSRR=20*log10(fabs(cs_pmos_property_PSRR));
cs_pmos_property_PSRR=cs_pmos_property_Adc-cs_pmos_property_PSRR;
if (cs_pmos_max_Adc<cs_pmos_property_Adc) cs_pmos_max_Adc=cs_pmos_property_Adc;
PAT *p=(PAT *)Pcs_pmos_cs_pmos_circuits_PAT;
float sizes[4];
sizes[0]=cs_pmos_size_L;
sizes[1]=cs_pmos_size_W;
sizes[2]=cs_pmos_size_iref;
sizes[3]=cs_pmos_out_V;
float properties[15];
if ((cs_pmos_config_factor_Adc!=0)||(cs_pmos_config_shift_Adc!=0)) cs_pmos_property_Adc=cs_pmos_property_Adc*cs_pmos_config_factor_Adc+cs_pmos_config_shift_Adc;
properties[0]=cs_pmos_property_Adc;
if ((cs_pmos_config_factor_CMRR!=0)||(cs_pmos_config_shift_CMRR!=0)) cs_pmos_property_CMRR=cs_pmos_property_CMRR*cs_pmos_config_factor_CMRR+cs_pmos_config_shift_CMRR;
properties[1]=cs_pmos_property_CMRR;
if ((cs_pmos_config_factor_PSRR!=0)||(cs_pmos_config_shift_PSRR!=0)) cs_pmos_property_PSRR=cs_pmos_property_PSRR*cs_pmos_config_factor_PSRR+cs_pmos_config_shift_PSRR;
properties[2]=cs_pmos_property_PSRR;
if ((cs_pmos_config_factor_Rout!=0)||(cs_pmos_config_shift_Rout!=0)) cs_pmos_property_Rout=cs_pmos_property_Rout*cs_pmos_config_factor_Rout+cs_pmos_config_shift_Rout;
properties[3]=cs_pmos_property_Rout;
if ((cs_pmos_config_factor_BW!=0)||(cs_pmos_config_shift_BW!=0)) cs_pmos_property_BW=cs_pmos_property_BW*cs_pmos_config_factor_BW+cs_pmos_config_shift_BW;
properties[4]=cs_pmos_property_BW;
if ((cs_pmos_config_factor_PM!=0)||(cs_pmos_config_shift_PM!=0)) cs_pmos_property_PM=cs_pmos_property_PM*cs_pmos_config_factor_PM+cs_pmos_config_shift_PM;
properties[5]=cs_pmos_property_PM;
if ((cs_pmos_config_factor_Cin!=0)||(cs_pmos_config_shift_Cin!=0)) cs_pmos_property_Cin=cs_pmos_property_Cin*cs_pmos_config_factor_Cin+cs_pmos_config_shift_Cin;
properties[6]=cs_pmos_property_Cin;
if ((cs_pmos_config_factor_ts!=0)||(cs_pmos_config_shift_ts!=0)) cs_pmos_property_ts=cs_pmos_property_ts*cs_pmos_config_factor_ts+cs_pmos_config_shift_ts;
properties[7]=cs_pmos_property_ts;
if ((cs_pmos_config_factor_Nt!=0)||(cs_pmos_config_shift_Nt!=0)) cs_pmos_property_Nt=cs_pmos_property_Nt*cs_pmos_config_factor_Nt+cs_pmos_config_shift_Nt;
properties[8]=cs_pmos_property_Nt;
if ((cs_pmos_config_factor_Nf!=0)||(cs_pmos_config_shift_Nf!=0)) cs_pmos_property_Nf=cs_pmos_property_Nf*cs_pmos_config_factor_Nf+cs_pmos_config_shift_Nf;
properties[9]=cs_pmos_property_Nf;
if ((cs_pmos_config_factor_TotalNoise!=0)||(cs_pmos_config_shift_TotalNoise!=0)) cs_pmos_property_TotalNoise=cs_pmos_property_TotalNoise*cs_pmos_config_factor_TotalNoise+cs_pmos_config_shift_TotalNoise;
properties[10]=cs_pmos_property_TotalNoise;
if ((cs_pmos_config_factor_fc!=0)||(cs_pmos_config_shift_fc!=0)) cs_pmos_property_fc=cs_pmos_property_fc*cs_pmos_config_factor_fc+cs_pmos_config_shift_fc;
properties[11]=cs_pmos_property_fc;
if ((cs_pmos_config_factor_Vos!=0)||(cs_pmos_config_shift_Vos!=0)) cs_pmos_property_Vos=cs_pmos_property_Vos*cs_pmos_config_factor_Vos+cs_pmos_config_shift_Vos;
properties[12]=cs_pmos_property_Vos;
if ((cs_pmos_config_factor_Area!=0)||(cs_pmos_config_shift_Area!=0)) cs_pmos_property_Area=cs_pmos_property_Area*cs_pmos_config_factor_Area+cs_pmos_config_shift_Area;
properties[13]=cs_pmos_property_Area;
if ((cs_pmos_config_factor_Power!=0)||(cs_pmos_config_shift_Power!=0)) cs_pmos_property_Power=cs_pmos_property_Power*cs_pmos_config_factor_Power+cs_pmos_config_shift_Power;
properties[14]=cs_pmos_property_Power;
cs_pmos_status_fail=op_it;
cs_pmos_status_index=add_pat_array(p,sizes,properties);

            return TCL_OK;
        }
        //      static int tcl_gamma_grad_cmd(ClientData clientData,Tcl_Interp *interp,int argc,char *argv[]) {
            //            Tcl_ResetResult(interp);
            //          GRAD_CODE_GOES_HERE
            //         return TCL_OK;
        //    }
        static int tcl_gamma_cs_pmos_heatmap_cmd(ClientData clientData,Tcl_Interp *interp,int argc,char *argv[]) {
            int i,j;
ClientData CD;
if ((argc!=15)&&(argc!=14)&&(argc!=13)) {
    #Error: "%s: usage: %s <x context> <minX> <maxX> <stepX> <y context> <minY> <maxY> <stepY> <z context> <pixel width> <pixel height> <pallet> [<pallet mode> {[<pass threshold>]}]" argv[0] argv[0]
    return TCL_ERROR;
}
    float *pX=(float *)&(create_context(argv[1]))->value.s;
    float *pY=(float *)&(create_context(argv[5]))->value.s;
    float *pZ=(float *)&(create_context(argv[7]))->value.s;
    float *PX=NULL;
if (strcmp(argv[1],"param:area_spacing")==0) PX=&(cs_pmos_param_area_spacing);
if (strcmp(argv[1],"param:iref")==0) PX=&(cs_pmos_param_iref);
if (strcmp(argv[1],"param:rload")==0) PX=&(cs_pmos_param_rload);
if (strcmp(argv[1],"param:in")==0) PX=&(cs_pmos_param_in);
if (strcmp(argv[1],"param:vdd")==0) PX=&(cs_pmos_param_vdd);
if (strcmp(argv[1],"param:unique")==0) PX=&(cs_pmos_param_unique);
if (strcmp(argv[1],"look_up_tables:nch")==0) PX=&(cs_pmos_look_up_tables_nch);
if (strcmp(argv[1],"look_up_tables:pch")==0) PX=&(cs_pmos_look_up_tables_pch);
if (strcmp(argv[1],"size:L")==0) PX=&(cs_pmos_size_L);
if (strcmp(argv[1],"size:W")==0) PX=&(cs_pmos_size_W);
if (strcmp(argv[1],"size:iref")==0) PX=&(cs_pmos_size_iref);
if (strcmp(argv[1],"0:V")==0) PX=&(cs_pmos_0_V);
if (strcmp(argv[1],"0:Next")==0) PX=&(cs_pmos_0_Next);
if (strcmp(argv[1],"out:V")==0) PX=&(cs_pmos_out_V);
if (strcmp(argv[1],"out:Next")==0) PX=&(cs_pmos_out_Next);
if (strcmp(argv[1],"in:V")==0) PX=&(cs_pmos_in_V);
if (strcmp(argv[1],"in:Next")==0) PX=&(cs_pmos_in_Next);
if (strcmp(argv[1],"vdd:V")==0) PX=&(cs_pmos_vdd_V);
if (strcmp(argv[1],"vdd:Next")==0) PX=&(cs_pmos_vdd_Next);
if (strcmp(argv[1],"property:Adc")==0) PX=&(cs_pmos_property_Adc);
if (strcmp(argv[1],"property:CMRR")==0) PX=&(cs_pmos_property_CMRR);
if (strcmp(argv[1],"property:PSRR")==0) PX=&(cs_pmos_property_PSRR);
if (strcmp(argv[1],"property:Rout")==0) PX=&(cs_pmos_property_Rout);
if (strcmp(argv[1],"property:BW")==0) PX=&(cs_pmos_property_BW);
if (strcmp(argv[1],"property:PM")==0) PX=&(cs_pmos_property_PM);
if (strcmp(argv[1],"property:Cin")==0) PX=&(cs_pmos_property_Cin);
if (strcmp(argv[1],"property:ts")==0) PX=&(cs_pmos_property_ts);
if (strcmp(argv[1],"property:Nt")==0) PX=&(cs_pmos_property_Nt);
if (strcmp(argv[1],"property:Nf")==0) PX=&(cs_pmos_property_Nf);
if (strcmp(argv[1],"property:TotalNoise")==0) PX=&(cs_pmos_property_TotalNoise);
if (strcmp(argv[1],"property:fc")==0) PX=&(cs_pmos_property_fc);
if (strcmp(argv[1],"property:Vos")==0) PX=&(cs_pmos_property_Vos);
if (strcmp(argv[1],"property:Area")==0) PX=&(cs_pmos_property_Area);
if (strcmp(argv[1],"property:Power")==0) PX=&(cs_pmos_property_Power);
if (strcmp(argv[1],"pin:Ideq")==0) PX=&(cs_pmos_pin_Ideq);
if (strcmp(argv[1],"pin:go")==0) PX=&(cs_pmos_pin_go);
if (strcmp(argv[1],"pin:gm")==0) PX=&(cs_pmos_pin_gm);
if (strcmp(argv[1],"pin:cgd")==0) PX=&(cs_pmos_pin_cgd);
if (strcmp(argv[1],"pin:cgg")==0) PX=&(cs_pmos_pin_cgg);
if (strcmp(argv[1],"pin:cgs")==0) PX=&(cs_pmos_pin_cgs);
if (strcmp(argv[1],"pin:cgb")==0) PX=&(cs_pmos_pin_cgb);
if (strcmp(argv[1],"pin:cdd")==0) PX=&(cs_pmos_pin_cdd);
if (strcmp(argv[1],"pin:cdg")==0) PX=&(cs_pmos_pin_cdg);
if (strcmp(argv[1],"pin:cds")==0) PX=&(cs_pmos_pin_cds);
if (strcmp(argv[1],"pin:cdb")==0) PX=&(cs_pmos_pin_cdb);
if (strcmp(argv[1],"pin:csd")==0) PX=&(cs_pmos_pin_csd);
if (strcmp(argv[1],"pin:csg")==0) PX=&(cs_pmos_pin_csg);
if (strcmp(argv[1],"pin:css")==0) PX=&(cs_pmos_pin_css);
if (strcmp(argv[1],"pin:csb")==0) PX=&(cs_pmos_pin_csb);
if (strcmp(argv[1],"pin:cbd")==0) PX=&(cs_pmos_pin_cbd);
if (strcmp(argv[1],"pin:cbg")==0) PX=&(cs_pmos_pin_cbg);
if (strcmp(argv[1],"pin:cbs")==0) PX=&(cs_pmos_pin_cbs);
if (strcmp(argv[1],"pin:cbb")==0) PX=&(cs_pmos_pin_cbb);
if (PX==NULL) {
    #Error: "%s: context %s is not available for heatmap generation." argv[0] argv[1]
    return TCL_ERROR;
}
float minX=atof(argv[2]);
float maxX=atof(argv[3]);
float stepX=atof(argv[4]);
    float *PY=NULL;
if (strcmp(argv[5],"param:area_spacing")==0) PY=&(cs_pmos_param_area_spacing);
if (strcmp(argv[5],"param:iref")==0) PY=&(cs_pmos_param_iref);
if (strcmp(argv[5],"param:rload")==0) PY=&(cs_pmos_param_rload);
if (strcmp(argv[5],"param:in")==0) PY=&(cs_pmos_param_in);
if (strcmp(argv[5],"param:vdd")==0) PY=&(cs_pmos_param_vdd);
if (strcmp(argv[5],"param:unique")==0) PY=&(cs_pmos_param_unique);
if (strcmp(argv[5],"look_up_tables:nch")==0) PY=&(cs_pmos_look_up_tables_nch);
if (strcmp(argv[5],"look_up_tables:pch")==0) PY=&(cs_pmos_look_up_tables_pch);
if (strcmp(argv[5],"size:L")==0) PY=&(cs_pmos_size_L);
if (strcmp(argv[5],"size:W")==0) PY=&(cs_pmos_size_W);
if (strcmp(argv[5],"size:iref")==0) PY=&(cs_pmos_size_iref);
if (strcmp(argv[5],"0:V")==0) PY=&(cs_pmos_0_V);
if (strcmp(argv[5],"0:Next")==0) PY=&(cs_pmos_0_Next);
if (strcmp(argv[5],"out:V")==0) PY=&(cs_pmos_out_V);
if (strcmp(argv[5],"out:Next")==0) PY=&(cs_pmos_out_Next);
if (strcmp(argv[5],"in:V")==0) PY=&(cs_pmos_in_V);
if (strcmp(argv[5],"in:Next")==0) PY=&(cs_pmos_in_Next);
if (strcmp(argv[5],"vdd:V")==0) PY=&(cs_pmos_vdd_V);
if (strcmp(argv[5],"vdd:Next")==0) PY=&(cs_pmos_vdd_Next);
if (strcmp(argv[5],"property:Adc")==0) PY=&(cs_pmos_property_Adc);
if (strcmp(argv[5],"property:CMRR")==0) PY=&(cs_pmos_property_CMRR);
if (strcmp(argv[5],"property:PSRR")==0) PY=&(cs_pmos_property_PSRR);
if (strcmp(argv[5],"property:Rout")==0) PY=&(cs_pmos_property_Rout);
if (strcmp(argv[5],"property:BW")==0) PY=&(cs_pmos_property_BW);
if (strcmp(argv[5],"property:PM")==0) PY=&(cs_pmos_property_PM);
if (strcmp(argv[5],"property:Cin")==0) PY=&(cs_pmos_property_Cin);
if (strcmp(argv[5],"property:ts")==0) PY=&(cs_pmos_property_ts);
if (strcmp(argv[5],"property:Nt")==0) PY=&(cs_pmos_property_Nt);
if (strcmp(argv[5],"property:Nf")==0) PY=&(cs_pmos_property_Nf);
if (strcmp(argv[5],"property:TotalNoise")==0) PY=&(cs_pmos_property_TotalNoise);
if (strcmp(argv[5],"property:fc")==0) PY=&(cs_pmos_property_fc);
if (strcmp(argv[5],"property:Vos")==0) PY=&(cs_pmos_property_Vos);
if (strcmp(argv[5],"property:Area")==0) PY=&(cs_pmos_property_Area);
if (strcmp(argv[5],"property:Power")==0) PY=&(cs_pmos_property_Power);
if (strcmp(argv[5],"pin:Ideq")==0) PY=&(cs_pmos_pin_Ideq);
if (strcmp(argv[5],"pin:go")==0) PY=&(cs_pmos_pin_go);
if (strcmp(argv[5],"pin:gm")==0) PY=&(cs_pmos_pin_gm);
if (strcmp(argv[5],"pin:cgd")==0) PY=&(cs_pmos_pin_cgd);
if (strcmp(argv[5],"pin:cgg")==0) PY=&(cs_pmos_pin_cgg);
if (strcmp(argv[5],"pin:cgs")==0) PY=&(cs_pmos_pin_cgs);
if (strcmp(argv[5],"pin:cgb")==0) PY=&(cs_pmos_pin_cgb);
if (strcmp(argv[5],"pin:cdd")==0) PY=&(cs_pmos_pin_cdd);
if (strcmp(argv[5],"pin:cdg")==0) PY=&(cs_pmos_pin_cdg);
if (strcmp(argv[5],"pin:cds")==0) PY=&(cs_pmos_pin_cds);
if (strcmp(argv[5],"pin:cdb")==0) PY=&(cs_pmos_pin_cdb);
if (strcmp(argv[5],"pin:csd")==0) PY=&(cs_pmos_pin_csd);
if (strcmp(argv[5],"pin:csg")==0) PY=&(cs_pmos_pin_csg);
if (strcmp(argv[5],"pin:css")==0) PY=&(cs_pmos_pin_css);
if (strcmp(argv[5],"pin:csb")==0) PY=&(cs_pmos_pin_csb);
if (strcmp(argv[5],"pin:cbd")==0) PY=&(cs_pmos_pin_cbd);
if (strcmp(argv[5],"pin:cbg")==0) PY=&(cs_pmos_pin_cbg);
if (strcmp(argv[5],"pin:cbs")==0) PY=&(cs_pmos_pin_cbs);
if (strcmp(argv[5],"pin:cbb")==0) PY=&(cs_pmos_pin_cbb);
if (PY==NULL) {
    #Error: "%s: context %s is not available for heatmap generation." argv[0] argv[1]
    return TCL_ERROR;
}
float minY=atof(argv[6]);
float maxY=atof(argv[7]);
float stepY=atof(argv[8]);
    float *PZ=NULL;
if (strcmp(argv[7],"param:area_spacing")==0) PZ=&(cs_pmos_param_area_spacing);
if (strcmp(argv[7],"param:iref")==0) PZ=&(cs_pmos_param_iref);
if (strcmp(argv[7],"param:rload")==0) PZ=&(cs_pmos_param_rload);
if (strcmp(argv[7],"param:in")==0) PZ=&(cs_pmos_param_in);
if (strcmp(argv[7],"param:vdd")==0) PZ=&(cs_pmos_param_vdd);
if (strcmp(argv[7],"param:unique")==0) PZ=&(cs_pmos_param_unique);
if (strcmp(argv[7],"look_up_tables:nch")==0) PZ=&(cs_pmos_look_up_tables_nch);
if (strcmp(argv[7],"look_up_tables:pch")==0) PZ=&(cs_pmos_look_up_tables_pch);
if (strcmp(argv[7],"size:L")==0) PZ=&(cs_pmos_size_L);
if (strcmp(argv[7],"size:W")==0) PZ=&(cs_pmos_size_W);
if (strcmp(argv[7],"size:iref")==0) PZ=&(cs_pmos_size_iref);
if (strcmp(argv[7],"0:V")==0) PZ=&(cs_pmos_0_V);
if (strcmp(argv[7],"0:Next")==0) PZ=&(cs_pmos_0_Next);
if (strcmp(argv[7],"out:V")==0) PZ=&(cs_pmos_out_V);
if (strcmp(argv[7],"out:Next")==0) PZ=&(cs_pmos_out_Next);
if (strcmp(argv[7],"in:V")==0) PZ=&(cs_pmos_in_V);
if (strcmp(argv[7],"in:Next")==0) PZ=&(cs_pmos_in_Next);
if (strcmp(argv[7],"vdd:V")==0) PZ=&(cs_pmos_vdd_V);
if (strcmp(argv[7],"vdd:Next")==0) PZ=&(cs_pmos_vdd_Next);
if (strcmp(argv[7],"property:Adc")==0) PZ=&(cs_pmos_property_Adc);
if (strcmp(argv[7],"property:CMRR")==0) PZ=&(cs_pmos_property_CMRR);
if (strcmp(argv[7],"property:PSRR")==0) PZ=&(cs_pmos_property_PSRR);
if (strcmp(argv[7],"property:Rout")==0) PZ=&(cs_pmos_property_Rout);
if (strcmp(argv[7],"property:BW")==0) PZ=&(cs_pmos_property_BW);
if (strcmp(argv[7],"property:PM")==0) PZ=&(cs_pmos_property_PM);
if (strcmp(argv[7],"property:Cin")==0) PZ=&(cs_pmos_property_Cin);
if (strcmp(argv[7],"property:ts")==0) PZ=&(cs_pmos_property_ts);
if (strcmp(argv[7],"property:Nt")==0) PZ=&(cs_pmos_property_Nt);
if (strcmp(argv[7],"property:Nf")==0) PZ=&(cs_pmos_property_Nf);
if (strcmp(argv[7],"property:TotalNoise")==0) PZ=&(cs_pmos_property_TotalNoise);
if (strcmp(argv[7],"property:fc")==0) PZ=&(cs_pmos_property_fc);
if (strcmp(argv[7],"property:Vos")==0) PZ=&(cs_pmos_property_Vos);
if (strcmp(argv[7],"property:Area")==0) PZ=&(cs_pmos_property_Area);
if (strcmp(argv[7],"property:Power")==0) PZ=&(cs_pmos_property_Power);
if (strcmp(argv[7],"pin:Ideq")==0) PZ=&(cs_pmos_pin_Ideq);
if (strcmp(argv[7],"pin:go")==0) PZ=&(cs_pmos_pin_go);
if (strcmp(argv[7],"pin:gm")==0) PZ=&(cs_pmos_pin_gm);
if (strcmp(argv[7],"pin:cgd")==0) PZ=&(cs_pmos_pin_cgd);
if (strcmp(argv[7],"pin:cgg")==0) PZ=&(cs_pmos_pin_cgg);
if (strcmp(argv[7],"pin:cgs")==0) PZ=&(cs_pmos_pin_cgs);
if (strcmp(argv[7],"pin:cgb")==0) PZ=&(cs_pmos_pin_cgb);
if (strcmp(argv[7],"pin:cdd")==0) PZ=&(cs_pmos_pin_cdd);
if (strcmp(argv[7],"pin:cdg")==0) PZ=&(cs_pmos_pin_cdg);
if (strcmp(argv[7],"pin:cds")==0) PZ=&(cs_pmos_pin_cds);
if (strcmp(argv[7],"pin:cdb")==0) PZ=&(cs_pmos_pin_cdb);
if (strcmp(argv[7],"pin:csd")==0) PZ=&(cs_pmos_pin_csd);
if (strcmp(argv[7],"pin:csg")==0) PZ=&(cs_pmos_pin_csg);
if (strcmp(argv[7],"pin:css")==0) PZ=&(cs_pmos_pin_css);
if (strcmp(argv[7],"pin:csb")==0) PZ=&(cs_pmos_pin_csb);
if (strcmp(argv[7],"pin:cbd")==0) PZ=&(cs_pmos_pin_cbd);
if (strcmp(argv[7],"pin:cbg")==0) PZ=&(cs_pmos_pin_cbg);
if (strcmp(argv[7],"pin:cbs")==0) PZ=&(cs_pmos_pin_cbs);
if (strcmp(argv[7],"pin:cbb")==0) PZ=&(cs_pmos_pin_cbb);
if (PZ==NULL) {
    #Error: "%s: context %s is not available for heatmap generation." argv[0] argv[1]
    return TCL_ERROR;
}
int width=(int)(maxX-minX)/stepX+1;
int height=(int)(maxY-minY)/stepY+1;
int ARGC;
char **ARGV;
Tcl_SplitList(interp,argv[12],&ARGC,&ARGV);
int *pal=(int *)malloc(sizeof(int)*ARGC);
for (i=0;i<ARGC;i++) pal[i]=atoi(ARGV[i]);
heatmap *hm=new_heatmap(width,height,atoi(argv[10]),atoi(argv[11]),pal,ARGC);
int mode=-1;
float th=0;
if (argc==13) mode=HM_TH_MODE_FLAT; else {
if (strcmp(argv[13],"flat")==0) mode=HM_TH_MODE_FLAT;
if (strcmp(argv[13],"snap")==0) mode=HM_TH_MODE_SNAP;
if (strcmp(argv[13],"half")==0) mode=HM_TH_MODE_HALF;
}
if (mode==-1) {
	#Error: "%s: pallet mode %s is not available for heatmap generation. Use flat, snap or half" argv[0] argv[13]
	return TCL_ERROR;
}
if ((mode!=HM_TH_MODE_FLAT)&&(argc!=15)) {
	#Error: "%s: pallet mode %s requires a threshold for passing specifications." argv[0] argv[13]
	return TCL_ERROR;
} else th=atof(argv[14]);
float X,Y;
i=0;
for (X=minX;X<=maxX;X+=stepX) {
    j=0;
    for (Y=minY;Y<=maxY;Y+=stepY) {
        *PX=X;
        *PY=Y;
        tcl_gamma_cs_pmos_op_cmd(CD,NULL,0,NULL);
        set_heatmap_pixel(hm,i,j,*PZ);
        j++;
    }
    i++;
}
heatmap_thresholds(hm,mode,th);
char *out_channel_name=Tcl_GetVar(interp,"::HTML",0);
FILE *HTML;
Tcl_GetOpenFile(interp,out_channel_name,1,0,&HTML);
plot_heatmap(hm,0,0,HTML);

            return TCL_OK;
        }
        static int tcl_gamma_cs_pmos_random_cmd(ClientData clientData,Tcl_Interp *interp,int argc,char *argv[]) {
            ClientData CD;
PAT *p=(PAT *)Pcs_pmos_cs_pmos_circuits_PAT;
while (p->content->num_of<cs_pmos_config_pat_size_target) {
cs_pmos_size_L=cs_pmos_size_L_min+random()*(cs_pmos_size_L_max-cs_pmos_size_L_min)/RAND_MAX;
cs_pmos_size_W=cs_pmos_size_L+random()*(cs_pmos_size_W_max-cs_pmos_size_L)/RAND_MAX;
cs_pmos_size_iref=cs_pmos_size_iref_min+random()*(cs_pmos_size_iref_max-cs_pmos_size_iref_min)/RAND_MAX;
if (tcl_gamma_cs_pmos_op_cmd(CD,NULL,0,NULL)==TCL_ERROR) continue;
}

            return TCL_OK;
        }
        static int tcl_gamma_cs_pmos_breed_cmd(ClientData clientData,Tcl_Interp *interp,int argc,char *argv[]) {
            ClientData CD;
int i,viable;
PAT *p=(PAT *)Pcs_pmos_cs_pmos_circuits_PAT;
int more_to_breed=1;
while (more_to_breed&&(p->content->num_of<cs_pmos_pat_size_target)) {
more_to_breed=0;
int sweep_size=p->content->num_of;
for (i=0;i<sweep_size;i++) {
if (p->content->content[i]->flags) continue;
p->content->content[i]->flags=1;
more_to_breed++;
cs_pmos_size_L=p->content->content[i]->sizes->content[0];
cs_pmos_size_W=p->content->content[i]->sizes->content[1];
cs_pmos_size_iref=p->content->content[i]->sizes->content[2];
cs_pmos_size_L=cs_pmos_size_L+cs_pmos_size_L_step;
viable=1;
if ((cs_pmos_size_L>=cs_pmos_size_L_min)&&(cs_pmos_size_L<=cs_pmos_size_L_max)) {
tcl_gamma_cs_pmos_op_cmd(CD,NULL,0,NULL);
}
cs_pmos_size_L=cs_pmos_size_L-2*cs_pmos_size_L_step;
viable=1;
if ((cs_pmos_size_L>=cs_pmos_size_L_min)&&(cs_pmos_size_L<=cs_pmos_size_L_max)) {
tcl_gamma_cs_pmos_op_cmd(CD,NULL,0,NULL);
}
cs_pmos_size_L=cs_pmos_size_L+cs_pmos_size_L_step;
cs_pmos_size_W=cs_pmos_size_W+cs_pmos_size_W_step;
viable=1;
if ((cs_pmos_size_W>=cs_pmos_size_L)&&(cs_pmos_size_W<=cs_pmos_size_W_max)) {
tcl_gamma_cs_pmos_op_cmd(CD,NULL,0,NULL);
}
cs_pmos_size_W=cs_pmos_size_W-2*cs_pmos_size_W_step;
viable=1;
if ((cs_pmos_size_W>=cs_pmos_size_L)&&(cs_pmos_size_W<=cs_pmos_size_W_max)) {
tcl_gamma_cs_pmos_op_cmd(CD,NULL,0,NULL);
}
cs_pmos_size_W=cs_pmos_size_W+cs_pmos_size_W_step;
cs_pmos_size_iref=cs_pmos_size_iref+cs_pmos_size_iref_step;
viable=1;
if ((cs_pmos_size_iref>=cs_pmos_size_iref_min)&&(cs_pmos_size_iref<=cs_pmos_size_iref_max)) {
tcl_gamma_cs_pmos_op_cmd(CD,NULL,0,NULL);
}
cs_pmos_size_iref=cs_pmos_size_iref-2*cs_pmos_size_iref_step;
viable=1;
if ((cs_pmos_size_iref>=cs_pmos_size_iref_min)&&(cs_pmos_size_iref<=cs_pmos_size_iref_max)) {
tcl_gamma_cs_pmos_op_cmd(CD,NULL,0,NULL);
}
cs_pmos_size_iref=cs_pmos_size_iref+cs_pmos_size_iref_step;
if (p->content->num_of%100==0) {
    printf("               %ld/%g=%g%%\n",p->content->num_of,cs_pmos_pat_size_target,100*p->content->num_of/cs_pmos_pat_size_target);
    fflush(stdout);
    if (cs_pmos_param_unique>0) {
        pat_unique(p,cs_pmos_param_unique);
}
}
}
printf("   Done %ld/%g=%g%% (%ld visited)\n",p->content->num_of,cs_pmos_pat_size_target,100*p->content->num_of/cs_pmos_pat_size_target,more_to_breed);
}

            return TCL_OK;
        }
        static int tcl_gamma_cs_pmos_random_breed_cmd(ClientData clientData,Tcl_Interp *interp,int argc,char *argv[]) {
            ClientData CD;
int i,j;
PAT *p=(PAT *)Pcs_pmos_cs_pmos_circuits_PAT;
long int r;
float step;
while (1) {
    if (p->content->num_of>cs_pmos_config_pat_size_target) break;
int sweep_size=p->content->num_of;
for (i=0;i<sweep_size;i++) {
cs_pmos_size_L=p->content->content[i]->sizes->content[0];
cs_pmos_size_W=p->content->content[i]->sizes->content[1];
cs_pmos_size_iref=p->content->content[i]->sizes->content[2];
while (1) {
step=(2.0*random()/RAND_MAX-1)*cs_pmos_size_L_step;
if (cs_pmos_size_L+step<cs_pmos_size_L_min) continue;
if (cs_pmos_size_L+step>cs_pmos_size_L_max) continue;
break;
}
cs_pmos_size_L+=step;
while (1) {
step=(2.0*random()/RAND_MAX-1)*cs_pmos_size_W_step;
if (cs_pmos_size_W+step<cs_pmos_size_L) continue;
if (cs_pmos_size_W+step>cs_pmos_size_W_max) continue;
break;
}
cs_pmos_size_W+=step;
while (1) {
step=(2.0*random()/RAND_MAX-1)*cs_pmos_size_iref_step;
if (cs_pmos_size_iref+step<cs_pmos_size_iref_min) continue;
if (cs_pmos_size_iref+step>cs_pmos_size_iref_max) continue;
break;
}
cs_pmos_size_iref+=step;
int pre_volume=p->content->num_of;
if (tcl_gamma_cs_pmos_op_cmd(CD,NULL,0,NULL)==TCL_ERROR) {i--; continue;}
if (pre_volume==p->content->num_of) {i--; continue;}
if (p->content->num_of%1000==0) {
    printf("               %ld/%g=%g%% max gain=%g\n",p->content->num_of,cs_pmos_config_pat_size_target,100*p->content->num_of/cs_pmos_config_pat_size_target,cs_pmos_max_Adc);
    printf("               %ld/%g=%g%%\n",p->content->num_of,cs_pmos_config_pat_size_target,100*p->content->num_of/cs_pmos_config_pat_size_target);
    fflush(stdout);
    if (cs_pmos_param_unique>0) {
        pat_unique(p,cs_pmos_param_unique);
    printf("               post unique: %ld/%g=%g%%\n",p->content->num_of,cs_pmos_config_pat_size_target,100*p->content->num_of/cs_pmos_config_pat_size_target);
    if (p->content->num_of>0.92*cs_pmos_config_pat_size_target) break;
}
}
    if (p->content->num_of>cs_pmos_config_pat_size_target) break;
}
    if (p->content->num_of>cs_pmos_config_pat_size_target) break;
}

            return TCL_OK;
        }
        static int tcl_gamma_cs_pmos_random_breed_single_cmd(ClientData clientData,Tcl_Interp *interp,int argc,char *argv[]) {
            ClientData CD;
int i;
PAT *p=(PAT *)Pcs_pmos_cs_pmos_circuits_PAT;
int more_to_breed=0;
long int r;
long int breed_count=p->content->num_of;
long int watchdog=0;
float step;
int sweep_size=p->content->num_of;
int searched_id=(int)cs_pmos_circuit_breed_id;
for (i=0;i<p->content->num_of;i++) {
    if (p->content->content[i]->id==searched_id) break;
}
printf("Found circuit id %d at index %d\n",searched_id,i);
while (watchdog++<10000) {
cs_pmos_size_L=p->content->content[i]->sizes->content[0];
cs_pmos_size_W=p->content->content[i]->sizes->content[1];
cs_pmos_size_iref=p->content->content[i]->sizes->content[2];
while (1) {
step=(2.0*random()/RAND_MAX-1)*cs_pmos_size_L_step;
if (cs_pmos_size_L+step<cs_pmos_size_L_min) continue;
if (cs_pmos_size_L+step>cs_pmos_size_L_max) continue;
break;
}
cs_pmos_size_L+=step;
while (1) {
step=(2.0*random()/RAND_MAX-1)*cs_pmos_size_W_step;
if (cs_pmos_size_W+step<cs_pmos_size_L) continue;
if (cs_pmos_size_W+step>cs_pmos_size_W_max) continue;
break;
}
cs_pmos_size_W+=step;
while (1) {
step=(2.0*random()/RAND_MAX-1)*cs_pmos_size_iref_step;
if (cs_pmos_size_iref+step<cs_pmos_size_iref_min) continue;
if (cs_pmos_size_iref+step>cs_pmos_size_iref_max) continue;
break;
}
cs_pmos_size_iref+=step;
if (tcl_gamma_cs_pmos_op_cmd(CD,NULL,0,NULL)==TCL_ERROR) continue;
if (p->content->num_of>=breed_count+cs_pmos_circuit_breed_target) break;
}

            return TCL_OK;
        }
        // Initializing cTree references and registering the tcl_gamma_op_cmd command as ::C::cs_pmos
        int Gamma_cs_pmos_Init(Tcl_Interp *interp) {
            float *array_entry;
            context *c;
            c=create_context("cs_pmos:param:area_spacing");
Pcs_pmos_param_area_spacing=(float *)(&c->value.s);
c=create_context("cs_pmos:param:iref");
Pcs_pmos_param_iref=(float *)(&c->value.s);
c=create_context("cs_pmos:param:rload");
Pcs_pmos_param_rload=(float *)(&c->value.s);
c=create_context("cs_pmos:param:in");
Pcs_pmos_param_in=(float *)(&c->value.s);
c=create_context("cs_pmos:param:vdd");
Pcs_pmos_param_vdd=(float *)(&c->value.s);
c=create_context("cs_pmos:param:unique");
Pcs_pmos_param_unique=(float *)(&c->value.s);
c=create_context("cs_pmos:look_up_tables:nch");
Pcs_pmos_look_up_tables_nch=(float *)(&c->value.s);
c=create_context("cs_pmos:look_up_tables:pch");
Pcs_pmos_look_up_tables_pch=(float *)(&c->value.s);
c=create_context("cs_pmos:size:L");
Pcs_pmos_size_L=(float *)(&c->value.s);
c=create_context("cs_pmos:size:W");
Pcs_pmos_size_W=(float *)(&c->value.s);
c=create_context("cs_pmos:size:iref");
Pcs_pmos_size_iref=(float *)(&c->value.s);
c=create_context("cs_pmos:0:V");
Pcs_pmos_0_V=(float *)(&c->value.s);
c=create_context("cs_pmos:0:Next");
Pcs_pmos_0_Next=(float *)(&c->value.s);
c=create_context("cs_pmos:out:V");
Pcs_pmos_out_V=(float *)(&c->value.s);
c=create_context("cs_pmos:out:Next");
Pcs_pmos_out_Next=(float *)(&c->value.s);
c=create_context("cs_pmos:in:V");
Pcs_pmos_in_V=(float *)(&c->value.s);
c=create_context("cs_pmos:in:Next");
Pcs_pmos_in_Next=(float *)(&c->value.s);
c=create_context("cs_pmos:vdd:V");
Pcs_pmos_vdd_V=(float *)(&c->value.s);
c=create_context("cs_pmos:vdd:Next");
Pcs_pmos_vdd_Next=(float *)(&c->value.s);
c=create_context("cs_pmos:property:Adc");
Pcs_pmos_property_Adc=(float *)(&c->value.s);
c=create_context("cs_pmos:property:CMRR");
Pcs_pmos_property_CMRR=(float *)(&c->value.s);
c=create_context("cs_pmos:property:PSRR");
Pcs_pmos_property_PSRR=(float *)(&c->value.s);
c=create_context("cs_pmos:property:Rout");
Pcs_pmos_property_Rout=(float *)(&c->value.s);
c=create_context("cs_pmos:property:BW");
Pcs_pmos_property_BW=(float *)(&c->value.s);
c=create_context("cs_pmos:property:PM");
Pcs_pmos_property_PM=(float *)(&c->value.s);
c=create_context("cs_pmos:property:Cin");
Pcs_pmos_property_Cin=(float *)(&c->value.s);
c=create_context("cs_pmos:property:ts");
Pcs_pmos_property_ts=(float *)(&c->value.s);
c=create_context("cs_pmos:property:Nt");
Pcs_pmos_property_Nt=(float *)(&c->value.s);
c=create_context("cs_pmos:property:Nf");
Pcs_pmos_property_Nf=(float *)(&c->value.s);
c=create_context("cs_pmos:property:TotalNoise");
Pcs_pmos_property_TotalNoise=(float *)(&c->value.s);
c=create_context("cs_pmos:property:fc");
Pcs_pmos_property_fc=(float *)(&c->value.s);
c=create_context("cs_pmos:property:Vos");
Pcs_pmos_property_Vos=(float *)(&c->value.s);
c=create_context("cs_pmos:property:Area");
Pcs_pmos_property_Area=(float *)(&c->value.s);
c=create_context("cs_pmos:property:Power");
Pcs_pmos_property_Power=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:Ideq");
Pcs_pmos_pin_Ideq=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:go");
Pcs_pmos_pin_go=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:gm");
Pcs_pmos_pin_gm=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:cgd");
Pcs_pmos_pin_cgd=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:cgg");
Pcs_pmos_pin_cgg=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:cgs");
Pcs_pmos_pin_cgs=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:cgb");
Pcs_pmos_pin_cgb=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:cdd");
Pcs_pmos_pin_cdd=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:cdg");
Pcs_pmos_pin_cdg=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:cds");
Pcs_pmos_pin_cds=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:cdb");
Pcs_pmos_pin_cdb=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:csd");
Pcs_pmos_pin_csd=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:csg");
Pcs_pmos_pin_csg=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:css");
Pcs_pmos_pin_css=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:csb");
Pcs_pmos_pin_csb=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:cbd");
Pcs_pmos_pin_cbd=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:cbg");
Pcs_pmos_pin_cbg=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:cbs");
Pcs_pmos_pin_cbs=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:cbb");
Pcs_pmos_pin_cbb=(float *)(&c->value.s);
Pcs_pmos_cs_pmos_circuits_PAT=(float *)get_PAT("cs_pmos:cs_pmos:circuits");
c=create_context("cs_pmos:config:pat_size_target");
Pcs_pmos_config_pat_size_target=(float *)(&c->value.s);
c=create_context("cs_pmos:size:L:min");
Pcs_pmos_size_L_min=(float *)(&c->value.s);
c=create_context("cs_pmos:size:L:max");
Pcs_pmos_size_L_max=(float *)(&c->value.s);
c=create_context("cs_pmos:size:W:max");
Pcs_pmos_size_W_max=(float *)(&c->value.s);
c=create_context("cs_pmos:size:iref:min");
Pcs_pmos_size_iref_min=(float *)(&c->value.s);
c=create_context("cs_pmos:size:iref:max");
Pcs_pmos_size_iref_max=(float *)(&c->value.s);
c=create_context("cs_pmos:size:L:step");
Pcs_pmos_size_L_step=(float *)(&c->value.s);
c=create_context("cs_pmos:size:W:step");
Pcs_pmos_size_W_step=(float *)(&c->value.s);
c=create_context("cs_pmos:size:iref:step");
Pcs_pmos_size_iref_step=(float *)(&c->value.s);
c=create_context("cs_pmos:max_Adc");
Pcs_pmos_max_Adc=(float *)(&c->value.s);
c=create_context("cs_pmos:pat_size_target");
Pcs_pmos_pat_size_target=(float *)(&c->value.s);
c=create_context("cs_pmos:mode:freash_op");
Pcs_pmos_mode_freash_op=(float *)(&c->value.s);
c=create_context("cs_pmos:status:index");
Pcs_pmos_status_index=(float *)(&c->value.s);
c=create_context("cs_pmos:config:size:L");
Pcs_pmos_config_size_L=(float *)(&c->value.s);
c=create_context("cs_pmos:config:size:W");
Pcs_pmos_config_size_W=(float *)(&c->value.s);
c=create_context("cs_pmos:config:size:iref");
Pcs_pmos_config_size_iref=(float *)(&c->value.s);
c=create_context("cs_pmos:status:fail");
Pcs_pmos_status_fail=(float *)(&c->value.s);
c=create_context("cs_pmos:design_feedback");
Pcs_pmos_design_feedback=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:bin");
Pcs_pmos_pin_bin=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:W");
Pcs_pmos_pin_W=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:L");
Pcs_pmos_pin_L=(float *)(&c->value.s);
Pcs_pmos_look_up_tables_pch_binning_LUT=(float *)get_LUT("look_up_tables:pch:binning");
c=create_context("cs_pmos:leak");
Pcs_pmos_leak=(float *)(&c->value.s);
c=create_context("cs_pmos:config:op_iterations");
Pcs_pmos_config_op_iterations=(float *)(&c->value.s);
c=create_context("cs_pmos:config:kcl_th");
Pcs_pmos_config_kcl_th=(float *)(&c->value.s);
c=create_context("cs_pmos:config:design_feedback_th");
Pcs_pmos_config_design_feedback_th=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:gb");
Pcs_pmos_pin_gb=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:Ids");
Pcs_pmos_pin_Ids=(float *)(&c->value.s);
c=create_context("cs_pmos:look_up_tables:pch:go:ss");
Pcs_pmos_look_up_tables_pch_go_ss_CONTEXT=(float *)&c;
c=create_context("cs_pmos:look_up_tables:pch:gm:ss");
Pcs_pmos_look_up_tables_pch_gm_ss_CONTEXT=(float *)&c;
c=create_context("cs_pmos:look_up_tables:pch:gb:ss");
Pcs_pmos_look_up_tables_pch_gb_ss_CONTEXT=(float *)&c;
c=create_context("cs_pmos:look_up_tables:pch:Ids:ss");
Pcs_pmos_look_up_tables_pch_Ids_ss_CONTEXT=(float *)&c;
c=create_context("cs_pmos:config:kcl_step");
Pcs_pmos_config_kcl_step=(float *)(&c->value.s);
c=create_context("cs_pmos:config:fail_on_properties");
Pcs_pmos_config_fail_on_properties=(float *)(&c->value.s);
c=create_context("cs_pmos:s");
Pcs_pmos_s=(float *)(&c->value.s);
c=create_context("cs_pmos:config:cgg_factor");
Pcs_pmos_config_cgg_factor=(float *)(&c->value.s);
Pcs_pmos_look_up_tables_pch_cgg_ss_LUT=(float *)get_LUT("look_up_tables:pch:cgg:ss");
c=create_context("cs_pmos:config:cgd_factor");
Pcs_pmos_config_cgd_factor=(float *)(&c->value.s);
Pcs_pmos_look_up_tables_pch_cgd_ss_LUT=(float *)get_LUT("look_up_tables:pch:cgd:ss");
c=create_context("cs_pmos:config:cgs_factor");
Pcs_pmos_config_cgs_factor=(float *)(&c->value.s);
Pcs_pmos_look_up_tables_pch_cgs_ss_LUT=(float *)get_LUT("look_up_tables:pch:cgs:ss");
c=create_context("cs_pmos:config:cgb_factor");
Pcs_pmos_config_cgb_factor=(float *)(&c->value.s);
Pcs_pmos_look_up_tables_pch_cgb_ss_LUT=(float *)get_LUT("look_up_tables:pch:cgb:ss");
c=create_context("cs_pmos:config:cdd_factor");
Pcs_pmos_config_cdd_factor=(float *)(&c->value.s);
Pcs_pmos_look_up_tables_pch_cdd_ss_LUT=(float *)get_LUT("look_up_tables:pch:cdd:ss");
c=create_context("cs_pmos:config:cdg_factor");
Pcs_pmos_config_cdg_factor=(float *)(&c->value.s);
Pcs_pmos_look_up_tables_pch_cdg_ss_LUT=(float *)get_LUT("look_up_tables:pch:cdg:ss");
c=create_context("cs_pmos:config:cdb_factor");
Pcs_pmos_config_cdb_factor=(float *)(&c->value.s);
Pcs_pmos_look_up_tables_pch_cdb_ss_LUT=(float *)get_LUT("look_up_tables:pch:cdb:ss");
c=create_context("cs_pmos:config:cds_factor");
Pcs_pmos_config_cds_factor=(float *)(&c->value.s);
Pcs_pmos_look_up_tables_pch_cds_ss_LUT=(float *)get_LUT("look_up_tables:pch:cds:ss");
c=create_context("cs_pmos:config:csd_factor");
Pcs_pmos_config_csd_factor=(float *)(&c->value.s);
Pcs_pmos_look_up_tables_pch_csd_ss_LUT=(float *)get_LUT("look_up_tables:pch:csd:ss");
c=create_context("cs_pmos:config:csg_factor");
Pcs_pmos_config_csg_factor=(float *)(&c->value.s);
Pcs_pmos_look_up_tables_pch_csg_ss_LUT=(float *)get_LUT("look_up_tables:pch:csg:ss");
c=create_context("cs_pmos:config:css_factor");
Pcs_pmos_config_css_factor=(float *)(&c->value.s);
Pcs_pmos_look_up_tables_pch_css_ss_LUT=(float *)get_LUT("look_up_tables:pch:css:ss");
c=create_context("cs_pmos:config:csb_factor");
Pcs_pmos_config_csb_factor=(float *)(&c->value.s);
Pcs_pmos_look_up_tables_pch_csb_ss_LUT=(float *)get_LUT("look_up_tables:pch:csb:ss");
c=create_context("cs_pmos:config:cbd_factor");
Pcs_pmos_config_cbd_factor=(float *)(&c->value.s);
Pcs_pmos_look_up_tables_pch_cbd_ss_LUT=(float *)get_LUT("look_up_tables:pch:cbd:ss");
c=create_context("cs_pmos:config:cbg_factor");
Pcs_pmos_config_cbg_factor=(float *)(&c->value.s);
Pcs_pmos_look_up_tables_pch_cbg_ss_LUT=(float *)get_LUT("look_up_tables:pch:cbg:ss");
c=create_context("cs_pmos:config:cbs_factor");
Pcs_pmos_config_cbs_factor=(float *)(&c->value.s);
Pcs_pmos_look_up_tables_pch_cbs_ss_LUT=(float *)get_LUT("look_up_tables:pch:cbs:ss");
c=create_context("cs_pmos:config:cbb_factor");
Pcs_pmos_config_cbb_factor=(float *)(&c->value.s);
Pcs_pmos_look_up_tables_pch_cbb_ss_LUT=(float *)get_LUT("look_up_tables:pch:cbb:ss");
c=create_context("cs_pmos:property:BW:s");
Pcs_pmos_property_BW_s=(float *)(&c->value.s);
c=create_context("cs_pmos:p1");
Pcs_pmos_p1=(float *)(&c->value.s);
c=create_context("cs_pmos:p2");
Pcs_pmos_p2=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:dNt_dvgs");
Pcs_pmos_pin_dNt_dvgs=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:dNt_dvds");
Pcs_pmos_pin_dNt_dvds=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:dNt_dvbs");
Pcs_pmos_pin_dNt_dvbs=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:dNt_dl");
Pcs_pmos_pin_dNt_dl=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:Nt_unit");
Pcs_pmos_pin_Nt_unit=(float *)(&c->value.s);
Pcs_pmos__look_up_tables_pch_thermal_noise_ss_LUT=(float *)get_LUT(":look_up_tables:pch:thermal_noise:ss");
c=create_context("cs_pmos:pin:Nt");
Pcs_pmos_pin_Nt=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:dNf_dvgs");
Pcs_pmos_pin_dNf_dvgs=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:dNf_dvds");
Pcs_pmos_pin_dNf_dvds=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:dNf_dvbs");
Pcs_pmos_pin_dNf_dvbs=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:dNf_dl");
Pcs_pmos_pin_dNf_dl=(float *)(&c->value.s);
c=create_context("cs_pmos:pin:Nf_unit");
Pcs_pmos_pin_Nf_unit=(float *)(&c->value.s);
Pcs_pmos__look_up_tables_pch_flicker_noise_ss_LUT=(float *)get_LUT(":look_up_tables:pch:flicker_noise:ss");
c=create_context("cs_pmos:pin:Nf");
Pcs_pmos_pin_Nf=(float *)(&c->value.s);
c=create_context("cs_pmos:config:shift:Adc");
Pcs_pmos_config_shift_Adc=(float *)(&c->value.s);
c=create_context("cs_pmos:config:factor:Adc");
Pcs_pmos_config_factor_Adc=(float *)(&c->value.s);
c=create_context("cs_pmos:config:shift:CMRR");
Pcs_pmos_config_shift_CMRR=(float *)(&c->value.s);
c=create_context("cs_pmos:config:factor:CMRR");
Pcs_pmos_config_factor_CMRR=(float *)(&c->value.s);
c=create_context("cs_pmos:config:shift:PSRR");
Pcs_pmos_config_shift_PSRR=(float *)(&c->value.s);
c=create_context("cs_pmos:config:factor:PSRR");
Pcs_pmos_config_factor_PSRR=(float *)(&c->value.s);
c=create_context("cs_pmos:config:shift:Rout");
Pcs_pmos_config_shift_Rout=(float *)(&c->value.s);
c=create_context("cs_pmos:config:factor:Rout");
Pcs_pmos_config_factor_Rout=(float *)(&c->value.s);
c=create_context("cs_pmos:config:shift:BW");
Pcs_pmos_config_shift_BW=(float *)(&c->value.s);
c=create_context("cs_pmos:config:factor:BW");
Pcs_pmos_config_factor_BW=(float *)(&c->value.s);
c=create_context("cs_pmos:config:shift:PM");
Pcs_pmos_config_shift_PM=(float *)(&c->value.s);
c=create_context("cs_pmos:config:factor:PM");
Pcs_pmos_config_factor_PM=(float *)(&c->value.s);
c=create_context("cs_pmos:config:shift:Cin");
Pcs_pmos_config_shift_Cin=(float *)(&c->value.s);
c=create_context("cs_pmos:config:factor:Cin");
Pcs_pmos_config_factor_Cin=(float *)(&c->value.s);
c=create_context("cs_pmos:config:shift:ts");
Pcs_pmos_config_shift_ts=(float *)(&c->value.s);
c=create_context("cs_pmos:config:factor:ts");
Pcs_pmos_config_factor_ts=(float *)(&c->value.s);
c=create_context("cs_pmos:config:shift:Nt");
Pcs_pmos_config_shift_Nt=(float *)(&c->value.s);
c=create_context("cs_pmos:config:factor:Nt");
Pcs_pmos_config_factor_Nt=(float *)(&c->value.s);
c=create_context("cs_pmos:config:shift:Nf");
Pcs_pmos_config_shift_Nf=(float *)(&c->value.s);
c=create_context("cs_pmos:config:factor:Nf");
Pcs_pmos_config_factor_Nf=(float *)(&c->value.s);
c=create_context("cs_pmos:config:shift:TotalNoise");
Pcs_pmos_config_shift_TotalNoise=(float *)(&c->value.s);
c=create_context("cs_pmos:config:factor:TotalNoise");
Pcs_pmos_config_factor_TotalNoise=(float *)(&c->value.s);
c=create_context("cs_pmos:config:shift:fc");
Pcs_pmos_config_shift_fc=(float *)(&c->value.s);
c=create_context("cs_pmos:config:factor:fc");
Pcs_pmos_config_factor_fc=(float *)(&c->value.s);
c=create_context("cs_pmos:config:shift:Vos");
Pcs_pmos_config_shift_Vos=(float *)(&c->value.s);
c=create_context("cs_pmos:config:factor:Vos");
Pcs_pmos_config_factor_Vos=(float *)(&c->value.s);
c=create_context("cs_pmos:config:shift:Area");
Pcs_pmos_config_shift_Area=(float *)(&c->value.s);
c=create_context("cs_pmos:config:factor:Area");
Pcs_pmos_config_factor_Area=(float *)(&c->value.s);
c=create_context("cs_pmos:config:shift:Power");
Pcs_pmos_config_shift_Power=(float *)(&c->value.s);
c=create_context("cs_pmos:config:factor:Power");
Pcs_pmos_config_factor_Power=(float *)(&c->value.s);
c=create_context("cs_pmos:circuit_breed_id");
Pcs_pmos_circuit_breed_id=(float *)(&c->value.s);
c=create_context("cs_pmos:circuit_breed_target");
Pcs_pmos_circuit_breed_target=(float *)(&c->value.s);

            return TCL_OK;
        }
        int Gamma_cs_pmos_Register(Tcl_Interp *interp) {
            Tcl_CreateCommand(interp, "::Gamma::cs_pmos::heatmap", tcl_gamma_cs_pmos_heatmap_cmd, NULL, NULL);
            Tcl_CreateCommand(interp, "::Gamma::cs_pmos::random", tcl_gamma_cs_pmos_random_cmd, NULL, NULL);
            Tcl_CreateCommand(interp, "::Gamma::cs_pmos::random_breed", tcl_gamma_cs_pmos_random_breed_cmd, NULL, NULL);
            Tcl_CreateCommand(interp, "::Gamma::cs_pmos::random_breed_single", tcl_gamma_cs_pmos_random_breed_single_cmd, NULL, NULL);
            Tcl_CreateCommand(interp, "::Gamma::cs_pmos::breed", tcl_gamma_cs_pmos_breed_cmd, NULL, NULL);
            Tcl_CreateCommand(interp, "::Gamma::cs_pmos::op", tcl_gamma_cs_pmos_op_cmd, NULL, NULL);
            Tcl_CreateCommand(interp, "::Gamma::cs_pmos::import", tcl_gamma_cs_pmos_import_cmd, NULL, NULL);
            Tcl_CreateCommand(interp, "::Gamma::cs_pmos::export", tcl_gamma_cs_pmos_export_cmd, NULL, NULL);
            return TCL_OK;
        }
    
