#include <tcl.h>
#include <stdio.h>
#include "ctree.h"
#include "look_up_table.h"
// Some global pointers to keep reference of the contexts this object manipulates
float *Pop_iterations;
float *Pn_ref_gm;
float *P_look_up_tables_nch_gm_ss_LUT;
float *Pgate_V;
float *Pout_V;
float *P0_V;
float *Psize_L;
float *Pn_ref_dgm_dvgs;
float *Pn_ref_dgm_dvds;
float *Pn_ref_dgm_dvbs;
float *Pn_ref_dgm_dl;
float *Psize_W;
float *Pn_ref_go;
float *P_look_up_tables_nch_ro_ss_LUT;
float *Pn_ref_dro_dvgs;
float *Pn_ref_dro_dvds;
float *Pn_ref_dro_dvbs;
float *Pn_ref_dro_dl;
float *Pn_ref_Ideq;
float *P_look_up_tables_nch_Ids_ss_LUT;
float *PGds_out_0;
float *Pparam_rload;
float *PDet;
float *PTed;
float *Pparam_in;
float *Pin_V;
float *Pparam_iref;
float *Pvdd_V;
float *Pparam_vdd;
float *Pn_ref_Nt_unit;
float *P_look_up_tables_nch_thermal_noise_ss_LUT;
float *Pn_ref_dNt_dvgs;
float *Pn_ref_dNt_dvds;
float *Pn_ref_dNt_dvbs;
float *Pn_ref_dNt_dl;
float *Pn_ref_Nt;
float *Pn_ref_Nf_unit;
float *P_look_up_tables_nch_flicker_noise_ss_LUT;
float *Pn_ref_dNf_dvgs;
float *Pn_ref_dNf_dvds;
float *Pn_ref_dNf_dvbs;
float *Pn_ref_dNf_dl;
float *Pn_ref_Nf;
float *Pproperty_Adc;
float *Pproperty_PSRR;
float *Pn_ref_gm_size_W;
float *Pn_ref_gm_size_L;
float *Pn_ref_go_size_W;
float *Pn_ref_go_size_L;
float *PDet_n_ref_gm;
float *PTed_n_ref_gm;
float *PDet_n_ref_go;
float *PTed_n_ref_go;
float *PDet_L;
float *PTed_L;
float *PDet_W;
float *PTed_W;
float *Pproperty_Adc_n_ref_gm;
float *PAdc;
float *Pproperty_Adc_n_ref_go;
float *Pproperty_Adc_L;
float *Pproperty_Adc_W;
float *Pproperty_PSRR_n_ref_gm;
float *PPSRR;
float *Pproperty_PSRR_n_ref_go;
float *Pproperty_PSRR_L;
float *Pproperty_PSRR_W;
float *Pproperty_Zout;
float *Pproperty_Zout_n_ref_gm;
float *PTed_n_ref_gm0;
float *PZout;
float *Pproperty_Zout_n_ref_go;
float *PTed_n_ref_go0;
float *Pproperty_Zout_L;
float *Pproperty_Zout_W;
float *Pn_ref_cgs;
float *Plook_up_tables_nch_cox;
float *Pn_ref_cgd;
float *Ps;
float *Pproperty_BW_s;
float *Pp1;
float *Pproperty_BW;
float *Pp2;
float *Pproperty_ts;
float *Pproperty_ts_s;
float *PDet_ac_n_ref_gm;
float *PDet_ac_n_ref_go;
float *Pproperty_BW_L;
float *Pproperty_ts_L;
float *Pproperty_BW_W;
float *Pproperty_ts_W;
float *Pn_ref_Nt_L;
float *Pn_ref_Nf_L;
float *Pout_0_dNf_dl;
float *Pout_0_gm;
float *Pn_ref_Nt_W;
float *Pn_ref_Nf_W;
float *Pn_ref_noise_trans;
float *Pn_ref_noise_trans_L;
float *Pn_ref_noise_trans_W;
float *Pproperty_Nt;
float *Pproperty_Nt_L;
float *Pproperty_Nt_W;
float *Pproperty_Nf;
float *Pproperty_Nf_L;
float *Pproperty_Nf_W;
float *Pproperty_fc;
float *Pproperty_fc_L;
float *Pproperty_fc_W;
float op_iterations;
float n_ref_gm;
float _look_up_tables_nch_gm_ss_LUT;
float gate_V;
float out_V;
float CONST_0_V;
float size_L;
float n_ref_dgm_dvgs;
float n_ref_dgm_dvds;
float n_ref_dgm_dvbs;
float n_ref_dgm_dl;
float size_W;
float n_ref_go;
float _look_up_tables_nch_ro_ss_LUT;
float n_ref_dro_dvgs;
float n_ref_dro_dvds;
float n_ref_dro_dvbs;
float n_ref_dro_dl;
float n_ref_Ideq;
float _look_up_tables_nch_Ids_ss_LUT;
float Gds_out_0;
float param_rload;
float Det;
float Ted;
float param_in;
float in_V;
float param_iref;
float vdd_V;
float param_vdd;
float n_ref_Nt_unit;
float _look_up_tables_nch_thermal_noise_ss_LUT;
float n_ref_dNt_dvgs;
float n_ref_dNt_dvds;
float n_ref_dNt_dvbs;
float n_ref_dNt_dl;
float n_ref_Nt;
float n_ref_Nf_unit;
float _look_up_tables_nch_flicker_noise_ss_LUT;
float n_ref_dNf_dvgs;
float n_ref_dNf_dvds;
float n_ref_dNf_dvbs;
float n_ref_dNf_dl;
float n_ref_Nf;
float property_Adc;
float property_PSRR;
float n_ref_gm_size_W;
float n_ref_gm_size_L;
float n_ref_go_size_W;
float n_ref_go_size_L;
float Det_n_ref_gm;
float Ted_n_ref_gm;
float Det_n_ref_go;
float Ted_n_ref_go;
float Det_L;
float Ted_L;
float Det_W;
float Ted_W;
float property_Adc_n_ref_gm;
float Adc;
float property_Adc_n_ref_go;
float property_Adc_L;
float property_Adc_W;
float property_PSRR_n_ref_gm;
float PSRR;
float property_PSRR_n_ref_go;
float property_PSRR_L;
float property_PSRR_W;
float property_Zout;
float property_Zout_n_ref_gm;
float Ted_n_ref_gm0;
float Zout;
float property_Zout_n_ref_go;
float Ted_n_ref_go0;
float property_Zout_L;
float property_Zout_W;
float n_ref_cgs;
float look_up_tables_nch_cox;
float n_ref_cgd;
float s;
float property_BW_s;
float p1;
float property_BW;
float p2;
float property_ts;
float property_ts_s;
float Det_ac_n_ref_gm;
float Det_ac_n_ref_go;
float property_BW_L;
float property_ts_L;
float property_BW_W;
float property_ts_W;
float n_ref_Nt_L;
float n_ref_Nf_L;
float out_0_dNf_dl;
float out_0_gm;
float n_ref_Nt_W;
float n_ref_Nf_W;
float n_ref_noise_trans;
float n_ref_noise_trans_L;
float n_ref_noise_trans_W;
float property_Nt;
float property_Nt_L;
float property_Nt_W;
float property_Nf;
float property_Nf_L;
float property_Nf_W;
float property_fc;
float property_fc_L;
float property_fc_W;
// The compiled function
static int tcl_gamma_import_cmd(ClientData clientData,Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    op_iterations=*Pop_iterations;
    n_ref_gm=*Pn_ref_gm;
    gate_V=*Pgate_V;
    out_V=*Pout_V;
    CONST_0_V=*P0_V;
    size_L=*Psize_L;
    n_ref_dgm_dvgs=*Pn_ref_dgm_dvgs;
    n_ref_dgm_dvds=*Pn_ref_dgm_dvds;
    n_ref_dgm_dvbs=*Pn_ref_dgm_dvbs;
    n_ref_dgm_dl=*Pn_ref_dgm_dl;
    size_W=*Psize_W;
    n_ref_go=*Pn_ref_go;
    n_ref_dro_dvgs=*Pn_ref_dro_dvgs;
    n_ref_dro_dvds=*Pn_ref_dro_dvds;
    n_ref_dro_dvbs=*Pn_ref_dro_dvbs;
    n_ref_dro_dl=*Pn_ref_dro_dl;
    n_ref_Ideq=*Pn_ref_Ideq;
    Gds_out_0=*PGds_out_0;
    param_rload=*Pparam_rload;
    Det=*PDet;
    Ted=*PTed;
    param_in=*Pparam_in;
    in_V=*Pin_V;
    param_iref=*Pparam_iref;
    vdd_V=*Pvdd_V;
    param_vdd=*Pparam_vdd;
    n_ref_Nt_unit=*Pn_ref_Nt_unit;
    n_ref_dNt_dvgs=*Pn_ref_dNt_dvgs;
    n_ref_dNt_dvds=*Pn_ref_dNt_dvds;
    n_ref_dNt_dvbs=*Pn_ref_dNt_dvbs;
    n_ref_dNt_dl=*Pn_ref_dNt_dl;
    n_ref_Nt=*Pn_ref_Nt;
    n_ref_Nf_unit=*Pn_ref_Nf_unit;
    n_ref_dNf_dvgs=*Pn_ref_dNf_dvgs;
    n_ref_dNf_dvds=*Pn_ref_dNf_dvds;
    n_ref_dNf_dvbs=*Pn_ref_dNf_dvbs;
    n_ref_dNf_dl=*Pn_ref_dNf_dl;
    n_ref_Nf=*Pn_ref_Nf;
    property_Adc=*Pproperty_Adc;
    property_PSRR=*Pproperty_PSRR;
    n_ref_gm_size_W=*Pn_ref_gm_size_W;
    n_ref_gm_size_L=*Pn_ref_gm_size_L;
    n_ref_go_size_W=*Pn_ref_go_size_W;
    n_ref_go_size_L=*Pn_ref_go_size_L;
    Det_n_ref_gm=*PDet_n_ref_gm;
    Ted_n_ref_gm=*PTed_n_ref_gm;
    Det_n_ref_go=*PDet_n_ref_go;
    Ted_n_ref_go=*PTed_n_ref_go;
    Det_L=*PDet_L;
    Ted_L=*PTed_L;
    Det_W=*PDet_W;
    Ted_W=*PTed_W;
    property_Adc_n_ref_gm=*Pproperty_Adc_n_ref_gm;
    Adc=*PAdc;
    property_Adc_n_ref_go=*Pproperty_Adc_n_ref_go;
    property_Adc_L=*Pproperty_Adc_L;
    property_Adc_W=*Pproperty_Adc_W;
    property_PSRR_n_ref_gm=*Pproperty_PSRR_n_ref_gm;
    PSRR=*PPSRR;
    property_PSRR_n_ref_go=*Pproperty_PSRR_n_ref_go;
    property_PSRR_L=*Pproperty_PSRR_L;
    property_PSRR_W=*Pproperty_PSRR_W;
    property_Zout=*Pproperty_Zout;
    property_Zout_n_ref_gm=*Pproperty_Zout_n_ref_gm;
    Ted_n_ref_gm0=*PTed_n_ref_gm0;
    Zout=*PZout;
    property_Zout_n_ref_go=*Pproperty_Zout_n_ref_go;
    Ted_n_ref_go0=*PTed_n_ref_go0;
    property_Zout_L=*Pproperty_Zout_L;
    property_Zout_W=*Pproperty_Zout_W;
    n_ref_cgs=*Pn_ref_cgs;
    look_up_tables_nch_cox=*Plook_up_tables_nch_cox;
    n_ref_cgd=*Pn_ref_cgd;
    s=*Ps;
    property_BW_s=*Pproperty_BW_s;
    p1=*Pp1;
    property_BW=*Pproperty_BW;
    p2=*Pp2;
    property_ts=*Pproperty_ts;
    property_ts_s=*Pproperty_ts_s;
    Det_ac_n_ref_gm=*PDet_ac_n_ref_gm;
    Det_ac_n_ref_go=*PDet_ac_n_ref_go;
    property_BW_L=*Pproperty_BW_L;
    property_ts_L=*Pproperty_ts_L;
    property_BW_W=*Pproperty_BW_W;
    property_ts_W=*Pproperty_ts_W;
    n_ref_Nt_L=*Pn_ref_Nt_L;
    n_ref_Nf_L=*Pn_ref_Nf_L;
    out_0_dNf_dl=*Pout_0_dNf_dl;
    out_0_gm=*Pout_0_gm;
    n_ref_Nt_W=*Pn_ref_Nt_W;
    n_ref_Nf_W=*Pn_ref_Nf_W;
    n_ref_noise_trans=*Pn_ref_noise_trans;
    n_ref_noise_trans_L=*Pn_ref_noise_trans_L;
    n_ref_noise_trans_W=*Pn_ref_noise_trans_W;
    property_Nt=*Pproperty_Nt;
    property_Nt_L=*Pproperty_Nt_L;
    property_Nt_W=*Pproperty_Nt_W;
    property_Nf=*Pproperty_Nf;
    property_Nf_L=*Pproperty_Nf_L;
    property_Nf_W=*Pproperty_Nf_W;
    property_fc=*Pproperty_fc;
    property_fc_L=*Pproperty_fc_L;
    property_fc_W=*Pproperty_fc_W;
    return TCL_OK;
}
static int tcl_gamma_export_cmd(ClientData clientData,Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    *Pop_iterations=op_iterations;
    *Pn_ref_gm=n_ref_gm;
    *Pgate_V=gate_V;
    *Pout_V=out_V;
    *P0_V=CONST_0_V;
    *Psize_L=size_L;
    *Pn_ref_dgm_dvgs=n_ref_dgm_dvgs;
    *Pn_ref_dgm_dvds=n_ref_dgm_dvds;
    *Pn_ref_dgm_dvbs=n_ref_dgm_dvbs;
    *Pn_ref_dgm_dl=n_ref_dgm_dl;
    *Psize_W=size_W;
    *Pn_ref_go=n_ref_go;
    *Pn_ref_dro_dvgs=n_ref_dro_dvgs;
    *Pn_ref_dro_dvds=n_ref_dro_dvds;
    *Pn_ref_dro_dvbs=n_ref_dro_dvbs;
    *Pn_ref_dro_dl=n_ref_dro_dl;
    *Pn_ref_Ideq=n_ref_Ideq;
    *PGds_out_0=Gds_out_0;
    *Pparam_rload=param_rload;
    *PDet=Det;
    *PTed=Ted;
    *Pparam_in=param_in;
    *Pin_V=in_V;
    *Pparam_iref=param_iref;
    *Pvdd_V=vdd_V;
    *Pparam_vdd=param_vdd;
    *Pn_ref_Nt_unit=n_ref_Nt_unit;
    *Pn_ref_dNt_dvgs=n_ref_dNt_dvgs;
    *Pn_ref_dNt_dvds=n_ref_dNt_dvds;
    *Pn_ref_dNt_dvbs=n_ref_dNt_dvbs;
    *Pn_ref_dNt_dl=n_ref_dNt_dl;
    *Pn_ref_Nt=n_ref_Nt;
    *Pn_ref_Nf_unit=n_ref_Nf_unit;
    *Pn_ref_dNf_dvgs=n_ref_dNf_dvgs;
    *Pn_ref_dNf_dvds=n_ref_dNf_dvds;
    *Pn_ref_dNf_dvbs=n_ref_dNf_dvbs;
    *Pn_ref_dNf_dl=n_ref_dNf_dl;
    *Pn_ref_Nf=n_ref_Nf;
    *Pproperty_Adc=property_Adc;
    *Pproperty_PSRR=property_PSRR;
    *Pn_ref_gm_size_W=n_ref_gm_size_W;
    *Pn_ref_gm_size_L=n_ref_gm_size_L;
    *Pn_ref_go_size_W=n_ref_go_size_W;
    *Pn_ref_go_size_L=n_ref_go_size_L;
    *PDet_n_ref_gm=Det_n_ref_gm;
    *PTed_n_ref_gm=Ted_n_ref_gm;
    *PDet_n_ref_go=Det_n_ref_go;
    *PTed_n_ref_go=Ted_n_ref_go;
    *PDet_L=Det_L;
    *PTed_L=Ted_L;
    *PDet_W=Det_W;
    *PTed_W=Ted_W;
    *Pproperty_Adc_n_ref_gm=property_Adc_n_ref_gm;
    *PAdc=Adc;
    *Pproperty_Adc_n_ref_go=property_Adc_n_ref_go;
    *Pproperty_Adc_L=property_Adc_L;
    *Pproperty_Adc_W=property_Adc_W;
    *Pproperty_PSRR_n_ref_gm=property_PSRR_n_ref_gm;
    *PPSRR=PSRR;
    *Pproperty_PSRR_n_ref_go=property_PSRR_n_ref_go;
    *Pproperty_PSRR_L=property_PSRR_L;
    *Pproperty_PSRR_W=property_PSRR_W;
    *Pproperty_Zout=property_Zout;
    *Pproperty_Zout_n_ref_gm=property_Zout_n_ref_gm;
    *PTed_n_ref_gm0=Ted_n_ref_gm0;
    *PZout=Zout;
    *Pproperty_Zout_n_ref_go=property_Zout_n_ref_go;
    *PTed_n_ref_go0=Ted_n_ref_go0;
    *Pproperty_Zout_L=property_Zout_L;
    *Pproperty_Zout_W=property_Zout_W;
    *Pn_ref_cgs=n_ref_cgs;
    *Plook_up_tables_nch_cox=look_up_tables_nch_cox;
    *Pn_ref_cgd=n_ref_cgd;
    *Ps=s;
    *Pproperty_BW_s=property_BW_s;
    *Pp1=p1;
    *Pproperty_BW=property_BW;
    *Pp2=p2;
    *Pproperty_ts=property_ts;
    *Pproperty_ts_s=property_ts_s;
    *PDet_ac_n_ref_gm=Det_ac_n_ref_gm;
    *PDet_ac_n_ref_go=Det_ac_n_ref_go;
    *Pproperty_BW_L=property_BW_L;
    *Pproperty_ts_L=property_ts_L;
    *Pproperty_BW_W=property_BW_W;
    *Pproperty_ts_W=property_ts_W;
    *Pn_ref_Nt_L=n_ref_Nt_L;
    *Pn_ref_Nf_L=n_ref_Nf_L;
    *Pout_0_dNf_dl=out_0_dNf_dl;
    *Pout_0_gm=out_0_gm;
    *Pn_ref_Nt_W=n_ref_Nt_W;
    *Pn_ref_Nf_W=n_ref_Nf_W;
    *Pn_ref_noise_trans=n_ref_noise_trans;
    *Pn_ref_noise_trans_L=n_ref_noise_trans_L;
    *Pn_ref_noise_trans_W=n_ref_noise_trans_W;
    *Pproperty_Nt=property_Nt;
    *Pproperty_Nt_L=property_Nt_L;
    *Pproperty_Nt_W=property_Nt_W;
    *Pproperty_Nf=property_Nf;
    *Pproperty_Nf_L=property_Nf_L;
    *Pproperty_Nf_W=property_Nf_W;
    *Pproperty_fc=property_fc;
    *Pproperty_fc_L=property_fc_L;
    *Pproperty_fc_W=property_fc_W;
    return TCL_OK;
}
static int tcl_gamma_op_cmd(ClientData clientData,Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    Tcl_ResetResult(interp);
    // Calculating circuit operating point:
    int op_it=0;
    for (op_it=0;op_it<op_iterations;op_it++) {
        n_ref_gm=gamma_gcc_interpolateg_4(P_look_up_tables_nch_gm_ss_LUT,gate_V,out_V,CONST_0_V,size_L,&n_ref_dgm_dvgs,&n_ref_dgm_dvds,&n_ref_dgm_dvbs,&n_ref_dgm_dl)*size_W/size_L;
        n_ref_go=size_W/size_L/gamma_gcc_interpolateg_4(P_look_up_tables_nch_ro_ss_LUT,gate_V,out_V,CONST_0_V,size_L,&n_ref_dro_dvgs,&n_ref_dro_dvds,&n_ref_dro_dvbs,&n_ref_dro_dl);
        n_ref_Ideq=gamma_gcc_interpolate_4(P_look_up_tables_nch_Ids_ss_LUT,gate_V,out_V,CONST_0_V,size_L)*size_W/size_L-n_ref_gm*gate_V-n_ref_go*out_V;
        Gds_out_0=1.0/param_rload;
        if (n_ref_gm==0) n_ref_gm=1e-6;
        if (n_ref_go==0) n_ref_go=1e-6;
        Det=0.001*(Gds_out_0+n_ref_go);
        Ted=1/Det;
        // Updating node voltages
        gate_V=(-(-0.001)*((-(Gds_out_0+n_ref_go)*(-param_in))))*Ted;
        if (gate_V<0) gate_V=0;
        if (gate_V>1.1) gate_V=1.1;
        in_V=(0.001*((-(Gds_out_0+n_ref_go)*(-param_in))))*Ted;
        if (in_V<0) in_V=0;
        if (in_V>1.1) in_V=1.1;
        out_V=(0.001*(param_iref-n_ref_Ideq)-(-0.001)*(n_ref_gm*(-param_in)))*Ted;
        if (out_V<0) out_V=0;
        if (out_V>1.1) out_V=1.1;
        vdd_V=(0.001*((-(Gds_out_0+n_ref_go)*(-param_vdd))))*Ted;
        if (vdd_V<0) vdd_V=0;
        if (vdd_V>1.1) vdd_V=1.1;
    }
    n_ref_Nt_unit=gamma_gcc_interpolateg_4(P_look_up_tables_nch_thermal_noise_ss_LUT,gate_V,out_V,CONST_0_V,size_L,&n_ref_dNt_dvgs,&n_ref_dNt_dvds,&n_ref_dNt_dvbs,&n_ref_dNt_dl);
    n_ref_Nt=n_ref_Nt_unit*sqrt(n_ref_gm);
    n_ref_Nf_unit=gamma_gcc_interpolateg_4(P_look_up_tables_nch_flicker_noise_ss_LUT,gate_V,out_V,CONST_0_V,size_L,&n_ref_dNf_dvgs,&n_ref_dNf_dvds,&n_ref_dNf_dvbs,&n_ref_dNf_dl);
    n_ref_Nf=n_ref_Nf_unit*n_ref_gm*n_ref_gm/(size_W*size_L);
    // Calculating circuit properties:
    property_Adc=((-(-0.001*((-n_ref_gm))))*Ted);
    property_PSRR=(0.0);
    // Calculating circuit properties' gradients:
    n_ref_gm_size_W=n_ref_gm/size_W;
    n_ref_gm_size_L=(size_W*n_ref_dgm_dl-2*n_ref_gm)/size_L;
    n_ref_go_size_W=n_ref_go/size_W;
    n_ref_go_size_L=(n_ref_dro_dl*size_L/size_W-size_L/n_ref_go)*n_ref_go*n_ref_go;
    // Main determinant gradient:
    Det_n_ref_gm=(0.0);
    Ted_n_ref_gm=-Det_n_ref_gm/(Det*Det);
    Det_n_ref_go=(0.001);
    Ted_n_ref_go=-Det_n_ref_go/(Det*Det);
    Det_L=Det_n_ref_gm*n_ref_gm_size_L+Det_n_ref_go*n_ref_go_size_L;
    Ted_L=-Det_L/(Det*Det);
    Det_W=Det_n_ref_go*n_ref_go_size_W+Det_n_ref_gm*n_ref_gm_size_W;
    Ted_W=-Det_W/(Det*Det);
    property_Adc_n_ref_gm=Ted_n_ref_gm*Adc+(-0.001*Ted);
    property_Adc_n_ref_go=Ted_n_ref_go*Adc+(0.0);
    property_Adc_L=n_ref_gm_size_L*property_Adc_n_ref_gm+n_ref_go_size_L*property_Adc_n_ref_go;
    property_Adc_W=n_ref_go_size_W*property_Adc_n_ref_go+n_ref_gm_size_W*property_Adc_n_ref_gm;
    property_PSRR_n_ref_gm=Ted_n_ref_gm*PSRR+0;
    property_PSRR_n_ref_go=Ted_n_ref_go*PSRR+0;
    property_PSRR_L=n_ref_gm_size_L*property_PSRR_n_ref_gm+n_ref_go_size_L*property_PSRR_n_ref_go;
    property_PSRR_W=n_ref_go_size_W*property_PSRR_n_ref_go+n_ref_gm_size_W*property_PSRR_n_ref_gm;
    property_Zout=(0.001)*Ted;
    property_Zout_n_ref_gm=Ted_n_ref_gm0*Zout+0;
    property_Zout_n_ref_go=Ted_n_ref_go0*Zout+0;
    property_Zout_L=n_ref_gm_size_L*property_Zout_n_ref_gm+n_ref_go_size_L*property_Zout_n_ref_go;
    property_Zout_W=n_ref_go_size_W*property_Zout_n_ref_go+n_ref_gm_size_W*property_Zout_n_ref_gm;
    n_ref_cgs=0.66666*look_up_tables_nch_cox*size_L*size_W;
    n_ref_cgd=0.33333*look_up_tables_nch_cox*size_L*size_W;
    s=-1;
    int BW_it;
    for (BW_it=0;BW_it<5;BW_it++) {
        s-=(-0.001*(Gds_out_0+n_ref_go)+(-n_ref_cgd*s)*(n_ref_gm+n_ref_cgd*s))/((((-n_ref_cgd*s)*((n_ref_cgd))+(-(n_ref_cgd))*(n_ref_gm+n_ref_cgd*s))));
    }
    property_BW_s=(((-n_ref_cgd*s)*((n_ref_cgd))+(-(n_ref_cgd))*(n_ref_gm+n_ref_cgd*s)));
    p1=-s;
    property_BW=p1/(2*3.141592656);
    s-=1e3;
    for (BW_it=0;BW_it<20;BW_it++) {
        s-=((-0.001*(Gds_out_0+n_ref_go)+(-n_ref_cgd*s)*(n_ref_gm+n_ref_cgd*s))*(s+p1-5e2))/(((((-n_ref_cgd*s)*((n_ref_cgd))+(-(n_ref_cgd))*(n_ref_gm+n_ref_cgd*s))))*(s+p1-5e2)-(-0.001*(Gds_out_0+n_ref_go)+(-n_ref_cgd*s)*(n_ref_gm+n_ref_cgd*s)));
    }
    p2=-s;
    float A1=-p2/(-p1+p2);
    float A2=-p1/(-p1+p2);
    property_ts=0;
    for (BW_it=0;BW_it<10;BW_it++) {
        property_ts-=(0.02+A1*exp(-p1*property_ts)+A2*exp(-p2*property_ts))/(-p1*A1*exp(-p1*property_ts)-p2*A2*exp(-p2*property_ts));
    }
    property_ts_s=-p1*A1*exp(-p1*property_ts)-p2*A2*exp(-p2*property_ts);
    Det_ac_n_ref_gm=(((-n_ref_cgd*s)));
    Det_ac_n_ref_go=(-0.001);
    property_BW_L=-(n_ref_gm_size_L*Det_ac_n_ref_gm+n_ref_go_size_L*Det_ac_n_ref_go)/property_BW_s;
    property_ts_L=-(n_ref_gm_size_L*Det_ac_n_ref_gm+n_ref_go_size_L*Det_ac_n_ref_go)/property_ts_s;
    property_BW_W=-(n_ref_go_size_W*Det_ac_n_ref_go+n_ref_gm_size_W*Det_ac_n_ref_gm)/property_BW_s;
    property_ts_W=-(n_ref_go_size_W*Det_ac_n_ref_go+n_ref_gm_size_W*Det_ac_n_ref_gm)/property_ts_s;
    n_ref_Nt_L=n_ref_dNt_dl*sqrt(n_ref_gm)+0.5*n_ref_Nt_unit/sqrt(n_ref_gm)*n_ref_gm_size_L;
    n_ref_Nf_L=out_0_dNf_dl*out_0_gm/sqrt(size_W*size_L)+n_ref_Nf_unit*n_ref_gm_size_L/sqrt(size_W*size_L)-n_ref_Nf_unit*out_0_gm/sqrt(size_W*size_L);
    n_ref_Nt_L=n_ref_dNt_dl*sqrt(n_ref_gm)+0.5*n_ref_Nt_unit/sqrt(n_ref_gm)*n_ref_gm_size_L;
    n_ref_Nf_L=out_0_dNf_dl*out_0_gm/sqrt(size_W*size_L)+n_ref_Nf_unit*n_ref_gm_size_L/sqrt(size_W*size_L)-n_ref_Nf_unit*out_0_gm/sqrt(size_W*size_L);
    n_ref_Nt_W=n_ref_Nt_unit/sqrt(n_ref_gm)*n_ref_gm_size_W;
    n_ref_Nf_W=n_ref_Nf_unit*n_ref_gm_size_W/sqrt(size_W*size_L)-0.5*n_ref_Nf_unit*n_ref_gm/(sqrt(size_W)*size_L*size_W);
    n_ref_Nt_W=n_ref_Nt_unit/sqrt(n_ref_gm)*n_ref_gm_size_W;
    n_ref_Nf_W=n_ref_Nf_unit*n_ref_gm_size_W/sqrt(size_W*size_L)-0.5*n_ref_Nf_unit*n_ref_gm/(sqrt(size_W)*size_L*size_W);
    n_ref_noise_trans=Ted*(-0.001)/property_Adc;
    n_ref_noise_trans_L=0;
    n_ref_noise_trans_W=0;
    property_Nt=n_ref_noise_trans*n_ref_noise_trans*n_ref_Nt;
    property_Nt_L=2*n_ref_noise_trans*n_ref_noise_trans_L*n_ref_Nt+n_ref_noise_trans*n_ref_noise_trans*n_ref_Nt_L;
    property_Nt_W=2*n_ref_noise_trans*n_ref_noise_trans_W*n_ref_Nt+n_ref_noise_trans*n_ref_noise_trans*n_ref_Nt_W;
    property_Nf=n_ref_noise_trans*n_ref_noise_trans*n_ref_Nf;
    property_Nf_L=2*n_ref_noise_trans*n_ref_noise_trans_L*n_ref_Nf+n_ref_noise_trans*n_ref_noise_trans*n_ref_Nf_L;
    property_Nf_W=2*n_ref_noise_trans*n_ref_noise_trans_W*n_ref_Nf+n_ref_noise_trans*n_ref_noise_trans*n_ref_Nf_W;
    property_fc=property_Nf/property_Nt;
    property_fc_L=property_Nf_L/property_Nt-property_Nf/(property_Nt*property_Nt)*property_Nt_L;
    property_fc_W=property_Nf_W/property_Nt-property_Nf/(property_Nt*property_Nt)*property_Nt_W;
    return TCL_OK;
}
// Initializing cTree references and registering the tcl_gamma_op_cmd command as ::C::cs_nmos
int Gamma_Init(Tcl_Interp *interp) {
    if (Tcl_InitStubs(interp, TCL_VERSION, 0) == NULL) {
        return TCL_ERROR;
    }
    float *array_entry;
    context *c;
    c=create_context("op_iterations");
    Pop_iterations=(float *)(&c->value.s);
    c=create_context("n_ref:gm");
    Pn_ref_gm=(float *)(&c->value.s);
    P_look_up_tables_nch_gm_ss_LUT=(float *)get_LUT(":look_up_tables:nch:gm:ss");
    c=create_context("gate:V");
    Pgate_V=(float *)(&c->value.s);
    c=create_context("out:V");
    Pout_V=(float *)(&c->value.s);
    c=create_context("0:V");
    P0_V=(float *)(&c->value.s);
    c=create_context("size:L");
    Psize_L=(float *)(&c->value.s);
    c=create_context("n_ref:dgm_dvgs");
    Pn_ref_dgm_dvgs=(float *)(&c->value.s);
    c=create_context("n_ref:dgm_dvds");
    Pn_ref_dgm_dvds=(float *)(&c->value.s);
    c=create_context("n_ref:dgm_dvbs");
    Pn_ref_dgm_dvbs=(float *)(&c->value.s);
    c=create_context("n_ref:dgm_dl");
    Pn_ref_dgm_dl=(float *)(&c->value.s);
    c=create_context("size:W");
    Psize_W=(float *)(&c->value.s);
    c=create_context("n_ref:go");
    Pn_ref_go=(float *)(&c->value.s);
    P_look_up_tables_nch_ro_ss_LUT=(float *)get_LUT(":look_up_tables:nch:ro:ss");
    c=create_context("n_ref:dro_dvgs");
    Pn_ref_dro_dvgs=(float *)(&c->value.s);
    c=create_context("n_ref:dro_dvds");
    Pn_ref_dro_dvds=(float *)(&c->value.s);
    c=create_context("n_ref:dro_dvbs");
    Pn_ref_dro_dvbs=(float *)(&c->value.s);
    c=create_context("n_ref:dro_dl");
    Pn_ref_dro_dl=(float *)(&c->value.s);
    c=create_context("n_ref:Ideq");
    Pn_ref_Ideq=(float *)(&c->value.s);
    P_look_up_tables_nch_Ids_ss_LUT=(float *)get_LUT(":look_up_tables:nch:Ids:ss");
    c=create_context("Gds_out_0");
    PGds_out_0=(float *)(&c->value.s);
    c=create_context("param:rload");
    Pparam_rload=(float *)(&c->value.s);
    c=create_context("Det");
    PDet=(float *)(&c->value.s);
    c=create_context("Ted");
    PTed=(float *)(&c->value.s);
    c=create_context("param:in");
    Pparam_in=(float *)(&c->value.s);
    c=create_context("in:V");
    Pin_V=(float *)(&c->value.s);
    c=create_context("param:iref");
    Pparam_iref=(float *)(&c->value.s);
    c=create_context("vdd:V");
    Pvdd_V=(float *)(&c->value.s);
    c=create_context("param:vdd");
    Pparam_vdd=(float *)(&c->value.s);
    c=create_context("n_ref:Nt_unit");
    Pn_ref_Nt_unit=(float *)(&c->value.s);
    P_look_up_tables_nch_thermal_noise_ss_LUT=(float *)get_LUT(":look_up_tables:nch:thermal_noise:ss");
    c=create_context("n_ref:dNt_dvgs");
    Pn_ref_dNt_dvgs=(float *)(&c->value.s);
    c=create_context("n_ref:dNt_dvds");
    Pn_ref_dNt_dvds=(float *)(&c->value.s);
    c=create_context("n_ref:dNt_dvbs");
    Pn_ref_dNt_dvbs=(float *)(&c->value.s);
    c=create_context("n_ref:dNt_dl");
    Pn_ref_dNt_dl=(float *)(&c->value.s);
    c=create_context("n_ref:Nt");
    Pn_ref_Nt=(float *)(&c->value.s);
    c=create_context("n_ref:Nf_unit");
    Pn_ref_Nf_unit=(float *)(&c->value.s);
    P_look_up_tables_nch_flicker_noise_ss_LUT=(float *)get_LUT(":look_up_tables:nch:flicker_noise:ss");
    c=create_context("n_ref:dNf_dvgs");
    Pn_ref_dNf_dvgs=(float *)(&c->value.s);
    c=create_context("n_ref:dNf_dvds");
    Pn_ref_dNf_dvds=(float *)(&c->value.s);
    c=create_context("n_ref:dNf_dvbs");
    Pn_ref_dNf_dvbs=(float *)(&c->value.s);
    c=create_context("n_ref:dNf_dl");
    Pn_ref_dNf_dl=(float *)(&c->value.s);
    c=create_context("n_ref:Nf");
    Pn_ref_Nf=(float *)(&c->value.s);
    c=create_context("property:Adc");
    Pproperty_Adc=(float *)(&c->value.s);
    c=create_context("property:PSRR");
    Pproperty_PSRR=(float *)(&c->value.s);
    c=create_context("n_ref:gm:size:W");
    Pn_ref_gm_size_W=(float *)(&c->value.s);
    c=create_context("n_ref:gm:size:L");
    Pn_ref_gm_size_L=(float *)(&c->value.s);
    c=create_context("n_ref:go:size:W");
    Pn_ref_go_size_W=(float *)(&c->value.s);
    c=create_context("n_ref:go:size:L");
    Pn_ref_go_size_L=(float *)(&c->value.s);
    c=create_context("Det:n_ref:gm");
    PDet_n_ref_gm=(float *)(&c->value.s);
    c=create_context("Ted:n_ref:gm");
    PTed_n_ref_gm=(float *)(&c->value.s);
    c=create_context("Det:n_ref:go");
    PDet_n_ref_go=(float *)(&c->value.s);
    c=create_context("Ted:n_ref:go");
    PTed_n_ref_go=(float *)(&c->value.s);
    c=create_context("Det:L");
    PDet_L=(float *)(&c->value.s);
    c=create_context("Ted:L");
    PTed_L=(float *)(&c->value.s);
    c=create_context("Det:W");
    PDet_W=(float *)(&c->value.s);
    c=create_context("Ted:W");
    PTed_W=(float *)(&c->value.s);
    c=create_context("property:Adc:n_ref:gm");
    Pproperty_Adc_n_ref_gm=(float *)(&c->value.s);
    c=create_context("Adc");
    PAdc=(float *)(&c->value.s);
    c=create_context("property:Adc:n_ref:go");
    Pproperty_Adc_n_ref_go=(float *)(&c->value.s);
    c=create_context("property:Adc:L");
    Pproperty_Adc_L=(float *)(&c->value.s);
    c=create_context("property:Adc:W");
    Pproperty_Adc_W=(float *)(&c->value.s);
    c=create_context("property:PSRR:n_ref:gm");
    Pproperty_PSRR_n_ref_gm=(float *)(&c->value.s);
    c=create_context("PSRR");
    PPSRR=(float *)(&c->value.s);
    c=create_context("property:PSRR:n_ref:go");
    Pproperty_PSRR_n_ref_go=(float *)(&c->value.s);
    c=create_context("property:PSRR:L");
    Pproperty_PSRR_L=(float *)(&c->value.s);
    c=create_context("property:PSRR:W");
    Pproperty_PSRR_W=(float *)(&c->value.s);
    c=create_context("property:Zout");
    Pproperty_Zout=(float *)(&c->value.s);
    c=create_context("property:Zout:n_ref:gm");
    Pproperty_Zout_n_ref_gm=(float *)(&c->value.s);
    c=create_context("Ted_n_ref_gm");
    PTed_n_ref_gm0=(float *)(&c->value.s);
    c=create_context("Zout");
    PZout=(float *)(&c->value.s);
    c=create_context("property:Zout:n_ref:go");
    Pproperty_Zout_n_ref_go=(float *)(&c->value.s);
    c=create_context("Ted_n_ref_go");
    PTed_n_ref_go0=(float *)(&c->value.s);
    c=create_context("property:Zout:L");
    Pproperty_Zout_L=(float *)(&c->value.s);
    c=create_context("property:Zout:W");
    Pproperty_Zout_W=(float *)(&c->value.s);
    c=create_context("n_ref:cgs");
    Pn_ref_cgs=(float *)(&c->value.s);
    c=create_context("look_up_tables:nch:cox");
    Plook_up_tables_nch_cox=(float *)(&c->value.s);
    c=create_context("n_ref:cgd");
    Pn_ref_cgd=(float *)(&c->value.s);
    c=create_context("s");
    Ps=(float *)(&c->value.s);
    c=create_context("property:BW:s");
    Pproperty_BW_s=(float *)(&c->value.s);
    c=create_context("p1");
    Pp1=(float *)(&c->value.s);
    c=create_context("property:BW");
    Pproperty_BW=(float *)(&c->value.s);
    c=create_context("p2");
    Pp2=(float *)(&c->value.s);
    c=create_context("property:ts");
    Pproperty_ts=(float *)(&c->value.s);
    c=create_context("property:ts:s");
    Pproperty_ts_s=(float *)(&c->value.s);
    c=create_context("Det_ac:n_ref:gm");
    PDet_ac_n_ref_gm=(float *)(&c->value.s);
    c=create_context("Det_ac:n_ref:go");
    PDet_ac_n_ref_go=(float *)(&c->value.s);
    c=create_context("property:BW:L");
    Pproperty_BW_L=(float *)(&c->value.s);
    c=create_context("property:ts:L");
    Pproperty_ts_L=(float *)(&c->value.s);
    c=create_context("property:BW:W");
    Pproperty_BW_W=(float *)(&c->value.s);
    c=create_context("property:ts:W");
    Pproperty_ts_W=(float *)(&c->value.s);
    c=create_context("n_ref:Nt:L");
    Pn_ref_Nt_L=(float *)(&c->value.s);
    c=create_context("n_ref:Nf:L");
    Pn_ref_Nf_L=(float *)(&c->value.s);
    c=create_context("out_0:dNf_dl");
    Pout_0_dNf_dl=(float *)(&c->value.s);
    c=create_context("out_0:gm");
    Pout_0_gm=(float *)(&c->value.s);
    c=create_context("n_ref:Nt:W");
    Pn_ref_Nt_W=(float *)(&c->value.s);
    c=create_context("n_ref:Nf:W");
    Pn_ref_Nf_W=(float *)(&c->value.s);
    c=create_context("n_ref:noise_trans");
    Pn_ref_noise_trans=(float *)(&c->value.s);
    c=create_context("n_ref:noise_trans:L");
    Pn_ref_noise_trans_L=(float *)(&c->value.s);
    c=create_context("n_ref:noise_trans:W");
    Pn_ref_noise_trans_W=(float *)(&c->value.s);
    c=create_context("property:Nt");
    Pproperty_Nt=(float *)(&c->value.s);
    c=create_context("property:Nt:L");
    Pproperty_Nt_L=(float *)(&c->value.s);
    c=create_context("property:Nt:W");
    Pproperty_Nt_W=(float *)(&c->value.s);
    c=create_context("property:Nf");
    Pproperty_Nf=(float *)(&c->value.s);
    c=create_context("property:Nf:L");
    Pproperty_Nf_L=(float *)(&c->value.s);
    c=create_context("property:Nf:W");
    Pproperty_Nf_W=(float *)(&c->value.s);
    c=create_context("property:fc");
    Pproperty_fc=(float *)(&c->value.s);
    c=create_context("property:fc:L");
    Pproperty_fc_L=(float *)(&c->value.s);
    c=create_context("property:fc:W");
    Pproperty_fc_W=(float *)(&c->value.s);
    Tcl_CreateObjCommand(interp, "::C::op", tcl_gamma_op_cmd, NULL, NULL);
    Tcl_CreateObjCommand(interp, "::C::import", tcl_gamma_import_cmd, NULL, NULL);
    Tcl_CreateObjCommand(interp, "::C::export", tcl_gamma_export_cmd, NULL, NULL);
    return TCL_OK;
}
