#include <tcl.h>
#include <stdio.h>
#include <stdlib.h>
#include "ctree.h"
#include "look_up_table.h"
// Some global pointers to keep reference of the contexts this object manipulates
float *Poutput_nmos_circuits_PAT;
float *Pconfig_pat_size_target;
float *Psize_L;
float *Psize_L_min;
float *Psize_L_max;
float *Psize_W;
float *Psize_W_max;
float *Psize_Lp;
float *Psize_Lp_min;
float *Psize_Lp_max;
float *Psize_Wp;
float *Psize_Wp_max;
float *Psize_rin;
float *Psize_rin_min;
float *Psize_rin_max;
float *Psize_L_step;
float *Psize_W_step;
float *Psize_Lp_step;
float *Psize_Wp_step;
float *Psize_rin_step;
float *Pmax_Adc;
float *Pparam_unique;
float *Ppat_size_target;
float *Pmode_freash_op;
float *Pin_V;
float *Pparam_in;
float *Pout_V;
float *Pvdd_V;
float *Pmid_V;
float *Pstatus_index;
float *Pconfig_size_L;
float *Pconfig_size_W;
float *Pconfig_size_Lp;
float *Pconfig_size_Wp;
float *Pconfig_size_rin;
float *P0_V;
float *Pstatus_fail;
float *Pdesign_feedback;
float *Pleak;
float *Pconfig_op_iterations;
float *Pconfig_kcl_th;
float *Pconfig_design_feedback_th;
float *Plook_up_tables_pch_Ids_ss_LUT;
float *Plook_up_tables_pch_gm_ss_LUT;
float *Plook_up_tables_pch_ro_ss_LUT;
float *Pp_gm;
float *Pp_go;
float *Pp_Ids;
float *Plook_up_tables_nch_Ids_ss_LUT;
float *Plook_up_tables_nch_gm_ss_LUT;
float *Plook_up_tables_nch_ro_ss_LUT;
float *Pn_ref_gm;
float *Pn_ref_go;
float *Pn_ref_Ids;
float *PGds_in_mid;
float *Pconfig_kcl_step;
float *PDet;
float *PTed;
float *Pproperty_Adc;
float *Pproperty_CMRR;
float *Pproperty_PSRR;
float *Pconfig_fail_on_properties;
float *Pproperty_Rout;
float *Pn_ref_cdg;
float *Ps;
float *Pn_ref_cgg;
float *Pn_ref_Ideq;
float *Pp_Ideq;
float *Pp_cgs;
float *Pp_cgb;
float *Pp_cds;
float *Pp_cdb;
float *Pn_ref_cds;
float *Pn_ref_cdb;
float *Pparam_vdd;
float *Pn_ref_cgs;
float *Pn_ref_cgb;
float *Pp_cgd;
float *Pp_cgg;
float *Pp_cdd;
float *Pp_cdg;
float *Pn_ref_cdd;
float *Pn_ref_cgd;
float *Plook_up_tables_pch_cgg_ss_LUT;
float *Pconfig_cgg_factor;
float *Plook_up_tables_pch_cgd_ss_LUT;
float *Pconfig_cgd_factor;
float *Plook_up_tables_pch_cgs_ss_LUT;
float *Pconfig_cgs_factor;
float *Plook_up_tables_pch_cgb_ss_LUT;
float *Pconfig_cgb_factor;
float *Plook_up_tables_pch_cdd_ss_LUT;
float *Pconfig_cdd_factor;
float *Plook_up_tables_pch_cdg_ss_LUT;
float *Pconfig_cdg_factor;
float *Plook_up_tables_pch_cdb_ss_LUT;
float *Pconfig_cdb_factor;
float *Plook_up_tables_pch_cds_ss_LUT;
float *Pconfig_cds_factor;
float *Pp_csd;
float *Plook_up_tables_pch_csd_ss_LUT;
float *Pconfig_csd_factor;
float *Pp_csg;
float *Plook_up_tables_pch_csg_ss_LUT;
float *Pconfig_csg_factor;
float *Pp_css;
float *Plook_up_tables_pch_css_ss_LUT;
float *Pconfig_css_factor;
float *Pp_csb;
float *Plook_up_tables_pch_csb_ss_LUT;
float *Pconfig_csb_factor;
float *Pp_cbd;
float *Plook_up_tables_pch_cbd_ss_LUT;
float *Pconfig_cbd_factor;
float *Pp_cbg;
float *Plook_up_tables_pch_cbg_ss_LUT;
float *Pconfig_cbg_factor;
float *Pp_cbs;
float *Plook_up_tables_pch_cbs_ss_LUT;
float *Pconfig_cbs_factor;
float *Pp_cbb;
float *Plook_up_tables_pch_cbb_ss_LUT;
float *Pconfig_cbb_factor;
float *Plook_up_tables_nch_cgg_ss_LUT;
float *Plook_up_tables_nch_cgd_ss_LUT;
float *Plook_up_tables_nch_cgs_ss_LUT;
float *Plook_up_tables_nch_cgb_ss_LUT;
float *Plook_up_tables_nch_cdd_ss_LUT;
float *Plook_up_tables_nch_cdg_ss_LUT;
float *Plook_up_tables_nch_cdb_ss_LUT;
float *Plook_up_tables_nch_cds_ss_LUT;
float *Pn_ref_csd;
float *Plook_up_tables_nch_csd_ss_LUT;
float *Pn_ref_csg;
float *Plook_up_tables_nch_csg_ss_LUT;
float *Pn_ref_css;
float *Plook_up_tables_nch_css_ss_LUT;
float *Pn_ref_csb;
float *Plook_up_tables_nch_csb_ss_LUT;
float *Pn_ref_cbd;
float *Plook_up_tables_nch_cbd_ss_LUT;
float *Pn_ref_cbg;
float *Plook_up_tables_nch_cbg_ss_LUT;
float *Pn_ref_cbs;
float *Plook_up_tables_nch_cbs_ss_LUT;
float *Pn_ref_cbb;
float *Plook_up_tables_nch_cbb_ss_LUT;
float *Pproperty_BW;
float *Pproperty_BW_s;
float *Pp1;
float *Pp2;
float *Pproperty_ts;
float *Pproperty_PM;
float *Pp_Nt_unit;
float *P_look_up_tables_pch_thermal_noise_ss_LUT;
float *Pp_dNt_dvgs;
float *Pp_dNt_dvds;
float *Pp_dNt_dvbs;
float *Pp_dNt_dl;
float *Pp_Nt;
float *Pp_Nf_unit;
float *P_look_up_tables_pch_flicker_noise_ss_LUT;
float *Pp_dNf_dvgs;
float *Pp_dNf_dvds;
float *Pp_dNf_dvbs;
float *Pp_dNf_dl;
float *Pp_Nf;
float *Pn_ref_Nt_unit;
float *P_look_up_tables_nch_thermal_noise_ss_LUT;
float *Pn_ref_dNt_dvgs;
float *Pn_ref_dNt_dvds;
float *Pn_ref_dNt_dvbs;
float *Pn_ref_dNt_dl;
float *Pn_ref_Nt;
float *Pn_ref_Nf_unit;
float *P_look_up_tables_nch_flicker_noise_ss_LUT;
float *Pn_ref_dNf_dvgs;
float *Pn_ref_dNf_dvds;
float *Pn_ref_dNf_dvbs;
float *Pn_ref_dNf_dl;
float *Pn_ref_Nf;
float *Pproperty_Nt;
float *Pproperty_Nf;
float *Pproperty_fc;
float *Pproperty_TotalNoise;
float *Pproperty_Area;
float *Pproperty_Vos;
float *Pproperty_Power;
float *Pconfig_factor_Adc;
float *Pconfig_shift_Adc;
float *Pconfig_factor_CMRR;
float *Pconfig_shift_CMRR;
float *Pconfig_factor_PSRR;
float *Pconfig_shift_PSRR;
float *Pconfig_factor_Rout;
float *Pconfig_shift_Rout;
float *Pconfig_factor_BW;
float *Pconfig_shift_BW;
float *Pconfig_factor_PM;
float *Pconfig_shift_PM;
float *Pconfig_factor_Cin;
float *Pconfig_shift_Cin;
float *Pproperty_Cin;
float *Pconfig_factor_ts;
float *Pconfig_shift_ts;
float *Pconfig_factor_Nt;
float *Pconfig_shift_Nt;
float *Pconfig_factor_Nf;
float *Pconfig_shift_Nf;
float *Pconfig_factor_TotalNoise;
float *Pconfig_shift_TotalNoise;
float *Pconfig_factor_fc;
float *Pconfig_shift_fc;
float *Pconfig_factor_Vos;
float *Pconfig_shift_Vos;
float *Pconfig_factor_Area;
float *Pconfig_shift_Area;
float *Pconfig_factor_Power;
float *Pconfig_shift_Power;
float *Pcircuit_breed_id;
float *Pcircuit_breed_target;
float output_nmos_circuits_PAT;
float config_pat_size_target;
float size_L;
float size_L_min;
float size_L_max;
float size_W;
float size_W_max;
float size_Lp;
float size_Lp_min;
float size_Lp_max;
float size_Wp;
float size_Wp_max;
float size_rin;
float size_rin_min;
float size_rin_max;
float size_L_step;
float size_W_step;
float size_Lp_step;
float size_Wp_step;
float size_rin_step;
float max_Adc;
float param_unique;
float pat_size_target;
float mode_freash_op;
float in_V;
float param_in;
float out_V;
float vdd_V;
float mid_V;
float status_index;
float config_size_L;
float config_size_W;
float config_size_Lp;
float config_size_Wp;
float config_size_rin;
float CONST_0_V;
float status_fail;
float design_feedback;
float leak;
float config_op_iterations;
float config_kcl_th;
float config_design_feedback_th;
float look_up_tables_pch_Ids_ss_LUT;
float look_up_tables_pch_gm_ss_LUT;
float look_up_tables_pch_ro_ss_LUT;
float p_gm;
float p_go;
float p_Ids;
float look_up_tables_nch_Ids_ss_LUT;
float look_up_tables_nch_gm_ss_LUT;
float look_up_tables_nch_ro_ss_LUT;
float n_ref_gm;
float n_ref_go;
float n_ref_Ids;
float Gds_in_mid;
float config_kcl_step;
float Det;
float Ted;
float property_Adc;
float property_CMRR;
float property_PSRR;
float config_fail_on_properties;
float property_Rout;
float n_ref_cdg;
float s;
float n_ref_cgg;
float n_ref_Ideq;
float p_Ideq;
float p_cgs;
float p_cgb;
float p_cds;
float p_cdb;
float n_ref_cds;
float n_ref_cdb;
float param_vdd;
float n_ref_cgs;
float n_ref_cgb;
float p_cgd;
float p_cgg;
float p_cdd;
float p_cdg;
float n_ref_cdd;
float n_ref_cgd;
float look_up_tables_pch_cgg_ss_LUT;
float config_cgg_factor;
float look_up_tables_pch_cgd_ss_LUT;
float config_cgd_factor;
float look_up_tables_pch_cgs_ss_LUT;
float config_cgs_factor;
float look_up_tables_pch_cgb_ss_LUT;
float config_cgb_factor;
float look_up_tables_pch_cdd_ss_LUT;
float config_cdd_factor;
float look_up_tables_pch_cdg_ss_LUT;
float config_cdg_factor;
float look_up_tables_pch_cdb_ss_LUT;
float config_cdb_factor;
float look_up_tables_pch_cds_ss_LUT;
float config_cds_factor;
float p_csd;
float look_up_tables_pch_csd_ss_LUT;
float config_csd_factor;
float p_csg;
float look_up_tables_pch_csg_ss_LUT;
float config_csg_factor;
float p_css;
float look_up_tables_pch_css_ss_LUT;
float config_css_factor;
float p_csb;
float look_up_tables_pch_csb_ss_LUT;
float config_csb_factor;
float p_cbd;
float look_up_tables_pch_cbd_ss_LUT;
float config_cbd_factor;
float p_cbg;
float look_up_tables_pch_cbg_ss_LUT;
float config_cbg_factor;
float p_cbs;
float look_up_tables_pch_cbs_ss_LUT;
float config_cbs_factor;
float p_cbb;
float look_up_tables_pch_cbb_ss_LUT;
float config_cbb_factor;
float look_up_tables_nch_cgg_ss_LUT;
float look_up_tables_nch_cgd_ss_LUT;
float look_up_tables_nch_cgs_ss_LUT;
float look_up_tables_nch_cgb_ss_LUT;
float look_up_tables_nch_cdd_ss_LUT;
float look_up_tables_nch_cdg_ss_LUT;
float look_up_tables_nch_cdb_ss_LUT;
float look_up_tables_nch_cds_ss_LUT;
float n_ref_csd;
float look_up_tables_nch_csd_ss_LUT;
float n_ref_csg;
float look_up_tables_nch_csg_ss_LUT;
float n_ref_css;
float look_up_tables_nch_css_ss_LUT;
float n_ref_csb;
float look_up_tables_nch_csb_ss_LUT;
float n_ref_cbd;
float look_up_tables_nch_cbd_ss_LUT;
float n_ref_cbg;
float look_up_tables_nch_cbg_ss_LUT;
float n_ref_cbs;
float look_up_tables_nch_cbs_ss_LUT;
float n_ref_cbb;
float look_up_tables_nch_cbb_ss_LUT;
float property_BW;
float property_BW_s;
float p1;
float p2;
float property_ts;
float property_PM;
float p_Nt_unit;
float _look_up_tables_pch_thermal_noise_ss_LUT;
float p_dNt_dvgs;
float p_dNt_dvds;
float p_dNt_dvbs;
float p_dNt_dl;
float p_Nt;
float p_Nf_unit;
float _look_up_tables_pch_flicker_noise_ss_LUT;
float p_dNf_dvgs;
float p_dNf_dvds;
float p_dNf_dvbs;
float p_dNf_dl;
float p_Nf;
float n_ref_Nt_unit;
float _look_up_tables_nch_thermal_noise_ss_LUT;
float n_ref_dNt_dvgs;
float n_ref_dNt_dvds;
float n_ref_dNt_dvbs;
float n_ref_dNt_dl;
float n_ref_Nt;
float n_ref_Nf_unit;
float _look_up_tables_nch_flicker_noise_ss_LUT;
float n_ref_dNf_dvgs;
float n_ref_dNf_dvds;
float n_ref_dNf_dvbs;
float n_ref_dNf_dl;
float n_ref_Nf;
float property_Nt;
float property_Nf;
float property_fc;
float property_TotalNoise;
float property_Area;
float property_Vos;
float property_Power;
float config_factor_Adc;
float config_shift_Adc;
float config_factor_CMRR;
float config_shift_CMRR;
float config_factor_PSRR;
float config_shift_PSRR;
float config_factor_Rout;
float config_shift_Rout;
float config_factor_BW;
float config_shift_BW;
float config_factor_PM;
float config_shift_PM;
float config_factor_Cin;
float config_shift_Cin;
float property_Cin;
float config_factor_ts;
float config_shift_ts;
float config_factor_Nt;
float config_shift_Nt;
float config_factor_Nf;
float config_shift_Nf;
float config_factor_TotalNoise;
float config_shift_TotalNoise;
float config_factor_fc;
float config_shift_fc;
float config_factor_Vos;
float config_shift_Vos;
float config_factor_Area;
float config_shift_Area;
float config_factor_Power;
float config_shift_Power;
float circuit_breed_id;
float circuit_breed_target;
// The compiled function
float vos(float isize) {
    float x = property_Area;
    float y = isize;
    float a,b,c,d,e,f,g,h,i,j,k;
    if((x >=0) && (y <= 60)) {
        //Date= Feb 21, 2012
        //Time= 11:11:46 AM
        //File Source= c:_tradeoffresults0nm_char_stdev_40n_nch_ss_-40_ln_g_size_gr_0__isize_lt_60.xls
        //Data= offset_stdev_40n_nch_ss_-40_ln_g_size_gr_0__isize_lt_60.xls : (1)offset_std
        a = 12.8855796266630426;
        b = -5.41083764511328898;
        c = -1.30763085764638906;
        d = 0.313643695922134216;
        e = 0.093119070398655552;
        f = 0.000152253934602799006;
        g = 0.027558789121119705;
        h = -0.0908038658897388513;
        i = -0.00736092968454125981;
        j = 0.00997803516051362148;
        return (a+b*logf(x)+c*pow((logf(x)),2)+d*pow((logf(x)),3)+e*pow((logf(x)),4)+f*pow((logf(x)),5)+g*logf(y)+h*pow((logf(y)),2)+i*pow((logf(y)),3)+j*pow((logf(y)),4))/1000;
    } else if((x <= 0) && (y <= 60)) {
        //Date= Feb 21, 2012
        //Time= 11:23:06 AM
        //File Source= c:_tradeoffresults0nm_char_stdev_40n_nch_ss_-40_ln_g_size_lt_0_isize_lt_60.xls
        //Data= offset_stdev_40n_nch_ss_-40_ln_g_size_lt_0_isize_lt_60.xls : (1)offset_std
        a = 2.93660485783974259;
        b = -0.332364084793881404;
        c = 0.00766917418689004997;
        d = 0.0815859439577785321;
        e = -0.0511853190713728586;
        f = 0.0146507924776217549;
        g = -0.00248296699178136492;
        return (expf(a+b*x+c*pow(x,2)+d*pow(y,(1.5))+e*pow(y,2)+f*pow(y,2)*logf(y)+g*pow(y,(2.5))))/1000;
    } else if((x > 0) && (y > 60)) {
        //Date= Feb 21, 2012
        //Time= 11:29:50 AM
        //File Source= c:_tradeoffresults0nm_char_stdev_40n_nch_ss_-40_ln_g_size_gr_0_isize_gr_60.xls
        //Data= offset_stdev_40n_nch_ss_-40_ln_g_size_gr_0_isize_gr_60.xls : (1)offset_std
        a = 0.0245510804148098408;
        b = 0.00571642685094725414;
        c = -0.038594299737104845;
        d = -0.00293384210596431143;
        e = 0.0164401882567682581;
        return (1/(a+b*pow(x,(2.5))+c*expf(-x)+d*y+e*y/logf(y)))/1000;
    } else {
        //Date= Feb 21, 2012
        //Time= 11:34:55 AM
        //File Source= c:_tradeoffresults0nm_char_stdev_40n_nch_ss_-40_ln_g_size_lt_0_isize_gr_60.xls
        //Data= offset_stdev_40n_nch_ss_-40_ln_g_size_lt_0_isize_gr_60.xls : (1)offset_std
        a = 16.2036851911088104;
        b = 0.21279234971619464;
        c = -1.7053361877790996;
        d = -0.00746030946920476022;
        e = -0.118672118503179062;
        f = 0.0131583901472111854;
        g = -0.138292160061225562;
        h = 1.76686418477095332e-05;
        i = 0.000389109336629294047;
        j = -0.000674088087058916077;
        k = 0.00383260060449367847;
        return (((a+c*x+e*y+g*pow(x,2)+i*pow(y,2)+k*x*y)/(1+b*x+d*y+f*pow(x,2)+h*pow(y,2)+j*x*y))/1000);
    }
}
static int tcl_gamma_import_cmd(ClientData clientData,Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    config_pat_size_target=*Pconfig_pat_size_target;
    size_L=*Psize_L;
    size_L_min=*Psize_L_min;
    size_L_max=*Psize_L_max;
    size_W=*Psize_W;
    size_W_max=*Psize_W_max;
    size_Lp=*Psize_Lp;
    size_Lp_min=*Psize_Lp_min;
    size_Lp_max=*Psize_Lp_max;
    size_Wp=*Psize_Wp;
    size_Wp_max=*Psize_Wp_max;
    size_rin=*Psize_rin;
    size_rin_min=*Psize_rin_min;
    size_rin_max=*Psize_rin_max;
    size_L_step=*Psize_L_step;
    size_W_step=*Psize_W_step;
    size_Lp_step=*Psize_Lp_step;
    size_Wp_step=*Psize_Wp_step;
    size_rin_step=*Psize_rin_step;
    max_Adc=*Pmax_Adc;
    param_unique=*Pparam_unique;
    pat_size_target=*Ppat_size_target;
    mode_freash_op=*Pmode_freash_op;
    in_V=*Pin_V;
    param_in=*Pparam_in;
    out_V=*Pout_V;
    vdd_V=*Pvdd_V;
    mid_V=*Pmid_V;
    status_index=*Pstatus_index;
    config_size_L=*Pconfig_size_L;
    config_size_W=*Pconfig_size_W;
    config_size_Lp=*Pconfig_size_Lp;
    config_size_Wp=*Pconfig_size_Wp;
    config_size_rin=*Pconfig_size_rin;
    CONST_0_V=*P0_V;
    status_fail=*Pstatus_fail;
    design_feedback=*Pdesign_feedback;
    leak=*Pleak;
    config_op_iterations=*Pconfig_op_iterations;
    config_kcl_th=*Pconfig_kcl_th;
    config_design_feedback_th=*Pconfig_design_feedback_th;
    p_gm=*Pp_gm;
    p_go=*Pp_go;
    p_Ids=*Pp_Ids;
    n_ref_gm=*Pn_ref_gm;
    n_ref_go=*Pn_ref_go;
    n_ref_Ids=*Pn_ref_Ids;
    Gds_in_mid=*PGds_in_mid;
    config_kcl_step=*Pconfig_kcl_step;
    Det=*PDet;
    Ted=*PTed;
    property_Adc=*Pproperty_Adc;
    property_CMRR=*Pproperty_CMRR;
    property_PSRR=*Pproperty_PSRR;
    config_fail_on_properties=*Pconfig_fail_on_properties;
    property_Rout=*Pproperty_Rout;
    n_ref_cdg=*Pn_ref_cdg;
    s=*Ps;
    n_ref_cgg=*Pn_ref_cgg;
    n_ref_Ideq=*Pn_ref_Ideq;
    p_Ideq=*Pp_Ideq;
    p_cgs=*Pp_cgs;
    p_cgb=*Pp_cgb;
    p_cds=*Pp_cds;
    p_cdb=*Pp_cdb;
    n_ref_cds=*Pn_ref_cds;
    n_ref_cdb=*Pn_ref_cdb;
    param_vdd=*Pparam_vdd;
    n_ref_cgs=*Pn_ref_cgs;
    n_ref_cgb=*Pn_ref_cgb;
    p_cgd=*Pp_cgd;
    p_cgg=*Pp_cgg;
    p_cdd=*Pp_cdd;
    p_cdg=*Pp_cdg;
    n_ref_cdd=*Pn_ref_cdd;
    n_ref_cgd=*Pn_ref_cgd;
    config_cgg_factor=*Pconfig_cgg_factor;
    config_cgd_factor=*Pconfig_cgd_factor;
    config_cgs_factor=*Pconfig_cgs_factor;
    config_cgb_factor=*Pconfig_cgb_factor;
    config_cdd_factor=*Pconfig_cdd_factor;
    config_cdg_factor=*Pconfig_cdg_factor;
    config_cdb_factor=*Pconfig_cdb_factor;
    config_cds_factor=*Pconfig_cds_factor;
    p_csd=*Pp_csd;
    config_csd_factor=*Pconfig_csd_factor;
    p_csg=*Pp_csg;
    config_csg_factor=*Pconfig_csg_factor;
    p_css=*Pp_css;
    config_css_factor=*Pconfig_css_factor;
    p_csb=*Pp_csb;
    config_csb_factor=*Pconfig_csb_factor;
    p_cbd=*Pp_cbd;
    config_cbd_factor=*Pconfig_cbd_factor;
    p_cbg=*Pp_cbg;
    config_cbg_factor=*Pconfig_cbg_factor;
    p_cbs=*Pp_cbs;
    config_cbs_factor=*Pconfig_cbs_factor;
    p_cbb=*Pp_cbb;
    config_cbb_factor=*Pconfig_cbb_factor;
    n_ref_csd=*Pn_ref_csd;
    n_ref_csg=*Pn_ref_csg;
    n_ref_css=*Pn_ref_css;
    n_ref_csb=*Pn_ref_csb;
    n_ref_cbd=*Pn_ref_cbd;
    n_ref_cbg=*Pn_ref_cbg;
    n_ref_cbs=*Pn_ref_cbs;
    n_ref_cbb=*Pn_ref_cbb;
    property_BW=*Pproperty_BW;
    property_BW_s=*Pproperty_BW_s;
    p1=*Pp1;
    p2=*Pp2;
    property_ts=*Pproperty_ts;
    property_PM=*Pproperty_PM;
    p_Nt_unit=*Pp_Nt_unit;
    p_dNt_dvgs=*Pp_dNt_dvgs;
    p_dNt_dvds=*Pp_dNt_dvds;
    p_dNt_dvbs=*Pp_dNt_dvbs;
    p_dNt_dl=*Pp_dNt_dl;
    p_Nt=*Pp_Nt;
    p_Nf_unit=*Pp_Nf_unit;
    p_dNf_dvgs=*Pp_dNf_dvgs;
    p_dNf_dvds=*Pp_dNf_dvds;
    p_dNf_dvbs=*Pp_dNf_dvbs;
    p_dNf_dl=*Pp_dNf_dl;
    p_Nf=*Pp_Nf;
    n_ref_Nt_unit=*Pn_ref_Nt_unit;
    n_ref_dNt_dvgs=*Pn_ref_dNt_dvgs;
    n_ref_dNt_dvds=*Pn_ref_dNt_dvds;
    n_ref_dNt_dvbs=*Pn_ref_dNt_dvbs;
    n_ref_dNt_dl=*Pn_ref_dNt_dl;
    n_ref_Nt=*Pn_ref_Nt;
    n_ref_Nf_unit=*Pn_ref_Nf_unit;
    n_ref_dNf_dvgs=*Pn_ref_dNf_dvgs;
    n_ref_dNf_dvds=*Pn_ref_dNf_dvds;
    n_ref_dNf_dvbs=*Pn_ref_dNf_dvbs;
    n_ref_dNf_dl=*Pn_ref_dNf_dl;
    n_ref_Nf=*Pn_ref_Nf;
    property_Nt=*Pproperty_Nt;
    property_Nf=*Pproperty_Nf;
    property_fc=*Pproperty_fc;
    property_TotalNoise=*Pproperty_TotalNoise;
    property_Area=*Pproperty_Area;
    property_Vos=*Pproperty_Vos;
    property_Power=*Pproperty_Power;
    config_factor_Adc=*Pconfig_factor_Adc;
    config_shift_Adc=*Pconfig_shift_Adc;
    config_factor_CMRR=*Pconfig_factor_CMRR;
    config_shift_CMRR=*Pconfig_shift_CMRR;
    config_factor_PSRR=*Pconfig_factor_PSRR;
    config_shift_PSRR=*Pconfig_shift_PSRR;
    config_factor_Rout=*Pconfig_factor_Rout;
    config_shift_Rout=*Pconfig_shift_Rout;
    config_factor_BW=*Pconfig_factor_BW;
    config_shift_BW=*Pconfig_shift_BW;
    config_factor_PM=*Pconfig_factor_PM;
    config_shift_PM=*Pconfig_shift_PM;
    config_factor_Cin=*Pconfig_factor_Cin;
    config_shift_Cin=*Pconfig_shift_Cin;
    property_Cin=*Pproperty_Cin;
    config_factor_ts=*Pconfig_factor_ts;
    config_shift_ts=*Pconfig_shift_ts;
    config_factor_Nt=*Pconfig_factor_Nt;
    config_shift_Nt=*Pconfig_shift_Nt;
    config_factor_Nf=*Pconfig_factor_Nf;
    config_shift_Nf=*Pconfig_shift_Nf;
    config_factor_TotalNoise=*Pconfig_factor_TotalNoise;
    config_shift_TotalNoise=*Pconfig_shift_TotalNoise;
    config_factor_fc=*Pconfig_factor_fc;
    config_shift_fc=*Pconfig_shift_fc;
    config_factor_Vos=*Pconfig_factor_Vos;
    config_shift_Vos=*Pconfig_shift_Vos;
    config_factor_Area=*Pconfig_factor_Area;
    config_shift_Area=*Pconfig_shift_Area;
    config_factor_Power=*Pconfig_factor_Power;
    config_shift_Power=*Pconfig_shift_Power;
    circuit_breed_id=*Pcircuit_breed_id;
    circuit_breed_target=*Pcircuit_breed_target;
    return TCL_OK;
}
static int tcl_gamma_export_cmd(ClientData clientData,Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    *Pconfig_pat_size_target=config_pat_size_target;
    *Psize_L=size_L;
    *Psize_L_min=size_L_min;
    *Psize_L_max=size_L_max;
    *Psize_W=size_W;
    *Psize_W_max=size_W_max;
    *Psize_Lp=size_Lp;
    *Psize_Lp_min=size_Lp_min;
    *Psize_Lp_max=size_Lp_max;
    *Psize_Wp=size_Wp;
    *Psize_Wp_max=size_Wp_max;
    *Psize_rin=size_rin;
    *Psize_rin_min=size_rin_min;
    *Psize_rin_max=size_rin_max;
    *Psize_L_step=size_L_step;
    *Psize_W_step=size_W_step;
    *Psize_Lp_step=size_Lp_step;
    *Psize_Wp_step=size_Wp_step;
    *Psize_rin_step=size_rin_step;
    *Pmax_Adc=max_Adc;
    *Pparam_unique=param_unique;
    *Ppat_size_target=pat_size_target;
    *Pmode_freash_op=mode_freash_op;
    *Pin_V=in_V;
    *Pparam_in=param_in;
    *Pout_V=out_V;
    *Pvdd_V=vdd_V;
    *Pmid_V=mid_V;
    *Pstatus_index=status_index;
    *Pconfig_size_L=config_size_L;
    *Pconfig_size_W=config_size_W;
    *Pconfig_size_Lp=config_size_Lp;
    *Pconfig_size_Wp=config_size_Wp;
    *Pconfig_size_rin=config_size_rin;
    *P0_V=CONST_0_V;
    *Pstatus_fail=status_fail;
    *Pdesign_feedback=design_feedback;
    *Pleak=leak;
    *Pconfig_op_iterations=config_op_iterations;
    *Pconfig_kcl_th=config_kcl_th;
    *Pconfig_design_feedback_th=config_design_feedback_th;
    *Pp_gm=p_gm;
    *Pp_go=p_go;
    *Pp_Ids=p_Ids;
    *Pn_ref_gm=n_ref_gm;
    *Pn_ref_go=n_ref_go;
    *Pn_ref_Ids=n_ref_Ids;
    *PGds_in_mid=Gds_in_mid;
    *Pconfig_kcl_step=config_kcl_step;
    *PDet=Det;
    *PTed=Ted;
    *Pproperty_Adc=property_Adc;
    *Pproperty_CMRR=property_CMRR;
    *Pproperty_PSRR=property_PSRR;
    *Pconfig_fail_on_properties=config_fail_on_properties;
    *Pproperty_Rout=property_Rout;
    *Pn_ref_cdg=n_ref_cdg;
    *Ps=s;
    *Pn_ref_cgg=n_ref_cgg;
    *Pn_ref_Ideq=n_ref_Ideq;
    *Pp_Ideq=p_Ideq;
    *Pp_cgs=p_cgs;
    *Pp_cgb=p_cgb;
    *Pp_cds=p_cds;
    *Pp_cdb=p_cdb;
    *Pn_ref_cds=n_ref_cds;
    *Pn_ref_cdb=n_ref_cdb;
    *Pparam_vdd=param_vdd;
    *Pn_ref_cgs=n_ref_cgs;
    *Pn_ref_cgb=n_ref_cgb;
    *Pp_cgd=p_cgd;
    *Pp_cgg=p_cgg;
    *Pp_cdd=p_cdd;
    *Pp_cdg=p_cdg;
    *Pn_ref_cdd=n_ref_cdd;
    *Pn_ref_cgd=n_ref_cgd;
    *Pconfig_cgg_factor=config_cgg_factor;
    *Pconfig_cgd_factor=config_cgd_factor;
    *Pconfig_cgs_factor=config_cgs_factor;
    *Pconfig_cgb_factor=config_cgb_factor;
    *Pconfig_cdd_factor=config_cdd_factor;
    *Pconfig_cdg_factor=config_cdg_factor;
    *Pconfig_cdb_factor=config_cdb_factor;
    *Pconfig_cds_factor=config_cds_factor;
    *Pp_csd=p_csd;
    *Pconfig_csd_factor=config_csd_factor;
    *Pp_csg=p_csg;
    *Pconfig_csg_factor=config_csg_factor;
    *Pp_css=p_css;
    *Pconfig_css_factor=config_css_factor;
    *Pp_csb=p_csb;
    *Pconfig_csb_factor=config_csb_factor;
    *Pp_cbd=p_cbd;
    *Pconfig_cbd_factor=config_cbd_factor;
    *Pp_cbg=p_cbg;
    *Pconfig_cbg_factor=config_cbg_factor;
    *Pp_cbs=p_cbs;
    *Pconfig_cbs_factor=config_cbs_factor;
    *Pp_cbb=p_cbb;
    *Pconfig_cbb_factor=config_cbb_factor;
    *Pn_ref_csd=n_ref_csd;
    *Pn_ref_csg=n_ref_csg;
    *Pn_ref_css=n_ref_css;
    *Pn_ref_csb=n_ref_csb;
    *Pn_ref_cbd=n_ref_cbd;
    *Pn_ref_cbg=n_ref_cbg;
    *Pn_ref_cbs=n_ref_cbs;
    *Pn_ref_cbb=n_ref_cbb;
    *Pproperty_BW=property_BW;
    *Pproperty_BW_s=property_BW_s;
    *Pp1=p1;
    *Pp2=p2;
    *Pproperty_ts=property_ts;
    *Pproperty_PM=property_PM;
    *Pp_Nt_unit=p_Nt_unit;
    *Pp_dNt_dvgs=p_dNt_dvgs;
    *Pp_dNt_dvds=p_dNt_dvds;
    *Pp_dNt_dvbs=p_dNt_dvbs;
    *Pp_dNt_dl=p_dNt_dl;
    *Pp_Nt=p_Nt;
    *Pp_Nf_unit=p_Nf_unit;
    *Pp_dNf_dvgs=p_dNf_dvgs;
    *Pp_dNf_dvds=p_dNf_dvds;
    *Pp_dNf_dvbs=p_dNf_dvbs;
    *Pp_dNf_dl=p_dNf_dl;
    *Pp_Nf=p_Nf;
    *Pn_ref_Nt_unit=n_ref_Nt_unit;
    *Pn_ref_dNt_dvgs=n_ref_dNt_dvgs;
    *Pn_ref_dNt_dvds=n_ref_dNt_dvds;
    *Pn_ref_dNt_dvbs=n_ref_dNt_dvbs;
    *Pn_ref_dNt_dl=n_ref_dNt_dl;
    *Pn_ref_Nt=n_ref_Nt;
    *Pn_ref_Nf_unit=n_ref_Nf_unit;
    *Pn_ref_dNf_dvgs=n_ref_dNf_dvgs;
    *Pn_ref_dNf_dvds=n_ref_dNf_dvds;
    *Pn_ref_dNf_dvbs=n_ref_dNf_dvbs;
    *Pn_ref_dNf_dl=n_ref_dNf_dl;
    *Pn_ref_Nf=n_ref_Nf;
    *Pproperty_Nt=property_Nt;
    *Pproperty_Nf=property_Nf;
    *Pproperty_fc=property_fc;
    *Pproperty_TotalNoise=property_TotalNoise;
    *Pproperty_Area=property_Area;
    *Pproperty_Vos=property_Vos;
    *Pproperty_Power=property_Power;
    *Pconfig_factor_Adc=config_factor_Adc;
    *Pconfig_shift_Adc=config_shift_Adc;
    *Pconfig_factor_CMRR=config_factor_CMRR;
    *Pconfig_shift_CMRR=config_shift_CMRR;
    *Pconfig_factor_PSRR=config_factor_PSRR;
    *Pconfig_shift_PSRR=config_shift_PSRR;
    *Pconfig_factor_Rout=config_factor_Rout;
    *Pconfig_shift_Rout=config_shift_Rout;
    *Pconfig_factor_BW=config_factor_BW;
    *Pconfig_shift_BW=config_shift_BW;
    *Pconfig_factor_PM=config_factor_PM;
    *Pconfig_shift_PM=config_shift_PM;
    *Pconfig_factor_Cin=config_factor_Cin;
    *Pconfig_shift_Cin=config_shift_Cin;
    *Pproperty_Cin=property_Cin;
    *Pconfig_factor_ts=config_factor_ts;
    *Pconfig_shift_ts=config_shift_ts;
    *Pconfig_factor_Nt=config_factor_Nt;
    *Pconfig_shift_Nt=config_shift_Nt;
    *Pconfig_factor_Nf=config_factor_Nf;
    *Pconfig_shift_Nf=config_shift_Nf;
    *Pconfig_factor_TotalNoise=config_factor_TotalNoise;
    *Pconfig_shift_TotalNoise=config_shift_TotalNoise;
    *Pconfig_factor_fc=config_factor_fc;
    *Pconfig_shift_fc=config_shift_fc;
    *Pconfig_factor_Vos=config_factor_Vos;
    *Pconfig_shift_Vos=config_shift_Vos;
    *Pconfig_factor_Area=config_factor_Area;
    *Pconfig_shift_Area=config_shift_Area;
    *Pconfig_factor_Power=config_factor_Power;
    *Pconfig_shift_Power=config_shift_Power;
    *Pcircuit_breed_id=circuit_breed_id;
    *Pcircuit_breed_target=circuit_breed_target;
    return TCL_OK;
}
static int tcl_gamma_op_cmd(ClientData clientData,Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    //            Tcl_ResetResult(interp);
    if (mode_freash_op) {
        in_V=param_in;
        out_V=vdd_V/2;
        mid_V=vdd_V/2;
    }
    status_index=0;
    if(config_size_L!=0) size_L=config_size_L;
    if(config_size_W!=0) size_W=config_size_W;
    if(config_size_Lp!=0) size_Lp=config_size_Lp;
    if(config_size_Wp!=0) size_Wp=config_size_Wp;
    if(config_size_rin!=0) size_rin=config_size_rin;
    vdd_V=1.1;
    CONST_0_V=0;
    // Calculating circuit operating point:
    int op_it=0;
    status_fail=-1;
    design_feedback=1000;
    leak=1e3;
    float node_step=0;
    for (op_it=0;(op_it<config_op_iterations)&&((leak>config_kcl_th)||(design_feedback>config_design_feedback_th));op_it++) {
        float previous_out_dc=out_V;
        composite_gamma_gcc_interpolate_4(Plook_up_tables_pch_Ids_ss_LUT,Plook_up_tables_pch_gm_ss_LUT,Plook_up_tables_pch_ro_ss_LUT,&(p_gm),&(p_go),&(p_Ids),(out_V)-(vdd_V),(out_V)-(vdd_V),(vdd_V)-(vdd_V),size_Lp,size_Wp);
        p_Ids=-p_Ids;
        composite_gamma_gcc_interpolate_4(Plook_up_tables_nch_Ids_ss_LUT,Plook_up_tables_nch_gm_ss_LUT,Plook_up_tables_nch_ro_ss_LUT,&(n_ref_gm),&(n_ref_go),&(n_ref_Ids),(mid_V)-(CONST_0_V),(out_V)-(CONST_0_V),(CONST_0_V)-(CONST_0_V),size_L,size_W);
        Gds_in_mid=1.0/size_rin;
        if (p_gm==0) p_gm=1e-6;
        if (p_go==0) p_go=1e-6;
        if (n_ref_gm==0) n_ref_gm=1e-6;
        if (n_ref_go==0) n_ref_go=1e-6;
        // Updating node voltages
        leak=0;
        node_step=config_kcl_step*(0)/(Gds_in_mid);
        if (node_step<-0.02) node_step=-0.02;
        if (node_step>0.02) node_step=0.02;
        in_V+=node_step;
        if (fabs(0)>leak) leak=fabs(0);
        if (in_V<0) in_V=0;
        if (in_V>1.1) in_V=1.1;
        node_step=config_kcl_step*(0)/(Gds_in_mid);
        if (node_step<-0.02) node_step=-0.02;
        if (node_step>0.02) node_step=0.02;
        mid_V+=node_step;
        if (fabs(0)>leak) leak=fabs(0);
        if (mid_V<0) mid_V=0;
        if (mid_V>1.1) mid_V=1.1;
        node_step=config_kcl_step*(-n_ref_Ids-p_Ids)/(p_go+n_ref_go);
        if (node_step<-0.02) node_step=-0.02;
        if (node_step>0.02) node_step=0.02;
        out_V+=node_step;
        if (fabs(-n_ref_Ids-p_Ids)>leak) leak=fabs(-n_ref_Ids-p_Ids);
        if (out_V<0) out_V=0;
        if (out_V>1.1) out_V=1.1;
        design_feedback=0;
    }
    if (op_it>=config_op_iterations) {status_fail=leak; return TCL_ERROR;}
    if (vdd_V<out_V) {status_fail=4; return TCL_ERROR;}
    if (CONST_0_V>out_V) {status_fail=3; return TCL_ERROR;}
    Det=(-(-Gds_in_mid*(-((p_go+p_gm)+n_ref_go))));
    Ted=1/Det;
    property_Adc=Ted*((-(-Gds_in_mid)*n_ref_gm));
    property_CMRR=property_Adc;
    property_PSRR=Ted*((-(-Gds_in_mid*((-p_go)-p_gm))));
    property_Adc=fabs(property_Adc);
    if ((property_Adc<1)&&(config_fail_on_properties)) {status_fail=2; return TCL_ERROR;}
    property_Rout=fabs(((-(-Gds_in_mid)))*Ted);
    //AC output: (-(((-Gds_in_mid)*(n_ref_gm+n_ref_cdg*s)*(-param_in)-(Gds_in_mid+n_ref_cgg*s)*((-((-n_ref_Ideq)-p_Ideq))+((((((((-p_go)-p_gm)+p_cgs*s)+p_cgb*s)+p_cds*s)+p_cdb*s)+n_ref_cds*s)+n_ref_cdb*s)*(-param_vdd)))-(n_ref_cgs*s+n_ref_cgb*s)*(-(n_ref_gm+n_ref_cdg*s)*(-param_vdd))))/(-((-(Gds_in_mid+n_ref_cgg*s)*(-(((((((p_go+p_gm)+p_cgd*s)+p_cgg*s)+p_cdd*s)+p_cdg*s)+n_ref_go)+n_ref_cdd*s)))+n_ref_cgd*s*(-(n_ref_gm+n_ref_cdg*s))))
    //AC gain: (-(-Gds_in_mid)*(n_ref_gm+n_ref_cdg*s))/(-((-(Gds_in_mid+n_ref_cgg*s)*(-(((((((p_go+p_gm)+p_cgd*s)+p_cgg*s)+p_cdd*s)+p_cdg*s)+n_ref_go)+n_ref_cdd*s)))+n_ref_cgd*s*(-(n_ref_gm+n_ref_cdg*s))))
    p_cgg=gamma_gcc_interpolate_4(Plook_up_tables_pch_cgg_ss_LUT,(out_V)-(vdd_V),(out_V)-(vdd_V),(vdd_V)-(vdd_V),size_Lp)*size_Lp*size_Wp*config_cgg_factor;
    p_cgd=gamma_gcc_interpolate_4(Plook_up_tables_pch_cgd_ss_LUT,(out_V)-(vdd_V),(out_V)-(vdd_V),(vdd_V)-(vdd_V),size_Lp)*size_Lp*size_Wp*config_cgd_factor;
    p_cgs=gamma_gcc_interpolate_4(Plook_up_tables_pch_cgs_ss_LUT,(out_V)-(vdd_V),(out_V)-(vdd_V),(vdd_V)-(vdd_V),size_Lp)*size_Lp*size_Wp*config_cgs_factor;
    p_cgb=gamma_gcc_interpolate_4(Plook_up_tables_pch_cgb_ss_LUT,(out_V)-(vdd_V),(out_V)-(vdd_V),(vdd_V)-(vdd_V),size_Lp)*size_Lp*size_Wp*config_cgb_factor;
    p_cdd=gamma_gcc_interpolate_4(Plook_up_tables_pch_cdd_ss_LUT,(out_V)-(vdd_V),(out_V)-(vdd_V),(vdd_V)-(vdd_V),size_Lp)*size_Lp*size_Wp*config_cdd_factor;
    p_cdg=gamma_gcc_interpolate_4(Plook_up_tables_pch_cdg_ss_LUT,(out_V)-(vdd_V),(out_V)-(vdd_V),(vdd_V)-(vdd_V),size_Lp)*size_Lp*size_Wp*config_cdg_factor;
    p_cdb=gamma_gcc_interpolate_4(Plook_up_tables_pch_cdb_ss_LUT,(out_V)-(vdd_V),(out_V)-(vdd_V),(vdd_V)-(vdd_V),size_Lp)*size_Lp*size_Wp*config_cdb_factor;
    p_cds=gamma_gcc_interpolate_4(Plook_up_tables_pch_cds_ss_LUT,(out_V)-(vdd_V),(out_V)-(vdd_V),(vdd_V)-(vdd_V),size_Lp)*size_Lp*size_Wp*config_cds_factor;
    p_csd=gamma_gcc_interpolate_4(Plook_up_tables_pch_csd_ss_LUT,(out_V)-(vdd_V),(out_V)-(vdd_V),(vdd_V)-(vdd_V),size_Lp)*size_Lp*size_Wp*config_csd_factor;
    p_csg=gamma_gcc_interpolate_4(Plook_up_tables_pch_csg_ss_LUT,(out_V)-(vdd_V),(out_V)-(vdd_V),(vdd_V)-(vdd_V),size_Lp)*size_Lp*size_Wp*config_csg_factor;
    p_css=gamma_gcc_interpolate_4(Plook_up_tables_pch_css_ss_LUT,(out_V)-(vdd_V),(out_V)-(vdd_V),(vdd_V)-(vdd_V),size_Lp)*size_Lp*size_Wp*config_css_factor;
    p_csb=gamma_gcc_interpolate_4(Plook_up_tables_pch_csb_ss_LUT,(out_V)-(vdd_V),(out_V)-(vdd_V),(vdd_V)-(vdd_V),size_Lp)*size_Lp*size_Wp*config_csb_factor;
    p_cbd=gamma_gcc_interpolate_4(Plook_up_tables_pch_cbd_ss_LUT,(out_V)-(vdd_V),(out_V)-(vdd_V),(vdd_V)-(vdd_V),size_Lp)*size_Lp*size_Wp*config_cbd_factor;
    p_cbg=gamma_gcc_interpolate_4(Plook_up_tables_pch_cbg_ss_LUT,(out_V)-(vdd_V),(out_V)-(vdd_V),(vdd_V)-(vdd_V),size_Lp)*size_Lp*size_Wp*config_cbg_factor;
    p_cbs=gamma_gcc_interpolate_4(Plook_up_tables_pch_cbs_ss_LUT,(out_V)-(vdd_V),(out_V)-(vdd_V),(vdd_V)-(vdd_V),size_Lp)*size_Lp*size_Wp*config_cbs_factor;
    p_cbb=gamma_gcc_interpolate_4(Plook_up_tables_pch_cbb_ss_LUT,(out_V)-(vdd_V),(out_V)-(vdd_V),(vdd_V)-(vdd_V),size_Lp)*size_Lp*size_Wp*config_cbb_factor;
    n_ref_cgg=gamma_gcc_interpolate_4(Plook_up_tables_nch_cgg_ss_LUT,(mid_V)-(CONST_0_V),(out_V)-(CONST_0_V),(CONST_0_V)-(CONST_0_V),size_L)*size_L*size_W*config_cgg_factor;
    n_ref_cgd=gamma_gcc_interpolate_4(Plook_up_tables_nch_cgd_ss_LUT,(mid_V)-(CONST_0_V),(out_V)-(CONST_0_V),(CONST_0_V)-(CONST_0_V),size_L)*size_L*size_W*config_cgd_factor;
    n_ref_cgs=gamma_gcc_interpolate_4(Plook_up_tables_nch_cgs_ss_LUT,(mid_V)-(CONST_0_V),(out_V)-(CONST_0_V),(CONST_0_V)-(CONST_0_V),size_L)*size_L*size_W*config_cgs_factor;
    n_ref_cgb=gamma_gcc_interpolate_4(Plook_up_tables_nch_cgb_ss_LUT,(mid_V)-(CONST_0_V),(out_V)-(CONST_0_V),(CONST_0_V)-(CONST_0_V),size_L)*size_L*size_W*config_cgb_factor;
    n_ref_cdd=gamma_gcc_interpolate_4(Plook_up_tables_nch_cdd_ss_LUT,(mid_V)-(CONST_0_V),(out_V)-(CONST_0_V),(CONST_0_V)-(CONST_0_V),size_L)*size_L*size_W*config_cdd_factor;
    n_ref_cdg=gamma_gcc_interpolate_4(Plook_up_tables_nch_cdg_ss_LUT,(mid_V)-(CONST_0_V),(out_V)-(CONST_0_V),(CONST_0_V)-(CONST_0_V),size_L)*size_L*size_W*config_cdg_factor;
    n_ref_cdb=gamma_gcc_interpolate_4(Plook_up_tables_nch_cdb_ss_LUT,(mid_V)-(CONST_0_V),(out_V)-(CONST_0_V),(CONST_0_V)-(CONST_0_V),size_L)*size_L*size_W*config_cdb_factor;
    n_ref_cds=gamma_gcc_interpolate_4(Plook_up_tables_nch_cds_ss_LUT,(mid_V)-(CONST_0_V),(out_V)-(CONST_0_V),(CONST_0_V)-(CONST_0_V),size_L)*size_L*size_W*config_cds_factor;
    n_ref_csd=gamma_gcc_interpolate_4(Plook_up_tables_nch_csd_ss_LUT,(mid_V)-(CONST_0_V),(out_V)-(CONST_0_V),(CONST_0_V)-(CONST_0_V),size_L)*size_L*size_W*config_csd_factor;
    n_ref_csg=gamma_gcc_interpolate_4(Plook_up_tables_nch_csg_ss_LUT,(mid_V)-(CONST_0_V),(out_V)-(CONST_0_V),(CONST_0_V)-(CONST_0_V),size_L)*size_L*size_W*config_csg_factor;
    n_ref_css=gamma_gcc_interpolate_4(Plook_up_tables_nch_css_ss_LUT,(mid_V)-(CONST_0_V),(out_V)-(CONST_0_V),(CONST_0_V)-(CONST_0_V),size_L)*size_L*size_W*config_css_factor;
    n_ref_csb=gamma_gcc_interpolate_4(Plook_up_tables_nch_csb_ss_LUT,(mid_V)-(CONST_0_V),(out_V)-(CONST_0_V),(CONST_0_V)-(CONST_0_V),size_L)*size_L*size_W*config_csb_factor;
    n_ref_cbd=gamma_gcc_interpolate_4(Plook_up_tables_nch_cbd_ss_LUT,(mid_V)-(CONST_0_V),(out_V)-(CONST_0_V),(CONST_0_V)-(CONST_0_V),size_L)*size_L*size_W*config_cbd_factor;
    n_ref_cbg=gamma_gcc_interpolate_4(Plook_up_tables_nch_cbg_ss_LUT,(mid_V)-(CONST_0_V),(out_V)-(CONST_0_V),(CONST_0_V)-(CONST_0_V),size_L)*size_L*size_W*config_cbg_factor;
    n_ref_cbs=gamma_gcc_interpolate_4(Plook_up_tables_nch_cbs_ss_LUT,(mid_V)-(CONST_0_V),(out_V)-(CONST_0_V),(CONST_0_V)-(CONST_0_V),size_L)*size_L*size_W*config_cbs_factor;
    n_ref_cbb=gamma_gcc_interpolate_4(Plook_up_tables_nch_cbb_ss_LUT,(mid_V)-(CONST_0_V),(out_V)-(CONST_0_V),(CONST_0_V)-(CONST_0_V),size_L)*size_L*size_W*config_cbb_factor;
    s=-1;
    int BW_it;
    float W=0;
    float BW_Mag0=1;
    float BW_Mag=1;
    float snr;
    float sni;
    float sdr;
    float sdi;
    while ((BW_Mag0/BW_Mag)<2) {
        snr=-((-Gds_in_mid)*n_ref_gm);
        sni=-((-Gds_in_mid)*n_ref_cdg*W);
        sdr=-(-(Gds_in_mid*(-(p_go+p_gm+n_ref_go))-n_ref_cgg*W*(-(p_cgd*W+p_cgg*W+p_cdd*W+p_cdg*W+n_ref_cdd*W)))-(n_ref_cgd*W*(-n_ref_cdg*W)));
        sdi=-(-(Gds_in_mid*(-(p_cgd*W+p_cgg*W+p_cdd*W+p_cdg*W+n_ref_cdd*W))+n_ref_cgg*W*(-(p_go+p_gm+n_ref_go)))+n_ref_cgd*W*(-n_ref_gm));
        BW_Mag=(snr*snr+sni*sni)/(sdr*sdr+sdi*sdi);
        if (W==0) BW_Mag0=BW_Mag;
        if (W==0) W=1; else W*=1.1;
    }
    property_BW=fabs(W/(2*3.141592656)/1.01);
    for (BW_it=0;BW_it<5;BW_it++)  s-=((-((-(Gds_in_mid+n_ref_cgg*s)*(-(((((((p_go+p_gm)+p_cgd*s)+p_cgg*s)+p_cdd*s)+p_cdg*s)+n_ref_go)+n_ref_cdd*s)))+n_ref_cgd*s*(-(n_ref_gm+n_ref_cdg*s)))))/((-((-(n_ref_cgg*(-(((((((p_go+p_gm)+p_cgd*s)+p_cgg*s)+p_cdd*s)+p_cdg*s)+n_ref_go)+n_ref_cdd*s))+(Gds_in_mid+n_ref_cgg*s)*(-((((p_cgd+p_cgg)+p_cdd)+p_cdg)+n_ref_cdd))))+(n_ref_cgd*(-(n_ref_gm+n_ref_cdg*s))+n_ref_cgd*s*(-n_ref_cdg)))));
    property_BW_s=(-((-(n_ref_cgg*(-(((((((p_go+p_gm)+p_cgd*s)+p_cgg*s)+p_cdd*s)+p_cdg*s)+n_ref_go)+n_ref_cdd*s))+(Gds_in_mid+n_ref_cgg*s)*(-((((p_cgd+p_cgg)+p_cdd)+p_cdg)+n_ref_cdd))))+(n_ref_cgd*(-(n_ref_gm+n_ref_cdg*s))+n_ref_cgd*s*(-n_ref_cdg))));
    p1=-s;
    if (!isfinite(property_BW))  {status_fail=8; return TCL_ERROR;}
    s-=1e3;
    for (BW_it=0;BW_it<20;BW_it++)  s-=(((-((-(Gds_in_mid+n_ref_cgg*s)*(-(((((((p_go+p_gm)+p_cgd*s)+p_cgg*s)+p_cdd*s)+p_cdg*s)+n_ref_go)+n_ref_cdd*s)))+n_ref_cgd*s*(-(n_ref_gm+n_ref_cdg*s)))))*(s+p1-5e2))/(((-((-(n_ref_cgg*(-(((((((p_go+p_gm)+p_cgd*s)+p_cgg*s)+p_cdd*s)+p_cdg*s)+n_ref_go)+n_ref_cdd*s))+(Gds_in_mid+n_ref_cgg*s)*(-((((p_cgd+p_cgg)+p_cdd)+p_cdg)+n_ref_cdd))))+(n_ref_cgd*(-(n_ref_gm+n_ref_cdg*s))+n_ref_cgd*s*(-n_ref_cdg)))))*(s+p1-5e2)-((-((-(Gds_in_mid+n_ref_cgg*s)*(-(((((((p_go+p_gm)+p_cgd*s)+p_cgg*s)+p_cdd*s)+p_cdg*s)+n_ref_go)+n_ref_cdd*s)))+n_ref_cgd*s*(-(n_ref_gm+n_ref_cdg*s))))));
    p2=-s;
    if (!isfinite(p1)) {
        property_ts=1/property_BW;
    } else if (!isfinite(p2)) {
        property_ts=-log(0.02)/p1;
    } else {
        float A1=-p2/(-p1+p2);
        float A2=-p1/(-p1+p2);
        property_ts=0;
        for (BW_it=0;BW_it<10;BW_it++) property_ts-=(0.02+A1*exp(-p1*property_ts)+A2*exp(-p2*property_ts))/(-p1*A1*exp(-p1*property_ts)-p2*A2*exp(-p2*property_ts));
    }
    if (!isfinite(property_ts)) {
        property_ts=1/property_BW;
    }
    while (BW_Mag>4) {
        snr=-((-Gds_in_mid)*n_ref_gm);
        sni=-((-Gds_in_mid)*n_ref_cdg*W);
        sdr=-(-(Gds_in_mid*(-(p_go+p_gm+n_ref_go))-n_ref_cgg*W*(-(p_cgd*W+p_cgg*W+p_cdd*W+p_cdg*W+n_ref_cdd*W)))-(n_ref_cgd*W*(-n_ref_cdg*W)));
        sdi=-(-(Gds_in_mid*(-(p_cgd*W+p_cgg*W+p_cdd*W+p_cdg*W+n_ref_cdd*W))+n_ref_cgg*W*(-(p_go+p_gm+n_ref_go)))+n_ref_cgd*W*(-n_ref_gm));
        BW_Mag=(snr*snr+sni*sni)/(sdr*sdr+sdi*sdi);
        W*=1.01;
    }
    property_PM=180-180*(atan(sni/snr)-atan(sdi/sdr))/3.1415926;
    p_Nt_unit=gamma_gcc_interpolateg_4(P_look_up_tables_pch_thermal_noise_ss_LUT,(out_V-vdd_V),(out_V-vdd_V),0,size_Lp,&p_dNt_dvgs,&p_dNt_dvds,&p_dNt_dvbs,&p_dNt_dl);
    p_Nt=p_Nt_unit*p_go;
    if (!isfinite(p_Nt))  {status_fail=5; return TCL_ERROR;}
    p_Nf_unit=gamma_gcc_interpolateg_4(P_look_up_tables_pch_flicker_noise_ss_LUT,(out_V-vdd_V),(out_V-vdd_V),0,size_Lp,&p_dNf_dvgs,&p_dNf_dvds,&p_dNf_dvbs,&p_dNf_dl);
    p_Nf=p_Nf_unit*p_go*p_go/(size_Wp*size_Lp);
    if (!isfinite(p_Nf))  {status_fail=6; return TCL_ERROR;}
    n_ref_Nt_unit=gamma_gcc_interpolateg_4(P_look_up_tables_nch_thermal_noise_ss_LUT,mid_V,out_V,CONST_0_V,size_L,&n_ref_dNt_dvgs,&n_ref_dNt_dvds,&n_ref_dNt_dvbs,&n_ref_dNt_dl);
    n_ref_Nt=n_ref_Nt_unit*n_ref_go;
    if (!isfinite(n_ref_Nt))  {status_fail=5; return TCL_ERROR;}
    n_ref_Nf_unit=gamma_gcc_interpolateg_4(P_look_up_tables_nch_flicker_noise_ss_LUT,mid_V,out_V,CONST_0_V,size_L,&n_ref_dNf_dvgs,&n_ref_dNf_dvds,&n_ref_dNf_dvbs,&n_ref_dNf_dl);
    n_ref_Nf=n_ref_Nf_unit*n_ref_go*n_ref_go/(size_W*size_L);
    if (!isfinite(n_ref_Nf))  {status_fail=6; return TCL_ERROR;}
    float current_transfer_p=Ted*((-(-Gds_in_mid)))/property_Adc;
    float current_transfer_n_ref=Ted*((-(-Gds_in_mid)))/property_Adc;
    property_Nt=(current_transfer_p*current_transfer_p*p_Nt+current_transfer_n_ref*current_transfer_n_ref*n_ref_Nt)/property_Adc;
    property_Nf=(current_transfer_p*current_transfer_p*p_Nf+current_transfer_n_ref*current_transfer_n_ref*n_ref_Nf)/property_Adc;
    property_fc=property_Nf/property_Nt;
    property_TotalNoise=(log(2*property_BW)*property_Nf+2*property_BW*property_Nt);
    property_Area=1e12*(size_Wp*size_Lp+size_W*size_L);
    float single_transistor_vos;
    property_Vos=0;
    property_Vos=1e-3*sqrt(property_Vos);
    property_Power=0;
    property_Power+=fabs(p_Ids*((out_V)-(vdd_V)));
    property_Power+=fabs(n_ref_Ids*((out_V)-(CONST_0_V)));
    property_Adc=20*log10(fabs(property_Adc));
    property_CMRR=20*log10(fabs(property_CMRR));
    property_CMRR=property_Adc-property_CMRR;
    property_PSRR=20*log10(fabs(property_PSRR));
    property_PSRR=property_Adc-property_PSRR;
    if (max_Adc<property_Adc) max_Adc=property_Adc;
    PAT *p=(PAT *)Poutput_nmos_circuits_PAT;
    float sizes[7];
    sizes[0]=size_L;
    sizes[1]=size_W;
    sizes[2]=size_Lp;
    sizes[3]=size_Wp;
    sizes[4]=size_rin;
    sizes[5]=out_V;
    sizes[6]=mid_V;
    float properties[15];
    if ((config_factor_Adc!=0)||(config_shift_Adc!=0)) property_Adc=property_Adc*config_factor_Adc+config_shift_Adc;
    properties[0]=property_Adc;
    if ((config_factor_CMRR!=0)||(config_shift_CMRR!=0)) property_CMRR=property_CMRR*config_factor_CMRR+config_shift_CMRR;
    properties[1]=property_CMRR;
    if ((config_factor_PSRR!=0)||(config_shift_PSRR!=0)) property_PSRR=property_PSRR*config_factor_PSRR+config_shift_PSRR;
    properties[2]=property_PSRR;
    if ((config_factor_Rout!=0)||(config_shift_Rout!=0)) property_Rout=property_Rout*config_factor_Rout+config_shift_Rout;
    properties[3]=property_Rout;
    if ((config_factor_BW!=0)||(config_shift_BW!=0)) property_BW=property_BW*config_factor_BW+config_shift_BW;
    properties[4]=property_BW;
    if ((config_factor_PM!=0)||(config_shift_PM!=0)) property_PM=property_PM*config_factor_PM+config_shift_PM;
    properties[5]=property_PM;
    if ((config_factor_Cin!=0)||(config_shift_Cin!=0)) property_Cin=property_Cin*config_factor_Cin+config_shift_Cin;
    properties[6]=property_Cin;
    if ((config_factor_ts!=0)||(config_shift_ts!=0)) property_ts=property_ts*config_factor_ts+config_shift_ts;
    properties[7]=property_ts;
    if ((config_factor_Nt!=0)||(config_shift_Nt!=0)) property_Nt=property_Nt*config_factor_Nt+config_shift_Nt;
    properties[8]=property_Nt;
    if ((config_factor_Nf!=0)||(config_shift_Nf!=0)) property_Nf=property_Nf*config_factor_Nf+config_shift_Nf;
    properties[9]=property_Nf;
    if ((config_factor_TotalNoise!=0)||(config_shift_TotalNoise!=0)) property_TotalNoise=property_TotalNoise*config_factor_TotalNoise+config_shift_TotalNoise;
    properties[10]=property_TotalNoise;
    if ((config_factor_fc!=0)||(config_shift_fc!=0)) property_fc=property_fc*config_factor_fc+config_shift_fc;
    properties[11]=property_fc;
    if ((config_factor_Vos!=0)||(config_shift_Vos!=0)) property_Vos=property_Vos*config_factor_Vos+config_shift_Vos;
    properties[12]=property_Vos;
    if ((config_factor_Area!=0)||(config_shift_Area!=0)) property_Area=property_Area*config_factor_Area+config_shift_Area;
    properties[13]=property_Area;
    if ((config_factor_Power!=0)||(config_shift_Power!=0)) property_Power=property_Power*config_factor_Power+config_shift_Power;
    properties[14]=property_Power;
    status_fail=op_it;
    status_index=add_pat_array(p,sizes,properties);
    return TCL_OK;
}
//      static int tcl_gamma_grad_cmd(ClientData clientData,Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    //            Tcl_ResetResult(interp);
    //          GRAD_CODE_GOES_HERE
    //         return TCL_OK;
//    }
static int tcl_gamma_random_cmd(ClientData clientData,Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    ClientData CD;
    PAT *p=(PAT *)Poutput_nmos_circuits_PAT;
    while (p->content->num_of<config_pat_size_target) {
        size_L=size_L_min+random()*(size_L_max-size_L_min)/RAND_MAX;
        size_W=size_L+random()*(size_W_max-size_L)/RAND_MAX;
        size_Lp=size_Lp_min+random()*(size_Lp_max-size_Lp_min)/RAND_MAX;
        size_Wp=size_L+random()*(size_Wp_max-size_L)/RAND_MAX;
        size_rin=size_rin_min+random()*(size_rin_max-size_rin_min)/RAND_MAX;
        if (tcl_gamma_op_cmd(CD,NULL,0,NULL)==TCL_ERROR) continue;
    }
    return TCL_OK;
}
static int tcl_gamma_breed_cmd(ClientData clientData,Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    ClientData CD;
    int i,viable;
    PAT *p=(PAT *)Poutput_nmos_circuits_PAT;
    int more_to_breed=1;
    while (more_to_breed&&(p->content->num_of<pat_size_target)) {
        more_to_breed=0;
        int sweep_size=p->content->num_of;
        for (i=0;i<sweep_size;i++) {
            if (p->content->content[i]->flags) continue;
            p->content->content[i]->flags=1;
            more_to_breed++;
            size_L=p->content->content[i]->sizes->content[0];
            size_W=p->content->content[i]->sizes->content[1];
            size_Lp=p->content->content[i]->sizes->content[2];
            size_Wp=p->content->content[i]->sizes->content[3];
            size_rin=p->content->content[i]->sizes->content[4];
            size_L=size_L+size_L_step;
            viable=1;
            if ((size_L>=size_L_min)&&(size_L<=size_L_max)) {
                tcl_gamma_op_cmd(CD,NULL,0,NULL);
            }
            size_L=size_L-2*size_L_step;
            viable=1;
            if ((size_L>=size_L_min)&&(size_L<=size_L_max)) {
                tcl_gamma_op_cmd(CD,NULL,0,NULL);
            }
            size_L=size_L+size_L_step;
            size_W=size_W+size_W_step;
            viable=1;
            if ((size_W>=size_L)&&(size_W<=size_W_max)) {
                tcl_gamma_op_cmd(CD,NULL,0,NULL);
            }
            size_W=size_W-2*size_W_step;
            viable=1;
            if ((size_W>=size_L)&&(size_W<=size_W_max)) {
                tcl_gamma_op_cmd(CD,NULL,0,NULL);
            }
            size_W=size_W+size_W_step;
            size_Lp=size_Lp+size_Lp_step;
            viable=1;
            if ((size_Lp>=size_Lp_min)&&(size_Lp<=size_Lp_max)) {
                tcl_gamma_op_cmd(CD,NULL,0,NULL);
            }
            size_Lp=size_Lp-2*size_Lp_step;
            viable=1;
            if ((size_Lp>=size_Lp_min)&&(size_Lp<=size_Lp_max)) {
                tcl_gamma_op_cmd(CD,NULL,0,NULL);
            }
            size_Lp=size_Lp+size_Lp_step;
            size_Wp=size_Wp+size_Wp_step;
            viable=1;
            if ((size_Wp>=size_L)&&(size_Wp<=size_Wp_max)) {
                tcl_gamma_op_cmd(CD,NULL,0,NULL);
            }
            size_Wp=size_Wp-2*size_Wp_step;
            viable=1;
            if ((size_Wp>=size_L)&&(size_Wp<=size_Wp_max)) {
                tcl_gamma_op_cmd(CD,NULL,0,NULL);
            }
            size_Wp=size_Wp+size_Wp_step;
            size_rin=size_rin+size_rin_step;
            viable=1;
            if ((size_rin>=size_rin_min)&&(size_rin<=size_rin_max)) {
                tcl_gamma_op_cmd(CD,NULL,0,NULL);
            }
            size_rin=size_rin-2*size_rin_step;
            viable=1;
            if ((size_rin>=size_rin_min)&&(size_rin<=size_rin_max)) {
                tcl_gamma_op_cmd(CD,NULL,0,NULL);
            }
            size_rin=size_rin+size_rin_step;
            if (p->content->num_of%100==0) {
                printf("               %ld/%g=%g%%\n",p->content->num_of,pat_size_target,100*p->content->num_of/pat_size_target);
                fflush(stdout);
                if (param_unique>0) {
                    pat_unique(p,param_unique);
                }
            }
        }
        printf("   Done %ld/%g=%g%% (%ld visited)\n",p->content->num_of,pat_size_target,100*p->content->num_of/pat_size_target,more_to_breed);
    }
    return TCL_OK;
}
static int tcl_gamma_random_breed_cmd(ClientData clientData,Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    ClientData CD;
    int i,j;
    PAT *p=(PAT *)Poutput_nmos_circuits_PAT;
    long int r;
    float step;
    while (1) {
        if (p->content->num_of>config_pat_size_target) break;
        int sweep_size=p->content->num_of;
        for (i=0;i<sweep_size;i++) {
            size_L=p->content->content[i]->sizes->content[0];
            size_W=p->content->content[i]->sizes->content[1];
            size_Lp=p->content->content[i]->sizes->content[2];
            size_Wp=p->content->content[i]->sizes->content[3];
            size_rin=p->content->content[i]->sizes->content[4];
            while (1) {
                step=(2.0*random()/RAND_MAX-1)*size_L_step;
                if (size_L+step<size_L_min) continue;
                if (size_L+step>size_L_max) continue;
                break;
            }
            size_L+=step;
            while (1) {
                step=(2.0*random()/RAND_MAX-1)*size_W_step;
                if (size_W+step<size_L) continue;
                if (size_W+step>size_W_max) continue;
                break;
            }
            size_W+=step;
            while (1) {
                step=(2.0*random()/RAND_MAX-1)*size_Lp_step;
                if (size_Lp+step<size_Lp_min) continue;
                if (size_Lp+step>size_Lp_max) continue;
                break;
            }
            size_Lp+=step;
            while (1) {
                step=(2.0*random()/RAND_MAX-1)*size_Wp_step;
                if (size_Wp+step<size_L) continue;
                if (size_Wp+step>size_Wp_max) continue;
                break;
            }
            size_Wp+=step;
            while (1) {
                step=(2.0*random()/RAND_MAX-1)*size_rin_step;
                if (size_rin+step<size_rin_min) continue;
                if (size_rin+step>size_rin_max) continue;
                break;
            }
            size_rin+=step;
            int pre_volume=p->content->num_of;
            if (tcl_gamma_op_cmd(CD,NULL,0,NULL)==TCL_ERROR) {i--; continue;}
            if (pre_volume==p->content->num_of) {i--; continue;}
            if (p->content->num_of%1000==0) {
                printf("               %ld/%g=%g%% max gain=%g\n",p->content->num_of,config_pat_size_target,100*p->content->num_of/config_pat_size_target,max_Adc);
                printf("               %ld/%g=%g%%\n",p->content->num_of,config_pat_size_target,100*p->content->num_of/config_pat_size_target);
                fflush(stdout);
                if (param_unique>0) {
                    pat_unique(p,param_unique);
                    printf("               post unique: %ld/%g=%g%%\n",p->content->num_of,config_pat_size_target,100*p->content->num_of/config_pat_size_target);
                    if (p->content->num_of>0.92*config_pat_size_target) break;
                }
            }
            if (p->content->num_of>config_pat_size_target) break;
        }
        if (p->content->num_of>config_pat_size_target) break;
    }
    return TCL_OK;
}
static int tcl_gamma_random_breed_single_cmd(ClientData clientData,Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    ClientData CD;
    int i;
    PAT *p=(PAT *)Poutput_nmos_circuits_PAT;
    int more_to_breed=0;
    long int r;
    long int breed_count=p->content->num_of;
    long int watchdog=0;
    float step;
    int sweep_size=p->content->num_of;
    int searched_id=(int)circuit_breed_id;
    for (i=0;i<p->content->num_of;i++) {
        if (p->content->content[i]->id==searched_id) break;
    }
    printf("Found circuit id %d at index %d\n",searched_id,i);
    while (watchdog++<10000) {
        size_L=p->content->content[i]->sizes->content[0];
        size_W=p->content->content[i]->sizes->content[1];
        size_Lp=p->content->content[i]->sizes->content[2];
        size_Wp=p->content->content[i]->sizes->content[3];
        size_rin=p->content->content[i]->sizes->content[4];
        while (1) {
            step=(2.0*random()/RAND_MAX-1)*size_L_step;
            if (size_L+step<size_L_min) continue;
            if (size_L+step>size_L_max) continue;
            break;
        }
        size_L+=step;
        while (1) {
            step=(2.0*random()/RAND_MAX-1)*size_W_step;
            if (size_W+step<size_L) continue;
            if (size_W+step>size_W_max) continue;
            break;
        }
        size_W+=step;
        while (1) {
            step=(2.0*random()/RAND_MAX-1)*size_Lp_step;
            if (size_Lp+step<size_Lp_min) continue;
            if (size_Lp+step>size_Lp_max) continue;
            break;
        }
        size_Lp+=step;
        while (1) {
            step=(2.0*random()/RAND_MAX-1)*size_Wp_step;
            if (size_Wp+step<size_L) continue;
            if (size_Wp+step>size_Wp_max) continue;
            break;
        }
        size_Wp+=step;
        while (1) {
            step=(2.0*random()/RAND_MAX-1)*size_rin_step;
            if (size_rin+step<size_rin_min) continue;
            if (size_rin+step>size_rin_max) continue;
            break;
        }
        size_rin+=step;
        if (tcl_gamma_op_cmd(CD,NULL,0,NULL)==TCL_ERROR) continue;
        if (p->content->num_of>=breed_count+circuit_breed_target) break;
    }
    return TCL_OK;
}
// Initializing cTree references and registering the tcl_gamma_op_cmd command as ::C::output_nmos
int Gamma_Init(Tcl_Interp *interp) {
    if (Tcl_InitStubs(interp, TCL_VERSION, 0) == NULL) {
        return TCL_ERROR;
    }
    float *array_entry;
    context *c;
    Poutput_nmos_circuits_PAT=(float *)get_PAT("output_nmos:circuits");
    c=create_context("config:pat_size_target");
    Pconfig_pat_size_target=(float *)(&c->value.s);
    c=create_context("size:L");
    Psize_L=(float *)(&c->value.s);
    c=create_context("size:L:min");
    Psize_L_min=(float *)(&c->value.s);
    c=create_context("size:L:max");
    Psize_L_max=(float *)(&c->value.s);
    c=create_context("size:W");
    Psize_W=(float *)(&c->value.s);
    c=create_context("size:W:max");
    Psize_W_max=(float *)(&c->value.s);
    c=create_context("size:Lp");
    Psize_Lp=(float *)(&c->value.s);
    c=create_context("size:Lp:min");
    Psize_Lp_min=(float *)(&c->value.s);
    c=create_context("size:Lp:max");
    Psize_Lp_max=(float *)(&c->value.s);
    c=create_context("size:Wp");
    Psize_Wp=(float *)(&c->value.s);
    c=create_context("size:Wp:max");
    Psize_Wp_max=(float *)(&c->value.s);
    c=create_context("size:rin");
    Psize_rin=(float *)(&c->value.s);
    c=create_context("size:rin:min");
    Psize_rin_min=(float *)(&c->value.s);
    c=create_context("size:rin:max");
    Psize_rin_max=(float *)(&c->value.s);
    c=create_context("size:L:step");
    Psize_L_step=(float *)(&c->value.s);
    c=create_context("size:W:step");
    Psize_W_step=(float *)(&c->value.s);
    c=create_context("size:Lp:step");
    Psize_Lp_step=(float *)(&c->value.s);
    c=create_context("size:Wp:step");
    Psize_Wp_step=(float *)(&c->value.s);
    c=create_context("size:rin:step");
    Psize_rin_step=(float *)(&c->value.s);
    c=create_context("max_Adc");
    Pmax_Adc=(float *)(&c->value.s);
    c=create_context("param:unique");
    Pparam_unique=(float *)(&c->value.s);
    c=create_context("pat_size_target");
    Ppat_size_target=(float *)(&c->value.s);
    c=create_context("mode:freash_op");
    Pmode_freash_op=(float *)(&c->value.s);
    c=create_context("in:V");
    Pin_V=(float *)(&c->value.s);
    c=create_context("param:in");
    Pparam_in=(float *)(&c->value.s);
    c=create_context("out:V");
    Pout_V=(float *)(&c->value.s);
    c=create_context("vdd:V");
    Pvdd_V=(float *)(&c->value.s);
    c=create_context("mid:V");
    Pmid_V=(float *)(&c->value.s);
    c=create_context("status:index");
    Pstatus_index=(float *)(&c->value.s);
    c=create_context("config:size:L");
    Pconfig_size_L=(float *)(&c->value.s);
    c=create_context("config:size:W");
    Pconfig_size_W=(float *)(&c->value.s);
    c=create_context("config:size:Lp");
    Pconfig_size_Lp=(float *)(&c->value.s);
    c=create_context("config:size:Wp");
    Pconfig_size_Wp=(float *)(&c->value.s);
    c=create_context("config:size:rin");
    Pconfig_size_rin=(float *)(&c->value.s);
    c=create_context("0:V");
    P0_V=(float *)(&c->value.s);
    c=create_context("status:fail");
    Pstatus_fail=(float *)(&c->value.s);
    c=create_context("design_feedback");
    Pdesign_feedback=(float *)(&c->value.s);
    c=create_context("leak");
    Pleak=(float *)(&c->value.s);
    c=create_context("config:op_iterations");
    Pconfig_op_iterations=(float *)(&c->value.s);
    c=create_context("config:kcl_th");
    Pconfig_kcl_th=(float *)(&c->value.s);
    c=create_context("config:design_feedback_th");
    Pconfig_design_feedback_th=(float *)(&c->value.s);
    Plook_up_tables_pch_Ids_ss_LUT=(float *)get_LUT("look_up_tables:pch:Ids:ss");
    Plook_up_tables_pch_gm_ss_LUT=(float *)get_LUT("look_up_tables:pch:gm:ss");
    Plook_up_tables_pch_ro_ss_LUT=(float *)get_LUT("look_up_tables:pch:ro:ss");
    c=create_context("p:gm");
    Pp_gm=(float *)(&c->value.s);
    c=create_context("p:go");
    Pp_go=(float *)(&c->value.s);
    c=create_context("p:Ids");
    Pp_Ids=(float *)(&c->value.s);
    Plook_up_tables_nch_Ids_ss_LUT=(float *)get_LUT("look_up_tables:nch:Ids:ss");
    Plook_up_tables_nch_gm_ss_LUT=(float *)get_LUT("look_up_tables:nch:gm:ss");
    Plook_up_tables_nch_ro_ss_LUT=(float *)get_LUT("look_up_tables:nch:ro:ss");
    c=create_context("n_ref:gm");
    Pn_ref_gm=(float *)(&c->value.s);
    c=create_context("n_ref:go");
    Pn_ref_go=(float *)(&c->value.s);
    c=create_context("n_ref:Ids");
    Pn_ref_Ids=(float *)(&c->value.s);
    c=create_context("Gds_in_mid");
    PGds_in_mid=(float *)(&c->value.s);
    c=create_context("config:kcl_step");
    Pconfig_kcl_step=(float *)(&c->value.s);
    c=create_context("Det");
    PDet=(float *)(&c->value.s);
    c=create_context("Ted");
    PTed=(float *)(&c->value.s);
    c=create_context("property:Adc");
    Pproperty_Adc=(float *)(&c->value.s);
    c=create_context("property:CMRR");
    Pproperty_CMRR=(float *)(&c->value.s);
    c=create_context("property:PSRR");
    Pproperty_PSRR=(float *)(&c->value.s);
    c=create_context("config:fail_on_properties");
    Pconfig_fail_on_properties=(float *)(&c->value.s);
    c=create_context("property:Rout");
    Pproperty_Rout=(float *)(&c->value.s);
    c=create_context("n_ref:cdg");
    Pn_ref_cdg=(float *)(&c->value.s);
    c=create_context("s");
    Ps=(float *)(&c->value.s);
    c=create_context("n_ref:cgg");
    Pn_ref_cgg=(float *)(&c->value.s);
    c=create_context("n_ref:Ideq");
    Pn_ref_Ideq=(float *)(&c->value.s);
    c=create_context("p:Ideq");
    Pp_Ideq=(float *)(&c->value.s);
    c=create_context("p:cgs");
    Pp_cgs=(float *)(&c->value.s);
    c=create_context("p:cgb");
    Pp_cgb=(float *)(&c->value.s);
    c=create_context("p:cds");
    Pp_cds=(float *)(&c->value.s);
    c=create_context("p:cdb");
    Pp_cdb=(float *)(&c->value.s);
    c=create_context("n_ref:cds");
    Pn_ref_cds=(float *)(&c->value.s);
    c=create_context("n_ref:cdb");
    Pn_ref_cdb=(float *)(&c->value.s);
    c=create_context("param:vdd");
    Pparam_vdd=(float *)(&c->value.s);
    c=create_context("n_ref:cgs");
    Pn_ref_cgs=(float *)(&c->value.s);
    c=create_context("n_ref:cgb");
    Pn_ref_cgb=(float *)(&c->value.s);
    c=create_context("p:cgd");
    Pp_cgd=(float *)(&c->value.s);
    c=create_context("p:cgg");
    Pp_cgg=(float *)(&c->value.s);
    c=create_context("p:cdd");
    Pp_cdd=(float *)(&c->value.s);
    c=create_context("p:cdg");
    Pp_cdg=(float *)(&c->value.s);
    c=create_context("n_ref:cdd");
    Pn_ref_cdd=(float *)(&c->value.s);
    c=create_context("n_ref:cgd");
    Pn_ref_cgd=(float *)(&c->value.s);
    Plook_up_tables_pch_cgg_ss_LUT=(float *)get_LUT("look_up_tables:pch:cgg:ss");
    c=create_context("config:cgg_factor");
    Pconfig_cgg_factor=(float *)(&c->value.s);
    Plook_up_tables_pch_cgd_ss_LUT=(float *)get_LUT("look_up_tables:pch:cgd:ss");
    c=create_context("config:cgd_factor");
    Pconfig_cgd_factor=(float *)(&c->value.s);
    Plook_up_tables_pch_cgs_ss_LUT=(float *)get_LUT("look_up_tables:pch:cgs:ss");
    c=create_context("config:cgs_factor");
    Pconfig_cgs_factor=(float *)(&c->value.s);
    Plook_up_tables_pch_cgb_ss_LUT=(float *)get_LUT("look_up_tables:pch:cgb:ss");
    c=create_context("config:cgb_factor");
    Pconfig_cgb_factor=(float *)(&c->value.s);
    Plook_up_tables_pch_cdd_ss_LUT=(float *)get_LUT("look_up_tables:pch:cdd:ss");
    c=create_context("config:cdd_factor");
    Pconfig_cdd_factor=(float *)(&c->value.s);
    Plook_up_tables_pch_cdg_ss_LUT=(float *)get_LUT("look_up_tables:pch:cdg:ss");
    c=create_context("config:cdg_factor");
    Pconfig_cdg_factor=(float *)(&c->value.s);
    Plook_up_tables_pch_cdb_ss_LUT=(float *)get_LUT("look_up_tables:pch:cdb:ss");
    c=create_context("config:cdb_factor");
    Pconfig_cdb_factor=(float *)(&c->value.s);
    Plook_up_tables_pch_cds_ss_LUT=(float *)get_LUT("look_up_tables:pch:cds:ss");
    c=create_context("config:cds_factor");
    Pconfig_cds_factor=(float *)(&c->value.s);
    c=create_context("p:csd");
    Pp_csd=(float *)(&c->value.s);
    Plook_up_tables_pch_csd_ss_LUT=(float *)get_LUT("look_up_tables:pch:csd:ss");
    c=create_context("config:csd_factor");
    Pconfig_csd_factor=(float *)(&c->value.s);
    c=create_context("p:csg");
    Pp_csg=(float *)(&c->value.s);
    Plook_up_tables_pch_csg_ss_LUT=(float *)get_LUT("look_up_tables:pch:csg:ss");
    c=create_context("config:csg_factor");
    Pconfig_csg_factor=(float *)(&c->value.s);
    c=create_context("p:css");
    Pp_css=(float *)(&c->value.s);
    Plook_up_tables_pch_css_ss_LUT=(float *)get_LUT("look_up_tables:pch:css:ss");
    c=create_context("config:css_factor");
    Pconfig_css_factor=(float *)(&c->value.s);
    c=create_context("p:csb");
    Pp_csb=(float *)(&c->value.s);
    Plook_up_tables_pch_csb_ss_LUT=(float *)get_LUT("look_up_tables:pch:csb:ss");
    c=create_context("config:csb_factor");
    Pconfig_csb_factor=(float *)(&c->value.s);
    c=create_context("p:cbd");
    Pp_cbd=(float *)(&c->value.s);
    Plook_up_tables_pch_cbd_ss_LUT=(float *)get_LUT("look_up_tables:pch:cbd:ss");
    c=create_context("config:cbd_factor");
    Pconfig_cbd_factor=(float *)(&c->value.s);
    c=create_context("p:cbg");
    Pp_cbg=(float *)(&c->value.s);
    Plook_up_tables_pch_cbg_ss_LUT=(float *)get_LUT("look_up_tables:pch:cbg:ss");
    c=create_context("config:cbg_factor");
    Pconfig_cbg_factor=(float *)(&c->value.s);
    c=create_context("p:cbs");
    Pp_cbs=(float *)(&c->value.s);
    Plook_up_tables_pch_cbs_ss_LUT=(float *)get_LUT("look_up_tables:pch:cbs:ss");
    c=create_context("config:cbs_factor");
    Pconfig_cbs_factor=(float *)(&c->value.s);
    c=create_context("p:cbb");
    Pp_cbb=(float *)(&c->value.s);
    Plook_up_tables_pch_cbb_ss_LUT=(float *)get_LUT("look_up_tables:pch:cbb:ss");
    c=create_context("config:cbb_factor");
    Pconfig_cbb_factor=(float *)(&c->value.s);
    Plook_up_tables_nch_cgg_ss_LUT=(float *)get_LUT("look_up_tables:nch:cgg:ss");
    Plook_up_tables_nch_cgd_ss_LUT=(float *)get_LUT("look_up_tables:nch:cgd:ss");
    Plook_up_tables_nch_cgs_ss_LUT=(float *)get_LUT("look_up_tables:nch:cgs:ss");
    Plook_up_tables_nch_cgb_ss_LUT=(float *)get_LUT("look_up_tables:nch:cgb:ss");
    Plook_up_tables_nch_cdd_ss_LUT=(float *)get_LUT("look_up_tables:nch:cdd:ss");
    Plook_up_tables_nch_cdg_ss_LUT=(float *)get_LUT("look_up_tables:nch:cdg:ss");
    Plook_up_tables_nch_cdb_ss_LUT=(float *)get_LUT("look_up_tables:nch:cdb:ss");
    Plook_up_tables_nch_cds_ss_LUT=(float *)get_LUT("look_up_tables:nch:cds:ss");
    c=create_context("n_ref:csd");
    Pn_ref_csd=(float *)(&c->value.s);
    Plook_up_tables_nch_csd_ss_LUT=(float *)get_LUT("look_up_tables:nch:csd:ss");
    c=create_context("n_ref:csg");
    Pn_ref_csg=(float *)(&c->value.s);
    Plook_up_tables_nch_csg_ss_LUT=(float *)get_LUT("look_up_tables:nch:csg:ss");
    c=create_context("n_ref:css");
    Pn_ref_css=(float *)(&c->value.s);
    Plook_up_tables_nch_css_ss_LUT=(float *)get_LUT("look_up_tables:nch:css:ss");
    c=create_context("n_ref:csb");
    Pn_ref_csb=(float *)(&c->value.s);
    Plook_up_tables_nch_csb_ss_LUT=(float *)get_LUT("look_up_tables:nch:csb:ss");
    c=create_context("n_ref:cbd");
    Pn_ref_cbd=(float *)(&c->value.s);
    Plook_up_tables_nch_cbd_ss_LUT=(float *)get_LUT("look_up_tables:nch:cbd:ss");
    c=create_context("n_ref:cbg");
    Pn_ref_cbg=(float *)(&c->value.s);
    Plook_up_tables_nch_cbg_ss_LUT=(float *)get_LUT("look_up_tables:nch:cbg:ss");
    c=create_context("n_ref:cbs");
    Pn_ref_cbs=(float *)(&c->value.s);
    Plook_up_tables_nch_cbs_ss_LUT=(float *)get_LUT("look_up_tables:nch:cbs:ss");
    c=create_context("n_ref:cbb");
    Pn_ref_cbb=(float *)(&c->value.s);
    Plook_up_tables_nch_cbb_ss_LUT=(float *)get_LUT("look_up_tables:nch:cbb:ss");
    c=create_context("property:BW");
    Pproperty_BW=(float *)(&c->value.s);
    c=create_context("property:BW:s");
    Pproperty_BW_s=(float *)(&c->value.s);
    c=create_context("p1");
    Pp1=(float *)(&c->value.s);
    c=create_context("p2");
    Pp2=(float *)(&c->value.s);
    c=create_context("property:ts");
    Pproperty_ts=(float *)(&c->value.s);
    c=create_context("property:PM");
    Pproperty_PM=(float *)(&c->value.s);
    c=create_context("p:Nt_unit");
    Pp_Nt_unit=(float *)(&c->value.s);
    P_look_up_tables_pch_thermal_noise_ss_LUT=(float *)get_LUT(":look_up_tables:pch:thermal_noise:ss");
    c=create_context("p:dNt_dvgs");
    Pp_dNt_dvgs=(float *)(&c->value.s);
    c=create_context("p:dNt_dvds");
    Pp_dNt_dvds=(float *)(&c->value.s);
    c=create_context("p:dNt_dvbs");
    Pp_dNt_dvbs=(float *)(&c->value.s);
    c=create_context("p:dNt_dl");
    Pp_dNt_dl=(float *)(&c->value.s);
    c=create_context("p:Nt");
    Pp_Nt=(float *)(&c->value.s);
    c=create_context("p:Nf_unit");
    Pp_Nf_unit=(float *)(&c->value.s);
    P_look_up_tables_pch_flicker_noise_ss_LUT=(float *)get_LUT(":look_up_tables:pch:flicker_noise:ss");
    c=create_context("p:dNf_dvgs");
    Pp_dNf_dvgs=(float *)(&c->value.s);
    c=create_context("p:dNf_dvds");
    Pp_dNf_dvds=(float *)(&c->value.s);
    c=create_context("p:dNf_dvbs");
    Pp_dNf_dvbs=(float *)(&c->value.s);
    c=create_context("p:dNf_dl");
    Pp_dNf_dl=(float *)(&c->value.s);
    c=create_context("p:Nf");
    Pp_Nf=(float *)(&c->value.s);
    c=create_context("n_ref:Nt_unit");
    Pn_ref_Nt_unit=(float *)(&c->value.s);
    P_look_up_tables_nch_thermal_noise_ss_LUT=(float *)get_LUT(":look_up_tables:nch:thermal_noise:ss");
    c=create_context("n_ref:dNt_dvgs");
    Pn_ref_dNt_dvgs=(float *)(&c->value.s);
    c=create_context("n_ref:dNt_dvds");
    Pn_ref_dNt_dvds=(float *)(&c->value.s);
    c=create_context("n_ref:dNt_dvbs");
    Pn_ref_dNt_dvbs=(float *)(&c->value.s);
    c=create_context("n_ref:dNt_dl");
    Pn_ref_dNt_dl=(float *)(&c->value.s);
    c=create_context("n_ref:Nt");
    Pn_ref_Nt=(float *)(&c->value.s);
    c=create_context("n_ref:Nf_unit");
    Pn_ref_Nf_unit=(float *)(&c->value.s);
    P_look_up_tables_nch_flicker_noise_ss_LUT=(float *)get_LUT(":look_up_tables:nch:flicker_noise:ss");
    c=create_context("n_ref:dNf_dvgs");
    Pn_ref_dNf_dvgs=(float *)(&c->value.s);
    c=create_context("n_ref:dNf_dvds");
    Pn_ref_dNf_dvds=(float *)(&c->value.s);
    c=create_context("n_ref:dNf_dvbs");
    Pn_ref_dNf_dvbs=(float *)(&c->value.s);
    c=create_context("n_ref:dNf_dl");
    Pn_ref_dNf_dl=(float *)(&c->value.s);
    c=create_context("n_ref:Nf");
    Pn_ref_Nf=(float *)(&c->value.s);
    c=create_context("property:Nt");
    Pproperty_Nt=(float *)(&c->value.s);
    c=create_context("property:Nf");
    Pproperty_Nf=(float *)(&c->value.s);
    c=create_context("property:fc");
    Pproperty_fc=(float *)(&c->value.s);
    c=create_context("property:TotalNoise");
    Pproperty_TotalNoise=(float *)(&c->value.s);
    c=create_context("property:Area");
    Pproperty_Area=(float *)(&c->value.s);
    c=create_context("property:Vos");
    Pproperty_Vos=(float *)(&c->value.s);
    c=create_context("property:Power");
    Pproperty_Power=(float *)(&c->value.s);
    c=create_context("config:factor:Adc");
    Pconfig_factor_Adc=(float *)(&c->value.s);
    c=create_context("config:shift:Adc");
    Pconfig_shift_Adc=(float *)(&c->value.s);
    c=create_context("config:factor:CMRR");
    Pconfig_factor_CMRR=(float *)(&c->value.s);
    c=create_context("config:shift:CMRR");
    Pconfig_shift_CMRR=(float *)(&c->value.s);
    c=create_context("config:factor:PSRR");
    Pconfig_factor_PSRR=(float *)(&c->value.s);
    c=create_context("config:shift:PSRR");
    Pconfig_shift_PSRR=(float *)(&c->value.s);
    c=create_context("config:factor:Rout");
    Pconfig_factor_Rout=(float *)(&c->value.s);
    c=create_context("config:shift:Rout");
    Pconfig_shift_Rout=(float *)(&c->value.s);
    c=create_context("config:factor:BW");
    Pconfig_factor_BW=(float *)(&c->value.s);
    c=create_context("config:shift:BW");
    Pconfig_shift_BW=(float *)(&c->value.s);
    c=create_context("config:factor:PM");
    Pconfig_factor_PM=(float *)(&c->value.s);
    c=create_context("config:shift:PM");
    Pconfig_shift_PM=(float *)(&c->value.s);
    c=create_context("config:factor:Cin");
    Pconfig_factor_Cin=(float *)(&c->value.s);
    c=create_context("config:shift:Cin");
    Pconfig_shift_Cin=(float *)(&c->value.s);
    c=create_context("property:Cin");
    Pproperty_Cin=(float *)(&c->value.s);
    c=create_context("config:factor:ts");
    Pconfig_factor_ts=(float *)(&c->value.s);
    c=create_context("config:shift:ts");
    Pconfig_shift_ts=(float *)(&c->value.s);
    c=create_context("config:factor:Nt");
    Pconfig_factor_Nt=(float *)(&c->value.s);
    c=create_context("config:shift:Nt");
    Pconfig_shift_Nt=(float *)(&c->value.s);
    c=create_context("config:factor:Nf");
    Pconfig_factor_Nf=(float *)(&c->value.s);
    c=create_context("config:shift:Nf");
    Pconfig_shift_Nf=(float *)(&c->value.s);
    c=create_context("config:factor:TotalNoise");
    Pconfig_factor_TotalNoise=(float *)(&c->value.s);
    c=create_context("config:shift:TotalNoise");
    Pconfig_shift_TotalNoise=(float *)(&c->value.s);
    c=create_context("config:factor:fc");
    Pconfig_factor_fc=(float *)(&c->value.s);
    c=create_context("config:shift:fc");
    Pconfig_shift_fc=(float *)(&c->value.s);
    c=create_context("config:factor:Vos");
    Pconfig_factor_Vos=(float *)(&c->value.s);
    c=create_context("config:shift:Vos");
    Pconfig_shift_Vos=(float *)(&c->value.s);
    c=create_context("config:factor:Area");
    Pconfig_factor_Area=(float *)(&c->value.s);
    c=create_context("config:shift:Area");
    Pconfig_shift_Area=(float *)(&c->value.s);
    c=create_context("config:factor:Power");
    Pconfig_factor_Power=(float *)(&c->value.s);
    c=create_context("config:shift:Power");
    Pconfig_shift_Power=(float *)(&c->value.s);
    c=create_context("circuit_breed_id");
    Pcircuit_breed_id=(float *)(&c->value.s);
    c=create_context("circuit_breed_target");
    Pcircuit_breed_target=(float *)(&c->value.s);
    Tcl_CreateObjCommand(interp, "::C::random", tcl_gamma_random_cmd, NULL, NULL);
    Tcl_CreateObjCommand(interp, "::C::random_breed", tcl_gamma_random_breed_cmd, NULL, NULL);
    Tcl_CreateObjCommand(interp, "::C::random_breed_single", tcl_gamma_random_breed_single_cmd, NULL, NULL);
    Tcl_CreateObjCommand(interp, "::C::breed", tcl_gamma_breed_cmd, NULL, NULL);
    // Tcl_CreateObjCommand(interp, "::C::grad", tcl_gamma_grad_cmd, NULL, NULL);
    Tcl_CreateObjCommand(interp, "::C::op", tcl_gamma_op_cmd, NULL, NULL);
    Tcl_CreateObjCommand(interp, "::C::import", tcl_gamma_import_cmd, NULL, NULL);
    Tcl_CreateObjCommand(interp, "::C::export", tcl_gamma_export_cmd, NULL, NULL);
    return TCL_OK;
}
