
        #include <tcl.h>
        #include <stdio.h>
        #include <stdlib.h>
        #include "Gamma/Data/ctree.h"
        #include "Gamma/LUT/look_up_table.h"
        #include "Gamma/Web/heatmap/heatmap.h"
        // Some global pointers to keep reference of the contexts this object manipulates
        float *Pparam_inp;
float *Pparam_inn;
float *Pparam_vdd;
float *Psize_iref;
float *Psize_Lp;
float *Psize_Wp;
float *Psize_Ln;
float *Psize_Wn;
float *Psize_Ls;
float *Pproperty_Adc;
float *Pproperty_CMRR;
float *Pdiffpair_pmos_circuits_PAT;
float *Pdiffpair_pmos_config_pat_size_target;
float *Psize_iref_min;
float *Psize_iref_max;
float *Pdiffpair_pmos_size_iref;
float *Psize_Lp_min;
float *Psize_Lp_max;
float *Pdiffpair_pmos_size_Lp;
float *Psize_Wp_max;
float *Pdiffpair_pmos_size_Wp;
float *Psize_Ln_min;
float *Psize_Ln_max;
float *Pdiffpair_pmos_size_Ln;
float *Psize_Wn_max;
float *Pdiffpair_pmos_size_Wn;
float *Psize_Ls_min;
float *Psize_Ls_max;
float *Pdiffpair_pmos_size_Ls;
float *Psize_iref_step;
float *Psize_Lp_step;
float *Psize_Wp_step;
float *Psize_Ln_step;
float *Psize_Wn_step;
float *Psize_Ls_step;
float *Pdiffpair_pmos_max_Adc;
float *Pdiffpair_pmos_param_unique;
float *Pdiffpair_pmos_pat_size_target;
float *Pdiffpair_pmos_size_iref_step;
float *Pdiffpair_pmos_size_Lp_step;
float *Pdiffpair_pmos_size_Wp_step;
float *Pdiffpair_pmos_size_Ln_step;
float *Pdiffpair_pmos_size_Wn_step;
float *Pdiffpair_pmos_size_Ls_step;
float *Pdiffpair_pmos_circuit_breed_id;
float *Pdiffpair_pmos_circuit_breed_target;
float *Pdiffpair_pmos_mode_freash_op;
float *Pdiffpair_pmos_status_index;
float *Pdiffpair_pmos_config_size_iref;
float *Pdiffpair_pmos_config_size_Lp;
float *Pdiffpair_pmos_config_size_Wp;
float *Pdiffpair_pmos_config_size_Ln;
float *Pdiffpair_pmos_config_size_Wn;
float *Pdiffpair_pmos_config_size_Ls;
float *Pdiffpair_pmos_vdd_V;
float *Pdiffpair_pmos_0_V;
float *Pdiffpair_pmos_status_fail;
float *Pdiffpair_pmos_design_feedback;
float *Pn_1_bin;
float *Pn_1_W;
float *Pn_1_L;
float *Plook_up_tables_nch_binning_LUT;
float *Pn_2_bin;
float *Pn_2_W;
float *Pn_2_L;
float *Ppin_1_bin;
float *Ppin_1_W;
float *Ppin_1_L;
float *Plook_up_tables_pch_binning_LUT;
float *Ppin_2_bin;
float *Ppin_2_W;
float *Ppin_2_L;
float *Pp_tail_bin;
float *Pp_tail_W;
float *Pp_tail_L;
float *Pp_ref_bin;
float *Pp_ref_W;
float *Pp_ref_L;
float *Pdiffpair_pmos_leak;
float *Pdiffpair_pmos_config_op_iterations;
float *Pdiffpair_pmos_config_kcl_th;
float *Pdiffpair_pmos_config_design_feedback_th;
float *Poutp_V;
float *Poutm_V;
float *Pn_1_go;
float *Pn_1_gm;
float *Pn_1_gb;
float *Pn_1_Ids;
float *P0_V;
float *Pdiffpair_pmos_look_up_tables_nch_go_ss_CONTEXT;
float *Pdiffpair_pmos_look_up_tables_nch_gm_ss_CONTEXT;
float *Pdiffpair_pmos_look_up_tables_nch_gb_ss_CONTEXT;
float *Pdiffpair_pmos_look_up_tables_nch_Ids_ss_CONTEXT;
float *Pn_2_go;
float *Pn_2_gm;
float *Pn_2_gb;
float *Pn_2_Ids;
float *Pvdd_V;
float *Ptail_V;
float *Ppin_1_go;
float *Ppin_1_gm;
float *Ppin_1_gb;
float *Ppin_1_Ids;
float *Pinp_V;
float *Pdiffpair_pmos_look_up_tables_pch_go_ss_CONTEXT;
float *Pdiffpair_pmos_look_up_tables_pch_gm_ss_CONTEXT;
float *Pdiffpair_pmos_look_up_tables_pch_gb_ss_CONTEXT;
float *Pdiffpair_pmos_look_up_tables_pch_Ids_ss_CONTEXT;
float *Ppin_2_go;
float *Ppin_2_gm;
float *Ppin_2_gb;
float *Ppin_2_Ids;
float *Pinn_V;
float *Pvbias_V;
float *Pp_tail_go;
float *Pp_tail_gm;
float *Pp_tail_gb;
float *Pp_tail_Ids;
float *Pp_ref_go;
float *Pp_ref_gm;
float *Pp_ref_gb;
float *Pp_ref_Ids;
float *Pdiffpair_pmos_config_kcl_step;
float *Pdiffpair_pmos_property_Adc;
float *Pdiffpair_pmos_property_CMRR;
float *Pdiffpair_pmos_property_PSRR;
float *Pdiffpair_pmos_config_fail_on_properties;
float *Pdiffpair_pmos_property_Rout;
float *Ppin_2_css;
float *Ppin_2_csd;
float *Ppin_2_cds;
float *Ppin_2_cdd;
float *Ppin_1_css;
float *Ppin_1_csd;
float *Ppin_1_cds;
float *Ppin_1_cdd;
float *Pp_tail_cgg;
float *Pp_tail_cgd;
float *Pp_tail_cdg;
float *Pp_tail_cdd;
float *Pp_ref_cgg;
float *Pp_ref_cgd;
float *Pp_ref_cdg;
float *Pp_ref_cdd;
float *Pn_2_cgg;
float *Pn_2_cgd;
float *Pn_2_cdg;
float *Pn_2_cdd;
float *Pn_1_cgg;
float *Pn_1_cgd;
float *Pn_1_cdg;
float *Pn_1_cdd;
float *Pdiffpair_pmos_property_BW;
float *Ps;
float *Pdiffpair_pmos_property_BW_s;
float *Pdiffpair_pmos_p1;
float *Pdiffpair_pmos_p2;
float *Pdiffpair_pmos_property_ts;
float *Ppin_1_cgs;
float *Ppin_1_cgd;
float *Pdiffpair_pmos_property_Cin;
float *Pdiffpair_pmos_property_PM;
float *Pn_1_dNt_dvgs;
float *Pn_1_dNt_dvds;
float *Pn_1_dNt_dvbs;
float *Pn_1_dNt_dl;
float *Pn_1_Nt_unit;
float *P_look_up_tables_nch_thermal_noise_ss_LUT;
float *Pn_1_Nt;
float *Pn_1_dNf_dvgs;
float *Pn_1_dNf_dvds;
float *Pn_1_dNf_dvbs;
float *Pn_1_dNf_dl;
float *Pn_1_Nf_unit;
float *P_look_up_tables_nch_flicker_noise_ss_LUT;
float *Pn_1_Nf;
float *Pn_2_dNt_dvgs;
float *Pn_2_dNt_dvds;
float *Pn_2_dNt_dvbs;
float *Pn_2_dNt_dl;
float *Pn_2_Nt_unit;
float *Pn_2_Nt;
float *Pn_2_dNf_dvgs;
float *Pn_2_dNf_dvds;
float *Pn_2_dNf_dvbs;
float *Pn_2_dNf_dl;
float *Pn_2_Nf_unit;
float *Pn_2_Nf;
float *Ppin_1_dNt_dvgs;
float *Ppin_1_dNt_dvds;
float *Ppin_1_dNt_dvbs;
float *Ppin_1_dNt_dl;
float *Ppin_1_Nt_unit;
float *P_look_up_tables_pch_thermal_noise_ss_LUT;
float *Ppin_1_Nt;
float *Ppin_1_dNf_dvgs;
float *Ppin_1_dNf_dvds;
float *Ppin_1_dNf_dvbs;
float *Ppin_1_dNf_dl;
float *Ppin_1_Nf_unit;
float *P_look_up_tables_pch_flicker_noise_ss_LUT;
float *Ppin_1_Nf;
float *Ppin_2_dNt_dvgs;
float *Ppin_2_dNt_dvds;
float *Ppin_2_dNt_dvbs;
float *Ppin_2_dNt_dl;
float *Ppin_2_Nt_unit;
float *Ppin_2_Nt;
float *Ppin_2_dNf_dvgs;
float *Ppin_2_dNf_dvds;
float *Ppin_2_dNf_dvbs;
float *Ppin_2_dNf_dl;
float *Ppin_2_Nf_unit;
float *Ppin_2_Nf;
float *Pp_tail_dNt_dvgs;
float *Pp_tail_dNt_dvds;
float *Pp_tail_dNt_dvbs;
float *Pp_tail_dNt_dl;
float *Pp_tail_Nt_unit;
float *Pp_tail_Nt;
float *Pp_tail_dNf_dvgs;
float *Pp_tail_dNf_dvds;
float *Pp_tail_dNf_dvbs;
float *Pp_tail_dNf_dl;
float *Pp_tail_Nf_unit;
float *Pp_tail_Nf;
float *Pp_ref_dNt_dvgs;
float *Pp_ref_dNt_dvds;
float *Pp_ref_dNt_dvbs;
float *Pp_ref_dNt_dl;
float *Pp_ref_Nt_unit;
float *Pp_ref_Nt;
float *Pp_ref_dNf_dvgs;
float *Pp_ref_dNf_dvds;
float *Pp_ref_dNf_dvbs;
float *Pp_ref_dNf_dl;
float *Pp_ref_Nf_unit;
float *Pp_ref_Nf;
float *Pdiffpair_pmos_property_Nt;
float *Pdiffpair_pmos_property_Nf;
float *Pdiffpair_pmos_property_fc;
float *Pdiffpair_pmos_property_TotalNoise;
float *Pdiffpair_pmos_property_Area;
float *Pdiffpair_pmos_property_Vos;
float *Pdiffpair_pmos_property_Power;
float *Pdiffpair_pmos_config_shift_Adc;
float *Pdiffpair_pmos_config_factor_Adc;
float *Pdiffpair_pmos_config_shift_CMRR;
float *Pdiffpair_pmos_config_factor_CMRR;

        float param_inp;
float param_inn;
float param_vdd;
float size_iref;
float size_Lp;
float size_Wp;
float size_Ln;
float size_Wn;
float size_Ls;
float property_Adc;
float property_CMRR;
float diffpair_pmos_circuits_PAT;
float diffpair_pmos_config_pat_size_target;
float size_iref_min;
float size_iref_max;
float diffpair_pmos_size_iref;
float size_Lp_min;
float size_Lp_max;
float diffpair_pmos_size_Lp;
float size_Wp_max;
float diffpair_pmos_size_Wp;
float size_Ln_min;
float size_Ln_max;
float diffpair_pmos_size_Ln;
float size_Wn_max;
float diffpair_pmos_size_Wn;
float size_Ls_min;
float size_Ls_max;
float diffpair_pmos_size_Ls;
float size_iref_step;
float size_Lp_step;
float size_Wp_step;
float size_Ln_step;
float size_Wn_step;
float size_Ls_step;
float diffpair_pmos_max_Adc;
float diffpair_pmos_param_unique;
float diffpair_pmos_pat_size_target;
float diffpair_pmos_size_iref_step;
float diffpair_pmos_size_Lp_step;
float diffpair_pmos_size_Wp_step;
float diffpair_pmos_size_Ln_step;
float diffpair_pmos_size_Wn_step;
float diffpair_pmos_size_Ls_step;
float diffpair_pmos_circuit_breed_id;
float diffpair_pmos_circuit_breed_target;
float diffpair_pmos_mode_freash_op;
float diffpair_pmos_status_index;
float diffpair_pmos_config_size_iref;
float diffpair_pmos_config_size_Lp;
float diffpair_pmos_config_size_Wp;
float diffpair_pmos_config_size_Ln;
float diffpair_pmos_config_size_Wn;
float diffpair_pmos_config_size_Ls;
float diffpair_pmos_vdd_V;
float diffpair_pmos_0_V;
float diffpair_pmos_status_fail;
float diffpair_pmos_design_feedback;
float n_1_bin;
float n_1_W;
float n_1_L;
float look_up_tables_nch_binning_LUT;
float n_2_bin;
float n_2_W;
float n_2_L;
float pin_1_bin;
float pin_1_W;
float pin_1_L;
float look_up_tables_pch_binning_LUT;
float pin_2_bin;
float pin_2_W;
float pin_2_L;
float p_tail_bin;
float p_tail_W;
float p_tail_L;
float p_ref_bin;
float p_ref_W;
float p_ref_L;
float diffpair_pmos_leak;
float diffpair_pmos_config_op_iterations;
float diffpair_pmos_config_kcl_th;
float diffpair_pmos_config_design_feedback_th;
float outp_V;
float outm_V;
float n_1_go;
float n_1_gm;
float n_1_gb;
float n_1_Ids;
float CONST_0_V;
float diffpair_pmos_look_up_tables_nch_go_ss_CONTEXT;
float diffpair_pmos_look_up_tables_nch_gm_ss_CONTEXT;
float diffpair_pmos_look_up_tables_nch_gb_ss_CONTEXT;
float diffpair_pmos_look_up_tables_nch_Ids_ss_CONTEXT;
float n_2_go;
float n_2_gm;
float n_2_gb;
float n_2_Ids;
float vdd_V;
float tail_V;
float pin_1_go;
float pin_1_gm;
float pin_1_gb;
float pin_1_Ids;
float inp_V;
float diffpair_pmos_look_up_tables_pch_go_ss_CONTEXT;
float diffpair_pmos_look_up_tables_pch_gm_ss_CONTEXT;
float diffpair_pmos_look_up_tables_pch_gb_ss_CONTEXT;
float diffpair_pmos_look_up_tables_pch_Ids_ss_CONTEXT;
float pin_2_go;
float pin_2_gm;
float pin_2_gb;
float pin_2_Ids;
float inn_V;
float vbias_V;
float p_tail_go;
float p_tail_gm;
float p_tail_gb;
float p_tail_Ids;
float p_ref_go;
float p_ref_gm;
float p_ref_gb;
float p_ref_Ids;
float diffpair_pmos_config_kcl_step;
float diffpair_pmos_property_Adc;
float diffpair_pmos_property_CMRR;
float diffpair_pmos_property_PSRR;
float diffpair_pmos_config_fail_on_properties;
float diffpair_pmos_property_Rout;
float pin_2_css;
float pin_2_csd;
float pin_2_cds;
float pin_2_cdd;
float pin_1_css;
float pin_1_csd;
float pin_1_cds;
float pin_1_cdd;
float p_tail_cgg;
float p_tail_cgd;
float p_tail_cdg;
float p_tail_cdd;
float p_ref_cgg;
float p_ref_cgd;
float p_ref_cdg;
float p_ref_cdd;
float n_2_cgg;
float n_2_cgd;
float n_2_cdg;
float n_2_cdd;
float n_1_cgg;
float n_1_cgd;
float n_1_cdg;
float n_1_cdd;
float diffpair_pmos_property_BW;
float s;
float diffpair_pmos_property_BW_s;
float diffpair_pmos_p1;
float diffpair_pmos_p2;
float diffpair_pmos_property_ts;
float pin_1_cgs;
float pin_1_cgd;
float diffpair_pmos_property_Cin;
float diffpair_pmos_property_PM;
float n_1_dNt_dvgs;
float n_1_dNt_dvds;
float n_1_dNt_dvbs;
float n_1_dNt_dl;
float n_1_Nt_unit;
float _look_up_tables_nch_thermal_noise_ss_LUT;
float n_1_Nt;
float n_1_dNf_dvgs;
float n_1_dNf_dvds;
float n_1_dNf_dvbs;
float n_1_dNf_dl;
float n_1_Nf_unit;
float _look_up_tables_nch_flicker_noise_ss_LUT;
float n_1_Nf;
float n_2_dNt_dvgs;
float n_2_dNt_dvds;
float n_2_dNt_dvbs;
float n_2_dNt_dl;
float n_2_Nt_unit;
float n_2_Nt;
float n_2_dNf_dvgs;
float n_2_dNf_dvds;
float n_2_dNf_dvbs;
float n_2_dNf_dl;
float n_2_Nf_unit;
float n_2_Nf;
float pin_1_dNt_dvgs;
float pin_1_dNt_dvds;
float pin_1_dNt_dvbs;
float pin_1_dNt_dl;
float pin_1_Nt_unit;
float _look_up_tables_pch_thermal_noise_ss_LUT;
float pin_1_Nt;
float pin_1_dNf_dvgs;
float pin_1_dNf_dvds;
float pin_1_dNf_dvbs;
float pin_1_dNf_dl;
float pin_1_Nf_unit;
float _look_up_tables_pch_flicker_noise_ss_LUT;
float pin_1_Nf;
float pin_2_dNt_dvgs;
float pin_2_dNt_dvds;
float pin_2_dNt_dvbs;
float pin_2_dNt_dl;
float pin_2_Nt_unit;
float pin_2_Nt;
float pin_2_dNf_dvgs;
float pin_2_dNf_dvds;
float pin_2_dNf_dvbs;
float pin_2_dNf_dl;
float pin_2_Nf_unit;
float pin_2_Nf;
float p_tail_dNt_dvgs;
float p_tail_dNt_dvds;
float p_tail_dNt_dvbs;
float p_tail_dNt_dl;
float p_tail_Nt_unit;
float p_tail_Nt;
float p_tail_dNf_dvgs;
float p_tail_dNf_dvds;
float p_tail_dNf_dvbs;
float p_tail_dNf_dl;
float p_tail_Nf_unit;
float p_tail_Nf;
float p_ref_dNt_dvgs;
float p_ref_dNt_dvds;
float p_ref_dNt_dvbs;
float p_ref_dNt_dl;
float p_ref_Nt_unit;
float p_ref_Nt;
float p_ref_dNf_dvgs;
float p_ref_dNf_dvds;
float p_ref_dNf_dvbs;
float p_ref_dNf_dl;
float p_ref_Nf_unit;
float p_ref_Nf;
float diffpair_pmos_property_Nt;
float diffpair_pmos_property_Nf;
float diffpair_pmos_property_fc;
float diffpair_pmos_property_TotalNoise;
float diffpair_pmos_property_Area;
float diffpair_pmos_property_Vos;
float diffpair_pmos_property_Power;
float diffpair_pmos_config_shift_Adc;
float diffpair_pmos_config_factor_Adc;
float diffpair_pmos_config_shift_CMRR;
float diffpair_pmos_config_factor_CMRR;

        // The compiled function
        static int tcl_gamma_diffpair_pmos_import_cmd(ClientData clientData,Tcl_Interp *interp,int argc,char *argv[]) {
	    Gamma_diffpair_pmos_Init(interp);
            param_inp=*Pparam_inp;
param_inn=*Pparam_inn;
param_vdd=*Pparam_vdd;
size_iref=*Psize_iref;
size_Lp=*Psize_Lp;
size_Wp=*Psize_Wp;
size_Ln=*Psize_Ln;
size_Wn=*Psize_Wn;
size_Ls=*Psize_Ls;
property_Adc=*Pproperty_Adc;
property_CMRR=*Pproperty_CMRR;
diffpair_pmos_config_pat_size_target=*Pdiffpair_pmos_config_pat_size_target;
size_iref_min=*Psize_iref_min;
size_iref_max=*Psize_iref_max;
diffpair_pmos_size_iref=*Pdiffpair_pmos_size_iref;
size_Lp_min=*Psize_Lp_min;
size_Lp_max=*Psize_Lp_max;
diffpair_pmos_size_Lp=*Pdiffpair_pmos_size_Lp;
size_Wp_max=*Psize_Wp_max;
diffpair_pmos_size_Wp=*Pdiffpair_pmos_size_Wp;
size_Ln_min=*Psize_Ln_min;
size_Ln_max=*Psize_Ln_max;
diffpair_pmos_size_Ln=*Pdiffpair_pmos_size_Ln;
size_Wn_max=*Psize_Wn_max;
diffpair_pmos_size_Wn=*Pdiffpair_pmos_size_Wn;
size_Ls_min=*Psize_Ls_min;
size_Ls_max=*Psize_Ls_max;
diffpair_pmos_size_Ls=*Pdiffpair_pmos_size_Ls;
size_iref_step=*Psize_iref_step;
size_Lp_step=*Psize_Lp_step;
size_Wp_step=*Psize_Wp_step;
size_Ln_step=*Psize_Ln_step;
size_Wn_step=*Psize_Wn_step;
size_Ls_step=*Psize_Ls_step;
diffpair_pmos_max_Adc=*Pdiffpair_pmos_max_Adc;
diffpair_pmos_param_unique=*Pdiffpair_pmos_param_unique;
diffpair_pmos_pat_size_target=*Pdiffpair_pmos_pat_size_target;
diffpair_pmos_size_iref_step=*Pdiffpair_pmos_size_iref_step;
diffpair_pmos_size_Lp_step=*Pdiffpair_pmos_size_Lp_step;
diffpair_pmos_size_Wp_step=*Pdiffpair_pmos_size_Wp_step;
diffpair_pmos_size_Ln_step=*Pdiffpair_pmos_size_Ln_step;
diffpair_pmos_size_Wn_step=*Pdiffpair_pmos_size_Wn_step;
diffpair_pmos_size_Ls_step=*Pdiffpair_pmos_size_Ls_step;
diffpair_pmos_circuit_breed_id=*Pdiffpair_pmos_circuit_breed_id;
diffpair_pmos_circuit_breed_target=*Pdiffpair_pmos_circuit_breed_target;
diffpair_pmos_mode_freash_op=*Pdiffpair_pmos_mode_freash_op;
diffpair_pmos_status_index=*Pdiffpair_pmos_status_index;
diffpair_pmos_config_size_iref=*Pdiffpair_pmos_config_size_iref;
diffpair_pmos_config_size_Lp=*Pdiffpair_pmos_config_size_Lp;
diffpair_pmos_config_size_Wp=*Pdiffpair_pmos_config_size_Wp;
diffpair_pmos_config_size_Ln=*Pdiffpair_pmos_config_size_Ln;
diffpair_pmos_config_size_Wn=*Pdiffpair_pmos_config_size_Wn;
diffpair_pmos_config_size_Ls=*Pdiffpair_pmos_config_size_Ls;
diffpair_pmos_vdd_V=*Pdiffpair_pmos_vdd_V;
diffpair_pmos_0_V=*Pdiffpair_pmos_0_V;
diffpair_pmos_status_fail=*Pdiffpair_pmos_status_fail;
diffpair_pmos_design_feedback=*Pdiffpair_pmos_design_feedback;
n_1_bin=*Pn_1_bin;
n_1_W=*Pn_1_W;
n_1_L=*Pn_1_L;
n_2_bin=*Pn_2_bin;
n_2_W=*Pn_2_W;
n_2_L=*Pn_2_L;
pin_1_bin=*Ppin_1_bin;
pin_1_W=*Ppin_1_W;
pin_1_L=*Ppin_1_L;
pin_2_bin=*Ppin_2_bin;
pin_2_W=*Ppin_2_W;
pin_2_L=*Ppin_2_L;
p_tail_bin=*Pp_tail_bin;
p_tail_W=*Pp_tail_W;
p_tail_L=*Pp_tail_L;
p_ref_bin=*Pp_ref_bin;
p_ref_W=*Pp_ref_W;
p_ref_L=*Pp_ref_L;
diffpair_pmos_leak=*Pdiffpair_pmos_leak;
diffpair_pmos_config_op_iterations=*Pdiffpair_pmos_config_op_iterations;
diffpair_pmos_config_kcl_th=*Pdiffpair_pmos_config_kcl_th;
diffpair_pmos_config_design_feedback_th=*Pdiffpair_pmos_config_design_feedback_th;
outp_V=*Poutp_V;
outm_V=*Poutm_V;
n_1_go=*Pn_1_go;
n_1_gm=*Pn_1_gm;
n_1_gb=*Pn_1_gb;
n_1_Ids=*Pn_1_Ids;
CONST_0_V=*P0_V;
n_2_go=*Pn_2_go;
n_2_gm=*Pn_2_gm;
n_2_gb=*Pn_2_gb;
n_2_Ids=*Pn_2_Ids;
vdd_V=*Pvdd_V;
tail_V=*Ptail_V;
pin_1_go=*Ppin_1_go;
pin_1_gm=*Ppin_1_gm;
pin_1_gb=*Ppin_1_gb;
pin_1_Ids=*Ppin_1_Ids;
inp_V=*Pinp_V;
pin_2_go=*Ppin_2_go;
pin_2_gm=*Ppin_2_gm;
pin_2_gb=*Ppin_2_gb;
pin_2_Ids=*Ppin_2_Ids;
inn_V=*Pinn_V;
vbias_V=*Pvbias_V;
p_tail_go=*Pp_tail_go;
p_tail_gm=*Pp_tail_gm;
p_tail_gb=*Pp_tail_gb;
p_tail_Ids=*Pp_tail_Ids;
p_ref_go=*Pp_ref_go;
p_ref_gm=*Pp_ref_gm;
p_ref_gb=*Pp_ref_gb;
p_ref_Ids=*Pp_ref_Ids;
diffpair_pmos_config_kcl_step=*Pdiffpair_pmos_config_kcl_step;
diffpair_pmos_property_Adc=*Pdiffpair_pmos_property_Adc;
diffpair_pmos_property_CMRR=*Pdiffpair_pmos_property_CMRR;
diffpair_pmos_property_PSRR=*Pdiffpair_pmos_property_PSRR;
diffpair_pmos_config_fail_on_properties=*Pdiffpair_pmos_config_fail_on_properties;
diffpair_pmos_property_Rout=*Pdiffpair_pmos_property_Rout;
pin_2_css=*Ppin_2_css;
pin_2_csd=*Ppin_2_csd;
pin_2_cds=*Ppin_2_cds;
pin_2_cdd=*Ppin_2_cdd;
pin_1_css=*Ppin_1_css;
pin_1_csd=*Ppin_1_csd;
pin_1_cds=*Ppin_1_cds;
pin_1_cdd=*Ppin_1_cdd;
p_tail_cgg=*Pp_tail_cgg;
p_tail_cgd=*Pp_tail_cgd;
p_tail_cdg=*Pp_tail_cdg;
p_tail_cdd=*Pp_tail_cdd;
p_ref_cgg=*Pp_ref_cgg;
p_ref_cgd=*Pp_ref_cgd;
p_ref_cdg=*Pp_ref_cdg;
p_ref_cdd=*Pp_ref_cdd;
n_2_cgg=*Pn_2_cgg;
n_2_cgd=*Pn_2_cgd;
n_2_cdg=*Pn_2_cdg;
n_2_cdd=*Pn_2_cdd;
n_1_cgg=*Pn_1_cgg;
n_1_cgd=*Pn_1_cgd;
n_1_cdg=*Pn_1_cdg;
n_1_cdd=*Pn_1_cdd;
diffpair_pmos_property_BW=*Pdiffpair_pmos_property_BW;
s=*Ps;
diffpair_pmos_property_BW_s=*Pdiffpair_pmos_property_BW_s;
diffpair_pmos_p1=*Pdiffpair_pmos_p1;
diffpair_pmos_p2=*Pdiffpair_pmos_p2;
diffpair_pmos_property_ts=*Pdiffpair_pmos_property_ts;
pin_1_cgs=*Ppin_1_cgs;
pin_1_cgd=*Ppin_1_cgd;
diffpair_pmos_property_Cin=*Pdiffpair_pmos_property_Cin;
diffpair_pmos_property_PM=*Pdiffpair_pmos_property_PM;
n_1_dNt_dvgs=*Pn_1_dNt_dvgs;
n_1_dNt_dvds=*Pn_1_dNt_dvds;
n_1_dNt_dvbs=*Pn_1_dNt_dvbs;
n_1_dNt_dl=*Pn_1_dNt_dl;
n_1_Nt_unit=*Pn_1_Nt_unit;
n_1_Nt=*Pn_1_Nt;
n_1_dNf_dvgs=*Pn_1_dNf_dvgs;
n_1_dNf_dvds=*Pn_1_dNf_dvds;
n_1_dNf_dvbs=*Pn_1_dNf_dvbs;
n_1_dNf_dl=*Pn_1_dNf_dl;
n_1_Nf_unit=*Pn_1_Nf_unit;
n_1_Nf=*Pn_1_Nf;
n_2_dNt_dvgs=*Pn_2_dNt_dvgs;
n_2_dNt_dvds=*Pn_2_dNt_dvds;
n_2_dNt_dvbs=*Pn_2_dNt_dvbs;
n_2_dNt_dl=*Pn_2_dNt_dl;
n_2_Nt_unit=*Pn_2_Nt_unit;
n_2_Nt=*Pn_2_Nt;
n_2_dNf_dvgs=*Pn_2_dNf_dvgs;
n_2_dNf_dvds=*Pn_2_dNf_dvds;
n_2_dNf_dvbs=*Pn_2_dNf_dvbs;
n_2_dNf_dl=*Pn_2_dNf_dl;
n_2_Nf_unit=*Pn_2_Nf_unit;
n_2_Nf=*Pn_2_Nf;
pin_1_dNt_dvgs=*Ppin_1_dNt_dvgs;
pin_1_dNt_dvds=*Ppin_1_dNt_dvds;
pin_1_dNt_dvbs=*Ppin_1_dNt_dvbs;
pin_1_dNt_dl=*Ppin_1_dNt_dl;
pin_1_Nt_unit=*Ppin_1_Nt_unit;
pin_1_Nt=*Ppin_1_Nt;
pin_1_dNf_dvgs=*Ppin_1_dNf_dvgs;
pin_1_dNf_dvds=*Ppin_1_dNf_dvds;
pin_1_dNf_dvbs=*Ppin_1_dNf_dvbs;
pin_1_dNf_dl=*Ppin_1_dNf_dl;
pin_1_Nf_unit=*Ppin_1_Nf_unit;
pin_1_Nf=*Ppin_1_Nf;
pin_2_dNt_dvgs=*Ppin_2_dNt_dvgs;
pin_2_dNt_dvds=*Ppin_2_dNt_dvds;
pin_2_dNt_dvbs=*Ppin_2_dNt_dvbs;
pin_2_dNt_dl=*Ppin_2_dNt_dl;
pin_2_Nt_unit=*Ppin_2_Nt_unit;
pin_2_Nt=*Ppin_2_Nt;
pin_2_dNf_dvgs=*Ppin_2_dNf_dvgs;
pin_2_dNf_dvds=*Ppin_2_dNf_dvds;
pin_2_dNf_dvbs=*Ppin_2_dNf_dvbs;
pin_2_dNf_dl=*Ppin_2_dNf_dl;
pin_2_Nf_unit=*Ppin_2_Nf_unit;
pin_2_Nf=*Ppin_2_Nf;
p_tail_dNt_dvgs=*Pp_tail_dNt_dvgs;
p_tail_dNt_dvds=*Pp_tail_dNt_dvds;
p_tail_dNt_dvbs=*Pp_tail_dNt_dvbs;
p_tail_dNt_dl=*Pp_tail_dNt_dl;
p_tail_Nt_unit=*Pp_tail_Nt_unit;
p_tail_Nt=*Pp_tail_Nt;
p_tail_dNf_dvgs=*Pp_tail_dNf_dvgs;
p_tail_dNf_dvds=*Pp_tail_dNf_dvds;
p_tail_dNf_dvbs=*Pp_tail_dNf_dvbs;
p_tail_dNf_dl=*Pp_tail_dNf_dl;
p_tail_Nf_unit=*Pp_tail_Nf_unit;
p_tail_Nf=*Pp_tail_Nf;
p_ref_dNt_dvgs=*Pp_ref_dNt_dvgs;
p_ref_dNt_dvds=*Pp_ref_dNt_dvds;
p_ref_dNt_dvbs=*Pp_ref_dNt_dvbs;
p_ref_dNt_dl=*Pp_ref_dNt_dl;
p_ref_Nt_unit=*Pp_ref_Nt_unit;
p_ref_Nt=*Pp_ref_Nt;
p_ref_dNf_dvgs=*Pp_ref_dNf_dvgs;
p_ref_dNf_dvds=*Pp_ref_dNf_dvds;
p_ref_dNf_dvbs=*Pp_ref_dNf_dvbs;
p_ref_dNf_dl=*Pp_ref_dNf_dl;
p_ref_Nf_unit=*Pp_ref_Nf_unit;
p_ref_Nf=*Pp_ref_Nf;
diffpair_pmos_property_Nt=*Pdiffpair_pmos_property_Nt;
diffpair_pmos_property_Nf=*Pdiffpair_pmos_property_Nf;
diffpair_pmos_property_fc=*Pdiffpair_pmos_property_fc;
diffpair_pmos_property_TotalNoise=*Pdiffpair_pmos_property_TotalNoise;
diffpair_pmos_property_Area=*Pdiffpair_pmos_property_Area;
diffpair_pmos_property_Vos=*Pdiffpair_pmos_property_Vos;
diffpair_pmos_property_Power=*Pdiffpair_pmos_property_Power;
diffpair_pmos_config_shift_Adc=*Pdiffpair_pmos_config_shift_Adc;
diffpair_pmos_config_factor_Adc=*Pdiffpair_pmos_config_factor_Adc;
diffpair_pmos_config_shift_CMRR=*Pdiffpair_pmos_config_shift_CMRR;
diffpair_pmos_config_factor_CMRR=*Pdiffpair_pmos_config_factor_CMRR;

            return TCL_OK;
        }
        static int tcl_gamma_diffpair_pmos_export_cmd(ClientData clientData,Tcl_Interp *interp,int argc,char *argv[]) {
            *Pparam_inp=param_inp;
*Pparam_inn=param_inn;
*Pparam_vdd=param_vdd;
*Psize_iref=size_iref;
*Psize_Lp=size_Lp;
*Psize_Wp=size_Wp;
*Psize_Ln=size_Ln;
*Psize_Wn=size_Wn;
*Psize_Ls=size_Ls;
*Pproperty_Adc=property_Adc;
*Pproperty_CMRR=property_CMRR;
*Pdiffpair_pmos_config_pat_size_target=diffpair_pmos_config_pat_size_target;
*Psize_iref_min=size_iref_min;
*Psize_iref_max=size_iref_max;
*Pdiffpair_pmos_size_iref=diffpair_pmos_size_iref;
*Psize_Lp_min=size_Lp_min;
*Psize_Lp_max=size_Lp_max;
*Pdiffpair_pmos_size_Lp=diffpair_pmos_size_Lp;
*Psize_Wp_max=size_Wp_max;
*Pdiffpair_pmos_size_Wp=diffpair_pmos_size_Wp;
*Psize_Ln_min=size_Ln_min;
*Psize_Ln_max=size_Ln_max;
*Pdiffpair_pmos_size_Ln=diffpair_pmos_size_Ln;
*Psize_Wn_max=size_Wn_max;
*Pdiffpair_pmos_size_Wn=diffpair_pmos_size_Wn;
*Psize_Ls_min=size_Ls_min;
*Psize_Ls_max=size_Ls_max;
*Pdiffpair_pmos_size_Ls=diffpair_pmos_size_Ls;
*Psize_iref_step=size_iref_step;
*Psize_Lp_step=size_Lp_step;
*Psize_Wp_step=size_Wp_step;
*Psize_Ln_step=size_Ln_step;
*Psize_Wn_step=size_Wn_step;
*Psize_Ls_step=size_Ls_step;
*Pdiffpair_pmos_max_Adc=diffpair_pmos_max_Adc;
*Pdiffpair_pmos_param_unique=diffpair_pmos_param_unique;
*Pdiffpair_pmos_pat_size_target=diffpair_pmos_pat_size_target;
*Pdiffpair_pmos_size_iref_step=diffpair_pmos_size_iref_step;
*Pdiffpair_pmos_size_Lp_step=diffpair_pmos_size_Lp_step;
*Pdiffpair_pmos_size_Wp_step=diffpair_pmos_size_Wp_step;
*Pdiffpair_pmos_size_Ln_step=diffpair_pmos_size_Ln_step;
*Pdiffpair_pmos_size_Wn_step=diffpair_pmos_size_Wn_step;
*Pdiffpair_pmos_size_Ls_step=diffpair_pmos_size_Ls_step;
*Pdiffpair_pmos_circuit_breed_id=diffpair_pmos_circuit_breed_id;
*Pdiffpair_pmos_circuit_breed_target=diffpair_pmos_circuit_breed_target;
*Pdiffpair_pmos_mode_freash_op=diffpair_pmos_mode_freash_op;
*Pdiffpair_pmos_status_index=diffpair_pmos_status_index;
*Pdiffpair_pmos_config_size_iref=diffpair_pmos_config_size_iref;
*Pdiffpair_pmos_config_size_Lp=diffpair_pmos_config_size_Lp;
*Pdiffpair_pmos_config_size_Wp=diffpair_pmos_config_size_Wp;
*Pdiffpair_pmos_config_size_Ln=diffpair_pmos_config_size_Ln;
*Pdiffpair_pmos_config_size_Wn=diffpair_pmos_config_size_Wn;
*Pdiffpair_pmos_config_size_Ls=diffpair_pmos_config_size_Ls;
*Pdiffpair_pmos_vdd_V=diffpair_pmos_vdd_V;
*Pdiffpair_pmos_0_V=diffpair_pmos_0_V;
*Pdiffpair_pmos_status_fail=diffpair_pmos_status_fail;
*Pdiffpair_pmos_design_feedback=diffpair_pmos_design_feedback;
*Pn_1_bin=n_1_bin;
*Pn_1_W=n_1_W;
*Pn_1_L=n_1_L;
*Pn_2_bin=n_2_bin;
*Pn_2_W=n_2_W;
*Pn_2_L=n_2_L;
*Ppin_1_bin=pin_1_bin;
*Ppin_1_W=pin_1_W;
*Ppin_1_L=pin_1_L;
*Ppin_2_bin=pin_2_bin;
*Ppin_2_W=pin_2_W;
*Ppin_2_L=pin_2_L;
*Pp_tail_bin=p_tail_bin;
*Pp_tail_W=p_tail_W;
*Pp_tail_L=p_tail_L;
*Pp_ref_bin=p_ref_bin;
*Pp_ref_W=p_ref_W;
*Pp_ref_L=p_ref_L;
*Pdiffpair_pmos_leak=diffpair_pmos_leak;
*Pdiffpair_pmos_config_op_iterations=diffpair_pmos_config_op_iterations;
*Pdiffpair_pmos_config_kcl_th=diffpair_pmos_config_kcl_th;
*Pdiffpair_pmos_config_design_feedback_th=diffpair_pmos_config_design_feedback_th;
*Poutp_V=outp_V;
*Poutm_V=outm_V;
*Pn_1_go=n_1_go;
*Pn_1_gm=n_1_gm;
*Pn_1_gb=n_1_gb;
*Pn_1_Ids=n_1_Ids;
*P0_V=CONST_0_V;
*Pn_2_go=n_2_go;
*Pn_2_gm=n_2_gm;
*Pn_2_gb=n_2_gb;
*Pn_2_Ids=n_2_Ids;
*Pvdd_V=vdd_V;
*Ptail_V=tail_V;
*Ppin_1_go=pin_1_go;
*Ppin_1_gm=pin_1_gm;
*Ppin_1_gb=pin_1_gb;
*Ppin_1_Ids=pin_1_Ids;
*Pinp_V=inp_V;
*Ppin_2_go=pin_2_go;
*Ppin_2_gm=pin_2_gm;
*Ppin_2_gb=pin_2_gb;
*Ppin_2_Ids=pin_2_Ids;
*Pinn_V=inn_V;
*Pvbias_V=vbias_V;
*Pp_tail_go=p_tail_go;
*Pp_tail_gm=p_tail_gm;
*Pp_tail_gb=p_tail_gb;
*Pp_tail_Ids=p_tail_Ids;
*Pp_ref_go=p_ref_go;
*Pp_ref_gm=p_ref_gm;
*Pp_ref_gb=p_ref_gb;
*Pp_ref_Ids=p_ref_Ids;
*Pdiffpair_pmos_config_kcl_step=diffpair_pmos_config_kcl_step;
*Pdiffpair_pmos_property_Adc=diffpair_pmos_property_Adc;
*Pdiffpair_pmos_property_CMRR=diffpair_pmos_property_CMRR;
*Pdiffpair_pmos_property_PSRR=diffpair_pmos_property_PSRR;
*Pdiffpair_pmos_config_fail_on_properties=diffpair_pmos_config_fail_on_properties;
*Pdiffpair_pmos_property_Rout=diffpair_pmos_property_Rout;
*Ppin_2_css=pin_2_css;
*Ppin_2_csd=pin_2_csd;
*Ppin_2_cds=pin_2_cds;
*Ppin_2_cdd=pin_2_cdd;
*Ppin_1_css=pin_1_css;
*Ppin_1_csd=pin_1_csd;
*Ppin_1_cds=pin_1_cds;
*Ppin_1_cdd=pin_1_cdd;
*Pp_tail_cgg=p_tail_cgg;
*Pp_tail_cgd=p_tail_cgd;
*Pp_tail_cdg=p_tail_cdg;
*Pp_tail_cdd=p_tail_cdd;
*Pp_ref_cgg=p_ref_cgg;
*Pp_ref_cgd=p_ref_cgd;
*Pp_ref_cdg=p_ref_cdg;
*Pp_ref_cdd=p_ref_cdd;
*Pn_2_cgg=n_2_cgg;
*Pn_2_cgd=n_2_cgd;
*Pn_2_cdg=n_2_cdg;
*Pn_2_cdd=n_2_cdd;
*Pn_1_cgg=n_1_cgg;
*Pn_1_cgd=n_1_cgd;
*Pn_1_cdg=n_1_cdg;
*Pn_1_cdd=n_1_cdd;
*Pdiffpair_pmos_property_BW=diffpair_pmos_property_BW;
*Ps=s;
*Pdiffpair_pmos_property_BW_s=diffpair_pmos_property_BW_s;
*Pdiffpair_pmos_p1=diffpair_pmos_p1;
*Pdiffpair_pmos_p2=diffpair_pmos_p2;
*Pdiffpair_pmos_property_ts=diffpair_pmos_property_ts;
*Ppin_1_cgs=pin_1_cgs;
*Ppin_1_cgd=pin_1_cgd;
*Pdiffpair_pmos_property_Cin=diffpair_pmos_property_Cin;
*Pdiffpair_pmos_property_PM=diffpair_pmos_property_PM;
*Pn_1_dNt_dvgs=n_1_dNt_dvgs;
*Pn_1_dNt_dvds=n_1_dNt_dvds;
*Pn_1_dNt_dvbs=n_1_dNt_dvbs;
*Pn_1_dNt_dl=n_1_dNt_dl;
*Pn_1_Nt_unit=n_1_Nt_unit;
*Pn_1_Nt=n_1_Nt;
*Pn_1_dNf_dvgs=n_1_dNf_dvgs;
*Pn_1_dNf_dvds=n_1_dNf_dvds;
*Pn_1_dNf_dvbs=n_1_dNf_dvbs;
*Pn_1_dNf_dl=n_1_dNf_dl;
*Pn_1_Nf_unit=n_1_Nf_unit;
*Pn_1_Nf=n_1_Nf;
*Pn_2_dNt_dvgs=n_2_dNt_dvgs;
*Pn_2_dNt_dvds=n_2_dNt_dvds;
*Pn_2_dNt_dvbs=n_2_dNt_dvbs;
*Pn_2_dNt_dl=n_2_dNt_dl;
*Pn_2_Nt_unit=n_2_Nt_unit;
*Pn_2_Nt=n_2_Nt;
*Pn_2_dNf_dvgs=n_2_dNf_dvgs;
*Pn_2_dNf_dvds=n_2_dNf_dvds;
*Pn_2_dNf_dvbs=n_2_dNf_dvbs;
*Pn_2_dNf_dl=n_2_dNf_dl;
*Pn_2_Nf_unit=n_2_Nf_unit;
*Pn_2_Nf=n_2_Nf;
*Ppin_1_dNt_dvgs=pin_1_dNt_dvgs;
*Ppin_1_dNt_dvds=pin_1_dNt_dvds;
*Ppin_1_dNt_dvbs=pin_1_dNt_dvbs;
*Ppin_1_dNt_dl=pin_1_dNt_dl;
*Ppin_1_Nt_unit=pin_1_Nt_unit;
*Ppin_1_Nt=pin_1_Nt;
*Ppin_1_dNf_dvgs=pin_1_dNf_dvgs;
*Ppin_1_dNf_dvds=pin_1_dNf_dvds;
*Ppin_1_dNf_dvbs=pin_1_dNf_dvbs;
*Ppin_1_dNf_dl=pin_1_dNf_dl;
*Ppin_1_Nf_unit=pin_1_Nf_unit;
*Ppin_1_Nf=pin_1_Nf;
*Ppin_2_dNt_dvgs=pin_2_dNt_dvgs;
*Ppin_2_dNt_dvds=pin_2_dNt_dvds;
*Ppin_2_dNt_dvbs=pin_2_dNt_dvbs;
*Ppin_2_dNt_dl=pin_2_dNt_dl;
*Ppin_2_Nt_unit=pin_2_Nt_unit;
*Ppin_2_Nt=pin_2_Nt;
*Ppin_2_dNf_dvgs=pin_2_dNf_dvgs;
*Ppin_2_dNf_dvds=pin_2_dNf_dvds;
*Ppin_2_dNf_dvbs=pin_2_dNf_dvbs;
*Ppin_2_dNf_dl=pin_2_dNf_dl;
*Ppin_2_Nf_unit=pin_2_Nf_unit;
*Ppin_2_Nf=pin_2_Nf;
*Pp_tail_dNt_dvgs=p_tail_dNt_dvgs;
*Pp_tail_dNt_dvds=p_tail_dNt_dvds;
*Pp_tail_dNt_dvbs=p_tail_dNt_dvbs;
*Pp_tail_dNt_dl=p_tail_dNt_dl;
*Pp_tail_Nt_unit=p_tail_Nt_unit;
*Pp_tail_Nt=p_tail_Nt;
*Pp_tail_dNf_dvgs=p_tail_dNf_dvgs;
*Pp_tail_dNf_dvds=p_tail_dNf_dvds;
*Pp_tail_dNf_dvbs=p_tail_dNf_dvbs;
*Pp_tail_dNf_dl=p_tail_dNf_dl;
*Pp_tail_Nf_unit=p_tail_Nf_unit;
*Pp_tail_Nf=p_tail_Nf;
*Pp_ref_dNt_dvgs=p_ref_dNt_dvgs;
*Pp_ref_dNt_dvds=p_ref_dNt_dvds;
*Pp_ref_dNt_dvbs=p_ref_dNt_dvbs;
*Pp_ref_dNt_dl=p_ref_dNt_dl;
*Pp_ref_Nt_unit=p_ref_Nt_unit;
*Pp_ref_Nt=p_ref_Nt;
*Pp_ref_dNf_dvgs=p_ref_dNf_dvgs;
*Pp_ref_dNf_dvds=p_ref_dNf_dvds;
*Pp_ref_dNf_dvbs=p_ref_dNf_dvbs;
*Pp_ref_dNf_dl=p_ref_dNf_dl;
*Pp_ref_Nf_unit=p_ref_Nf_unit;
*Pp_ref_Nf=p_ref_Nf;
*Pdiffpair_pmos_property_Nt=diffpair_pmos_property_Nt;
*Pdiffpair_pmos_property_Nf=diffpair_pmos_property_Nf;
*Pdiffpair_pmos_property_fc=diffpair_pmos_property_fc;
*Pdiffpair_pmos_property_TotalNoise=diffpair_pmos_property_TotalNoise;
*Pdiffpair_pmos_property_Area=diffpair_pmos_property_Area;
*Pdiffpair_pmos_property_Vos=diffpair_pmos_property_Vos;
*Pdiffpair_pmos_property_Power=diffpair_pmos_property_Power;
*Pdiffpair_pmos_config_shift_Adc=diffpair_pmos_config_shift_Adc;
*Pdiffpair_pmos_config_factor_Adc=diffpair_pmos_config_factor_Adc;
*Pdiffpair_pmos_config_shift_CMRR=diffpair_pmos_config_shift_CMRR;
*Pdiffpair_pmos_config_factor_CMRR=diffpair_pmos_config_factor_CMRR;

            return TCL_OK;
        }
        static int tcl_gamma_diffpair_pmos_op_cmd(ClientData clientData,Tcl_Interp *interp,int argc,char *argv[]) {
            //            Tcl_ResetResult(interp);
            if (diffpair_pmos_mode_freash_op) {
}
diffpair_pmos_status_index=0;
if(diffpair_pmos_config_size_iref!=0) diffpair_pmos_size_iref=diffpair_pmos_config_size_iref;
if(diffpair_pmos_config_size_Lp!=0) diffpair_pmos_size_Lp=diffpair_pmos_config_size_Lp;
if(diffpair_pmos_config_size_Wp!=0) diffpair_pmos_size_Wp=diffpair_pmos_config_size_Wp;
if(diffpair_pmos_config_size_Ln!=0) diffpair_pmos_size_Ln=diffpair_pmos_config_size_Ln;
if(diffpair_pmos_config_size_Wn!=0) diffpair_pmos_size_Wn=diffpair_pmos_config_size_Wn;
if(diffpair_pmos_config_size_Ls!=0) diffpair_pmos_size_Ls=diffpair_pmos_config_size_Ls;
diffpair_pmos_vdd_V=1.1;
diffpair_pmos_0_V=0;
// Calculating circuit operating point:
int op_it=0;
diffpair_pmos_status_fail=-1;
diffpair_pmos_design_feedback=1000;
n_1_bin=get_transistor_bin(Plook_up_tables_nch_binning_LUT,n_1_L,n_1_W);
n_2_bin=get_transistor_bin(Plook_up_tables_nch_binning_LUT,n_2_L,n_2_W);
pin_1_bin=get_transistor_bin(Plook_up_tables_pch_binning_LUT,pin_1_L,pin_1_W);
pin_2_bin=get_transistor_bin(Plook_up_tables_pch_binning_LUT,pin_2_L,pin_2_W);
p_tail_bin=get_transistor_bin(Plook_up_tables_pch_binning_LUT,p_tail_L,p_tail_W);
p_ref_bin=get_transistor_bin(Plook_up_tables_pch_binning_LUT,p_ref_L,p_ref_W);
diffpair_pmos_leak=1e3;
float node_step=0;
for (op_it=0;(op_it<diffpair_pmos_config_op_iterations)&&((diffpair_pmos_leak>diffpair_pmos_config_kcl_th)||(diffpair_pmos_design_feedback>diffpair_pmos_config_design_feedback_th));op_it++) {
float previous_out_dc=outp_V;
composite_gamma_gcc_interpolate_2p3(n_1_bin,Pdiffpair_pmos_look_up_tables_nch_Ids_ss_CONTEXT,Pdiffpair_pmos_look_up_tables_nch_gm_ss_CONTEXT,Pdiffpair_pmos_look_up_tables_nch_go_ss_CONTEXT,Pdiffpair_pmos_look_up_tables_nch_gb_ss_CONTEXT,&(n_1_gb),&(n_1_gm),&(n_1_go),&(n_1_Ids),(outm_V)-(CONST_0_V),(outm_V)-(CONST_0_V),(CONST_0_V)-(CONST_0_V),size_Ln,size_Wn);
if (n_1_Ids<0) n_1_Ids=0;
if (n_1_Ids>1e-3) n_1_Ids=1e-3;
composite_gamma_gcc_interpolate_2p3(n_2_bin,Pdiffpair_pmos_look_up_tables_nch_Ids_ss_CONTEXT,Pdiffpair_pmos_look_up_tables_nch_gm_ss_CONTEXT,Pdiffpair_pmos_look_up_tables_nch_go_ss_CONTEXT,Pdiffpair_pmos_look_up_tables_nch_gb_ss_CONTEXT,&(n_2_gb),&(n_2_gm),&(n_2_go),&(n_2_Ids),(outm_V)-(CONST_0_V),(outp_V)-(CONST_0_V),(CONST_0_V)-(CONST_0_V),size_Ln,size_Wn);
if (n_2_Ids<0) n_2_Ids=0;
if (n_2_Ids>1e-3) n_2_Ids=1e-3;
composite_gamma_gcc_interpolate_2p3(pin_1_bin,Pdiffpair_pmos_look_up_tables_pch_Ids_ss_CONTEXT,Pdiffpair_pmos_look_up_tables_pch_gm_ss_CONTEXT,Pdiffpair_pmos_look_up_tables_pch_go_ss_CONTEXT,Pdiffpair_pmos_look_up_tables_pch_gb_ss_CONTEXT,&(pin_1_gb),&(pin_1_gm),&(pin_1_go),&(pin_1_Ids),(inp_V)-(tail_V),(outm_V)-(tail_V),(vdd_V)-(tail_V),size_Lp,size_Wp);
if (pin_1_Ids<0) pin_1_Ids=0;
if (pin_1_Ids>1e-3) pin_1_Ids=1e-3;
pin_1_Ids=-pin_1_Ids;
composite_gamma_gcc_interpolate_2p3(pin_2_bin,Pdiffpair_pmos_look_up_tables_pch_Ids_ss_CONTEXT,Pdiffpair_pmos_look_up_tables_pch_gm_ss_CONTEXT,Pdiffpair_pmos_look_up_tables_pch_go_ss_CONTEXT,Pdiffpair_pmos_look_up_tables_pch_gb_ss_CONTEXT,&(pin_2_gb),&(pin_2_gm),&(pin_2_go),&(pin_2_Ids),(inn_V)-(tail_V),(outp_V)-(tail_V),(vdd_V)-(tail_V),size_Lp,size_Wp);
if (pin_2_Ids<0) pin_2_Ids=0;
if (pin_2_Ids>1e-3) pin_2_Ids=1e-3;
pin_2_Ids=-pin_2_Ids;
composite_gamma_gcc_interpolate_2p3(p_tail_bin,Pdiffpair_pmos_look_up_tables_pch_Ids_ss_CONTEXT,Pdiffpair_pmos_look_up_tables_pch_gm_ss_CONTEXT,Pdiffpair_pmos_look_up_tables_pch_go_ss_CONTEXT,Pdiffpair_pmos_look_up_tables_pch_gb_ss_CONTEXT,&(p_tail_gb),&(p_tail_gm),&(p_tail_go),&(p_tail_Ids),(vbias_V)-(vdd_V),(tail_V)-(vdd_V),(vdd_V)-(vdd_V),size_Ls,size_Ls*2*size_Wp/size_Lp);
if (p_tail_Ids<0) p_tail_Ids=0;
if (p_tail_Ids>1e-3) p_tail_Ids=1e-3;
p_tail_Ids=-p_tail_Ids;
composite_gamma_gcc_interpolate_2p3(p_ref_bin,Pdiffpair_pmos_look_up_tables_pch_Ids_ss_CONTEXT,Pdiffpair_pmos_look_up_tables_pch_gm_ss_CONTEXT,Pdiffpair_pmos_look_up_tables_pch_go_ss_CONTEXT,Pdiffpair_pmos_look_up_tables_pch_gb_ss_CONTEXT,&(p_ref_gb),&(p_ref_gm),&(p_ref_go),&(p_ref_Ids),(vbias_V)-(vdd_V),(vbias_V)-(vdd_V),(vdd_V)-(vdd_V),size_Ls,size_Ls*2*size_Wp/size_Lp);
if (p_ref_Ids<0) p_ref_Ids=0;
if (p_ref_Ids>1e-3) p_ref_Ids=1e-3;
p_ref_Ids=-p_ref_Ids;
if (n_1_gm==0) n_1_gm=1e-6;
if (n_1_go==0) n_1_go=1e-6;
if (n_2_gm==0) n_2_gm=1e-6;
if (n_2_go==0) n_2_go=1e-6;
if (pin_1_gm==0) pin_1_gm=1e-6;
if (pin_1_go==0) pin_1_go=1e-6;
if (pin_2_gm==0) pin_2_gm=1e-6;
if (pin_2_go==0) pin_2_go=1e-6;
if (p_tail_gm==0) p_tail_gm=1e-6;
if (p_tail_go==0) p_tail_go=1e-6;
if (p_ref_gm==0) p_ref_gm=1e-6;
if (p_ref_go==0) p_ref_go=1e-6;
// Updating node voltages
diffpair_pmos_leak=0;
node_step=diffpair_pmos_config_kcl_step*(-n_1_Ids-pin_1_Ids)/(n_1_go+n_1_gm+pin_1_go);
if (node_step<-0.02) node_step=-0.02;
if (node_step>0.02) node_step=0.02;
outm_V+=node_step;
if (fabs(-n_1_Ids-pin_1_Ids)>diffpair_pmos_leak) diffpair_pmos_leak=fabs(-n_1_Ids-pin_1_Ids);
if (outm_V<0) outm_V=0;
if (outm_V>1.1) outm_V=1.1;
node_step=diffpair_pmos_config_kcl_step*(-n_2_Ids-pin_2_Ids)/(n_2_go+pin_2_go);
if (node_step<-0.02) node_step=-0.02;
if (node_step>0.02) node_step=0.02;
outp_V+=node_step;
if (fabs(-n_2_Ids-pin_2_Ids)>diffpair_pmos_leak) diffpair_pmos_leak=fabs(-n_2_Ids-pin_2_Ids);
if (outp_V<0) outp_V=0;
if (outp_V>1.1) outp_V=1.1;
node_step=diffpair_pmos_config_kcl_step*(-p_tail_Ids+pin_2_Ids+pin_1_Ids)/(pin_1_go+pin_1_gm+pin_1_gb+pin_2_go+pin_2_gm+pin_2_gb+p_tail_go);
if (node_step<-0.02) node_step=-0.02;
if (node_step>0.02) node_step=0.02;
tail_V+=node_step;
if (fabs(-p_tail_Ids+pin_2_Ids+pin_1_Ids)>diffpair_pmos_leak) diffpair_pmos_leak=fabs(-p_tail_Ids+pin_2_Ids+pin_1_Ids);
if (tail_V<0) tail_V=0;
if (tail_V>1.1) tail_V=1.1;
node_step=diffpair_pmos_config_kcl_step*(size_iref-p_ref_Ids)/(p_ref_go+p_ref_gm);
if (node_step<-0.02) node_step=-0.02;
if (node_step>0.02) node_step=0.02;
vbias_V+=node_step;
if (fabs(size_iref-p_ref_Ids)>diffpair_pmos_leak) diffpair_pmos_leak=fabs(size_iref-p_ref_Ids);
if (vbias_V<0) vbias_V=0;
if (vbias_V>1.1) vbias_V=1.1;
diffpair_pmos_design_feedback=0;
}
if (op_it>=diffpair_pmos_config_op_iterations) {diffpair_pmos_status_fail=diffpair_pmos_leak; return TCL_ERROR;}
if (CONST_0_V>outm_V) {diffpair_pmos_status_fail=3; return TCL_ERROR;}
if (CONST_0_V>outp_V) {diffpair_pmos_status_fail=3; return TCL_ERROR;}
if (tail_V<outm_V) {diffpair_pmos_status_fail=4; return TCL_ERROR;}
if (tail_V<outp_V) {diffpair_pmos_status_fail=4; return TCL_ERROR;}
if (vdd_V<tail_V) {diffpair_pmos_status_fail=4; return TCL_ERROR;}
if (vdd_V<vbias_V) {diffpair_pmos_status_fail=4; return TCL_ERROR;}
float W,M;
double Det=(-(((n_1_go+n_1_gm)+pin_1_go)*((n_2_go+pin_2_go)*((((((pin_1_go+pin_1_gm)+pin_1_gb)+pin_2_go)+pin_2_gm)+pin_2_gb)+p_tail_go)*(p_ref_go+p_ref_gm)-(((-pin_2_go)-pin_2_gm)-pin_2_gb)*(-pin_2_go)*(p_ref_go+p_ref_gm))+(((-pin_1_go)-pin_1_gm)-pin_1_gb)*(n_2_gm*(-pin_2_go)*(p_ref_go+p_ref_gm)-(n_2_go+pin_2_go)*(-pin_1_go)*(p_ref_go+p_ref_gm))));
double Ted=1/Det;
double der_p=(-0);
double der_n=(-0);
diffpair_pmos_property_Adc=0.5*Ted*(fabs(der_p)+fabs(der_n));
diffpair_pmos_property_CMRR=Ted*(fabs(der_p)-fabs(der_n));
diffpair_pmos_property_PSRR=Ted*((-0));
diffpair_pmos_property_Adc=fabs(diffpair_pmos_property_Adc);
if ((diffpair_pmos_property_Adc<1)&&(diffpair_pmos_config_fail_on_properties)) {diffpair_pmos_status_fail=2; return TCL_ERROR;}
diffpair_pmos_property_Rout=fabs(((-(((n_1_go+n_1_gm)+pin_1_go)*((((((pin_1_go+pin_1_gm)+pin_1_gb)+pin_2_go)+pin_2_gm)+pin_2_gb)+p_tail_go)*(p_ref_go+p_ref_gm)+(((-pin_1_go)-pin_1_gm)-pin_1_gb)*(-(-pin_1_go)*(p_ref_go+p_ref_gm)))))*Ted);
float s=-1;
int BW_it;
W=0;
float BW_Mag0=1;
float BW_Mag=1;
float snr;
float sni;
float sdr;
float sdi;
while ((BW_Mag0/BW_Mag)<2) {
      snr=0;
      sni=0;
      sdr=-((n_1_go+n_1_gm+pin_1_go)*((n_2_go+pin_2_go)*((pin_1_go+pin_1_gm+pin_1_gb+pin_2_go+pin_2_gm+pin_2_gb+p_tail_go)*(p_ref_go+p_ref_gm)-(pin_1_css*W+pin_2_css*W+p_tail_cdd*W)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+p_tail_cdg*W*p_tail_cgd*W)-(n_2_cdd*W+pin_2_cdd*W)*((pin_1_go+pin_1_gm+pin_1_gb+pin_2_go+pin_2_gm+pin_2_gb+p_tail_go)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+(pin_1_css*W+pin_2_css*W+p_tail_cdd*W)*(p_ref_go+p_ref_gm)-p_tail_gm*p_tail_cgd*W)-((-pin_2_go-pin_2_gm-pin_2_gb)*(-pin_2_go)-pin_2_cds*W*pin_2_csd*W)*(p_ref_go+p_ref_gm)-((-pin_2_go-pin_2_gm-pin_2_gb)*pin_2_csd*W+pin_2_cds*W*(-pin_2_go))*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W))-(n_1_cgd*W+n_1_cgg*W+n_1_cdd*W+n_1_cdg*W+n_2_cgg*W+pin_1_cdd*W)*((n_2_go+pin_2_go)*((pin_1_go+pin_1_gm+pin_1_gb+pin_2_go+pin_2_gm+pin_2_gb+p_tail_go)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+(pin_1_css*W+pin_2_css*W+p_tail_cdd*W)*(p_ref_go+p_ref_gm)-p_tail_gm*p_tail_cgd*W)+(n_2_cdd*W+pin_2_cdd*W)*((pin_1_go+pin_1_gm+pin_1_gb+pin_2_go+pin_2_gm+pin_2_gb+p_tail_go)*(p_ref_go+p_ref_gm)-(pin_1_css*W+pin_2_css*W+p_tail_cdd*W)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+p_tail_cdg*W*p_tail_cgd*W)-((-pin_2_go-pin_2_gm-pin_2_gb)*(-pin_2_go)-pin_2_cds*W*pin_2_csd*W)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+((-pin_2_go-pin_2_gm-pin_2_gb)*pin_2_csd*W+pin_2_cds*W*(-pin_2_go))*(p_ref_go+p_ref_gm))+(n_2_cgd*W*(n_2_gm*((pin_1_go+pin_1_gm+pin_1_gb+pin_2_go+pin_2_gm+pin_2_gb+p_tail_go)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+(pin_1_css*W+pin_2_css*W+p_tail_cdd*W)*(p_ref_go+p_ref_gm)-p_tail_gm*p_tail_cgd*W)+n_2_cdg*W*((pin_1_go+pin_1_gm+pin_1_gb+pin_2_go+pin_2_gm+pin_2_gb+p_tail_go)*(p_ref_go+p_ref_gm)-(pin_1_css*W+pin_2_css*W+p_tail_cdd*W)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+p_tail_cdg*W*p_tail_cgd*W)-((-pin_2_go-pin_2_gm-pin_2_gb)*(-pin_1_go)-pin_2_cds*W*pin_1_csd*W)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+((-pin_2_go-pin_2_gm-pin_2_gb)*pin_1_csd*W+pin_2_cds*W*(-pin_1_go))*(p_ref_go+p_ref_gm)))+(-pin_1_go-pin_1_gm-pin_1_gb)*((n_2_gm*(-pin_2_go)-n_2_cdg*W*pin_2_csd*W)*(p_ref_go+p_ref_gm)-(n_2_gm*pin_2_csd*W+n_2_cdg*W*(-pin_2_go))*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)-((n_2_go+pin_2_go)*(-pin_1_go)-(n_2_cdd*W+pin_2_cdd*W)*pin_1_csd*W)*(p_ref_go+p_ref_gm)-((n_2_go+pin_2_go)*pin_1_csd*W+(n_2_cdd*W+pin_2_cdd*W)*(-pin_1_go))*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W))-pin_1_cds*W*((n_2_gm*(-pin_2_go)-n_2_cdg*W*pin_2_csd*W)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+(n_2_gm*pin_2_csd*W+n_2_cdg*W*(-pin_2_go))*(p_ref_go+p_ref_gm)-((n_2_go+pin_2_go)*(-pin_1_go)-(n_2_cdd*W+pin_2_cdd*W)*pin_1_csd*W)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+((n_2_go+pin_2_go)*pin_1_csd*W+(n_2_cdd*W+pin_2_cdd*W)*(-pin_1_go))*(p_ref_go+p_ref_gm)));
      sdi=-((n_1_go+n_1_gm+pin_1_go)*((n_2_go+pin_2_go)*((pin_1_go+pin_1_gm+pin_1_gb+pin_2_go+pin_2_gm+pin_2_gb+p_tail_go)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+(pin_1_css*W+pin_2_css*W+p_tail_cdd*W)*(p_ref_go+p_ref_gm)-p_tail_gm*p_tail_cgd*W)+(n_2_cdd*W+pin_2_cdd*W)*((pin_1_go+pin_1_gm+pin_1_gb+pin_2_go+pin_2_gm+pin_2_gb+p_tail_go)*(p_ref_go+p_ref_gm)-(pin_1_css*W+pin_2_css*W+p_tail_cdd*W)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+p_tail_cdg*W*p_tail_cgd*W)-((-pin_2_go-pin_2_gm-pin_2_gb)*(-pin_2_go)-pin_2_cds*W*pin_2_csd*W)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+((-pin_2_go-pin_2_gm-pin_2_gb)*pin_2_csd*W+pin_2_cds*W*(-pin_2_go))*(p_ref_go+p_ref_gm))+(n_1_cgd*W+n_1_cgg*W+n_1_cdd*W+n_1_cdg*W+n_2_cgg*W+pin_1_cdd*W)*((n_2_go+pin_2_go)*((pin_1_go+pin_1_gm+pin_1_gb+pin_2_go+pin_2_gm+pin_2_gb+p_tail_go)*(p_ref_go+p_ref_gm)-(pin_1_css*W+pin_2_css*W+p_tail_cdd*W)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+p_tail_cdg*W*p_tail_cgd*W)-(n_2_cdd*W+pin_2_cdd*W)*((pin_1_go+pin_1_gm+pin_1_gb+pin_2_go+pin_2_gm+pin_2_gb+p_tail_go)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+(pin_1_css*W+pin_2_css*W+p_tail_cdd*W)*(p_ref_go+p_ref_gm)-p_tail_gm*p_tail_cgd*W)-((-pin_2_go-pin_2_gm-pin_2_gb)*(-pin_2_go)-pin_2_cds*W*pin_2_csd*W)*(p_ref_go+p_ref_gm)-((-pin_2_go-pin_2_gm-pin_2_gb)*pin_2_csd*W+pin_2_cds*W*(-pin_2_go))*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W))-n_2_cgd*W*(n_2_gm*((pin_1_go+pin_1_gm+pin_1_gb+pin_2_go+pin_2_gm+pin_2_gb+p_tail_go)*(p_ref_go+p_ref_gm)-(pin_1_css*W+pin_2_css*W+p_tail_cdd*W)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+p_tail_cdg*W*p_tail_cgd*W)-n_2_cdg*W*((pin_1_go+pin_1_gm+pin_1_gb+pin_2_go+pin_2_gm+pin_2_gb+p_tail_go)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+(pin_1_css*W+pin_2_css*W+p_tail_cdd*W)*(p_ref_go+p_ref_gm)-p_tail_gm*p_tail_cgd*W)-((-pin_2_go-pin_2_gm-pin_2_gb)*(-pin_1_go)-pin_2_cds*W*pin_1_csd*W)*(p_ref_go+p_ref_gm)-((-pin_2_go-pin_2_gm-pin_2_gb)*pin_1_csd*W+pin_2_cds*W*(-pin_1_go))*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W))+(-pin_1_go-pin_1_gm-pin_1_gb)*((n_2_gm*(-pin_2_go)-n_2_cdg*W*pin_2_csd*W)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+(n_2_gm*pin_2_csd*W+n_2_cdg*W*(-pin_2_go))*(p_ref_go+p_ref_gm)-((n_2_go+pin_2_go)*(-pin_1_go)-(n_2_cdd*W+pin_2_cdd*W)*pin_1_csd*W)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+((n_2_go+pin_2_go)*pin_1_csd*W+(n_2_cdd*W+pin_2_cdd*W)*(-pin_1_go))*(p_ref_go+p_ref_gm))+pin_1_cds*W*((n_2_gm*(-pin_2_go)-n_2_cdg*W*pin_2_csd*W)*(p_ref_go+p_ref_gm)-(n_2_gm*pin_2_csd*W+n_2_cdg*W*(-pin_2_go))*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)-((n_2_go+pin_2_go)*(-pin_1_go)-(n_2_cdd*W+pin_2_cdd*W)*pin_1_csd*W)*(p_ref_go+p_ref_gm)-((n_2_go+pin_2_go)*pin_1_csd*W+(n_2_cdd*W+pin_2_cdd*W)*(-pin_1_go))*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)));
      BW_Mag=(snr*snr+sni*sni)/(sdr*sdr+sdi*sdi);
      if (W==0) BW_Mag0=BW_Mag;
      if (W==0) W=1; else W*=1.01;
}
diffpair_pmos_property_BW=fabs(W/(2*3.141592656));
for (BW_it=0;BW_it<5;BW_it++)  s-=((-((((((((((n_1_go+n_1_gm)+n_1_cgd*s)+n_1_cgg*s)+n_1_cdd*s)+n_1_cdg*s)+n_2_cgg*s)+pin_1_go)+pin_1_cdd*s)*((((n_2_go+n_2_cdd*s)+pin_2_go)+pin_2_cdd*s)*((((((((((pin_1_go+pin_1_gm)+pin_1_gb)+pin_1_css*s)+pin_2_go)+pin_2_gm)+pin_2_gb)+pin_2_css*s)+p_tail_go)+p_tail_cdd*s)*((((((p_tail_cgg*s+p_ref_go)+p_ref_gm)+p_ref_cgd*s)+p_ref_cgg*s)+p_ref_cdd*s)+p_ref_cdg*s)-(p_tail_gm+p_tail_cdg*s)*p_tail_cgd*s)-((((-pin_2_go)-pin_2_gm)-pin_2_gb)+pin_2_cds*s)*((-pin_2_go)+pin_2_csd*s)*((((((p_tail_cgg*s+p_ref_go)+p_ref_gm)+p_ref_cgd*s)+p_ref_cgg*s)+p_ref_cdd*s)+p_ref_cdg*s))-n_2_cgd*s*((n_2_gm+n_2_cdg*s)*((((((((((pin_1_go+pin_1_gm)+pin_1_gb)+pin_1_css*s)+pin_2_go)+pin_2_gm)+pin_2_gb)+pin_2_css*s)+p_tail_go)+p_tail_cdd*s)*((((((p_tail_cgg*s+p_ref_go)+p_ref_gm)+p_ref_cgd*s)+p_ref_cgg*s)+p_ref_cdd*s)+p_ref_cdg*s)-(p_tail_gm+p_tail_cdg*s)*p_tail_cgd*s)-((((-pin_2_go)-pin_2_gm)-pin_2_gb)+pin_2_cds*s)*((-pin_1_go)+pin_1_csd*s)*((((((p_tail_cgg*s+p_ref_go)+p_ref_gm)+p_ref_cgd*s)+p_ref_cgg*s)+p_ref_cdd*s)+p_ref_cdg*s)))+((((-pin_1_go)-pin_1_gm)-pin_1_gb)+pin_1_cds*s)*((n_2_gm+n_2_cdg*s)*((-pin_2_go)+pin_2_csd*s)*((((((p_tail_cgg*s+p_ref_go)+p_ref_gm)+p_ref_cgd*s)+p_ref_cgg*s)+p_ref_cdd*s)+p_ref_cdg*s)-(((n_2_go+n_2_cdd*s)+pin_2_go)+pin_2_cdd*s)*((-pin_1_go)+pin_1_csd*s)*((((((p_tail_cgg*s+p_ref_go)+p_ref_gm)+p_ref_cgd*s)+p_ref_cgg*s)+p_ref_cdd*s)+p_ref_cdg*s)))))/((-0));
diffpair_pmos_property_BW_s=(-0);
diffpair_pmos_p1=-s;
if (!isfinite(diffpair_pmos_property_BW))  {diffpair_pmos_status_fail=8; return TCL_ERROR;}
s-=1e3;
for (BW_it=0;BW_it<20;BW_it++)  s-=(((-((((((((((n_1_go+n_1_gm)+n_1_cgd*s)+n_1_cgg*s)+n_1_cdd*s)+n_1_cdg*s)+n_2_cgg*s)+pin_1_go)+pin_1_cdd*s)*((((n_2_go+n_2_cdd*s)+pin_2_go)+pin_2_cdd*s)*((((((((((pin_1_go+pin_1_gm)+pin_1_gb)+pin_1_css*s)+pin_2_go)+pin_2_gm)+pin_2_gb)+pin_2_css*s)+p_tail_go)+p_tail_cdd*s)*((((((p_tail_cgg*s+p_ref_go)+p_ref_gm)+p_ref_cgd*s)+p_ref_cgg*s)+p_ref_cdd*s)+p_ref_cdg*s)-(p_tail_gm+p_tail_cdg*s)*p_tail_cgd*s)-((((-pin_2_go)-pin_2_gm)-pin_2_gb)+pin_2_cds*s)*((-pin_2_go)+pin_2_csd*s)*((((((p_tail_cgg*s+p_ref_go)+p_ref_gm)+p_ref_cgd*s)+p_ref_cgg*s)+p_ref_cdd*s)+p_ref_cdg*s))-n_2_cgd*s*((n_2_gm+n_2_cdg*s)*((((((((((pin_1_go+pin_1_gm)+pin_1_gb)+pin_1_css*s)+pin_2_go)+pin_2_gm)+pin_2_gb)+pin_2_css*s)+p_tail_go)+p_tail_cdd*s)*((((((p_tail_cgg*s+p_ref_go)+p_ref_gm)+p_ref_cgd*s)+p_ref_cgg*s)+p_ref_cdd*s)+p_ref_cdg*s)-(p_tail_gm+p_tail_cdg*s)*p_tail_cgd*s)-((((-pin_2_go)-pin_2_gm)-pin_2_gb)+pin_2_cds*s)*((-pin_1_go)+pin_1_csd*s)*((((((p_tail_cgg*s+p_ref_go)+p_ref_gm)+p_ref_cgd*s)+p_ref_cgg*s)+p_ref_cdd*s)+p_ref_cdg*s)))+((((-pin_1_go)-pin_1_gm)-pin_1_gb)+pin_1_cds*s)*((n_2_gm+n_2_cdg*s)*((-pin_2_go)+pin_2_csd*s)*((((((p_tail_cgg*s+p_ref_go)+p_ref_gm)+p_ref_cgd*s)+p_ref_cgg*s)+p_ref_cdd*s)+p_ref_cdg*s)-(((n_2_go+n_2_cdd*s)+pin_2_go)+pin_2_cdd*s)*((-pin_1_go)+pin_1_csd*s)*((((((p_tail_cgg*s+p_ref_go)+p_ref_gm)+p_ref_cgd*s)+p_ref_cgg*s)+p_ref_cdd*s)+p_ref_cdg*s)))))*(s+diffpair_pmos_p1-5e2))/(((-0))*(s+diffpair_pmos_p1-5e2)-((-((((((((((n_1_go+n_1_gm)+n_1_cgd*s)+n_1_cgg*s)+n_1_cdd*s)+n_1_cdg*s)+n_2_cgg*s)+pin_1_go)+pin_1_cdd*s)*((((n_2_go+n_2_cdd*s)+pin_2_go)+pin_2_cdd*s)*((((((((((pin_1_go+pin_1_gm)+pin_1_gb)+pin_1_css*s)+pin_2_go)+pin_2_gm)+pin_2_gb)+pin_2_css*s)+p_tail_go)+p_tail_cdd*s)*((((((p_tail_cgg*s+p_ref_go)+p_ref_gm)+p_ref_cgd*s)+p_ref_cgg*s)+p_ref_cdd*s)+p_ref_cdg*s)-(p_tail_gm+p_tail_cdg*s)*p_tail_cgd*s)-((((-pin_2_go)-pin_2_gm)-pin_2_gb)+pin_2_cds*s)*((-pin_2_go)+pin_2_csd*s)*((((((p_tail_cgg*s+p_ref_go)+p_ref_gm)+p_ref_cgd*s)+p_ref_cgg*s)+p_ref_cdd*s)+p_ref_cdg*s))-n_2_cgd*s*((n_2_gm+n_2_cdg*s)*((((((((((pin_1_go+pin_1_gm)+pin_1_gb)+pin_1_css*s)+pin_2_go)+pin_2_gm)+pin_2_gb)+pin_2_css*s)+p_tail_go)+p_tail_cdd*s)*((((((p_tail_cgg*s+p_ref_go)+p_ref_gm)+p_ref_cgd*s)+p_ref_cgg*s)+p_ref_cdd*s)+p_ref_cdg*s)-(p_tail_gm+p_tail_cdg*s)*p_tail_cgd*s)-((((-pin_2_go)-pin_2_gm)-pin_2_gb)+pin_2_cds*s)*((-pin_1_go)+pin_1_csd*s)*((((((p_tail_cgg*s+p_ref_go)+p_ref_gm)+p_ref_cgd*s)+p_ref_cgg*s)+p_ref_cdd*s)+p_ref_cdg*s)))+((((-pin_1_go)-pin_1_gm)-pin_1_gb)+pin_1_cds*s)*((n_2_gm+n_2_cdg*s)*((-pin_2_go)+pin_2_csd*s)*((((((p_tail_cgg*s+p_ref_go)+p_ref_gm)+p_ref_cgd*s)+p_ref_cgg*s)+p_ref_cdd*s)+p_ref_cdg*s)-(((n_2_go+n_2_cdd*s)+pin_2_go)+pin_2_cdd*s)*((-pin_1_go)+pin_1_csd*s)*((((((p_tail_cgg*s+p_ref_go)+p_ref_gm)+p_ref_cgd*s)+p_ref_cgg*s)+p_ref_cdd*s)+p_ref_cdg*s))))));
diffpair_pmos_p2=-s;
if (!isfinite(diffpair_pmos_p1)) {
    diffpair_pmos_property_ts=1/diffpair_pmos_property_BW;
} else if (!isfinite(diffpair_pmos_p2)) {
    diffpair_pmos_property_ts=-log(0.02)/diffpair_pmos_p1;
} else {
    float A1=-diffpair_pmos_p2/(-diffpair_pmos_p1+diffpair_pmos_p2);
    float A2=-diffpair_pmos_p1/(-diffpair_pmos_p1+diffpair_pmos_p2);
    diffpair_pmos_property_ts=0;
    for (BW_it=0;BW_it<10;BW_it++) diffpair_pmos_property_ts-=(0.02+A1*exp(-diffpair_pmos_p1*diffpair_pmos_property_ts)+A2*exp(-diffpair_pmos_p2*diffpair_pmos_property_ts))/(-diffpair_pmos_p1*A1*exp(-diffpair_pmos_p1*diffpair_pmos_property_ts)-diffpair_pmos_p2*A2*exp(-diffpair_pmos_p2*diffpair_pmos_property_ts));
}
if (!isfinite(diffpair_pmos_property_ts)) {
    diffpair_pmos_property_ts=1/diffpair_pmos_property_BW;
}
diffpair_pmos_property_Cin=pin_1_cgd+pin_1_cgs;
diffpair_pmos_property_PM=(diffpair_pmos_property_BW/9.76e8)+(diffpair_pmos_property_Adc-21)-sqrt(size_Lp*size_Wp)/5e-7-diffpair_pmos_size_iref*2.5e4;
diffpair_pmos_property_PM=(diffpair_pmos_property_PM*180/3.1415)/2.16+29-1.4-0.75/2;
while (diffpair_pmos_property_PM<0) diffpair_pmos_property_PM+=360;
while (fabs(diffpair_pmos_property_PM)>180) diffpair_pmos_property_PM-=360;
diffpair_pmos_property_PM=fabs(diffpair_pmos_property_PM);
while (BW_Mag>4) {
      snr=0;
      sni=0;
      sdr=-((n_1_go+n_1_gm+pin_1_go)*((n_2_go+pin_2_go)*((pin_1_go+pin_1_gm+pin_1_gb+pin_2_go+pin_2_gm+pin_2_gb+p_tail_go)*(p_ref_go+p_ref_gm)-(pin_1_css*W+pin_2_css*W+p_tail_cdd*W)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+p_tail_cdg*W*p_tail_cgd*W)-(n_2_cdd*W+pin_2_cdd*W)*((pin_1_go+pin_1_gm+pin_1_gb+pin_2_go+pin_2_gm+pin_2_gb+p_tail_go)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+(pin_1_css*W+pin_2_css*W+p_tail_cdd*W)*(p_ref_go+p_ref_gm)-p_tail_gm*p_tail_cgd*W)-((-pin_2_go-pin_2_gm-pin_2_gb)*(-pin_2_go)-pin_2_cds*W*pin_2_csd*W)*(p_ref_go+p_ref_gm)-((-pin_2_go-pin_2_gm-pin_2_gb)*pin_2_csd*W+pin_2_cds*W*(-pin_2_go))*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W))-(n_1_cgd*W+n_1_cgg*W+n_1_cdd*W+n_1_cdg*W+n_2_cgg*W+pin_1_cdd*W)*((n_2_go+pin_2_go)*((pin_1_go+pin_1_gm+pin_1_gb+pin_2_go+pin_2_gm+pin_2_gb+p_tail_go)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+(pin_1_css*W+pin_2_css*W+p_tail_cdd*W)*(p_ref_go+p_ref_gm)-p_tail_gm*p_tail_cgd*W)+(n_2_cdd*W+pin_2_cdd*W)*((pin_1_go+pin_1_gm+pin_1_gb+pin_2_go+pin_2_gm+pin_2_gb+p_tail_go)*(p_ref_go+p_ref_gm)-(pin_1_css*W+pin_2_css*W+p_tail_cdd*W)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+p_tail_cdg*W*p_tail_cgd*W)-((-pin_2_go-pin_2_gm-pin_2_gb)*(-pin_2_go)-pin_2_cds*W*pin_2_csd*W)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+((-pin_2_go-pin_2_gm-pin_2_gb)*pin_2_csd*W+pin_2_cds*W*(-pin_2_go))*(p_ref_go+p_ref_gm))+(n_2_cgd*W*(n_2_gm*((pin_1_go+pin_1_gm+pin_1_gb+pin_2_go+pin_2_gm+pin_2_gb+p_tail_go)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+(pin_1_css*W+pin_2_css*W+p_tail_cdd*W)*(p_ref_go+p_ref_gm)-p_tail_gm*p_tail_cgd*W)+n_2_cdg*W*((pin_1_go+pin_1_gm+pin_1_gb+pin_2_go+pin_2_gm+pin_2_gb+p_tail_go)*(p_ref_go+p_ref_gm)-(pin_1_css*W+pin_2_css*W+p_tail_cdd*W)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+p_tail_cdg*W*p_tail_cgd*W)-((-pin_2_go-pin_2_gm-pin_2_gb)*(-pin_1_go)-pin_2_cds*W*pin_1_csd*W)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+((-pin_2_go-pin_2_gm-pin_2_gb)*pin_1_csd*W+pin_2_cds*W*(-pin_1_go))*(p_ref_go+p_ref_gm)))+(-pin_1_go-pin_1_gm-pin_1_gb)*((n_2_gm*(-pin_2_go)-n_2_cdg*W*pin_2_csd*W)*(p_ref_go+p_ref_gm)-(n_2_gm*pin_2_csd*W+n_2_cdg*W*(-pin_2_go))*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)-((n_2_go+pin_2_go)*(-pin_1_go)-(n_2_cdd*W+pin_2_cdd*W)*pin_1_csd*W)*(p_ref_go+p_ref_gm)-((n_2_go+pin_2_go)*pin_1_csd*W+(n_2_cdd*W+pin_2_cdd*W)*(-pin_1_go))*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W))-pin_1_cds*W*((n_2_gm*(-pin_2_go)-n_2_cdg*W*pin_2_csd*W)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+(n_2_gm*pin_2_csd*W+n_2_cdg*W*(-pin_2_go))*(p_ref_go+p_ref_gm)-((n_2_go+pin_2_go)*(-pin_1_go)-(n_2_cdd*W+pin_2_cdd*W)*pin_1_csd*W)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+((n_2_go+pin_2_go)*pin_1_csd*W+(n_2_cdd*W+pin_2_cdd*W)*(-pin_1_go))*(p_ref_go+p_ref_gm)));
      sdi=-((n_1_go+n_1_gm+pin_1_go)*((n_2_go+pin_2_go)*((pin_1_go+pin_1_gm+pin_1_gb+pin_2_go+pin_2_gm+pin_2_gb+p_tail_go)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+(pin_1_css*W+pin_2_css*W+p_tail_cdd*W)*(p_ref_go+p_ref_gm)-p_tail_gm*p_tail_cgd*W)+(n_2_cdd*W+pin_2_cdd*W)*((pin_1_go+pin_1_gm+pin_1_gb+pin_2_go+pin_2_gm+pin_2_gb+p_tail_go)*(p_ref_go+p_ref_gm)-(pin_1_css*W+pin_2_css*W+p_tail_cdd*W)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+p_tail_cdg*W*p_tail_cgd*W)-((-pin_2_go-pin_2_gm-pin_2_gb)*(-pin_2_go)-pin_2_cds*W*pin_2_csd*W)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+((-pin_2_go-pin_2_gm-pin_2_gb)*pin_2_csd*W+pin_2_cds*W*(-pin_2_go))*(p_ref_go+p_ref_gm))+(n_1_cgd*W+n_1_cgg*W+n_1_cdd*W+n_1_cdg*W+n_2_cgg*W+pin_1_cdd*W)*((n_2_go+pin_2_go)*((pin_1_go+pin_1_gm+pin_1_gb+pin_2_go+pin_2_gm+pin_2_gb+p_tail_go)*(p_ref_go+p_ref_gm)-(pin_1_css*W+pin_2_css*W+p_tail_cdd*W)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+p_tail_cdg*W*p_tail_cgd*W)-(n_2_cdd*W+pin_2_cdd*W)*((pin_1_go+pin_1_gm+pin_1_gb+pin_2_go+pin_2_gm+pin_2_gb+p_tail_go)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+(pin_1_css*W+pin_2_css*W+p_tail_cdd*W)*(p_ref_go+p_ref_gm)-p_tail_gm*p_tail_cgd*W)-((-pin_2_go-pin_2_gm-pin_2_gb)*(-pin_2_go)-pin_2_cds*W*pin_2_csd*W)*(p_ref_go+p_ref_gm)-((-pin_2_go-pin_2_gm-pin_2_gb)*pin_2_csd*W+pin_2_cds*W*(-pin_2_go))*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W))-n_2_cgd*W*(n_2_gm*((pin_1_go+pin_1_gm+pin_1_gb+pin_2_go+pin_2_gm+pin_2_gb+p_tail_go)*(p_ref_go+p_ref_gm)-(pin_1_css*W+pin_2_css*W+p_tail_cdd*W)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+p_tail_cdg*W*p_tail_cgd*W)-n_2_cdg*W*((pin_1_go+pin_1_gm+pin_1_gb+pin_2_go+pin_2_gm+pin_2_gb+p_tail_go)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+(pin_1_css*W+pin_2_css*W+p_tail_cdd*W)*(p_ref_go+p_ref_gm)-p_tail_gm*p_tail_cgd*W)-((-pin_2_go-pin_2_gm-pin_2_gb)*(-pin_1_go)-pin_2_cds*W*pin_1_csd*W)*(p_ref_go+p_ref_gm)-((-pin_2_go-pin_2_gm-pin_2_gb)*pin_1_csd*W+pin_2_cds*W*(-pin_1_go))*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W))+(-pin_1_go-pin_1_gm-pin_1_gb)*((n_2_gm*(-pin_2_go)-n_2_cdg*W*pin_2_csd*W)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+(n_2_gm*pin_2_csd*W+n_2_cdg*W*(-pin_2_go))*(p_ref_go+p_ref_gm)-((n_2_go+pin_2_go)*(-pin_1_go)-(n_2_cdd*W+pin_2_cdd*W)*pin_1_csd*W)*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)+((n_2_go+pin_2_go)*pin_1_csd*W+(n_2_cdd*W+pin_2_cdd*W)*(-pin_1_go))*(p_ref_go+p_ref_gm))+pin_1_cds*W*((n_2_gm*(-pin_2_go)-n_2_cdg*W*pin_2_csd*W)*(p_ref_go+p_ref_gm)-(n_2_gm*pin_2_csd*W+n_2_cdg*W*(-pin_2_go))*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)-((n_2_go+pin_2_go)*(-pin_1_go)-(n_2_cdd*W+pin_2_cdd*W)*pin_1_csd*W)*(p_ref_go+p_ref_gm)-((n_2_go+pin_2_go)*pin_1_csd*W+(n_2_cdd*W+pin_2_cdd*W)*(-pin_1_go))*(p_tail_cgg*W+p_ref_cgd*W+p_ref_cgg*W+p_ref_cdd*W+p_ref_cdg*W)));
      BW_Mag=(snr*snr+sni*sni)/(sdr*sdr+sdi*sdi);
      W*=1.01;
}
diffpair_pmos_property_PM=180-180*(atan(sni/snr)-atan(sdi/sdr))/3.1415926;
n_1_Nt_unit=gamma_gcc_interpolateg_4(P_look_up_tables_nch_thermal_noise_ss_LUT,outm_V,outm_V,CONST_0_V,size_Ln,&n_1_dNt_dvgs,&n_1_dNt_dvds,&n_1_dNt_dvbs,&n_1_dNt_dl);
n_1_Nt=n_1_Nt_unit*n_1_go;
if (!isfinite(n_1_Nt))  {diffpair_pmos_status_fail=5; return TCL_ERROR;}
n_1_Nf_unit=gamma_gcc_interpolateg_4(P_look_up_tables_nch_flicker_noise_ss_LUT,outm_V,outm_V,CONST_0_V,size_Ln,&n_1_dNf_dvgs,&n_1_dNf_dvds,&n_1_dNf_dvbs,&n_1_dNf_dl);
n_1_Nf=n_1_Nf_unit*n_1_go*n_1_go/(size_Wn*size_Ln);
if (!isfinite(n_1_Nf))  {diffpair_pmos_status_fail=6; return TCL_ERROR;}
n_2_Nt_unit=gamma_gcc_interpolateg_4(P_look_up_tables_nch_thermal_noise_ss_LUT,outm_V,outp_V,CONST_0_V,size_Ln,&n_2_dNt_dvgs,&n_2_dNt_dvds,&n_2_dNt_dvbs,&n_2_dNt_dl);
n_2_Nt=n_2_Nt_unit*n_2_go;
if (!isfinite(n_2_Nt))  {diffpair_pmos_status_fail=5; return TCL_ERROR;}
n_2_Nf_unit=gamma_gcc_interpolateg_4(P_look_up_tables_nch_flicker_noise_ss_LUT,outm_V,outp_V,CONST_0_V,size_Ln,&n_2_dNf_dvgs,&n_2_dNf_dvds,&n_2_dNf_dvbs,&n_2_dNf_dl);
n_2_Nf=n_2_Nf_unit*n_2_go*n_2_go/(size_Wn*size_Ln);
if (!isfinite(n_2_Nf))  {diffpair_pmos_status_fail=6; return TCL_ERROR;}
pin_1_Nt_unit=gamma_gcc_interpolateg_4(P_look_up_tables_pch_thermal_noise_ss_LUT,(inp_V-tail_V),(outm_V-tail_V),(vdd_V-tail_V),size_Lp,&pin_1_dNt_dvgs,&pin_1_dNt_dvds,&pin_1_dNt_dvbs,&pin_1_dNt_dl);
pin_1_Nt=pin_1_Nt_unit*pin_1_go;
if (!isfinite(pin_1_Nt))  {diffpair_pmos_status_fail=5; return TCL_ERROR;}
pin_1_Nf_unit=gamma_gcc_interpolateg_4(P_look_up_tables_pch_flicker_noise_ss_LUT,(inp_V-tail_V),(outm_V-tail_V),(vdd_V-tail_V),size_Lp,&pin_1_dNf_dvgs,&pin_1_dNf_dvds,&pin_1_dNf_dvbs,&pin_1_dNf_dl);
pin_1_Nf=pin_1_Nf_unit*pin_1_go*pin_1_go/(size_Wp*size_Lp);
if (!isfinite(pin_1_Nf))  {diffpair_pmos_status_fail=6; return TCL_ERROR;}
pin_2_Nt_unit=gamma_gcc_interpolateg_4(P_look_up_tables_pch_thermal_noise_ss_LUT,(inn_V-tail_V),(outp_V-tail_V),(vdd_V-tail_V),size_Lp,&pin_2_dNt_dvgs,&pin_2_dNt_dvds,&pin_2_dNt_dvbs,&pin_2_dNt_dl);
pin_2_Nt=pin_2_Nt_unit*pin_2_go;
if (!isfinite(pin_2_Nt))  {diffpair_pmos_status_fail=5; return TCL_ERROR;}
pin_2_Nf_unit=gamma_gcc_interpolateg_4(P_look_up_tables_pch_flicker_noise_ss_LUT,(inn_V-tail_V),(outp_V-tail_V),(vdd_V-tail_V),size_Lp,&pin_2_dNf_dvgs,&pin_2_dNf_dvds,&pin_2_dNf_dvbs,&pin_2_dNf_dl);
pin_2_Nf=pin_2_Nf_unit*pin_2_go*pin_2_go/(size_Wp*size_Lp);
if (!isfinite(pin_2_Nf))  {diffpair_pmos_status_fail=6; return TCL_ERROR;}
p_tail_Nt_unit=gamma_gcc_interpolateg_4(P_look_up_tables_pch_thermal_noise_ss_LUT,(vbias_V-vdd_V),(tail_V-vdd_V),0,size_Ls,&p_tail_dNt_dvgs,&p_tail_dNt_dvds,&p_tail_dNt_dvbs,&p_tail_dNt_dl);
p_tail_Nt=p_tail_Nt_unit*p_tail_go;
if (!isfinite(p_tail_Nt))  {diffpair_pmos_status_fail=5; return TCL_ERROR;}
p_tail_Nf_unit=gamma_gcc_interpolateg_4(P_look_up_tables_pch_flicker_noise_ss_LUT,(vbias_V-vdd_V),(tail_V-vdd_V),0,size_Ls,&p_tail_dNf_dvgs,&p_tail_dNf_dvds,&p_tail_dNf_dvbs,&p_tail_dNf_dl);
p_tail_Nf=p_tail_Nf_unit*p_tail_go*p_tail_go/(size_Ls*2*size_Wp/size_Lp*size_Ls);
if (!isfinite(p_tail_Nf))  {diffpair_pmos_status_fail=6; return TCL_ERROR;}
p_ref_Nt_unit=gamma_gcc_interpolateg_4(P_look_up_tables_pch_thermal_noise_ss_LUT,(vbias_V-vdd_V),(vbias_V-vdd_V),0,size_Ls,&p_ref_dNt_dvgs,&p_ref_dNt_dvds,&p_ref_dNt_dvbs,&p_ref_dNt_dl);
p_ref_Nt=p_ref_Nt_unit*p_ref_go;
if (!isfinite(p_ref_Nt))  {diffpair_pmos_status_fail=5; return TCL_ERROR;}
p_ref_Nf_unit=gamma_gcc_interpolateg_4(P_look_up_tables_pch_flicker_noise_ss_LUT,(vbias_V-vdd_V),(vbias_V-vdd_V),0,size_Ls,&p_ref_dNf_dvgs,&p_ref_dNf_dvds,&p_ref_dNf_dvbs,&p_ref_dNf_dl);
p_ref_Nf=p_ref_Nf_unit*p_ref_go*p_ref_go/(size_Ls*2*size_Wp/size_Lp*size_Ls);
if (!isfinite(p_ref_Nf))  {diffpair_pmos_status_fail=6; return TCL_ERROR;}
float current_transfer_n_1=Ted*((-(-(n_2_gm*((((((pin_1_go+pin_1_gm)+pin_1_gb)+pin_2_go)+pin_2_gm)+pin_2_gb)+p_tail_go)*(p_ref_go+p_ref_gm)-(((-pin_2_go)-pin_2_gm)-pin_2_gb)*(-pin_1_go)*(p_ref_go+p_ref_gm)))))/diffpair_pmos_property_Adc;
float current_transfer_n_2=Ted*((-(((n_1_go+n_1_gm)+pin_1_go)*((((((pin_1_go+pin_1_gm)+pin_1_gb)+pin_2_go)+pin_2_gm)+pin_2_gb)+p_tail_go)*(p_ref_go+p_ref_gm)+(((-pin_1_go)-pin_1_gm)-pin_1_gb)*(-(-pin_1_go)*(p_ref_go+p_ref_gm)))))/diffpair_pmos_property_Adc;
float current_transfer_pin_1=Ted*((-((((n_1_go+n_1_gm)+pin_1_go)*(-(((-pin_2_go)-pin_2_gm)-pin_2_gb)*(p_ref_go+p_ref_gm))-(n_2_gm*((((((pin_1_go+pin_1_gm)+pin_1_gb)+pin_2_go)+pin_2_gm)+pin_2_gb)+p_tail_go)*(p_ref_go+p_ref_gm)-(((-pin_2_go)-pin_2_gm)-pin_2_gb)*(-pin_1_go)*(p_ref_go+p_ref_gm)))+(((-pin_1_go)-pin_1_gm)-pin_1_gb)*n_2_gm*(p_ref_go+p_ref_gm))))/diffpair_pmos_property_Adc;
float current_transfer_pin_2=Ted*((-(((n_1_go+n_1_gm)+pin_1_go)*(((((((pin_1_go+pin_1_gm)+pin_1_gb)+pin_2_go)+pin_2_gm)+pin_2_gb)+p_tail_go)*(p_ref_go+p_ref_gm)-(((-pin_2_go)-pin_2_gm)-pin_2_gb)*(p_ref_go+p_ref_gm))+(((-pin_1_go)-pin_1_gm)-pin_1_gb)*(n_2_gm*(p_ref_go+p_ref_gm)-(-pin_1_go)*(p_ref_go+p_ref_gm)))))/diffpair_pmos_property_Adc;
float current_transfer_p_tail=Ted*((-(((n_1_go+n_1_gm)+pin_1_go)*(-(((-pin_2_go)-pin_2_gm)-pin_2_gb)*(p_ref_go+p_ref_gm))+(((-pin_1_go)-pin_1_gm)-pin_1_gb)*n_2_gm*(p_ref_go+p_ref_gm))))/diffpair_pmos_property_Adc;
float current_transfer_p_ref=Ted*((-(((n_1_go+n_1_gm)+pin_1_go)*(-(((-pin_2_go)-pin_2_gm)-pin_2_gb)*(-p_tail_gm))+(((-pin_1_go)-pin_1_gm)-pin_1_gb)*n_2_gm*(-p_tail_gm))))/diffpair_pmos_property_Adc;
diffpair_pmos_property_Nt=(current_transfer_n_1*current_transfer_n_1*n_1_Nt+current_transfer_n_2*current_transfer_n_2*n_2_Nt+current_transfer_pin_1*current_transfer_pin_1*pin_1_Nt+current_transfer_pin_2*current_transfer_pin_2*pin_2_Nt+current_transfer_p_tail*current_transfer_p_tail*p_tail_Nt+current_transfer_p_ref*current_transfer_p_ref*p_ref_Nt)/diffpair_pmos_property_Adc;
diffpair_pmos_property_Nf=(current_transfer_n_1*current_transfer_n_1*n_1_Nf+current_transfer_n_2*current_transfer_n_2*n_2_Nf+current_transfer_pin_1*current_transfer_pin_1*pin_1_Nf+current_transfer_pin_2*current_transfer_pin_2*pin_2_Nf+current_transfer_p_tail*current_transfer_p_tail*p_tail_Nf+current_transfer_p_ref*current_transfer_p_ref*p_ref_Nf)/diffpair_pmos_property_Adc;
diffpair_pmos_property_fc=diffpair_pmos_property_Nf/diffpair_pmos_property_Nt;
diffpair_pmos_property_TotalNoise=(log(2*diffpair_pmos_property_BW)*diffpair_pmos_property_Nf+2*diffpair_pmos_property_BW*diffpair_pmos_property_Nt);
diffpair_pmos_property_TotalNoise/=2;
diffpair_pmos_property_Area=1e12*(size_Wn*size_Ln+size_Wn*size_Ln+size_Wp*size_Lp+size_Wp*size_Lp+size_Ls*2*size_Wp/size_Lp*size_Ls+size_Ls*2*size_Wp/size_Lp*size_Ls);
float single_transistor_vos;
diffpair_pmos_property_Vos=0;
single_transistor_vos=vos(-pin_1_Ids*size_Lp/size_Wp,diffpair_pmos_property_Area);
diffpair_pmos_property_Vos+=single_transistor_vos*single_transistor_vos;
single_transistor_vos=vos(-pin_2_Ids*size_Lp/size_Wp,diffpair_pmos_property_Area);
diffpair_pmos_property_Vos+=single_transistor_vos*single_transistor_vos;
diffpair_pmos_property_Vos=1e-3*sqrt(diffpair_pmos_property_Vos);
diffpair_pmos_property_Power=0;
diffpair_pmos_property_Power+=fabs(n_1_Ids*((outm_V)-(CONST_0_V)));
diffpair_pmos_property_Power+=fabs(n_2_Ids*((outp_V)-(CONST_0_V)));
diffpair_pmos_property_Power+=fabs(pin_1_Ids*((outm_V)-(tail_V)));
diffpair_pmos_property_Power+=fabs(pin_2_Ids*((outp_V)-(tail_V)));
diffpair_pmos_property_Power+=fabs(p_tail_Ids*((tail_V)-(vdd_V)));
diffpair_pmos_property_Power+=fabs(p_ref_Ids*((vbias_V)-(vdd_V)));
diffpair_pmos_property_Adc=20*log10(fabs(diffpair_pmos_property_Adc));
diffpair_pmos_property_CMRR=20*log10(fabs(diffpair_pmos_property_CMRR));
diffpair_pmos_property_CMRR=diffpair_pmos_property_Adc-diffpair_pmos_property_CMRR;
if (diffpair_pmos_max_Adc<diffpair_pmos_property_Adc) diffpair_pmos_max_Adc=diffpair_pmos_property_Adc;
PAT *p=(PAT *)Pdiffpair_pmos_circuits_PAT;
float sizes[6];
sizes[0]=diffpair_pmos_size_iref;
sizes[1]=diffpair_pmos_size_Lp;
sizes[2]=diffpair_pmos_size_Wp;
sizes[3]=diffpair_pmos_size_Ln;
sizes[4]=diffpair_pmos_size_Wn;
sizes[5]=diffpair_pmos_size_Ls;
float properties[2];
if ((diffpair_pmos_config_factor_Adc!=0)||(diffpair_pmos_config_shift_Adc!=0)) diffpair_pmos_property_Adc=diffpair_pmos_property_Adc*diffpair_pmos_config_factor_Adc+diffpair_pmos_config_shift_Adc;
properties[0]=diffpair_pmos_property_Adc;
if ((diffpair_pmos_config_factor_CMRR!=0)||(diffpair_pmos_config_shift_CMRR!=0)) diffpair_pmos_property_CMRR=diffpair_pmos_property_CMRR*diffpair_pmos_config_factor_CMRR+diffpair_pmos_config_shift_CMRR;
properties[1]=diffpair_pmos_property_CMRR;
diffpair_pmos_status_fail=op_it;
diffpair_pmos_status_index=add_pat_array(p,sizes,properties);

            return TCL_OK;
        }
        //      static int tcl_gamma_grad_cmd(ClientData clientData,Tcl_Interp *interp,int argc,char *argv[]) {
            //            Tcl_ResetResult(interp);
            //          GRAD_CODE_GOES_HERE
            //         return TCL_OK;
        //    }
        static int tcl_gamma_diffpair_pmos_heatmap_cmd(ClientData clientData,Tcl_Interp *interp,int argc,char *argv[]) {
            int i,j;
ClientData CD;
if ((argc!=15)&&(argc!=14)&&(argc!=13)) {
    #Error: "%s: usage: %s <x context> <minX> <maxX> <stepX> <y context> <minY> <maxY> <stepY> <z context> <pixel width> <pixel height> <pallet> [<pallet mode> {[<pass threshold>]}]" argv[0] argv[0]
    return TCL_ERROR;
}
    float *pX=(float *)&(create_context(argv[1]))->value.s;
    float *pY=(float *)&(create_context(argv[5]))->value.s;
    float *pZ=(float *)&(create_context(argv[7]))->value.s;
    float *PX=NULL;
if (strcmp(argv[1],"param:inp")==0) PX=&(param_inp);
if (strcmp(argv[1],"param:inn")==0) PX=&(param_inn);
if (strcmp(argv[1],"param:vdd")==0) PX=&(param_vdd);
if (strcmp(argv[1],"size:iref")==0) PX=&(size_iref);
if (strcmp(argv[1],"size:Lp")==0) PX=&(size_Lp);
if (strcmp(argv[1],"size:Wp")==0) PX=&(size_Wp);
if (strcmp(argv[1],"size:Ln")==0) PX=&(size_Ln);
if (strcmp(argv[1],"size:Wn")==0) PX=&(size_Wn);
if (strcmp(argv[1],"size:Ls")==0) PX=&(size_Ls);
if (strcmp(argv[1],"property:Adc")==0) PX=&(property_Adc);
if (strcmp(argv[1],"property:CMRR")==0) PX=&(property_CMRR);
if (PX==NULL) {
    #Error: "%s: context %s is not available for heatmap generation." argv[0] argv[1]
    return TCL_ERROR;
}
float minX=atof(argv[2]);
float maxX=atof(argv[3]);
float stepX=atof(argv[4]);
    float *PY=NULL;
if (strcmp(argv[5],"param:inp")==0) PY=&(param_inp);
if (strcmp(argv[5],"param:inn")==0) PY=&(param_inn);
if (strcmp(argv[5],"param:vdd")==0) PY=&(param_vdd);
if (strcmp(argv[5],"size:iref")==0) PY=&(size_iref);
if (strcmp(argv[5],"size:Lp")==0) PY=&(size_Lp);
if (strcmp(argv[5],"size:Wp")==0) PY=&(size_Wp);
if (strcmp(argv[5],"size:Ln")==0) PY=&(size_Ln);
if (strcmp(argv[5],"size:Wn")==0) PY=&(size_Wn);
if (strcmp(argv[5],"size:Ls")==0) PY=&(size_Ls);
if (strcmp(argv[5],"property:Adc")==0) PY=&(property_Adc);
if (strcmp(argv[5],"property:CMRR")==0) PY=&(property_CMRR);
if (PY==NULL) {
    #Error: "%s: context %s is not available for heatmap generation." argv[0] argv[1]
    return TCL_ERROR;
}
float minY=atof(argv[6]);
float maxY=atof(argv[7]);
float stepY=atof(argv[8]);
    float *PZ=NULL;
if (strcmp(argv[7],"param:inp")==0) PZ=&(param_inp);
if (strcmp(argv[7],"param:inn")==0) PZ=&(param_inn);
if (strcmp(argv[7],"param:vdd")==0) PZ=&(param_vdd);
if (strcmp(argv[7],"size:iref")==0) PZ=&(size_iref);
if (strcmp(argv[7],"size:Lp")==0) PZ=&(size_Lp);
if (strcmp(argv[7],"size:Wp")==0) PZ=&(size_Wp);
if (strcmp(argv[7],"size:Ln")==0) PZ=&(size_Ln);
if (strcmp(argv[7],"size:Wn")==0) PZ=&(size_Wn);
if (strcmp(argv[7],"size:Ls")==0) PZ=&(size_Ls);
if (strcmp(argv[7],"property:Adc")==0) PZ=&(property_Adc);
if (strcmp(argv[7],"property:CMRR")==0) PZ=&(property_CMRR);
if (PZ==NULL) {
    #Error: "%s: context %s is not available for heatmap generation." argv[0] argv[1]
    return TCL_ERROR;
}
int width=(int)(maxX-minX)/stepX+1;
int height=(int)(maxY-minY)/stepY+1;
int ARGC;
char **ARGV;
Tcl_SplitList(interp,argv[12],&ARGC,&ARGV);
int *pal=(int *)malloc(sizeof(int)*ARGC);
for (i=0;i<ARGC;i++) pal[i]=atoi(ARGV[i]);
heatmap *hm=new_heatmap(width,height,atoi(argv[10]),atoi(argv[11]),pal,ARGC);
int mode=-1;
float th=0;
if (argc==13) mode=HM_TH_MODE_FLAT; else {
if (strcmp(argv[13],"flat")==0) mode=HM_TH_MODE_FLAT;
if (strcmp(argv[13],"snap")==0) mode=HM_TH_MODE_SNAP;
if (strcmp(argv[13],"half")==0) mode=HM_TH_MODE_HALF;
}
if (mode==-1) {
	#Error: "%s: pallet mode %s is not available for heatmap generation. Use flat, snap or half" argv[0] argv[13]
	return TCL_ERROR;
}
if ((mode!=HM_TH_MODE_FLAT)&&(argc!=15)) {
	#Error: "%s: pallet mode %s requires a threshold for passing specifications." argv[0] argv[13]
	return TCL_ERROR;
} else th=atof(argv[14]);
float X,Y;
i=0;
for (X=minX;X<=maxX;X+=stepX) {
    j=0;
    for (Y=minY;Y<=maxY;Y+=stepY) {
        *PX=X;
        *PY=Y;
        tcl_gamma_diffpair_pmos_op_cmd(CD,NULL,0,NULL);
        set_heatmap_pixel(hm,i,j,*PZ);
        j++;
    }
    i++;
}
heatmap_thresholds(hm,mode,th);
char *out_channel_name=Tcl_GetVar(interp,"::HTML",0);
FILE *HTML;
Tcl_GetOpenFile(interp,out_channel_name,1,0,&HTML);
plot_heatmap(hm,0,0,HTML);

            return TCL_OK;
        }
        static int tcl_gamma_diffpair_pmos_random_cmd(ClientData clientData,Tcl_Interp *interp,int argc,char *argv[]) {
            ClientData CD;
PAT *p=(PAT *)Pdiffpair_pmos_circuits_PAT;
while (p->content->num_of<diffpair_pmos_config_pat_size_target) {
diffpair_pmos_size_iref=size_iref_min+random()*(size_iref_max-size_iref_min)/RAND_MAX;
diffpair_pmos_size_Lp=size_Lp_min+random()*(size_Lp_max-size_Lp_min)/RAND_MAX;
diffpair_pmos_size_Wp=size_Lp+random()*(size_Wp_max-size_Lp)/RAND_MAX;
diffpair_pmos_size_Ln=size_Ln_min+random()*(size_Ln_max-size_Ln_min)/RAND_MAX;
diffpair_pmos_size_Wn=size_Ln+random()*(size_Wn_max-size_Ln)/RAND_MAX;
diffpair_pmos_size_Ls=size_Ls_min+random()*(size_Ls_max-size_Ls_min)/RAND_MAX;
if (tcl_gamma_diffpair_pmos_op_cmd(CD,NULL,0,NULL)==TCL_ERROR) continue;
}

            return TCL_OK;
        }
        static int tcl_gamma_diffpair_pmos_breed_cmd(ClientData clientData,Tcl_Interp *interp,int argc,char *argv[]) {
            ClientData CD;
int i,viable;
PAT *p=(PAT *)Pdiffpair_pmos_circuits_PAT;
int more_to_breed=1;
while (more_to_breed&&(p->content->num_of<diffpair_pmos_pat_size_target)) {
more_to_breed=0;
int sweep_size=p->content->num_of;
for (i=0;i<sweep_size;i++) {
if (p->content->content[i]->flags) continue;
p->content->content[i]->flags=1;
more_to_breed++;
diffpair_pmos_size_iref=p->content->content[i]->sizes->content[0];
diffpair_pmos_size_Lp=p->content->content[i]->sizes->content[1];
diffpair_pmos_size_Wp=p->content->content[i]->sizes->content[2];
diffpair_pmos_size_Ln=p->content->content[i]->sizes->content[3];
diffpair_pmos_size_Wn=p->content->content[i]->sizes->content[4];
diffpair_pmos_size_Ls=p->content->content[i]->sizes->content[5];
diffpair_pmos_size_iref=diffpair_pmos_size_iref+diffpair_pmos_size_iref_step;
viable=1;
if ((diffpair_pmos_size_iref>=size_iref_min)&&(diffpair_pmos_size_iref<=size_iref_max)) {
tcl_gamma_diffpair_pmos_op_cmd(CD,NULL,0,NULL);
}
diffpair_pmos_size_iref=diffpair_pmos_size_iref-2*diffpair_pmos_size_iref_step;
viable=1;
if ((diffpair_pmos_size_iref>=size_iref_min)&&(diffpair_pmos_size_iref<=size_iref_max)) {
tcl_gamma_diffpair_pmos_op_cmd(CD,NULL,0,NULL);
}
diffpair_pmos_size_iref=diffpair_pmos_size_iref+diffpair_pmos_size_iref_step;
diffpair_pmos_size_Lp=diffpair_pmos_size_Lp+diffpair_pmos_size_Lp_step;
viable=1;
if ((diffpair_pmos_size_Lp>=size_Lp_min)&&(diffpair_pmos_size_Lp<=size_Lp_max)) {
tcl_gamma_diffpair_pmos_op_cmd(CD,NULL,0,NULL);
}
diffpair_pmos_size_Lp=diffpair_pmos_size_Lp-2*diffpair_pmos_size_Lp_step;
viable=1;
if ((diffpair_pmos_size_Lp>=size_Lp_min)&&(diffpair_pmos_size_Lp<=size_Lp_max)) {
tcl_gamma_diffpair_pmos_op_cmd(CD,NULL,0,NULL);
}
diffpair_pmos_size_Lp=diffpair_pmos_size_Lp+diffpair_pmos_size_Lp_step;
diffpair_pmos_size_Wp=diffpair_pmos_size_Wp+diffpair_pmos_size_Wp_step;
viable=1;
if ((diffpair_pmos_size_Wp>=size_Lp)&&(diffpair_pmos_size_Wp<=size_Wp_max)) {
tcl_gamma_diffpair_pmos_op_cmd(CD,NULL,0,NULL);
}
diffpair_pmos_size_Wp=diffpair_pmos_size_Wp-2*diffpair_pmos_size_Wp_step;
viable=1;
if ((diffpair_pmos_size_Wp>=size_Lp)&&(diffpair_pmos_size_Wp<=size_Wp_max)) {
tcl_gamma_diffpair_pmos_op_cmd(CD,NULL,0,NULL);
}
diffpair_pmos_size_Wp=diffpair_pmos_size_Wp+diffpair_pmos_size_Wp_step;
diffpair_pmos_size_Ln=diffpair_pmos_size_Ln+diffpair_pmos_size_Ln_step;
viable=1;
if ((diffpair_pmos_size_Ln>=size_Ln_min)&&(diffpair_pmos_size_Ln<=size_Ln_max)) {
tcl_gamma_diffpair_pmos_op_cmd(CD,NULL,0,NULL);
}
diffpair_pmos_size_Ln=diffpair_pmos_size_Ln-2*diffpair_pmos_size_Ln_step;
viable=1;
if ((diffpair_pmos_size_Ln>=size_Ln_min)&&(diffpair_pmos_size_Ln<=size_Ln_max)) {
tcl_gamma_diffpair_pmos_op_cmd(CD,NULL,0,NULL);
}
diffpair_pmos_size_Ln=diffpair_pmos_size_Ln+diffpair_pmos_size_Ln_step;
diffpair_pmos_size_Wn=diffpair_pmos_size_Wn+diffpair_pmos_size_Wn_step;
viable=1;
if ((diffpair_pmos_size_Wn>=size_Ln)&&(diffpair_pmos_size_Wn<=size_Wn_max)) {
tcl_gamma_diffpair_pmos_op_cmd(CD,NULL,0,NULL);
}
diffpair_pmos_size_Wn=diffpair_pmos_size_Wn-2*diffpair_pmos_size_Wn_step;
viable=1;
if ((diffpair_pmos_size_Wn>=size_Ln)&&(diffpair_pmos_size_Wn<=size_Wn_max)) {
tcl_gamma_diffpair_pmos_op_cmd(CD,NULL,0,NULL);
}
diffpair_pmos_size_Wn=diffpair_pmos_size_Wn+diffpair_pmos_size_Wn_step;
diffpair_pmos_size_Ls=diffpair_pmos_size_Ls+diffpair_pmos_size_Ls_step;
viable=1;
if ((diffpair_pmos_size_Ls>=size_Ls_min)&&(diffpair_pmos_size_Ls<=size_Ls_max)) {
tcl_gamma_diffpair_pmos_op_cmd(CD,NULL,0,NULL);
}
diffpair_pmos_size_Ls=diffpair_pmos_size_Ls-2*diffpair_pmos_size_Ls_step;
viable=1;
if ((diffpair_pmos_size_Ls>=size_Ls_min)&&(diffpair_pmos_size_Ls<=size_Ls_max)) {
tcl_gamma_diffpair_pmos_op_cmd(CD,NULL,0,NULL);
}
diffpair_pmos_size_Ls=diffpair_pmos_size_Ls+diffpair_pmos_size_Ls_step;
if (p->content->num_of%100==0) {
	printf("		%ld/%g=%g%%\n",p->content->num_of,diffpair_pmos_pat_size_target,100*p->content->num_of/diffpair_pmos_pat_size_target);
	fflush(stdout);
	if (diffpair_pmos_param_unique>0) {
	    pat_unique(p,diffpair_pmos_param_unique);
}
}
}
printf("	Done %ld/%g=%g%% (%ld visited)\n",p->content->num_of,diffpair_pmos_pat_size_target,100*p->content->num_of/diffpair_pmos_pat_size_target,more_to_breed);
}

            return TCL_OK;
        }
        static int tcl_gamma_diffpair_pmos_random_breed_cmd(ClientData clientData,Tcl_Interp *interp,int argc,char *argv[]) {
            ClientData CD;
int i,j;
PAT *p=(PAT *)Pdiffpair_pmos_circuits_PAT;
long int r;
float step;
while (1) {
    if (p->content->num_of>diffpair_pmos_config_pat_size_target) break;
int sweep_size=p->content->num_of;
for (i=0;i<sweep_size;i++) {
diffpair_pmos_size_iref=p->content->content[i]->sizes->content[0];
diffpair_pmos_size_Lp=p->content->content[i]->sizes->content[1];
diffpair_pmos_size_Wp=p->content->content[i]->sizes->content[2];
diffpair_pmos_size_Ln=p->content->content[i]->sizes->content[3];
diffpair_pmos_size_Wn=p->content->content[i]->sizes->content[4];
diffpair_pmos_size_Ls=p->content->content[i]->sizes->content[5];
while (1) {
step=(2.0*random()/RAND_MAX-1)*size_iref_step;
if (diffpair_pmos_size_iref+step<size_iref_min) continue;
if (diffpair_pmos_size_iref+step>size_iref_max) continue;
break;
}
diffpair_pmos_size_iref+=step;
while (1) {
step=(2.0*random()/RAND_MAX-1)*size_Lp_step;
if (diffpair_pmos_size_Lp+step<size_Lp_min) continue;
if (diffpair_pmos_size_Lp+step>size_Lp_max) continue;
break;
}
diffpair_pmos_size_Lp+=step;
while (1) {
step=(2.0*random()/RAND_MAX-1)*size_Wp_step;
if (diffpair_pmos_size_Wp+step<size_Lp) continue;
if (diffpair_pmos_size_Wp+step>size_Wp_max) continue;
break;
}
diffpair_pmos_size_Wp+=step;
while (1) {
step=(2.0*random()/RAND_MAX-1)*size_Ln_step;
if (diffpair_pmos_size_Ln+step<size_Ln_min) continue;
if (diffpair_pmos_size_Ln+step>size_Ln_max) continue;
break;
}
diffpair_pmos_size_Ln+=step;
while (1) {
step=(2.0*random()/RAND_MAX-1)*size_Wn_step;
if (diffpair_pmos_size_Wn+step<size_Ln) continue;
if (diffpair_pmos_size_Wn+step>size_Wn_max) continue;
break;
}
diffpair_pmos_size_Wn+=step;
while (1) {
step=(2.0*random()/RAND_MAX-1)*size_Ls_step;
if (diffpair_pmos_size_Ls+step<size_Ls_min) continue;
if (diffpair_pmos_size_Ls+step>size_Ls_max) continue;
break;
}
diffpair_pmos_size_Ls+=step;
int pre_volume=p->content->num_of;
if (tcl_gamma_diffpair_pmos_op_cmd(CD,NULL,0,NULL)==TCL_ERROR) {i--; continue;}
if (pre_volume==p->content->num_of) {i--; continue;}
if (p->content->num_of%1000==0) {
    printf("               %ld/%g=%g%% max gain=%g\n",p->content->num_of,diffpair_pmos_config_pat_size_target,100*p->content->num_of/diffpair_pmos_config_pat_size_target,diffpair_pmos_max_Adc);
    printf("               %ld/%g=%g%%\n",p->content->num_of,diffpair_pmos_config_pat_size_target,100*p->content->num_of/diffpair_pmos_config_pat_size_target);
    fflush(stdout);
    if (diffpair_pmos_param_unique>0) {
        pat_unique(p,diffpair_pmos_param_unique);
    printf("               post unique: %ld/%g=%g%%\n",p->content->num_of,diffpair_pmos_config_pat_size_target,100*p->content->num_of/diffpair_pmos_config_pat_size_target);
    if (p->content->num_of>0.92*diffpair_pmos_config_pat_size_target) break;
}
}
    if (p->content->num_of>diffpair_pmos_config_pat_size_target) break;
}
    if (p->content->num_of>diffpair_pmos_config_pat_size_target) break;
}

            return TCL_OK;
        }
        static int tcl_gamma_diffpair_pmos_random_breed_single_cmd(ClientData clientData,Tcl_Interp *interp,int argc,char *argv[]) {
            ClientData CD;
int i;
PAT *p=(PAT *)Pdiffpair_pmos_circuits_PAT;
int more_to_breed=0;
long int r;
long int breed_count=p->content->num_of;
long int watchdog=0;
float step;
int sweep_size=p->content->num_of;
int searched_id=(int)diffpair_pmos_circuit_breed_id;
for (i=0;i<p->content->num_of;i++) {
    if (p->content->content[i]->id==searched_id) break;
}
printf("Found circuit id %d at index %d\n",searched_id,i);
while (watchdog++<10000) {
diffpair_pmos_size_iref=p->content->content[i]->sizes->content[0];
diffpair_pmos_size_Lp=p->content->content[i]->sizes->content[1];
diffpair_pmos_size_Wp=p->content->content[i]->sizes->content[2];
diffpair_pmos_size_Ln=p->content->content[i]->sizes->content[3];
diffpair_pmos_size_Wn=p->content->content[i]->sizes->content[4];
diffpair_pmos_size_Ls=p->content->content[i]->sizes->content[5];
while (1) {
step=(2.0*random()/RAND_MAX-1)*size_iref_step;
if (diffpair_pmos_size_iref+step<size_iref_min) continue;
if (diffpair_pmos_size_iref+step>size_iref_max) continue;
break;
}
diffpair_pmos_size_iref+=step;
while (1) {
step=(2.0*random()/RAND_MAX-1)*size_Lp_step;
if (diffpair_pmos_size_Lp+step<size_Lp_min) continue;
if (diffpair_pmos_size_Lp+step>size_Lp_max) continue;
break;
}
diffpair_pmos_size_Lp+=step;
while (1) {
step=(2.0*random()/RAND_MAX-1)*size_Wp_step;
if (diffpair_pmos_size_Wp+step<size_Lp) continue;
if (diffpair_pmos_size_Wp+step>size_Wp_max) continue;
break;
}
diffpair_pmos_size_Wp+=step;
while (1) {
step=(2.0*random()/RAND_MAX-1)*size_Ln_step;
if (diffpair_pmos_size_Ln+step<size_Ln_min) continue;
if (diffpair_pmos_size_Ln+step>size_Ln_max) continue;
break;
}
diffpair_pmos_size_Ln+=step;
while (1) {
step=(2.0*random()/RAND_MAX-1)*size_Wn_step;
if (diffpair_pmos_size_Wn+step<size_Ln) continue;
if (diffpair_pmos_size_Wn+step>size_Wn_max) continue;
break;
}
diffpair_pmos_size_Wn+=step;
while (1) {
step=(2.0*random()/RAND_MAX-1)*size_Ls_step;
if (diffpair_pmos_size_Ls+step<size_Ls_min) continue;
if (diffpair_pmos_size_Ls+step>size_Ls_max) continue;
break;
}
diffpair_pmos_size_Ls+=step;
if (tcl_gamma_diffpair_pmos_op_cmd(CD,NULL,0,NULL)==TCL_ERROR) continue;
if (p->content->num_of>=breed_count+diffpair_pmos_circuit_breed_target) break;
}

            return TCL_OK;
        }
        // Initializing cTree references and registering the tcl_gamma_op_cmd command as ::C::diffpair_pmos
        int Gamma_diffpair_pmos_Init(Tcl_Interp *interp) {
            float *array_entry;
            context *c;
            c=create_context("param:inp");
Pparam_inp=(float *)(&c->value.s);
c=create_context("param:inn");
Pparam_inn=(float *)(&c->value.s);
c=create_context("param:vdd");
Pparam_vdd=(float *)(&c->value.s);
c=create_context("size:iref");
Psize_iref=(float *)(&c->value.s);
c=create_context("size:Lp");
Psize_Lp=(float *)(&c->value.s);
c=create_context("size:Wp");
Psize_Wp=(float *)(&c->value.s);
c=create_context("size:Ln");
Psize_Ln=(float *)(&c->value.s);
c=create_context("size:Wn");
Psize_Wn=(float *)(&c->value.s);
c=create_context("size:Ls");
Psize_Ls=(float *)(&c->value.s);
c=create_context("property:Adc");
Pproperty_Adc=(float *)(&c->value.s);
c=create_context("property:CMRR");
Pproperty_CMRR=(float *)(&c->value.s);
Pdiffpair_pmos_circuits_PAT=(float *)get_PAT("diffpair_pmos:circuits");
c=create_context("diffpair_pmos:config:pat_size_target");
Pdiffpair_pmos_config_pat_size_target=(float *)(&c->value.s);
c=create_context("size:iref:min");
Psize_iref_min=(float *)(&c->value.s);
c=create_context("size:iref:max");
Psize_iref_max=(float *)(&c->value.s);
c=create_context("diffpair_pmos:size:iref");
Pdiffpair_pmos_size_iref=(float *)(&c->value.s);
c=create_context("size:Lp:min");
Psize_Lp_min=(float *)(&c->value.s);
c=create_context("size:Lp:max");
Psize_Lp_max=(float *)(&c->value.s);
c=create_context("diffpair_pmos:size:Lp");
Pdiffpair_pmos_size_Lp=(float *)(&c->value.s);
c=create_context("size:Wp:max");
Psize_Wp_max=(float *)(&c->value.s);
c=create_context("diffpair_pmos:size:Wp");
Pdiffpair_pmos_size_Wp=(float *)(&c->value.s);
c=create_context("size:Ln:min");
Psize_Ln_min=(float *)(&c->value.s);
c=create_context("size:Ln:max");
Psize_Ln_max=(float *)(&c->value.s);
c=create_context("diffpair_pmos:size:Ln");
Pdiffpair_pmos_size_Ln=(float *)(&c->value.s);
c=create_context("size:Wn:max");
Psize_Wn_max=(float *)(&c->value.s);
c=create_context("diffpair_pmos:size:Wn");
Pdiffpair_pmos_size_Wn=(float *)(&c->value.s);
c=create_context("size:Ls:min");
Psize_Ls_min=(float *)(&c->value.s);
c=create_context("size:Ls:max");
Psize_Ls_max=(float *)(&c->value.s);
c=create_context("diffpair_pmos:size:Ls");
Pdiffpair_pmos_size_Ls=(float *)(&c->value.s);
c=create_context("size:iref:step");
Psize_iref_step=(float *)(&c->value.s);
c=create_context("size:Lp:step");
Psize_Lp_step=(float *)(&c->value.s);
c=create_context("size:Wp:step");
Psize_Wp_step=(float *)(&c->value.s);
c=create_context("size:Ln:step");
Psize_Ln_step=(float *)(&c->value.s);
c=create_context("size:Wn:step");
Psize_Wn_step=(float *)(&c->value.s);
c=create_context("size:Ls:step");
Psize_Ls_step=(float *)(&c->value.s);
c=create_context("diffpair_pmos:max_Adc");
Pdiffpair_pmos_max_Adc=(float *)(&c->value.s);
c=create_context("diffpair_pmos:param:unique");
Pdiffpair_pmos_param_unique=(float *)(&c->value.s);
c=create_context("diffpair_pmos:pat_size_target");
Pdiffpair_pmos_pat_size_target=(float *)(&c->value.s);
c=create_context("diffpair_pmos:size:iref:step");
Pdiffpair_pmos_size_iref_step=(float *)(&c->value.s);
c=create_context("diffpair_pmos:size:Lp:step");
Pdiffpair_pmos_size_Lp_step=(float *)(&c->value.s);
c=create_context("diffpair_pmos:size:Wp:step");
Pdiffpair_pmos_size_Wp_step=(float *)(&c->value.s);
c=create_context("diffpair_pmos:size:Ln:step");
Pdiffpair_pmos_size_Ln_step=(float *)(&c->value.s);
c=create_context("diffpair_pmos:size:Wn:step");
Pdiffpair_pmos_size_Wn_step=(float *)(&c->value.s);
c=create_context("diffpair_pmos:size:Ls:step");
Pdiffpair_pmos_size_Ls_step=(float *)(&c->value.s);
c=create_context("diffpair_pmos:circuit_breed_id");
Pdiffpair_pmos_circuit_breed_id=(float *)(&c->value.s);
c=create_context("diffpair_pmos:circuit_breed_target");
Pdiffpair_pmos_circuit_breed_target=(float *)(&c->value.s);
c=create_context("diffpair_pmos:mode:freash_op");
Pdiffpair_pmos_mode_freash_op=(float *)(&c->value.s);
c=create_context("diffpair_pmos:status:index");
Pdiffpair_pmos_status_index=(float *)(&c->value.s);
c=create_context("diffpair_pmos:config:size:iref");
Pdiffpair_pmos_config_size_iref=(float *)(&c->value.s);
c=create_context("diffpair_pmos:config:size:Lp");
Pdiffpair_pmos_config_size_Lp=(float *)(&c->value.s);
c=create_context("diffpair_pmos:config:size:Wp");
Pdiffpair_pmos_config_size_Wp=(float *)(&c->value.s);
c=create_context("diffpair_pmos:config:size:Ln");
Pdiffpair_pmos_config_size_Ln=(float *)(&c->value.s);
c=create_context("diffpair_pmos:config:size:Wn");
Pdiffpair_pmos_config_size_Wn=(float *)(&c->value.s);
c=create_context("diffpair_pmos:config:size:Ls");
Pdiffpair_pmos_config_size_Ls=(float *)(&c->value.s);
c=create_context("diffpair_pmos:vdd:V");
Pdiffpair_pmos_vdd_V=(float *)(&c->value.s);
c=create_context("diffpair_pmos:0:V");
Pdiffpair_pmos_0_V=(float *)(&c->value.s);
c=create_context("diffpair_pmos:status:fail");
Pdiffpair_pmos_status_fail=(float *)(&c->value.s);
c=create_context("diffpair_pmos:design_feedback");
Pdiffpair_pmos_design_feedback=(float *)(&c->value.s);
c=create_context("n_1:bin");
Pn_1_bin=(float *)(&c->value.s);
c=create_context("n_1:W");
Pn_1_W=(float *)(&c->value.s);
c=create_context("n_1:L");
Pn_1_L=(float *)(&c->value.s);
Plook_up_tables_nch_binning_LUT=(float *)get_LUT("nch:binning");
c=create_context("n_2:bin");
Pn_2_bin=(float *)(&c->value.s);
c=create_context("n_2:W");
Pn_2_W=(float *)(&c->value.s);
c=create_context("n_2:L");
Pn_2_L=(float *)(&c->value.s);
c=create_context("pin_1:bin");
Ppin_1_bin=(float *)(&c->value.s);
c=create_context("pin_1:W");
Ppin_1_W=(float *)(&c->value.s);
c=create_context("pin_1:L");
Ppin_1_L=(float *)(&c->value.s);
Plook_up_tables_pch_binning_LUT=(float *)get_LUT("pch:binning");
c=create_context("pin_2:bin");
Ppin_2_bin=(float *)(&c->value.s);
c=create_context("pin_2:W");
Ppin_2_W=(float *)(&c->value.s);
c=create_context("pin_2:L");
Ppin_2_L=(float *)(&c->value.s);
c=create_context("p_tail:bin");
Pp_tail_bin=(float *)(&c->value.s);
c=create_context("p_tail:W");
Pp_tail_W=(float *)(&c->value.s);
c=create_context("p_tail:L");
Pp_tail_L=(float *)(&c->value.s);
c=create_context("p_ref:bin");
Pp_ref_bin=(float *)(&c->value.s);
c=create_context("p_ref:W");
Pp_ref_W=(float *)(&c->value.s);
c=create_context("p_ref:L");
Pp_ref_L=(float *)(&c->value.s);
c=create_context("diffpair_pmos:leak");
Pdiffpair_pmos_leak=(float *)(&c->value.s);
c=create_context("diffpair_pmos:config:op_iterations");
Pdiffpair_pmos_config_op_iterations=(float *)(&c->value.s);
c=create_context("diffpair_pmos:config:kcl_th");
Pdiffpair_pmos_config_kcl_th=(float *)(&c->value.s);
c=create_context("diffpair_pmos:config:design_feedback_th");
Pdiffpair_pmos_config_design_feedback_th=(float *)(&c->value.s);
c=create_context("outp:V");
Poutp_V=(float *)(&c->value.s);
c=create_context("outm:V");
Poutm_V=(float *)(&c->value.s);
c=create_context("n_1:go");
Pn_1_go=(float *)(&c->value.s);
c=create_context("n_1:gm");
Pn_1_gm=(float *)(&c->value.s);
c=create_context("n_1:gb");
Pn_1_gb=(float *)(&c->value.s);
c=create_context("n_1:Ids");
Pn_1_Ids=(float *)(&c->value.s);
c=create_context("0:V");
P0_V=(float *)(&c->value.s);
c=create_context("diffpair_pmos:look_up_tables:nch:go:ss");
Pdiffpair_pmos_look_up_tables_nch_go_ss_CONTEXT=(float *)&c;
c=create_context("diffpair_pmos:look_up_tables:nch:gm:ss");
Pdiffpair_pmos_look_up_tables_nch_gm_ss_CONTEXT=(float *)&c;
c=create_context("diffpair_pmos:look_up_tables:nch:gb:ss");
Pdiffpair_pmos_look_up_tables_nch_gb_ss_CONTEXT=(float *)&c;
c=create_context("diffpair_pmos:look_up_tables:nch:Ids:ss");
Pdiffpair_pmos_look_up_tables_nch_Ids_ss_CONTEXT=(float *)&c;
c=create_context("n_2:go");
Pn_2_go=(float *)(&c->value.s);
c=create_context("n_2:gm");
Pn_2_gm=(float *)(&c->value.s);
c=create_context("n_2:gb");
Pn_2_gb=(float *)(&c->value.s);
c=create_context("n_2:Ids");
Pn_2_Ids=(float *)(&c->value.s);
c=create_context("vdd:V");
Pvdd_V=(float *)(&c->value.s);
c=create_context("tail:V");
Ptail_V=(float *)(&c->value.s);
c=create_context("pin_1:go");
Ppin_1_go=(float *)(&c->value.s);
c=create_context("pin_1:gm");
Ppin_1_gm=(float *)(&c->value.s);
c=create_context("pin_1:gb");
Ppin_1_gb=(float *)(&c->value.s);
c=create_context("pin_1:Ids");
Ppin_1_Ids=(float *)(&c->value.s);
c=create_context("inp:V");
Pinp_V=(float *)(&c->value.s);
c=create_context("diffpair_pmos:look_up_tables:pch:go:ss");
Pdiffpair_pmos_look_up_tables_pch_go_ss_CONTEXT=(float *)&c;
c=create_context("diffpair_pmos:look_up_tables:pch:gm:ss");
Pdiffpair_pmos_look_up_tables_pch_gm_ss_CONTEXT=(float *)&c;
c=create_context("diffpair_pmos:look_up_tables:pch:gb:ss");
Pdiffpair_pmos_look_up_tables_pch_gb_ss_CONTEXT=(float *)&c;
c=create_context("diffpair_pmos:look_up_tables:pch:Ids:ss");
Pdiffpair_pmos_look_up_tables_pch_Ids_ss_CONTEXT=(float *)&c;
c=create_context("pin_2:go");
Ppin_2_go=(float *)(&c->value.s);
c=create_context("pin_2:gm");
Ppin_2_gm=(float *)(&c->value.s);
c=create_context("pin_2:gb");
Ppin_2_gb=(float *)(&c->value.s);
c=create_context("pin_2:Ids");
Ppin_2_Ids=(float *)(&c->value.s);
c=create_context("inn:V");
Pinn_V=(float *)(&c->value.s);
c=create_context("vbias:V");
Pvbias_V=(float *)(&c->value.s);
c=create_context("p_tail:go");
Pp_tail_go=(float *)(&c->value.s);
c=create_context("p_tail:gm");
Pp_tail_gm=(float *)(&c->value.s);
c=create_context("p_tail:gb");
Pp_tail_gb=(float *)(&c->value.s);
c=create_context("p_tail:Ids");
Pp_tail_Ids=(float *)(&c->value.s);
c=create_context("p_ref:go");
Pp_ref_go=(float *)(&c->value.s);
c=create_context("p_ref:gm");
Pp_ref_gm=(float *)(&c->value.s);
c=create_context("p_ref:gb");
Pp_ref_gb=(float *)(&c->value.s);
c=create_context("p_ref:Ids");
Pp_ref_Ids=(float *)(&c->value.s);
c=create_context("diffpair_pmos:config:kcl_step");
Pdiffpair_pmos_config_kcl_step=(float *)(&c->value.s);
c=create_context("diffpair_pmos:property:Adc");
Pdiffpair_pmos_property_Adc=(float *)(&c->value.s);
c=create_context("diffpair_pmos:property:CMRR");
Pdiffpair_pmos_property_CMRR=(float *)(&c->value.s);
c=create_context("diffpair_pmos:property:PSRR");
Pdiffpair_pmos_property_PSRR=(float *)(&c->value.s);
c=create_context("diffpair_pmos:config:fail_on_properties");
Pdiffpair_pmos_config_fail_on_properties=(float *)(&c->value.s);
c=create_context("diffpair_pmos:property:Rout");
Pdiffpair_pmos_property_Rout=(float *)(&c->value.s);
c=create_context("pin_2:css");
Ppin_2_css=(float *)(&c->value.s);
c=create_context("pin_2:csd");
Ppin_2_csd=(float *)(&c->value.s);
c=create_context("pin_2:cds");
Ppin_2_cds=(float *)(&c->value.s);
c=create_context("pin_2:cdd");
Ppin_2_cdd=(float *)(&c->value.s);
c=create_context("pin_1:css");
Ppin_1_css=(float *)(&c->value.s);
c=create_context("pin_1:csd");
Ppin_1_csd=(float *)(&c->value.s);
c=create_context("pin_1:cds");
Ppin_1_cds=(float *)(&c->value.s);
c=create_context("pin_1:cdd");
Ppin_1_cdd=(float *)(&c->value.s);
c=create_context("p_tail:cgg");
Pp_tail_cgg=(float *)(&c->value.s);
c=create_context("p_tail:cgd");
Pp_tail_cgd=(float *)(&c->value.s);
c=create_context("p_tail:cdg");
Pp_tail_cdg=(float *)(&c->value.s);
c=create_context("p_tail:cdd");
Pp_tail_cdd=(float *)(&c->value.s);
c=create_context("p_ref:cgg");
Pp_ref_cgg=(float *)(&c->value.s);
c=create_context("p_ref:cgd");
Pp_ref_cgd=(float *)(&c->value.s);
c=create_context("p_ref:cdg");
Pp_ref_cdg=(float *)(&c->value.s);
c=create_context("p_ref:cdd");
Pp_ref_cdd=(float *)(&c->value.s);
c=create_context("n_2:cgg");
Pn_2_cgg=(float *)(&c->value.s);
c=create_context("n_2:cgd");
Pn_2_cgd=(float *)(&c->value.s);
c=create_context("n_2:cdg");
Pn_2_cdg=(float *)(&c->value.s);
c=create_context("n_2:cdd");
Pn_2_cdd=(float *)(&c->value.s);
c=create_context("n_1:cgg");
Pn_1_cgg=(float *)(&c->value.s);
c=create_context("n_1:cgd");
Pn_1_cgd=(float *)(&c->value.s);
c=create_context("n_1:cdg");
Pn_1_cdg=(float *)(&c->value.s);
c=create_context("n_1:cdd");
Pn_1_cdd=(float *)(&c->value.s);
c=create_context("diffpair_pmos:property:BW");
Pdiffpair_pmos_property_BW=(float *)(&c->value.s);
c=create_context("s");
Ps=(float *)(&c->value.s);
c=create_context("diffpair_pmos:property:BW:s");
Pdiffpair_pmos_property_BW_s=(float *)(&c->value.s);
c=create_context("diffpair_pmos:p1");
Pdiffpair_pmos_p1=(float *)(&c->value.s);
c=create_context("diffpair_pmos:p2");
Pdiffpair_pmos_p2=(float *)(&c->value.s);
c=create_context("diffpair_pmos:property:ts");
Pdiffpair_pmos_property_ts=(float *)(&c->value.s);
c=create_context("pin_1:cgs");
Ppin_1_cgs=(float *)(&c->value.s);
c=create_context("pin_1:cgd");
Ppin_1_cgd=(float *)(&c->value.s);
c=create_context("diffpair_pmos:property:Cin");
Pdiffpair_pmos_property_Cin=(float *)(&c->value.s);
c=create_context("diffpair_pmos:property:PM");
Pdiffpair_pmos_property_PM=(float *)(&c->value.s);
c=create_context("n_1:dNt_dvgs");
Pn_1_dNt_dvgs=(float *)(&c->value.s);
c=create_context("n_1:dNt_dvds");
Pn_1_dNt_dvds=(float *)(&c->value.s);
c=create_context("n_1:dNt_dvbs");
Pn_1_dNt_dvbs=(float *)(&c->value.s);
c=create_context("n_1:dNt_dl");
Pn_1_dNt_dl=(float *)(&c->value.s);
c=create_context("n_1:Nt_unit");
Pn_1_Nt_unit=(float *)(&c->value.s);
P_look_up_tables_nch_thermal_noise_ss_LUT=(float *)get_LUT(":look_up_tables:nch:thermal_noise:ss");
c=create_context("n_1:Nt");
Pn_1_Nt=(float *)(&c->value.s);
c=create_context("n_1:dNf_dvgs");
Pn_1_dNf_dvgs=(float *)(&c->value.s);
c=create_context("n_1:dNf_dvds");
Pn_1_dNf_dvds=(float *)(&c->value.s);
c=create_context("n_1:dNf_dvbs");
Pn_1_dNf_dvbs=(float *)(&c->value.s);
c=create_context("n_1:dNf_dl");
Pn_1_dNf_dl=(float *)(&c->value.s);
c=create_context("n_1:Nf_unit");
Pn_1_Nf_unit=(float *)(&c->value.s);
P_look_up_tables_nch_flicker_noise_ss_LUT=(float *)get_LUT(":look_up_tables:nch:flicker_noise:ss");
c=create_context("n_1:Nf");
Pn_1_Nf=(float *)(&c->value.s);
c=create_context("n_2:dNt_dvgs");
Pn_2_dNt_dvgs=(float *)(&c->value.s);
c=create_context("n_2:dNt_dvds");
Pn_2_dNt_dvds=(float *)(&c->value.s);
c=create_context("n_2:dNt_dvbs");
Pn_2_dNt_dvbs=(float *)(&c->value.s);
c=create_context("n_2:dNt_dl");
Pn_2_dNt_dl=(float *)(&c->value.s);
c=create_context("n_2:Nt_unit");
Pn_2_Nt_unit=(float *)(&c->value.s);
c=create_context("n_2:Nt");
Pn_2_Nt=(float *)(&c->value.s);
c=create_context("n_2:dNf_dvgs");
Pn_2_dNf_dvgs=(float *)(&c->value.s);
c=create_context("n_2:dNf_dvds");
Pn_2_dNf_dvds=(float *)(&c->value.s);
c=create_context("n_2:dNf_dvbs");
Pn_2_dNf_dvbs=(float *)(&c->value.s);
c=create_context("n_2:dNf_dl");
Pn_2_dNf_dl=(float *)(&c->value.s);
c=create_context("n_2:Nf_unit");
Pn_2_Nf_unit=(float *)(&c->value.s);
c=create_context("n_2:Nf");
Pn_2_Nf=(float *)(&c->value.s);
c=create_context("pin_1:dNt_dvgs");
Ppin_1_dNt_dvgs=(float *)(&c->value.s);
c=create_context("pin_1:dNt_dvds");
Ppin_1_dNt_dvds=(float *)(&c->value.s);
c=create_context("pin_1:dNt_dvbs");
Ppin_1_dNt_dvbs=(float *)(&c->value.s);
c=create_context("pin_1:dNt_dl");
Ppin_1_dNt_dl=(float *)(&c->value.s);
c=create_context("pin_1:Nt_unit");
Ppin_1_Nt_unit=(float *)(&c->value.s);
P_look_up_tables_pch_thermal_noise_ss_LUT=(float *)get_LUT(":look_up_tables:pch:thermal_noise:ss");
c=create_context("pin_1:Nt");
Ppin_1_Nt=(float *)(&c->value.s);
c=create_context("pin_1:dNf_dvgs");
Ppin_1_dNf_dvgs=(float *)(&c->value.s);
c=create_context("pin_1:dNf_dvds");
Ppin_1_dNf_dvds=(float *)(&c->value.s);
c=create_context("pin_1:dNf_dvbs");
Ppin_1_dNf_dvbs=(float *)(&c->value.s);
c=create_context("pin_1:dNf_dl");
Ppin_1_dNf_dl=(float *)(&c->value.s);
c=create_context("pin_1:Nf_unit");
Ppin_1_Nf_unit=(float *)(&c->value.s);
P_look_up_tables_pch_flicker_noise_ss_LUT=(float *)get_LUT(":look_up_tables:pch:flicker_noise:ss");
c=create_context("pin_1:Nf");
Ppin_1_Nf=(float *)(&c->value.s);
c=create_context("pin_2:dNt_dvgs");
Ppin_2_dNt_dvgs=(float *)(&c->value.s);
c=create_context("pin_2:dNt_dvds");
Ppin_2_dNt_dvds=(float *)(&c->value.s);
c=create_context("pin_2:dNt_dvbs");
Ppin_2_dNt_dvbs=(float *)(&c->value.s);
c=create_context("pin_2:dNt_dl");
Ppin_2_dNt_dl=(float *)(&c->value.s);
c=create_context("pin_2:Nt_unit");
Ppin_2_Nt_unit=(float *)(&c->value.s);
c=create_context("pin_2:Nt");
Ppin_2_Nt=(float *)(&c->value.s);
c=create_context("pin_2:dNf_dvgs");
Ppin_2_dNf_dvgs=(float *)(&c->value.s);
c=create_context("pin_2:dNf_dvds");
Ppin_2_dNf_dvds=(float *)(&c->value.s);
c=create_context("pin_2:dNf_dvbs");
Ppin_2_dNf_dvbs=(float *)(&c->value.s);
c=create_context("pin_2:dNf_dl");
Ppin_2_dNf_dl=(float *)(&c->value.s);
c=create_context("pin_2:Nf_unit");
Ppin_2_Nf_unit=(float *)(&c->value.s);
c=create_context("pin_2:Nf");
Ppin_2_Nf=(float *)(&c->value.s);
c=create_context("p_tail:dNt_dvgs");
Pp_tail_dNt_dvgs=(float *)(&c->value.s);
c=create_context("p_tail:dNt_dvds");
Pp_tail_dNt_dvds=(float *)(&c->value.s);
c=create_context("p_tail:dNt_dvbs");
Pp_tail_dNt_dvbs=(float *)(&c->value.s);
c=create_context("p_tail:dNt_dl");
Pp_tail_dNt_dl=(float *)(&c->value.s);
c=create_context("p_tail:Nt_unit");
Pp_tail_Nt_unit=(float *)(&c->value.s);
c=create_context("p_tail:Nt");
Pp_tail_Nt=(float *)(&c->value.s);
c=create_context("p_tail:dNf_dvgs");
Pp_tail_dNf_dvgs=(float *)(&c->value.s);
c=create_context("p_tail:dNf_dvds");
Pp_tail_dNf_dvds=(float *)(&c->value.s);
c=create_context("p_tail:dNf_dvbs");
Pp_tail_dNf_dvbs=(float *)(&c->value.s);
c=create_context("p_tail:dNf_dl");
Pp_tail_dNf_dl=(float *)(&c->value.s);
c=create_context("p_tail:Nf_unit");
Pp_tail_Nf_unit=(float *)(&c->value.s);
c=create_context("p_tail:Nf");
Pp_tail_Nf=(float *)(&c->value.s);
c=create_context("p_ref:dNt_dvgs");
Pp_ref_dNt_dvgs=(float *)(&c->value.s);
c=create_context("p_ref:dNt_dvds");
Pp_ref_dNt_dvds=(float *)(&c->value.s);
c=create_context("p_ref:dNt_dvbs");
Pp_ref_dNt_dvbs=(float *)(&c->value.s);
c=create_context("p_ref:dNt_dl");
Pp_ref_dNt_dl=(float *)(&c->value.s);
c=create_context("p_ref:Nt_unit");
Pp_ref_Nt_unit=(float *)(&c->value.s);
c=create_context("p_ref:Nt");
Pp_ref_Nt=(float *)(&c->value.s);
c=create_context("p_ref:dNf_dvgs");
Pp_ref_dNf_dvgs=(float *)(&c->value.s);
c=create_context("p_ref:dNf_dvds");
Pp_ref_dNf_dvds=(float *)(&c->value.s);
c=create_context("p_ref:dNf_dvbs");
Pp_ref_dNf_dvbs=(float *)(&c->value.s);
c=create_context("p_ref:dNf_dl");
Pp_ref_dNf_dl=(float *)(&c->value.s);
c=create_context("p_ref:Nf_unit");
Pp_ref_Nf_unit=(float *)(&c->value.s);
c=create_context("p_ref:Nf");
Pp_ref_Nf=(float *)(&c->value.s);
c=create_context("diffpair_pmos:property:Nt");
Pdiffpair_pmos_property_Nt=(float *)(&c->value.s);
c=create_context("diffpair_pmos:property:Nf");
Pdiffpair_pmos_property_Nf=(float *)(&c->value.s);
c=create_context("diffpair_pmos:property:fc");
Pdiffpair_pmos_property_fc=(float *)(&c->value.s);
c=create_context("diffpair_pmos:property:TotalNoise");
Pdiffpair_pmos_property_TotalNoise=(float *)(&c->value.s);
c=create_context("diffpair_pmos:property:Area");
Pdiffpair_pmos_property_Area=(float *)(&c->value.s);
c=create_context("diffpair_pmos:property:Vos");
Pdiffpair_pmos_property_Vos=(float *)(&c->value.s);
c=create_context("diffpair_pmos:property:Power");
Pdiffpair_pmos_property_Power=(float *)(&c->value.s);
c=create_context("diffpair_pmos:config:shift:Adc");
Pdiffpair_pmos_config_shift_Adc=(float *)(&c->value.s);
c=create_context("diffpair_pmos:config:factor:Adc");
Pdiffpair_pmos_config_factor_Adc=(float *)(&c->value.s);
c=create_context("diffpair_pmos:config:shift:CMRR");
Pdiffpair_pmos_config_shift_CMRR=(float *)(&c->value.s);
c=create_context("diffpair_pmos:config:factor:CMRR");
Pdiffpair_pmos_config_factor_CMRR=(float *)(&c->value.s);

            return TCL_OK;
        }
        int Gamma_diffpair_pmos_Register(Tcl_Interp *interp) {
            Tcl_CreateCommand(interp, "::Gamma::diffpair_pmos::heatmap", tcl_gamma_diffpair_pmos_heatmap_cmd, NULL, NULL);
            Tcl_CreateCommand(interp, "::Gamma::diffpair_pmos::random", tcl_gamma_diffpair_pmos_random_cmd, NULL, NULL);
            Tcl_CreateCommand(interp, "::Gamma::diffpair_pmos::random_breed", tcl_gamma_diffpair_pmos_random_breed_cmd, NULL, NULL);
            Tcl_CreateCommand(interp, "::Gamma::diffpair_pmos::random_breed_single", tcl_gamma_diffpair_pmos_random_breed_single_cmd, NULL, NULL);
            Tcl_CreateCommand(interp, "::Gamma::diffpair_pmos::breed", tcl_gamma_diffpair_pmos_breed_cmd, NULL, NULL);
            Tcl_CreateCommand(interp, "::Gamma::diffpair_pmos::op", tcl_gamma_diffpair_pmos_op_cmd, NULL, NULL);
            Tcl_CreateCommand(interp, "::Gamma::diffpair_pmos::import", tcl_gamma_diffpair_pmos_import_cmd, NULL, NULL);
            Tcl_CreateCommand(interp, "::Gamma::diffpair_pmos::export", tcl_gamma_diffpair_pmos_export_cmd, NULL, NULL);
            return TCL_OK;
        }
    
